
<div class="mage-magictabs mc-random">
	<ul class="flexisel-content products-grid random zoomOut play">

		<li
			style="-webkit-animation-delay: 0ms; -moz-animation-delay: 0ms; -o-animation-delay: 0ms; animation-delay: 0ms;"
			class="item item-animate">
			<div class="per-product">
				<div class="images-container">
					<div class="product-hover">
						<a
							href="http://alothemes.com/demo/smije/index.php/slim-fit-dobby-oxford-shirt.html"
							title="Slim fit Dobby Oxford Shirt" class="product-image"> <img
							class="img-responsive"
							src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/3/_/3_4.jpg"
							width="290" height="372" alt="Slim fit Dobby Oxford Shirt" /> <span
							class="product-img-back"> <img class="img-responsive"
								src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/3/-/3-3_1.jpg"
								width="290" height="372" alt="Slim fit Dobby Oxford Shirt" />
						</span>
						</a>
					</div>
					<div class="actions-no">
						<div class="actions">
							<button type="button" title="Add to Cart"
								class="pull-left button btn-cart"
								onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNwcm9kdWN0L2luZGV4L2FqYXgv/product/27/form_key/Z9IuKHJORkq6jWdh/')">
								<span><span>Add to Cart</span></span>
							</button>
							<ul class="add-to-links pull-left">
								<li class="pull-left"><a
									href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/27/form_key/Z9IuKHJORkq6jWdh/"
									title="Add to Wishlist" class="link-wishlist">Add to Wishlist</a></li>
								<li class="pull-right"><span class="separator">|</span> <a
									href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/27/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNwcm9kdWN0L2luZGV4L2FqYXgv/form_key/Z9IuKHJORkq6jWdh/"
									title="Add to Compare" class="link-compare">Add to Compare</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="products-textlink clearfix">
					<h2 class="product-name">
						<a
							href="http://alothemes.com/demo/smije/index.php/slim-fit-dobby-oxford-shirt.html"
							title="Slim fit Dobby Oxford Shirt">Slim fit Dobby Oxford Shirt</a>
					</h2>



					<div class="price-box">
						<span class="regular-price" id="product-price-27"> <span
							class="price">$250.00</span>
						</span>

					</div>

				</div>
			</div>
		</li>

		<li
			style="-webkit-animation-delay: 0ms; -moz-animation-delay: 0ms; -o-animation-delay: 0ms; animation-delay: 0ms;"
			class="item item-animate">
			<div class="per-product">
				<div class="images-container">
					<div class="product-hover">
						<span class="sticker top-left"><span class="labelnew">New</span></span>
						<a
							href="http://alothemes.com/demo/smije/index.php/broad-st-flapover.html"
							title="Broad St. Flapover" class="product-image"> <img
							class="img-responsive"
							src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/1/8/18_6.jpg"
							width="290" height="372" alt="Broad St. Flapover" /> <span
							class="product-img-back"> <img class="img-responsive"
								src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/1/4/14_4.jpg"
								width="290" height="372" alt="Broad St. Flapover" />
						</span>
						</a>
					</div>
					<div class="actions-no">
						<div class="actions">
							<button type="button" title="Add to Cart"
								class="pull-left button btn-cart"
								onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNwcm9kdWN0L2luZGV4L2FqYXgv/product/41/form_key/Z9IuKHJORkq6jWdh/')">
								<span><span>Add to Cart</span></span>
							</button>
							<ul class="add-to-links pull-left">
								<li class="pull-left"><a
									href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/41/form_key/Z9IuKHJORkq6jWdh/"
									title="Add to Wishlist" class="link-wishlist">Add to Wishlist</a></li>
								<li class="pull-right"><span class="separator">|</span> <a
									href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/41/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNwcm9kdWN0L2luZGV4L2FqYXgv/form_key/Z9IuKHJORkq6jWdh/"
									title="Add to Compare" class="link-compare">Add to Compare</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="products-textlink clearfix">
					<h2 class="product-name">
						<a
							href="http://alothemes.com/demo/smije/index.php/broad-st-flapover.html"
							title="Broad St. Flapover">Broad St. Flapover</a>
					</h2>
					<div class="ratings">
						<div class="rating-box">
							<div class="rating" style="width: 60%"></div>
						</div>
						<span class="amount"><a href="#"
							onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/41/'; return false;">1
								Review(s)</a></span>
					</div>



					<div class="price-box">
						<span class="regular-price" id="product-price-41"> <span
							class="price">$234.00</span>
						</span>

					</div>

				</div>
			</div>
		</li>

		<li
			style="-webkit-animation-delay: 0ms; -moz-animation-delay: 0ms; -o-animation-delay: 0ms; animation-delay: 0ms;"
			class="item item-animate">
			<div class="per-product">
				<div class="images-container">
					<div class="product-hover">
						<a
							href="http://alothemes.com/demo/smije/index.php/roller-suitcase.html"
							title="Roller Suitcase" class="product-image"> <img
							class="img-responsive"
							src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/1/7/17_2.jpg"
							width="290" height="372" alt="Roller Suitcase" /> <span
							class="product-img-back"> <img class="img-responsive"
								src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/1/5/15_1.jpg"
								width="290" height="372" alt="Roller Suitcase" />
						</span>
						</a>
					</div>
					<div class="actions-no">
						<div class="actions">
							<button type="button" title="Add to Cart"
								class="pull-left button btn-cart"
								onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNwcm9kdWN0L2luZGV4L2FqYXgv/product/30/form_key/Z9IuKHJORkq6jWdh/')">
								<span><span>Add to Cart</span></span>
							</button>
							<ul class="add-to-links pull-left">
								<li class="pull-left"><a
									href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/30/form_key/Z9IuKHJORkq6jWdh/"
									title="Add to Wishlist" class="link-wishlist">Add to Wishlist</a></li>
								<li class="pull-right"><span class="separator">|</span> <a
									href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/30/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNwcm9kdWN0L2luZGV4L2FqYXgv/form_key/Z9IuKHJORkq6jWdh/"
									title="Add to Compare" class="link-compare">Add to Compare</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="products-textlink clearfix">
					<h2 class="product-name">
						<a
							href="http://alothemes.com/demo/smije/index.php/roller-suitcase.html"
							title="Roller Suitcase">Roller Suitcase</a>
					</h2>



					<div class="price-box">
						<span class="regular-price" id="product-price-30"> <span
							class="price">$456.00</span>
						</span>

					</div>

				</div>
			</div>
		</li>

		<li
			style="-webkit-animation-delay: 0ms; -moz-animation-delay: 0ms; -o-animation-delay: 0ms; animation-delay: 0ms;"
			class="item item-animate">
			<div class="per-product">
				<div class="images-container">
					<div class="product-hover">
						<span class="sticker top-left"><span class="labelnew">New</span></span>
						<a
							href="http://alothemes.com/demo/smije/index.php/houston-travel-wallet.html"
							title="Houston Travel Wallet" class="product-image"> <img
							class="img-responsive"
							src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/1/6/16_5.jpg"
							width="290" height="372" alt="Houston Travel Wallet" /> <span
							class="product-img-back"> <img class="img-responsive"
								src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/1/4/14_5.jpg"
								width="290" height="372" alt="Houston Travel Wallet" />
						</span>
						</a>
					</div>
					<div class="actions-no">
						<div class="actions">
							<button type="button" title="Add to Cart"
								class="pull-left button btn-cart"
								onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNwcm9kdWN0L2luZGV4L2FqYXgv/product/42/form_key/Z9IuKHJORkq6jWdh/')">
								<span><span>Add to Cart</span></span>
							</button>
							<ul class="add-to-links pull-left">
								<li class="pull-left"><a
									href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/42/form_key/Z9IuKHJORkq6jWdh/"
									title="Add to Wishlist" class="link-wishlist">Add to Wishlist</a></li>
								<li class="pull-right"><span class="separator">|</span> <a
									href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/42/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNwcm9kdWN0L2luZGV4L2FqYXgv/form_key/Z9IuKHJORkq6jWdh/"
									title="Add to Compare" class="link-compare">Add to Compare</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="products-textlink clearfix">
					<h2 class="product-name">
						<a
							href="http://alothemes.com/demo/smije/index.php/houston-travel-wallet.html"
							title="Houston Travel Wallet">Houston Travel Wallet</a>
					</h2>
					<div class="ratings">
						<div class="rating-box">
							<div class="rating" style="width: 60%"></div>
						</div>
						<span class="amount"><a href="#"
							onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/42/'; return false;">1
								Review(s)</a></span>
					</div>



					<div class="price-box">
						<span class="regular-price" id="product-price-42"> <span
							class="price">$156.00</span>
						</span>

					</div>

				</div>
			</div>
		</li>
	</ul>
</div>


