
<article>

            <div class="container">
                <div class="row box-an-767">

                    <div  class="col-sm-12">
                        <div id="abc" class="carousel slide" data-ride="carousel">
                            <!-- Indicators -->
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="3"></li>


                            </ol>

                            <!-- Wrapper for slides -->
                            <div class="carousel-inner " role="listbox">
                                <div class="item active">
                                    <div class="box-anhjs">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/slide-360/s1.jpg" class="img-responsive" alt="#"/>
                                        </a>
                                    </div>



                                </div>
                                <div class="item">
                                    <div class="box-anhjs">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/slide-360/s2.jpg" class="img-responsive" alt="#"/>
                                        </a>
                                    </div>


                                </div>

                                <div class="item">
                                    <div class="box-anhjs">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/slide-360/s3.jpg" class="img-responsive" alt="#"/>
                                        </a>
                                    </div>


                                </div>

                                <div class="item">
                                    <div class="box-anhjs">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/slide-360/s4.jpg" class="img-responsive" alt="#"/>
                                        </a>
                                    </div>


                                </div>

                            </div>

                            <!-- Controls -->
                            <a class="left carousel-control icon-right" href="#abc" role="button" data-slide="prev">
                                <span class="fa fa-chevron-circle-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control icon-right" href="#abc" role="button" data-slide="next">
                                <span class="fa fa-chevron-circle-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>

                        </div> 
                    </div>

                    <div class="col-sm-12 margin-top-nhieu">
                        <div class="menu">

                            <div class="menuresponsive">
                                <a href="#menu">

                                    <div class="col-sm-12 box-the-li">
                                        TẤT CẢ DANH MỤC
                                    </div>
                                </a>
                            </div>


                        </div>
                    </div>
                    <div class="col-sm-12 margin-top">
                        <div class="col-sm-12 box-the-li">
                            SẢN PHẨM BÁN CHẠY
                        </div>


                    </div>
                    <div class="col-sm-12 box-full-tuongtu">
                        <div class="col-sm-12 box-sanpham-tuongtu">



                            <div class="box-chua-anh-giamgia">
                                <div class="text-tron-giamgia">-4%</div>
                                <img src="<?php echo ROHLIK_LAZADA;?>/img/trangbay-lop1/iphone1.jpg" class="anh360" alt=""/>

                            </div>
                            <div class="box-chua-thongtin">
                                <div class="box-ten-sanpham">Apple iPhone 6 16GB (Vàng) - Hàng chính hãng</div>
                                <div class="box-text-deation-giua">17.789.000 VND</div>
                                <div class="box-text-giathuc">16.789.000 VND</div>
                                <div class="box-text-xemngay">XEM NGAY</div>
                                <div class="box-text-daban-chicon">Đã bán: 8 chỉ còn: 30</div>

                            </div>


                        </div>
                        <div class="col-sm-12 box-sanpham-tuongtu">



                            <div class="box-chua-anh-giamgia">
                                <div class="text-tron-giamgia">-9%</div>
                                <img src="<?php echo ROHLIK_LAZADA;?>/img/trangbay-lop1/asus.jpg" class="anh360" alt=""/>

                            </div>
                            <div class="box-chua-thongtin">
                                <div class="box-ten-sanpham">Asus Zenfone 5 A501 1G-8GB (Trắng) - Hàng nhập khẩu</div>
                                <div class="box-text-deation-giua">4.066.800 VND</div>
                                <div class="box-text-giathuc">2.739.000 VND</div>
                                <div class="box-text-xemngay">XEM NGAY</div>
                                <div class="box-text-daban-chicon">Đã bán: 12 chỉ còn: 3</div>

                            </div>


                        </div>
                        <div class="col-sm-12 box-sanpham-tuongtu">



                            <div class="box-chua-anh-giamgia">
                                <div class="text-tron-giamgia">-8%</div>
                                <img src="<?php echo ROHLIK_LAZADA;?>/img/trangbay-lop1/samsung.jpg" class="anh360" alt=""/>

                            </div>
                            <div class="box-chua-thongtin">
                                <div class="box-ten-sanpham">Samsung Galaxy V 4GB 2SIM (Đen)</div>
                                <div class="box-text-deation-giua"> 2.290.000 VND</div>
                                <div class="box-text-giathuc">1.739.000 VND</div>
                                <div class="box-text-xemngay">XEM NGAY</div>
                                <div class="box-text-daban-chicon">Đã bán: 43 chỉ còn: 1</div>

                            </div>


                        </div>
                        <div class="col-sm-12 box-sanpham-tuongtu">



                            <div class="box-chua-anh-giamgia">
                                <div class="text-tron-giamgia">-14%</div>
                                <img src="<?php echo ROHLIK_LAZADA;?>/img/trangbay-lop1/ipad1.jpg" class="anh360" alt=""/>

                            </div>
                            <div class="box-chua-thongtin">
                                <div class="box-ten-sanpham">Máy tính bảng Apple iPad Air 2 64GB 4G (Vàng)</div>
                                <div class="box-text-deation-giua">16.290.000 VND</div>
                                <div class="box-text-giathuc">13.990.000 VND</div>
                                <div class="box-text-xemngay">XEM NGAY</div>
                                <div class="box-text-daban-chicon">Đã bán: 8 chỉ còn: 30</div>

                            </div>


                        </div>
                        <div class="col-sm-12 box-sanpham-tuongtu">



                            <div class="box-chua-anh-giamgia">
                                <div class="text-tron-giamgia">-10%</div>
                                <img src="<?php echo ROHLIK_LAZADA;?>/img/trangbay-lop1/iphone2.jpg" class="anh360" alt=""/>

                            </div>
                            <div class="box-chua-thongtin">
                                <div class="box-ten-sanpham">Apple iPhone 6 32GB (Vàng) - Hàng chính hãng</div>
                                <div class="box-text-deation-giua">16.489.000 VND</div>
                                <div class="box-text-giathuc">15.780.000 VND</div>
                                <div class="box-text-xemngay">XEM NGAY</div>
                                <div class="box-text-daban-chicon">Đã bán: 15 chỉ còn: 13</div>

                            </div>


                        </div>
                    </div>

                    <div class="col-sm-12 margin-top">
                        <div class="col-sm-12 box-the-li">
                            SẢN PHẨM MỚI
                        </div>


                    </div>
                    <div class="col-sm-12 box-full-tuongtu">
                        <div class="col-sm-12 box-sanpham-tuongtu">



                            <div class="box-chua-anh-giamgia">
                                <div class="text-tron-giamgia">-48%</div>
                                <img src="<?php echo ROHLIK_LAZADA;?>/img/trangbay-lop1/lumia.jpg" class="anh360" alt=""/>

                            </div>
                            <div class="box-chua-thongtin">
                                <div class="box-ten-sanpham">Nokia Lumia 730 8GB 2 SIM (Đen)</div>
                                <div class="box-text-deation-giua">6.990.000 VND</div>
                                <div class="box-text-giathuc">3.628.000 VND</div>
                                <div class="box-text-xemngay">XEM NGAY</div>
                                <div class="box-text-daban-chicon">Đã bán: 32 chỉ còn: 4</div>

                            </div>


                        </div>
                        <div class="col-sm-12 box-sanpham-tuongtu">



                            <div class="box-chua-anh-giamgia">
                                <div class="text-tron-giamgia">-7%</div>
                                <img src="<?php echo ROHLIK_LAZADA;?>/img/trangbay-lop1/lenovo.jpg" class="anh360" alt=""/>

                            </div>
                            <div class="box-chua-thongtin">
                                <div class="box-ten-sanpham">Lenovo P70 16GB (Đen)</div>
                                <div class="box-text-deation-giua"> 5.390.000 VND</div>
                                <div class="box-text-giathuc">4.990.000 VND</div>
                                <div class="box-text-xemngay">XEM NGAY</div>
                                <div class="box-text-daban-chicon">Đã bán: 21 chỉ còn: 23</div>

                            </div>


                        </div>
                        <div class="col-sm-12 box-sanpham-tuongtu">



                            <div class="box-chua-anh-giamgia">
                                <div class="text-tron-giamgia">-38%</div>
                                <img src="<?php echo ROHLIK_LAZADA;?>/img/trangbay-lop1/lumia1.jpg" class="anh360" alt=""/>

                            </div>
                            <div class="box-chua-thongtin">
                                <div class="box-ten-sanpham">Nokia Lumia 630 8GB (Đen)</div>
                                <div class="box-text-deation-giua">3.500.000 VND</div>
                                <div class="box-text-giathuc">2.179.000 VND</div>
                                <div class="box-text-xemngay">XEM NGAY</div>
                                <div class="box-text-daban-chicon">Đã bán: 24 chỉ còn: 12</div>

                            </div>


                        </div>
                        <div class="col-sm-12 box-sanpham-tuongtu">



                            <div class="box-chua-anh-giamgia">
                                <div class="text-tron-giamgia">-10%</div>
                                <img src="<?php echo ROHLIK_LAZADA;?>/img/trangbay-lop1/asus1.jpg" class="anh360" alt=""/>

                            </div>
                            <div class="box-chua-thongtin">
                                <div class="box-ten-sanpham">Asus Zenfone C ZC451CG 8GB 2 SIM (Trắng)</div>
                                <div class="box-text-deation-giua">2.550.000 VND</div>
                                <div class="box-text-giathuc">2.290.000 VND</div>
                                <div class="box-text-xemngay">XEM NGAY</div>
                                <div class="box-text-daban-chicon">Đã bán: 24 chỉ còn: 32</div>

                            </div>


                        </div>
                        <div class="col-sm-12 box-sanpham-tuongtu">



                            <div class="box-chua-anh-giamgia">
                                <div class="text-tron-giamgia">-4%</div>
                                <img src="<?php echo ROHLIK_LAZADA;?>/img/trangbay-lop1/iphone1.jpg" class="anh360" alt=""/>

                            </div>
                            <div class="box-chua-thongtin">
                                <div class="box-ten-sanpham">Apple iPhone 6 Plus 64GB (Bạc) - Hàng nhập khẩu</div>
                                <div class="box-text-deation-giua">23.879.000 VND</div>
                                <div class="box-text-giathuc">22.099.000 VND</div>
                                <div class="box-text-xemngay">XEM NGAY</div>
                                <div class="box-text-daban-chicon">Đã bán: 43 chỉ còn: 2</div>

                            </div>


                        </div>
                    </div>

                </div>
            </div>
            <div class="container box-an-360">
                <div class="row">
                    <div class="col-sm-12 row-content-top" id="row-content-top1">
                        <div class="col-sm-2 menu_doc_left">
                            <ul id="tab-menu">
                                <?php
                               
                                foreach ($catalog as $keycat=>$valuecat){
                                ?>
                                <li ><a class="<?php if($keycat==0){ echo 'active-box';}?>" rel="#box-category<?php echo $valuecat['id']?>" href="<?php echo WEBPATH.'/lazada/index/viewproductcat/'.$valuecat['id']?>"> <span class="botron-icon"><i class="fa fa-heart-o"></i></span> <?php echo $valuecat['name']?></a></li>
                                <?php } ?>
                               
                            </ul>
                        </div>
                        <div>
                        <?php
                               
                                foreach ($catalog as $keycat1=>$valuecat1){
                                    $prent_id=$valuecat1['id'];
                                   // print_r($sub_menu[$prent_id]);
                                ?>
                        
                        <div class="col-sm-8 div-tab" id="box-category<?php echo $valuecat1['id']?>">
                            <div class="col-sm-12 nopading">
                                <div class="col-sm-3 box-tablet-50">
                                    <ul id="nav"  >
                                        <?php foreach ($sub_menu[$prent_id] as $keysub=>$valuesub){?>
                                        <li><a href="<?php echo WEBPATH.'/lazada/index/viewproductcat/'.$valuesub['id']?>"> <?php echo $valuesub['name']?></a></li>
                                        <?php } ?>
                                       
                                    </ul>

                                </div>
                                <div class="col-sm-6 nopading">
                                    <div class="col-sm-12 nopading">
                                        <img src="<?php echo WEBPATH_UPLOAD_PATH_IMG.'/thumb_catalog/'.$valuecat1['img'];?>" class="img-responsive" alt="#">  
                                    </div>
                                    <div class="col-sm-12 nopading">
                                        <div class="col-sm-6 nopading">
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/li.khuyenmai/bt1.jpg" class="img-responsive" alt="#"/>
                                        </div>
                                        <div class="col-sm-6 nopading">
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/li.khuyenmai/bt2.jpg" class="img-responsive" alt="#"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-3 box-an-980">
                                    <div class="col-sm-12 nopading">
                                        <img src="<?php echo ROHLIK_LAZADA;?>/img/li.khuyenmai/bt3.jpg"  class="img-responsive" alt="#"/>
                                    </div>
                                    <div class="col-sm-12 nopading">
                                        <img src="<?php echo ROHLIK_LAZADA;?>/img/li.khuyenmai/bt4.jpg"  class="img-responsive" alt="#"/>
                                    </div>
                                    <div class="col-sm-12 nopading">
                                        <img src="<?php echo ROHLIK_LAZADA;?>/img/li.khuyenmai/bt5.jpg"  class="img-responsive" alt="#"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                           
                                <?php } ?>
                        </div>

                        <div class="col-sm-2  menu-right-content">
                            <div class="col-sm-12 border_right_menu">
                                <span class="tieude-menu-right-content">THẢNH THƠI MUA SẮM</span>
                            </div>
                            <div class="col-sm-12 nopading-menu-right">
                                <ul>
                                    <li class="dropdown"><a href="#" data-toggle="modal" data-target=".popup_right_menu" ><span class="botron-icon-dienthoai_me"><i class="fa fa-unlock-alt"></i></span> Thanh toán khi nhận hàng</a>
                                        <div class="modal fade bs-example-modal-lg popup_right_menu" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                                            <div class="modal-dialog modal-lg">
                                                <div class="modal-content EFFORTLESS">
                                                    <div class="row">
                                                        <div  class="col-sm-12 domau-EFFORTLESS">
                                                            <div class="col-sm-12 margin-EFFORTLESS">
                                                                <div class="col-sm-1"></div>
                                                                <div class="col-sm-11">
                                                                    <h5>EFFORTLESS SHOPPING </h5>
                                                                </div>
                                                            </div>
                                                            <div class="col-sm-12 margin-EFFORTLESS">
                                                                <div class="col-sm-1">
                                                                    <span class="botron-icon-dienthoai_me"><i class="fa fa-unlock-alt"></i></span>
                                                                </div>
                                                                <div class="col-sm-11 EFFORTLESS_right">
                                                                    <div  class="col-sm-12 text-EFFORTLESS-dam">Cash on Delivery</div>
                                                                    <div class="col-sm-12 text-EFFORTLESS-nhat"> Use the Cash on Delivery payment method and have product delivered to you and conveniently pay at the doorstep of your home</div>
                                                                    <div class="col-sm-12 text-EFFORTLESS-link"> <a href="">Learn more</a></div>
                                                                </div>
                                                            </div>
                                                            <div class="col-sm-12 margin-EFFORTLESS">
                                                                <div class="col-sm-1">
                                                                    <span class="botron-icon"><i class="fa fa-truck"></i></span>
                                                                </div>
                                                                <div class="col-sm-11 EFFORTLESS_right">
                                                                    <div  class="col-sm-12 text-EFFORTLESS-dam"> Free Delivery</div>
                                                                    <div class="col-sm-12 text-EFFORTLESS-nhat"> Minimum value order at 250.000 VND. For orders below 250.000VND, Fulfillment fee will be charged depending on Billing address</div>
                                                                    <div class="col-sm-12 text-EFFORTLESS-link"> <a href="">Learn more</a></div>
                                                                </div>
                                                            </div>
                                                            <div class="col-sm-12 margin-EFFORTLESS">
                                                                <div class="col-sm-1">
                                                                    <span class="botron-icon"><i class="fa fa-umbrella"></i></span> 
                                                                </div>
                                                                <div class="col-sm-11 EFFORTLESS_right">
                                                                    <div  class="col-sm-12 text-EFFORTLESS-dam"> Buyer Protection Guarantee</div>
                                                                    <div class="col-sm-12 text-EFFORTLESS-nhat"> We want you to love your purchase. If you don’t, send it back and get your money back in 30days (depending on our policy). Click here xxxxxxxxxx for more information.</div>
                                                                    <div class="col-sm-12 text-EFFORTLESS-link"> <a href="">Learn more</a></div>
                                                                </div>
                                                            </div>
                                                            <div class="col-sm-12 margin-EFFORTLESS">
                                                                <div class="col-sm-1">
                                                                    <span class="botron-icon"><i class="fa fa-check"></i></span> 
                                                                </div>
                                                                <div class="col-sm-11 EFFORTLESS_right">
                                                                    <div  class="col-sm-12 text-EFFORTLESS-dam"> Trusted sellers only</div>
                                                                    <div class="col-sm-12 text-EFFORTLESS-nhat"> We are committed to ensure that you shop with conﬁdence on ABC. All sellers listed on Lazada have passed a thorough selection process in order to guarantee you a high quality shopping experience.</div>
                                                                </div>
                                                            </div>
                                                            <div class="col-sm-12 margin-EFFORTLESS">
                                                                <div class="col-sm-1">
                                                                    <span class="botron-icon-dienthoai_me"><i class="fa fa-phone"></i></span>
                                                                </div>
                                                                <div class="col-sm-11 EFFORTLESS_right">
                                                                    <div  class="col-sm-12 text-EFFORTLESS-dam"> Customer Service</div>
                                                                    <div class="col-sm-12 text-EFFORTLESS-nhat">  We would love to hear from you at anytime at www.lazada.vn/contact . For your questions of feedback, please contact our Customer Service team at Hotline (08) xxxx xxxx or (04) xxxx xxxx in working hours:</div>
                                                                </div>
                                                            </div>
                                                            <div class="col-sm-12 margin-EFFORTLESS">
                                                                <div class="col-sm-1">

                                                                </div>
                                                                <div class="col-sm-11 nopading">
                                                                    <div class="col-sm-4 box-hotline">
                                                                        <div class="col-sm-12">
                                                                            <i class="fa fa-phone"></i>  Hotline: HCM (08)3942 1188 or HN (04)7300 1188
                                                                        </div>
                                                                        <div class="col-sm-12 text-EFFORTLESS-footer">
                                                                            <a href="#">Consult the Help Center</a>
                                                                        </div>
                                                                    </div>
                                                                    <div class="col-sm-4 box-ngay-thoigian-lam">
                                                                        <ul>
                                                                            <li>Mon-Fri</li>
                                                                            <li>Sat</li>
                                                                            <li>Sun and Holiday</li>
                                                                        </ul>
                                                                    </div>
                                                                    <div class="col-sm-4 box-ngay-thoigian-lam">
                                                                        <ul>
                                                                            <li>From 7h to 20h</li>
                                                                            <li>From 7h to 18h</li>
                                                                            <li>From 7h to 17h</li>
                                                                        </ul>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>

                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                    <li><a href="#" data-toggle="modal" data-target=".popup_right_menu"><span class="botron-icon"><i class="fa fa-truck"></i></span> Giao hàng toàn uốc</a></li>
                                    <li><a href="#" data-toggle="modal" data-target=".popup_right_menu"><span class="botron-icon"><i class="fa fa-umbrella"></i></span> Trả hàng miễn phí trong 30 ngày</a></li>
                                    <li><a href="#" data-toggle="modal" data-target=".popup_right_menu"><span class="botron-icon"><i class="fa fa-check"></i></span> Bán hàng uy tín</a></li>
                                    <li><a href="#" data-toggle="modal" data-target=".popup_right_menu"><span class="botron-icon-dienthoai_me"><i class="fa fa-phone"></i></span> Dịch vụ CSKH chu đáo</a></li>
                                    <li><a href="#" data-toggle="modal" data-target=".popup_right_menu"> Xem thêm</a></li>

                                </ul>
                            </div>
                            <div class="col-sm-12 box-an-980">
                                <div class="col-sm-12 border_right_menu">
                                    <span class="tieude-menu-right-content"> Bán hàng cũng ABC</span>
                                </div>
                                <div class="col-sm-12">
                                    <span class="tieude-menu-right-nho" > Cửa hàng trực tuyến của chính bạn, <a href="#"> tìm hiểu thêm
                                        </a></span>
                                </div>
                                <div class="col-sm-12 border_right_menu">
                                    <span class="tieude-menu-right-content">  MUA SẮM MỌI LÚC, MỌI NƠI</span>
                                </div>
                                <div class="col-sm-12">
                                    <img src=img/uangcao_menu_right/voucher-179x190.jpg  class="img-responsive" alt="#"/>
                                </div>
                            </div>
                        </div>
                    </div>




                </div>
                <div class="row content-magin-top">
                    <div class="col-sm-12">
                        <div class="col-sm-2 khoicontent-left">
                            THƯƠNG HIỆU HÀNG ĐẦU
                        </div>
                        <div class="col-sm-8 khoicontent-center">
                            <div class="col-sm-12 box-nho-khoicontent-center"></div>
                        </div>
                        <div class="col-sm-2 khoicontent-right">
                            NHÀ BÁN HÀNG TIÊU BIỂU
                        </div>
                    </div>
                    <div class="col-sm-12 box-thuonghieu">
                        <div class="col-sm-2 nopading">
                            <div class="col-sm-12 thuonghieutrongngay">
                                THƯƠNG HIỆU TRONG NGÀY
                            </div>
                            <div class="col-sm-12 thuonghieu-bottom">
                                <img src="<?php echo ROHLIK_LAZADA;?>/img/thuonghieuhangdau/giamden.jpg" class="img-responsive anhlogothuonghieu" alt="#"/>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="row">
                                <?php foreach ($data_manu as $key=>$value){?>
                                <div class="box-thuonghieu-noitieng">
                                    <a href="<?php echo WEBPATH ?>/lazada/manufatured"><img src="<?php echo WEBPATH_UPLOAD_PATH_IMG.$value['img'];?>" class="img-responsive" alt="#"/></a>  
                                </div>
                                <?php } ?>
                            </div>
                            

                        </div>
                        <div class="col-sm-2 nopading">
                            <div class="col-sm-12 nopading">
                                <a href="#">   <img src="<?php echo ROHLIK_LAZADA;?>/img/Suntek_Logo_HP.jpg" class="img-responsive" alt="#"/></a>
                            </div>
                            <div class="col-sm-12 thuonghieu-bottom">
                                <a href="#">   <img src="<?php echo ROHLIK_LAZADA;?>/img/Suntek_HP.jpg" class="img-responsive" alt="#"/></a>
                            </div>
                        </div>
                    </div>
                </div>
                <?php foreach ($data_catalog_index as $keycat_index=>$valuecat_index){?>
                <div id="tang-<?php echo $keycat_index +=1;?>" class="row content-magin-top">
                    <div class="col-sm-12">
                        <div class="col-sm-12 content-tang-mobile-tablet">
                            <div class="col-sm-12 content-tang-mobile-tablet-nho">
                                <div class="col-sm-2 mobi-tablet-nho-left">TẦNG</div>
                                <div class="col-sm-10 mobi-tablet-nho-right">
                                    <div class="col-sm-1 nopading">
                                        <div class="so-tang-1">1</div>
                                    </div>
                                    <div class="col-sm-9 mobi-tablet-nho-nho-center">
                                        <a href="#">  ĐIỆN THOẠI & TABLET</a>
                                    </div>
                                    <div class="col-sm-2">
                                        <div class="icon-giua-left">
                                            <i onclick="showdiv(<?php echo $keycat_index +=1;?>);" class="show-div fa fa-angle-down"></i>
                                        </div>
                                        <div class="icon-giua-center">
                                            <i class="fa fa-bolt"></i>
                                        </div>
                                        <div class="icon-giua-right">
                                            <i onclick="showdiv(<?php echo $keycat_index -=2;?>);" class="fa fa-angle-up"></i>
                                        </div>
                                    </div>
                                </div> 
                            </div>
                        </div>
                        <div class="col-sm-12 contet-menu-img">
                            <div class="col-sm-2 menu-bottom-left">
                                <div class="col-sm-12 tieude-menu-left">GỢI Ý MUA SẮM</div>
                                <ul>
                                    <li><a href="#">Smartphone</a></li>
                                    <li><a href="#">Điện thoại phổ thông</a></li>
                                    <li><a href="#">Phụ kiện điện thoại</a></li>
                                    <li><a href="#">Máy tính bảng hỗ trợ chức năng thoại</a></li>
                                    <li><a href="#">Deal giá sốc</a></li>
                                    <li><a href="#">Máy tính bảng không hỗ trợ chức năng thoại</a></li>
                                    <li><a href="#">Tai nghe</a></li>
                                    <li><a href="#">Phụ kiện máy tính bảng</a></li>
                                    <li><a href="#">Điện thoại bàn</a></li>
                                    <li><a href="#">Sim/USB 3G</a></li>

                                </ul>
                            </div>
                            <div class="col-sm-8 nopading">
                                <div class="col-sm-3">
                                    <div class="col-sm-12 margin-top-nhieu">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/li.dienthoai_tablet/apple.jpg" class="img-responsive" alt="#"/>
                                        </a>
                                    </div>
                                    <div class="col-sm-12 margin-top-nhieu">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/li.dienthoai_tablet/htc.jpg" class="img-responsive" alt="#"/>
                                        </a>
                                    </div>
                                    <div class="col-sm-12 margin-top-nhieu">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/li.dienthoai_tablet/nokia.jpg" class="img-responsive" alt="#"/>
                                        </a>
                                    </div>
                                    <div class="col-sm-12 margin-top-nhieu">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/li.dienthoai_tablet/samsung.jpg" class="img-responsive" alt="#"/>
                                        </a>
                                    </div>
                                    <div class="col-sm-12 margin-top-nhieu">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/li.dienthoai_tablet/alcatel.jpg" class="img-responsive" alt="#"/>
                                        </a>
                                    </div>
                                    <div class="col-sm-12 margin-top-nhieu">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/li.dienthoai_tablet/acer.jpg" class="img-responsive" alt="#"/>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-sm-6 nopading">
                                    <a href="#"> 
                                        <img src="<?php echo ROHLIK_LAZADA;?>/img/li.dienthoai_tablet/VN.400x530.jpg" class="img-responsive" alt="#"/>
                                    </a>
                                </div>
                                <div class="col-sm-3 nopading">
                                    <div class="col-sm-12 nopading">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/li.dienthoai_tablet/pinsacduphong(200x353).jpg" class="img-responsive" alt="#"/>
                                        </a>
                                    </div>
                                    <div class="col-sm-12 nopading">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/li.dienthoai_tablet/4gb_2sim(1).jpg" class="img-responsive" alt="#"/>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-2 nopading">
                                <div class="col-sm-12 nopading">
                                    <a href="#"> 
                                        <img src="<?php echo ROHLIK_LAZADA;?>/img/li.dienthoai_tablet/VN.2015-04-(6).jpg" class="img-responsive" alt="#"/>
                                    </a>
                                </div>
                                <div class="col-sm-12 nopading">
                                    <a href="#"> 
                                        <img src="<?php echo ROHLIK_LAZADA;?>/img/li.dienthoai_tablet/hang_refur(3).jpg" class="img-responsive" alt="#"/>
                                    </a>
                                </div>
                                <div class="col-sm-12 nopading">
                                    <a href="#"> 
                                        <img src="<?php echo ROHLIK_LAZADA;?>/img/li.dienthoai_tablet/VN.2015-04-(4).jpg" class="img-responsive" alt="#"/>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php } ?>
                

                

                
                
                
                
                
                
                
                <div class="row">
                    <div class="col-sm-12 ">
                        <div class="col-sm-12 box-san-pham-ban-chay"> <h4>NHỮNG SẢN PHẨM BÁN CHẠY HÀNG ĐẦU</h4></div>
                    </div>
                    <div class="col-sm-12 margin-top">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <!-- Indicators -->
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>


                            </ol>

                            <!-- Wrapper for slides -->
                            <div class="carousel-inner " role="listbox">
                                <div class="item active">
                                    <div class="box-chua-anhjs">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/slide-java/1.jpg" class="img-responsive" alt="#"/>
                                            <h5>Apple iPhone 6 16GB (Vàng)</h5>
                                            <div class="gia-sanpham">429.000 VND</div>
                                        </a>

                                    </div>
                                    <div class="box-chua-anhjs">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/slide-java/2.jpg" class="img-responsive" alt="#"/>
                                            <h5>Bếp gas hồng ngọa Kokoro KR</h5>
                                            <div class="gia-sanpham">419.000 VND</div>
                                        </a>
                                    </div>
                                    <div class="box-chua-anhjs">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/slide-java/3.jpg" class="img-responsive" alt="#"/>
                                            <h5>Bộ máy khoan búa BLACK & DECKER HD560K-B1</h5>
                                            <div class="gia-sanpham">949.000 VND</div>
                                        </a>
                                    </div>
                                    <div class="box-chua-anhjs">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/slide-java/4.jpg" class="img-responsive" alt="#"/>
                                            <h5>Máy hút bụi cầm tay Omi Nanny V1(Xanh lá)</h5>
                                            <div class="gia-sanpham">499.000 VND</div>
                                        </a>
                                    </div>
                                    <div class="box-chua-anhjs">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/slide-java/5.jpg" class="img-responsive" alt="#"/>
                                            <h5>Nokia Lumia 630 8GB(Đen)</h5>
                                            <div class="gia-sanpham">2.628.000 VND</div>
                                        </a>
                                    </div>
                                    <div class="box-chua-anhjs">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/slide-java/6.jpg" class="img-responsive" alt="#"/>
                                            <h5>Nokkia Lumia 730 8GB 2 SIM (Đen)</h5>
                                            <div class="gia-sanpham">3.429.000 VND</div>
                                        </a>
                                    </div>

                                </div>
                                <div class="item">
                                    <div class="box-chua-anhjs">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/slide-java/7.jpg" class="img-responsive" alt="#"/>
                                            <h5>Nokia Lumia 630 8GB(Đen)</h5>
                                            <div class="gia-sanpham">2.429.000 VND</div>
                                        </a>
                                    </div>
                                    <div class="box-chua-anhjs">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/slide-java/8.jpg" class="img-responsive" alt="#"/>

                                            <h5>ĐTDĐ Suntek A8+ 2 SIM kiêm pin sạc dự phòng (Đen)</h5>
                                            <div class="gia-sanpham">429.000 VND</div>
                                        </a>
                                    </div>
                                    <div class="box-chua-anhjs">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/slide-java/9.jpg" class="img-responsive" alt="#"/>
                                            <h5>Đồng hồ camera ngụy trang SC 8GB Hongkong electronics(Bạc)</h5>
                                            <div class="gia-sanpham">479.000 VND</div>
                                        </a>
                                    </div>
                                    <div class="box-chua-anhjs">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/slide-java/10.jpg" class="img-responsive" alt="#"/>
                                            <h5>ĐTDĐ Suntek A8+ 2 SIM kiêm pin sạc dự phòng (Đen)</h5>
                                            <div class="gia-sanpham">429.000 VND</div>
                                        </a>
                                    </div>
                                    <div class="box-chua-anhjs">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/slide-java/3.jpg" class="img-responsive" alt="#"/>
                                            <h5>Bộ máy khoan búa BLACK & DECKER HD560K-B1</h5>
                                            <div class="gia-sanpham">429.000 VND</div>
                                        </a>
                                    </div>
                                    <div class="box-chua-anhjs">
                                        <a href="#"> 
                                            <img src="<?php echo ROHLIK_LAZADA;?>/img/slide-java/5.jpg" class="img-responsive" alt="#"/>
                                            <h5>Nokia Lumia 630 8GB(Đen)</h5>
                                            <div class="gia-sanpham">2.628.000 VND</div>
                                        </a>
                                    </div>

                                </div>



                            </div>

                            <!-- Controls -->
                            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">abc</span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">bgb</span>
                            </a>

                        </div> 
                    </div>
                </div>
            </div>






        </article>
<style>
    #tab-menu li a{
        
        text-transform: uppercase;
    }
    .div-tab{
        display: none;
        
    }
</style>