<?php

use Zend\Session\Container;

$session_user = new Container('userlogin');
$user_name = $session_user->username;
$id_Us =$session_user->idus;
?>
<article>

    <div class="container">
        <div class="row box-an-767">

            <div  class="col-sm-12">
                <div id="abc" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="3"></li>


                    </ol>

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner " role="listbox">
                        <div class="item active">
                            <div class="box-anhjs">
                                <a href="#"> 
                                    <img src="<?php echo ROHLIK_LAZADA; ?>/lazadanew/img/slide-360/s1.jpg" class="img-responsive" alt="#"/>
                                </a>
                            </div>



                        </div>
                        <div class="item">
                            <div class="box-anhjs">
                                <a href="#"> 
                                    <img src="<?php echo ROHLIK_LAZADA; ?>/lazadanew/img/slide-360/s2.jpg" class="img-responsive" alt="#"/>
                                </a>
                            </div>


                        </div>

                        <div class="item">
                            <div class="box-anhjs">
                                <a href="#"> 
                                    <img src="<?php echo ROHLIK_LAZADA; ?>/lazadanew/img/slide-360/s3.jpg" class="img-responsive" alt="#"/>
                                </a>
                            </div>


                        </div>

                        <div class="item">
                            <div class="box-anhjs">
                                <a href="#"> 
                                    <img src="<?php echo ROHLIK_LAZADA; ?>/lazadanew/img/slide-360/s4.jpg" class="img-responsive" alt="#"/>
                                </a>
                            </div>


                        </div>

                    </div>

                    <!-- Controls -->
                    <a class="left carousel-control icon-right" href="#abc" role="button" data-slide="prev">
                        <span class="fa fa-chevron-circle-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control icon-right" href="#abc" role="button" data-slide="next">
                        <span class="fa fa-chevron-circle-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>

                </div> 
            </div>

            <div class="col-sm-12 margin-top-nhieu">
                <div class="menu">

                    <div class="menuresponsive">
                        <a href="#menu">

                            <div class="col-sm-12 box-the-li">
                                TẤT CẢ DANH MỤC
                            </div>
                        </a>
                    </div>


                </div>
            </div>
            <div class="col-sm-12 margin-top">
                <div class="col-sm-12 box-the-li">
                    SẢN PHẨM BÁN CHẠY
                </div>


            </div>
            <div class="col-sm-12 box-full-tuongtu">
                <div class="col-sm-12 box-sanpham-tuongtu">



                    <div class="box-chua-anh-giamgia">
                        <div class="text-tron-giamgia">-4%</div>
                        <img src="<?php echo ROHLIK_LAZADA; ?>/lazadanew/img/trangbay-lop1/iphone1.jpg" class="anh360" alt=""/>

                    </div>
                    <div class="box-chua-thongtin">
                        <div class="box-ten-sanpham">Apple iPhone 6 16GB (Vàng) - Hàng chính hãng</div>
                        <div class="box-text-deation-giua">17.789.000 VND</div>
                        <div class="box-text-giathuc">16.789.000 VND</div>
                        <div class="box-text-xemngay">XEM NGAY</div>
                        <div class="box-text-daban-chicon">Đã bán: 8 chỉ còn: 30</div>

                    </div>


                </div>
                <div class="col-sm-12 box-sanpham-tuongtu">



                    <div class="box-chua-anh-giamgia">
                        <div class="text-tron-giamgia">-9%</div>
                        <img src="<?php echo ROHLIK_LAZADA; ?>/lazadanew/img/trangbay-lop1/asus.jpg" class="anh360" alt=""/>

                    </div>
                    <div class="box-chua-thongtin">
                        <div class="box-ten-sanpham">Asus Zenfone 5 A501 1G-8GB (Trắng) - Hàng nhập khẩu</div>
                        <div class="box-text-deation-giua">4.066.800 VND</div>
                        <div class="box-text-giathuc">2.739.000 VND</div>
                        <div class="box-text-xemngay">XEM NGAY</div>
                        <div class="box-text-daban-chicon">Đã bán: 12 chỉ còn: 3</div>

                    </div>


                </div>
                <div class="col-sm-12 box-sanpham-tuongtu">



                    <div class="box-chua-anh-giamgia">
                        <div class="text-tron-giamgia">-8%</div>
                        <img src="<?php echo ROHLIK_LAZADA; ?>/lazadanew/img/trangbay-lop1/samsung.jpg" class="anh360" alt=""/>

                    </div>
                    <div class="box-chua-thongtin">
                        <div class="box-ten-sanpham">Samsung Galaxy V 4GB 2SIM (Đen)</div>
                        <div class="box-text-deation-giua"> 2.290.000 VND</div>
                        <div class="box-text-giathuc">1.739.000 VND</div>
                        <div class="box-text-xemngay">XEM NGAY</div>
                        <div class="box-text-daban-chicon">Đã bán: 43 chỉ còn: 1</div>

                    </div>


                </div>
                <div class="col-sm-12 box-sanpham-tuongtu">



                    <div class="box-chua-anh-giamgia">
                        <div class="text-tron-giamgia">-14%</div>
                        <img src="<?php echo ROHLIK_LAZADA; ?>/lazadanew/img/trangbay-lop1/ipad1.jpg" class="anh360" alt=""/>

                    </div>
                    <div class="box-chua-thongtin">
                        <div class="box-ten-sanpham">Máy tính bảng Apple iPad Air 2 64GB 4G (Vàng)</div>
                        <div class="box-text-deation-giua">16.290.000 VND</div>
                        <div class="box-text-giathuc">13.990.000 VND</div>
                        <div class="box-text-xemngay">XEM NGAY</div>
                        <div class="box-text-daban-chicon">Đã bán: 8 chỉ còn: 30</div>

                    </div>


                </div>
                <div class="col-sm-12 box-sanpham-tuongtu">



                    <div class="box-chua-anh-giamgia">
                        <div class="text-tron-giamgia">-10%</div>
                        <img src="<?php echo ROHLIK_LAZADA; ?>/lazadanew/img/trangbay-lop1/iphone2.jpg" class="anh360" alt=""/>

                    </div>
                    <div class="box-chua-thongtin">
                        <div class="box-ten-sanpham">Apple iPhone 6 32GB (Vàng) - Hàng chính hãng</div>
                        <div class="box-text-deation-giua">16.489.000 VND</div>
                        <div class="box-text-giathuc">15.780.000 VND</div>
                        <div class="box-text-xemngay">XEM NGAY</div>
                        <div class="box-text-daban-chicon">Đã bán: 15 chỉ còn: 13</div>

                    </div>


                </div>
            </div>

            <div class="col-sm-12 margin-top">
                <div class="col-sm-12 box-the-li">
                    SẢN PHẨM MỚI
                </div>


            </div>
            <div class="col-sm-12 box-full-tuongtu">
                <div class="col-sm-12 box-sanpham-tuongtu">



                    <div class="box-chua-anh-giamgia">
                        <div class="text-tron-giamgia">-48%</div>
                        <img src="<?php echo ROHLIK_LAZADA; ?>/lazadanew/img/trangbay-lop1/lumia.jpg" class="anh360" alt=""/>

                    </div>
                    <div class="box-chua-thongtin">
                        <div class="box-ten-sanpham">Nokia Lumia 730 8GB 2 SIM (Đen)</div>
                        <div class="box-text-deation-giua">6.990.000 VND</div>
                        <div class="box-text-giathuc">3.628.000 VND</div>
                        <div class="box-text-xemngay">XEM NGAY</div>
                        <div class="box-text-daban-chicon">Đã bán: 32 chỉ còn: 4</div>

                    </div>


                </div>
                <div class="col-sm-12 box-sanpham-tuongtu">



                    <div class="box-chua-anh-giamgia">
                        <div class="text-tron-giamgia">-7%</div>
                        <img src="<?php echo ROHLIK_LAZADA; ?>/lazadanew/img/trangbay-lop1/lenovo.jpg" class="anh360" alt=""/>

                    </div>
                    <div class="box-chua-thongtin">
                        <div class="box-ten-sanpham">Lenovo P70 16GB (Đen)</div>
                        <div class="box-text-deation-giua"> 5.390.000 VND</div>
                        <div class="box-text-giathuc">4.990.000 VND</div>
                        <div class="box-text-xemngay">XEM NGAY</div>
                        <div class="box-text-daban-chicon">Đã bán: 21 chỉ còn: 23</div>

                    </div>


                </div>
                <div class="col-sm-12 box-sanpham-tuongtu">



                    <div class="box-chua-anh-giamgia">
                        <div class="text-tron-giamgia">-38%</div>
                        <img src="<?php echo ROHLIK_LAZADA; ?>/lazadanew/img/trangbay-lop1/lumia1.jpg" class="anh360" alt=""/>

                    </div>
                    <div class="box-chua-thongtin">
                        <div class="box-ten-sanpham">Nokia Lumia 630 8GB (Đen)</div>
                        <div class="box-text-deation-giua">3.500.000 VND</div>
                        <div class="box-text-giathuc">2.179.000 VND</div>
                        <div class="box-text-xemngay">XEM NGAY</div>
                        <div class="box-text-daban-chicon">Đã bán: 24 chỉ còn: 12</div>

                    </div>


                </div>
                <div class="col-sm-12 box-sanpham-tuongtu">



                    <div class="box-chua-anh-giamgia">
                        <div class="text-tron-giamgia">-10%</div>
                        <img src="<?php echo ROHLIK_LAZADA; ?>/lazadanew/img/trangbay-lop1/asus1.jpg" class="anh360" alt=""/>

                    </div>
                    <div class="box-chua-thongtin">
                        <div class="box-ten-sanpham">Asus Zenfone C ZC451CG 8GB 2 SIM (Trắng)</div>
                        <div class="box-text-deation-giua">2.550.000 VND</div>
                        <div class="box-text-giathuc">2.290.000 VND</div>
                        <div class="box-text-xemngay">XEM NGAY</div>
                        <div class="box-text-daban-chicon">Đã bán: 24 chỉ còn: 32</div>

                    </div>


                </div>
                <div class="col-sm-12 box-sanpham-tuongtu">



                    <div class="box-chua-anh-giamgia">
                        <div class="text-tron-giamgia">-4%</div>
                        <img src="<?php echo ROHLIK_LAZADA; ?>/lazadanew/img/trangbay-lop1/iphone1.jpg" class="anh360" alt=""/>

                    </div>
                    <div class="box-chua-thongtin">
                        <div class="box-ten-sanpham">Apple iPhone 6 Plus 64GB (Bạc) - Hàng nhập khẩu</div>
                        <div class="box-text-deation-giua">23.879.000 VND</div>
                        <div class="box-text-giathuc">22.099.000 VND</div>
                        <div class="box-text-xemngay">XEM NGAY</div>
                        <div class="box-text-daban-chicon">Đã bán: 43 chỉ còn: 2</div>

                    </div>


                </div>
            </div>

        </div>
    </div>
    <div class="container box-an-360">
        <div class="row">
            <div class="col-sm-12 row-content-top" id="row-content-top1">
                <div class="col-sm-2 col-xs-12 menu_doc_left ">
                    <ul id="tab-menu">
                        <?php
                        foreach ($catalog as $keycat => $valuecat) {
                            ?>
                            <li ><a class="<?php
                                if ($keycat == 0) {
                                    echo 'active-tab';
                                }
                                ?>" rel='#category-box<?php echo $valuecat['id'] ?>' href="<?php echo WEBPATH . '/lazada/index/viewproductcat/' . $valuecat['id'] ?>">  <div class="hinhtron ">Tầng <?php echo $keycat +=1; ?></div><?php echo $valuecat['name'] ?></a></li>
                                <?php } ?>
                    </ul>
                </div>
                <div class="right-mb">
                    <?php
                    foreach ($catalog as $keycat1 => $valuecat1) {
                        $prent_id = $valuecat1['id'];
                        // print_r($product_sales[$prent_id]);
                        ?>
                        <div class="col-sm-10 div-tab" id="category-box<?php echo $valuecat1['id'] ?>">
                            <div class="col-sm-12 nopading">
                                <div class="row nomargin">
                                    <div class="col-sm-3 box-tablet-50">

                                        <?php
                                        foreach ($product_sales[$prent_id] as $keysl => $valuesl) {
                                            // Sản phẩm khuyến mãi của danh mục
                                            ?>
                                            <div class="col-sm-12 box-an-980">
                                                <a href="<?php echo WEBPATH . '/lazada/index/detailproduct/' . $valuesl['id'] ?>">
                                                    <img src="<?php echo WEBPATH_UPLOAD_PATH_IMG_THUNB_ . $valuesl['img']; ?>" class="img-responsive" alt="#" onerror=this.src="<?php echo ROHLIK_LAZADA; ?>/img/no-product.png" />
                                                    <p><?php echo $valuesl['name'] ?></p>
                                                </a>
                                            </div>
                                        <?php }
                                        ?>
                                    </div>
                                    <div class="col-sm-6 nopading">
                                        <div class="col-sm-12 nopading">
                                            <img src="<?php echo WEBPATH_UPLOAD_PATH_IMG . '/thumb_catalog/' . $valuecat1['img']; ?>" class="img-responsive" alt="#">  
                                        </div>
                                        <div class="col-sm-12 nopading">
                                            <?php
                                            foreach ($product_hot[$prent_id] as $keyhot => $valuehot) {
                                                // sản phẩm hot của danh mục
                                                ?>
                                                <div class="col-sm-6 nopading">
                                                    <a href="<?php echo WEBPATH . '/lazada/index/detailproduct/' . $valuehot['id'] ?>">
                                                        <img src="<?php echo WEBPATH_UPLOAD_PATH_IMG_THUNB_ . $valuehot['img']; ?>"  class="img-responsive" alt="#" onerror=this.src="<?php echo ROHLIK_LAZADA; ?>/img/no-product.png" />
                                                        <p><?php echo $valuehot['name'] ?></p>
                                                    </a>
                                                    <p style="color:#BD1F25"><?php if($valuehot['price'] !=0){echo $valuehot['price'];} ?> Kč</p>
                                                </div>
                                            <?php } ?>
                                        </div>
                                    </div>
                                    <div class="col-sm-3 box-an-980">
                                        <?php
                                        foreach ($product_featured[$prent_id] as $keyft => $valueft) {
                                            // sản phẩm nổi bật của danh mục
                                            ?>
                                            <div class="col-sm-12 nopading">
                                                <a href="<?php echo WEBPATH . '/lazada/index/detailproduct/' . $valueft['id'] ?>">
                                                    <img src="<?php echo WEBPATH_UPLOAD_PATH_IMG_THUNB_ . $valueft['img']; ?>"  class="img-responsive" alt="#" onerror=this.src="<?php echo ROHLIK_LAZADA; ?>/img/no-product.png" />
                                                    <p><?php echo $valueft['name'] ?></p>
                                                </a>
                                                <p style="color:#BD1F25"><?php if($valueft['price'] !=0){echo number_format($valueft['price'], 0, ',', '.') . 'VNĐ';}  ?></p>
                                            </div>
                                        <?php } ?>
                                    </div>

                                </div>

                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>




        </div>
        <?php
        $so_tang = '';
        foreach ($catalog as $keycat_index => $valuecat_index) {
            $so_tang ++;
            $id_cat = $valuecat_index['id'];
            //$prent_id = $valuecat1['id'];
            // print_r($sub_menu[$prent_id]);
            ?>
            <div id="tang-<?php echo $so_tang; ?>" class="row content-magin-top">
                <div class="col-sm-12">
                    <div class="col-sm-12 content-tang-mobile-tablet">
                        <div class="col-sm-12 content-tang-mobile-tablet-nho">
                            <div class="col-sm-2 mobi-tablet-nho-left"><span class="name-destop">TẦNG</span><span class="name-mb"><?php echo $valuecat_index['name'] ?></span></div>
                            <div class="col-sm-10 mobi-tablet-nho-right">
                                <div class="col-sm-1 nopading">
                                    <div class="so-tang-1"><?php echo $so_tang; ?></div>
                                </div>
                                <div class="col-sm-9 mobi-tablet-nho-nho-center">
                                    <a href="<?php echo WEBPATH . '/lazada/index/viewproductcat/' . $valuecat_index['id'] ?>"><?php echo $valuecat_index['name'] ?></a>
                                </div>
                                <div class="col-sm-2">
                                    <div class="icon-giua-left">
                                        <i onclick="showdiv(<?php echo $so_tang + 1; ?>);" class="show-div fa fa-angle-down"></i>

                                    </div>
                                    <div class="icon-giua-center">
                                        <i class="fa fa-bolt"></i>
                                    </div>
                                    <div class="icon-giua-right">
                                        <i onclick="showdiv(<?php echo $so_tang - 1; ?>);" class="show-div fa fa-angle-up"></i>

                                    </div>
                                </div>
                            </div> 
                        </div>
                    </div>
                    <div class="col-sm-12 contet-menu-img">
                        <div class="col-sm-2 menu-bottom-left">
                            <div class="col-sm-12 tieude-menu-left"><!--alkohol--></div>
                            <ul>
                                <?php foreach ($sub_menu[$id_cat] as $keysub => $valuesub) { ?>
                                    <li>
                                        <a href="<?php echo WEBPATH . '/lazada/index/viewproductcat/' . $valuesub['id'] ?>">
                                            <div class="checkbox">
                                                <label>
                                                    <?php echo $valuesub['name']; ?>
                                                   <!-- <input type="checkbox">brandy a koňak-->
                                                </label>
                                            </div>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>


                        </div>

                        <div class="col-sm-10 nopading">
                            <div class="row">
                                <div class="col-md-12">
                                    <!-- <div class="filter">
                                         <ul>
                                             <li><label><input type="radio" name="filter" class="noreplace onChangeAjax"  checked=""><span class="like-radio"></span>Podle oblíbenosti</label></li>
                                             <li><label><input type="radio" name="filter" class="noreplace onChangeAjax"><span class="like-radio"></span>Od nejdražšího</label></li>
                                             <li><label><input type="radio" name="filter" class="noreplace onChangeAjax"><span class="like-radio"></span>Od nejlevnějšího</label></li>

                                             <li class="checkbox"><label><input type="checkbox" name="filter" value="" class="noreplace onChangeAjax pushCheckToGtm"><span class="like-checkbox"></span>mé oblíbené</label></li>
                                         </ul>
                                     </div>-->


                                </div>
                            </div>
                            <div class="row top-bottom">
                                <?php foreach ($productcat_index[$id_cat] as $keypro => $valuepro) {
                                    $get_wishlist=$product_wisht[$valuepro['id']];
                                    ?>
                                    <div class="col-md-3 col-sm-6">
                                        <div class="img-detail-main">
                                            <div class="img-sp-fav">
                                                <?php
                                                if($valuepro['id'] ==$get_wishlist['product_ID'] && $get_wishlist['customer_ID'] == $id_Us ){
                                                    echo '<span onclick="deleitemswish('.$valuepro['id'].',1);" ><i class="fa-red fa fa-heart"></i></span>';
                                                }  else {                                           
                                                
                                                ?>
                                                <span <?php
                                                if ($user_name == null) {
                                                    echo 'class="wishlist"';
                                                } else {
                                                    echo 'onclick="addwishlist(' . $valuepro['id'] . ');"';
                                                }
                                                ?> ><i class="fa fa-heart"></i></span>
                                                <?php } ?>
                                                <!--<div class="giamprice"> -33 %</div>-->
                                                <a href="<?php echo WEBPATH . '/lazada/index/detailproduct/' . $valuepro['id'] ?>">
                                                    <img src="<?php echo WEBPATH_UPLOAD_PATH_IMG_THUNB_ . $valuepro['img']; ?>" alt="" onerror=this.src="<?php echo ROHLIK_LAZADA; ?>/img/no-product.png" />
                                                </a>
                                            </div>
                                            <div class="title-detail">

                                                <span class="title-sp height-name"><a href="<?php echo WEBPATH . '/lazada/index/detailproduct/' . $valuepro['id'] ?>" ><?php echo $valuepro['name'] ?></a>

                                                </span>
												<?php if($valuepro['price'] !=0){ ?>
                                                <p> <span class="pricebuy">
                                                        <?php
                                                        if($valuepro['sale_products']==1){														
                                                        echo number_format($valuepro['price'] - ($valuepro['price'] * $valuepro['promotions']/100), 0, ',', '.').'VNĐ'; 
                                                        }else{
                                                        echo number_format($valuepro['price'],0, ',', '.').  'VNĐ';
                                                        }
                                                        ?>
                                                    </span>
                                                     <?php													
                                                        if($valuepro['sale_products']==1){
                                                   echo  '<del>'.number_format($valuepro['price'], 0, ',', '.').'VNĐ  </del>';
                                                         } ?>
                                                    <!--<span class="priceold"> (<?php echo $valuepro['price'] ?>&nbsp;Kč/kg)</span>-->
                                                </p>
												<?php } ?>
                                                <p class="adddetail">
                                                    <input type="hidden" id="number-pro<?php echo $valuepro['id']; ?>" value="<?php echo $valuepro['availability'] ?>"/>
                                                    <i  onclick="truqty(<?php echo $valuepro['id'] ?>);" class="fa fa-minus-circle"></i>
                                                    <input type="text" value="1" id="getqty<?php echo $valuepro['id'] ?>" class="">
                                                    <i  onclick="congqty(<?php echo $valuepro['id'] ?>);" class="fa fa-plus-circle"></i> 
                                                    <button onclick="addcart(<?php echo $valuepro['id'] ?>);" class="btn btn-success">Đặt Hàng</button>
                                                </p>

                                            </div>


                                        </div>
                                    </div>
                                <?php } ?>



                            </div>



                        </div>

                    </div>
                </div>
            </div>

        <?php } ?>







        <div class="row display-mb">
            <div class="col-sm-12 ">
                <div class="col-sm-12 box-san-pham-ban-chay"> <h4>NHỮNG SẢN PHẨM BÁN CHẠY HÀNG ĐẦU</h4></div>
            </div>
            <div class="col-sm-12 margin-top">
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="1"></li>


                    </ol>

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner " role="listbox">
                        <div class="item active">
                            <?php foreach ($product_new as $keypro => $valuepro) { ?>
                                <div class="box-chua-anhjs">
                                    <a href="<?php echo WEBPATH . '/lazada/index/detailproduct/' . $valuepro['id'] ?>"> 
                                        <figure>
                                            <center>
                                                <img src="<?php echo WEBPATH_UPLOAD_PATH_IMG_THUNB_ . $valuepro['img']; ?>" class="img-responsive" alt="#" onerror=this.src="<?php echo ROHLIK_LAZADA; ?>/img/no-product.png" />
                                            </center>
                                        </figure>
                                        <h5><?php echo $valuepro['name'] ?></h5>
                                        <div class="gia-sanpham"><?php if($valuepro['price'] !=0){echo number_format($valuepro['price'], 0, ',', '.') . 'VNĐ';} ?></div>
                                    </a>

                                </div>
                            <?php } ?>

                        </div>
                        <div class="item">
                            <?php foreach ($product_new as $keypro => $valuepro) { ?>
                                <div class="box-chua-anhjs">
                                    <a href="<?php echo WEBPATH . '/lazada/index/detailproduct/' . $valuepro['id'] ?>"> 
                                        <figure>
                                            <center>
                                                <img src="<?php echo WEBPATH_UPLOAD_PATH_IMG_THUNB_ . $valuepro['img']; ?>" class="img-responsive" alt="#" onerror=this.src="<?php echo ROHLIK_LAZADA; ?>/img/no-product.png" />
                                            </center>
                                        </figure>
                                        <h5><?php echo $valuepro['name'] ?></h5> 
                                        <div class="gia-sanpham"><?php if($valuepro['price'] !=0){ echo  number_format($valuepro['price'], 0, ',', '.') . 'VNĐ';} ?> </div>
                                    </a>

                                </div>
                            <?php } ?>



                        </div>



                    </div>

                    <!-- Controls -->
                    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">abc</span>
                    </a>
                    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">bgb</span>
                    </a>

                </div> 
            </div>
        </div>
    </div>






</article>

