<?php if ($this->pageCount): ?>
 
        <ul class="pagination pagination-centered">
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a data-mydata="<?php echo  WEBPATH;?>/ads/getpre">&laquo;</a></li>
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a data-mydata="<?php echo  WEBPATH;?>/ads/getpre">&lsaquo;</a></li>


            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <li <?php echo $page == $this->current ? 'class="active"' : ''; ?>><a  data-mydata="<?php echo  WEBPATH;?>/ads/getpre">
                        <?php echo $page; ?>
                    </a></li>
            <?php endforeach; ?>

            <!-- Next page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a data-mydata="<?php echo  WEBPATH;?>/ads/getpre">&rsaquo;</a></li>
            <!-- Last page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a data-mydata="<?php echo  WEBPATH;?>/ads/getpre">&raquo;</a></li>
        </ul>
  
<?php endif; ?>