<?php if (count($this->pagesInRange) > 1) { ?>
    <div class="align-lg-center">
        <ul class="pagination">
            <?php if ($this->current != 1) { ?>
                <li><a href="<?php echo $this->url('Catalog',array('action'=>'manacatalogue','id'=>null, 'uenc'=>null,'page'=> $this->first,'order_by'=>null,'search_by'=>null));?>">First</a></li>
            <?php } ?>
            <?php if ($this->previous) { ?>
                <li><a href="<?php echo $this->url('Catalog',array('action'=>'manacatalogue','id'=>null, 'uenc'=>null,'page'=> $this->previous,'order_by'=>null,'search_by'=>null));?>" title="Previous">Previous</a></li>
            <?php } ?>

            <?php foreach ($this->pagesInRange as $page) { ?>
                <li <?php echo $page == $this->current ? 'class="active"' : ''; ?> id="page_<?php echo $page; ?>">
                    <a href="<?php echo $this->url('Catalog',array('action'=>'manacatalogue','id'=>null, 'uenc'=>null,'page'=> $page,'order_by'=>null,'search_by'=>null));?>"><?php echo $page; ?></a>
                </li>
            <?php } ?>

            <?php if ($this->next) { ?>
                <li><a href="<?php echo $this->url('Catalog',array('action'=>'manacatalogue','id'=>null, 'uenc'=>null,'page'=> $this->next,'order_by'=>null,'search_by'=>null));?>" title="Next">Next</a></li>
            <?php } ?>
            <?php if ($this->current != $this->last) { ?>
                <li><a href="<?php echo $this->url('Catalog',array('action'=>'manacatalogue','id'=>null, 'uenc'=>null,'page'=> $this->last,'order_by'=>null,'search_by'=>null));?>" title="Page End">End</a></li>
                <?php } ?> 
        </ul>
    </div>
<?php } ?> 