<form id="co-shipping-method-form" action="<?php echo WEBPATH;?>/checkout/cart/estimateupdatepost">
            <dl class="sp-methods">
                                    <dt>Flat Rate</dt>
                    <dd>
                        <ul>
                                                    <li>
                                                                   <input name="estimate_method" type="radio" value="flatrate_flatrate" id="s_method_flatrate_flatrate" class="radio">
                                    <label for="s_method_flatrate_flatrate">Fixed                                                                                                            <span class="price">$5.00</span>                                                                        </label>
                                                           </li>
                                                </ul>
                    </dd>
                            </dl>
            <div class="buttons-set">
                <button type="submit" title="Update Total" class="button" name="do" value="Update Total"><span><span>Update Total</span></span></button>
            </div>
        </form>