<div class="main-container col2-left-layout">
	<div class="container">
		<div class="main">
			<div class="breadcrumbs">
				<ul>
					<li class="home"><a href="<?php echo WEBPATH;?>" title="Home">Home</a></li>
					<li class="magicproduct"><strong>Accessories</strong></li>
				</ul>
			</div>


			<div class="row show-grid">
				<div
					class="col-left sidebar col-lg-3 col-md-3 col-sm-3 col-pull-3 hidden-xs">

					<div id="leftcatalogue"></div>
					<!-- leftcatalogue -->

					<div id="bestsellera"></div>
					<!-- bestsellera -->

					<div id="saleproducta"></div>
					<!-- sale product -->

					<div id="blockcompare"></div>
					<!-- blockcompare -->
					<div id="populartags"></div>
					<!-- populartags -->

					<div id="containernone"></div>
					<!-- container-none -->

					<p></p>
				</div>

				<!--thay trang chi tiet vao--->
				<div
					class="col-main col-lg-9 col-md-9 col-sm-9 col-push-9 col-xs-12">
					<div class="page-title category-title">
						<h1>Accessories</h1>
					</div>






					<div class="category-products">
						<div class="toolbar">
							<div class="sorter">
								<p class="view-mode">
									<label>View as:</label> <strong title="Grid" class="grid">Grid</strong>&nbsp;
									<a href="/demo/listaccessories.html" title="List" class="list">List</a>&nbsp;
								</p>

								<div class="sort-by">
									<label>Sort By</label> <select
										onchange="setLocation(this.value)">
										<option
											value="http://alothemes.com/demo/smije/index.php/accessories.html?dir=asc&amp;order=position"
											selected="selected">Position</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/accessories.html?dir=asc&amp;order=name">
											Name</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/accessories.html?dir=asc&amp;order=price">
											Price</option>
									</select> <a
										href="http://alothemes.com/demo/smije/index.php/accessories.html?dir=desc&amp;order=position"
										title="Set Descending Direction"><img
										src="http://alothemes.com/demo/smije/skin/frontend/alosmije/smije_fashion/images/i_asc_arrow.gif"
										alt="Set Descending Direction" class="v-middle"></a>
								</div>
								<div class="limiter">
									<label>Show</label> <select onchange="setLocation(this.value)">
										<option
											value="http://alothemes.com/demo/smije/index.php/accessories.html?limit=8">
											8</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/accessories.html?limit=12"
											selected="selected">12</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/accessories.html?limit=32">
											32</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/accessories.html?limit=40">
											40</option>
									</select>
								</div>
							</div>
							<div class="pager">
								<p class="amount">Items 13 to 17 of 17 total</p>




								<div class="pages">
									<strong>Page:</strong>
									<ol>
										<li><a class="previous i-previous"
											href="http://alothemes.com/demo/smije/index.php/accessories.html?p=1"
											title="Previous"> <!--<img src="" alt="" class="v-middle" />-->
												<i class="fa fa-angle-left">&nbsp;</i>
										</a></li>



										<li><a
											href="http://alothemes.com/demo/smije/index.php/accessories.html?p=1">1</a></li>
										<li class="current">2</li>




									</ol>

								</div>



							</div>
						</div>


						<ul class="row show-grid products-grid first odd">
							<li
								class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-mobile-12 item first">
								<div class="images-container">
									<div class="product-hover">
										<a
											href="/demo/smije/magicshop/quickview/view/path/roller-suitcase.html"
											title="Roller Suitcase" class="product-image"> <img
											class="img-responsive hover-img"
											src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/1/7/17_2.jpg"
											width="770" height="988" alt="Roller Suitcase"> <span
											class="product-img-back"> <img class="img-responsive"
												src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/1/5/15_1.jpg"
												width="770" height="988" alt="Roller Suitcase">
										</span>
										</a>
									</div>
									<div class="actions-no">
										<div class="actions">
											<button type="button" title="Add to Cart"
												class="button btn-cart pull-left"
												onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvYWNjZXNzb3JpZXMuaHRtbD9wPTI,/product/30/form_key/EDAytNgQgcMj8GHw/')"
												magiccartEvent="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvYWNjZXNzb3JpZXMuaHRtbD9wPTI,/product/30/form_key/EDAytNgQgcMj8GHw/')">
												<span><span>Add to Cart</span></span>
											</button>
											<ul class="add-to-links pull-left">
												<li class="pull-left"><a
													href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/30/form_key/EDAytNgQgcMj8GHw/"
													class="link-wishlist">Add to Wishlist</a></li>
												<li class="pull-right"><a
													href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/30/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvYWNjZXNzb3JpZXMuaHRtbD9wPTI,/form_key/EDAytNgQgcMj8GHw/"
													class="link-compare">Add to Compare</a></li>
											</ul>
										</div>
									</div>
								</div>
								<div class="products-textlink clearfix">
									<h2 class="product-name">
										<a href="/demo/suede-loafer-navy.html" title="Roller Suitcase">Roller
											Suitcase</a>
									</h2>



									<div class="price-box">
										<span class="regular-price" id="product-price-30"> <span
											class="price">$456.00</span>
										</span>

									</div>

								</div>
							</li>
							<li
								class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-mobile-12 item">
								<div class="images-container">
									<div class="product-hover">
										<a
											href="/demo/smije/magicshop/quickview/view/path/roller-suitcase.html"
											title="Linen Blazer" class="product-image"> <img
											class="img-responsive hover-img"
											src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/4/_/4_4.jpg"
											width="770" height="988" alt="Linen Blazer"> <span
											class="product-img-back"> <img class="img-responsive"
												src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/4/-/4-4.jpg"
												width="770" height="988" alt="Linen Blazer">
										</span>
										</a>
									</div>
									<div class="actions-no">
										<div class="actions">
											<button type="button" title="Add to Cart"
												class="button btn-cart pull-left"
												onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvYWNjZXNzb3JpZXMuaHRtbD9wPTI,/product/28/form_key/EDAytNgQgcMj8GHw/')"
												magiccartEvent="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvYWNjZXNzb3JpZXMuaHRtbD9wPTI,/product/28/form_key/EDAytNgQgcMj8GHw/')">
												<span><span>Add to Cart</span></span>
											</button>
											<ul class="add-to-links pull-left">
												<li class="pull-left"><a
													href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/28/form_key/EDAytNgQgcMj8GHw/"
													class="link-wishlist">Add to Wishlist</a></li>
												<li class="pull-right"><a
													href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/28/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvYWNjZXNzb3JpZXMuaHRtbD9wPTI,/form_key/EDAytNgQgcMj8GHw/"
													class="link-compare">Add to Compare</a></li>
											</ul>
										</div>
									</div>
								</div>
								<div class="products-textlink clearfix">
									<h2 class="product-name">
										<a href="/demo/suede-loafer-navy.html" title="Linen Blazer">Linen
											Blazer</a>
									</h2>
									<div class="ratings">
										<div class="rating-box">
											<div class="rating" style="width: 60%"></div>
										</div>
										<span class="amount"><a href="#"
											onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/28/category/93/'; return false;">1
												Review(s)</a></span>
									</div>



									<div class="price-box">
										<span class="regular-price" id="product-price-28"> <span
											class="price">$234.00</span>
										</span>

									</div>

								</div>
							</li>
							<li
								class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-mobile-12 item">
								<div class="images-container">
									<div class="product-hover">
										<a
											href="/demo/smije/magicshop/quickview/view/path/roller-suitcase.html "
											title="Slim fit Dobby Oxford Shirt" class="product-image"> <img
											class="img-responsive hover-img"
											src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/3/_/3_4.jpg"
											width="770" height="988" alt="Slim fit Dobby Oxford Shirt"> <span
											class="product-img-back"> <img class="img-responsive"
												src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/3/-/3-3_1.jpg"
												width="770" height="988" alt="Slim fit Dobby Oxford Shirt">
										</span>
										</a>
									</div>
									<div class="actions-no">
										<div class="actions">
											<button type="button" title="Add to Cart"
												class="button btn-cart pull-left"
												onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvYWNjZXNzb3JpZXMuaHRtbD9wPTI,/product/27/form_key/EDAytNgQgcMj8GHw/')"
												magiccartEvent="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvYWNjZXNzb3JpZXMuaHRtbD9wPTI,/product/27/form_key/EDAytNgQgcMj8GHw/')">
												<span><span>Add to Cart</span></span>
											</button>
											<ul class="add-to-links pull-left">
												<li class="pull-left"><a
													href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/27/form_key/EDAytNgQgcMj8GHw/"
													class="link-wishlist">Add to Wishlist</a></li>
												<li class="pull-right"><a
													href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/27/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvYWNjZXNzb3JpZXMuaHRtbD9wPTI,/form_key/EDAytNgQgcMj8GHw/"
													class="link-compare">Add to Compare</a></li>
											</ul>
										</div>
									</div>
								</div>
								<div class="products-textlink clearfix">
									<h2 class="product-name">
										<a href="/demo/suede-loafer-navy.html"
											title="Slim fit Dobby Oxford Shirt">Slim fit Dobby Oxford
											Shirt</a>
									</h2>



									<div class="price-box">
										<span class="regular-price" id="product-price-27"> <span
											class="price">$250.00</span>
										</span>

									</div>

								</div>
							</li>
							<li
								class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-mobile-12 item last">
								<div class="images-container">
									<div class="product-hover">
										<span class="sticker top-left"><span class="labelnew">New</span></span>
										<a
											href="/demo/smije/magicshop/quickview/view/path/roller-suitcase.html "
											title="French Cuff Cotton" class="product-image"> <img
											class="img-responsive hover-img"
											src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/2/_/2_3.jpg"
											width="770" height="988" alt="French Cuff Cotton"> <span
											class="product-img-back"> <img class="img-responsive"
												src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/2/-/2-2_1.jpg"
												width="770" height="988" alt="French Cuff Cotton">
										</span>
										</a>
									</div>
									<div class="actions-no">
										<div class="actions">
											<button type="button" title="Add to Cart"
												class="button btn-cart pull-left"
												onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvYWNjZXNzb3JpZXMuaHRtbD9wPTI,/product/26/form_key/EDAytNgQgcMj8GHw/')"
												magiccartEvent="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvYWNjZXNzb3JpZXMuaHRtbD9wPTI,/product/26/form_key/EDAytNgQgcMj8GHw/')">
												<span><span>Add to Cart</span></span>
											</button>
											<ul class="add-to-links pull-left">
												<li class="pull-left"><a
													href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/26/form_key/EDAytNgQgcMj8GHw/"
													class="link-wishlist">Add to Wishlist</a></li>
												<li class="pull-right"><a
													href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/26/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvYWNjZXNzb3JpZXMuaHRtbD9wPTI,/form_key/EDAytNgQgcMj8GHw/"
													class="link-compare">Add to Compare</a></li>
											</ul>
										</div>
									</div>
								</div>
								<div class="products-textlink clearfix">
									<h2 class="product-name">
										<a href="/demo/suede-loafer-navy.html"
											title="French Cuff Cotton">French Cuff Cotton</a>
									</h2>
									<div class="ratings">
										<div class="rating-box">
											<div class="rating" style="width: 60%"></div>
										</div>
										<span class="amount"><a href="#"
											onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/26/category/93/'; return false;">1
												Review(s)</a></span>
									</div>



									<div class="price-box">
										<span class="regular-price" id="product-price-26"> <span
											class="price">$168.00</span>
										</span>

									</div>

								</div>
							</li>
						</ul>
						<ul class="row show-grid products-grid last even">
							<li
								class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-mobile-12 item first">
								<div class="images-container">
									<div class="product-hover">
										<span class="sticker top-left"><span class="labelnew">New</span></span>
										<a
											href="/demo/smije/magicshop/quickview/view/path/roller-suitcase.html"
											title="Houston Travel Wallet" class="product-image"> <img
											class="img-responsive hover-img"
											src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/1/6/16_5.jpg"
											width="770" height="988" alt="Houston Travel Wallet"> <span
											class="product-img-back"> <img class="img-responsive"
												src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/1/4/14_5.jpg"
												width="770" height="988" alt="Houston Travel Wallet">
										</span>
										</a>
									</div>
									<div class="actions-no">
										<div class="actions">
											<button type="button" title="Add to Cart"
												class="button btn-cart pull-left"
												onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvYWNjZXNzb3JpZXMuaHRtbD9wPTI,/product/42/form_key/EDAytNgQgcMj8GHw/')"
												magiccartEvent="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvYWNjZXNzb3JpZXMuaHRtbD9wPTI,/product/42/form_key/EDAytNgQgcMj8GHw/')">
												<span><span>Add to Cart</span></span>
											</button>
											<ul class="add-to-links pull-left">
												<li class="pull-left"><a
													href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/42/form_key/EDAytNgQgcMj8GHw/"
													class="link-wishlist">Add to Wishlist</a></li>
												<li class="pull-right"><a
													href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/42/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvYWNjZXNzb3JpZXMuaHRtbD9wPTI,/form_key/EDAytNgQgcMj8GHw/"
													class="link-compare">Add to Compare</a></li>
											</ul>
										</div>
									</div>
								</div>
								<div class="products-textlink clearfix">
									<h2 class="product-name">
										<a href="/demo/suede-loafer-navy.html"
											title="Houston Travel Wallet">Houston Travel Wallet</a>
									</h2>
									<div class="ratings">
										<div class="rating-box">
											<div class="rating" style="width: 60%"></div>
										</div>
										<span class="amount"><a href="#"
											onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/42/category/93/'; return false;">1
												Review(s)</a></span>
									</div>



									<div class="price-box">
										<span class="regular-price" id="product-price-42"> <span
											class="price">$156.00</span>
										</span>

									</div>

								</div>
							</li>
						</ul>
						<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>

						<div class="toolbar-bottom">
							<div class="toolbar">
								<div class="sorter">
									<p class="view-mode">
										<label>View as:</label> <strong title="Grid" class="grid">Grid</strong>&nbsp;
										<a href="/demo/listaccessories.html" title="List" class="list">List</a>&nbsp;
									</p>

									<div class="sort-by">
										<label>Sort By</label> <select
											onchange="setLocation(this.value)">
											<option
												value="http://alothemes.com/demo/smije/index.php/accessories.html?dir=asc&amp;order=position"
												selected="selected">Position</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/accessories.html?dir=asc&amp;order=name">
												Name</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/accessories.html?dir=asc&amp;order=price">
												Price</option>
										</select> <a
											href="http://alothemes.com/demo/smije/index.php/accessories.html?dir=desc&amp;order=position"
											title="Set Descending Direction"><img
											src="http://alothemes.com/demo/smije/skin/frontend/alosmije/smije_fashion/images/i_asc_arrow.gif"
											alt="Set Descending Direction" class="v-middle"></a>
									</div>
									<div class="limiter">
										<label>Show</label> <select onchange="setLocation(this.value)">
											<option
												value="http://alothemes.com/demo/smije/index.php/accessories.html?limit=8">
												8</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/accessories.html?limit=12"
												selected="selected">12</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/accessories.html?limit=32">
												32</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/accessories.html?limit=40">
												40</option>
										</select>
									</div>
								</div>
								<div class="pager">
									<p class="amount">Items 13 to 17 of 17 total</p>




									<div class="pages">
										<strong>Page:</strong>
										<ol>
											<li><a class="previous i-previous"
												href="http://alothemes.com/demo/smije/index.php/accessories.html?p=1"
												title="Previous"> <!--<img src="" alt="" class="v-middle" />-->
													<i class="fa fa-angle-left">&nbsp;</i>
											</a></li>



											<li><a
												href="http://alothemes.com/demo/smije/index.php/accessories.html?p=1">1</a></li>
											<li class="current">2</li>




										</ol>

									</div>



								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- Accessories -->
			</div>
		</div>
	</div>
</div>