<div class="main-container col2-left-layout">
	<div class="container">
		<div class="main">
			<div class="breadcrumbs">
				<ul>
					<li class="home"><a href="<?php echo WEBPATH;?>" title="Home">Home</a></li>
					<li class="magicproduct"><strong>Bestseller</strong></li>
				</ul>
			</div>


			<div class="row show-grid">
				<div
					class="col-left sidebar col-lg-3 col-md-3 col-sm-3 col-pull-3 hidden-xs">

					<div id="leftcatalogue"></div>
					<!-- leftcatalogue -->

					<div id="bestsellera"></div>
					<!-- bestsellera -->

					<div id="saleproducta"></div>
					<!-- sale product -->

					<div id="blockcompare"></div>
					<!-- blockcompare -->
					<div id="populartags"></div>
					<!-- populartags -->

					<div id="containernone"></div>
					<!-- container-none -->

					<p></p>
				</div>

				<!--thay trang chi tiet vao--->
				<div
					class="col-main col-lg-9 col-md-9 col-sm-9 col-push-9 col-xs-12">


					<div class="category-products">
						<div class="toolbar">
							<div class="sorter">
								<p class="view-mode">
									<label>View as:</label> <a href="/demo/Bestsellers.html"
										title="Grid" class="grid">Grid</a>&nbsp; <strong title="List"
										class="list">List</strong>&nbsp;
								</p>

								<div class="sort-by">
									<label>Sort By</label> <select
										onchange="setLocation(this.value)">
										<option
											value="http://alothemes.com/demo/smije/index.php/newproduct?dir=asc&amp;mode=list&amp;order=position"
											selected="selected">Position</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/newproduct?dir=asc&amp;mode=list&amp;order=name">
											Name</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/newproduct?dir=asc&amp;mode=list&amp;order=price">
											Price</option>
									</select> <a
										href="http://alothemes.com/demo/smije/index.php/newproduct?dir=desc&amp;mode=list&amp;order=position"
										title="Set Descending Direction"><img
										src="http://alothemes.com/demo/smije/skin/frontend/alosmije/smije_fashion/images/i_asc_arrow.gif"
										alt="Set Descending Direction" class="v-middle"></a>
								</div>
								<div class="limiter">
									<label>Show</label> <select onchange="setLocation(this.value)">
										<option
											value="http://alothemes.com/demo/smije/index.php/newproduct?limit=5&amp;mode=list">
											5</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/newproduct?limit=10&amp;mode=list"
											selected="selected">10</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/newproduct?limit=15&amp;mode=list">
											15</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/newproduct?limit=20&amp;mode=list">
											20</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/newproduct?limit=25&amp;mode=list">
											25</option>
									</select>
								</div>
							</div>
							<div class="pager">
								<p class="amount">
									<strong>4 Item(s)</strong>
								</p>







							</div>
						</div>
						<ol class="products-list" id="products-list">
							<li class="item row  odd">
								<div class="col-mobile-12 col-xs-5 col-lg-3 col-md-3 col-sm-3">
									<div class="products-list-container">
										<div class="images-container">
											<div class="product-hover">
												<span class="sticker top-left"><span class="labelnew">New</span></span>
												<a href="/demo/suede-loafer-navy.html"
													title="Plaid Cotton Shirt" class="product-image"> <img
													class="img-responsive"
													src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1.jpg"
													width="770" height="988" alt="Plaid Cotton Shirt"> <span
													class="product-img-back"> <img class="img-responsive"
														src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/1/-/1-1.jpg"
														width="770" height="988" alt="Plaid Cotton Shirt">
												</span>
												</a>
											</div>
										</div>
									</div>
								</div>
								<div
									class="product-shop col-mobile-12 col-xs-7 col-lg-9 col-md-9 col-sm-9">
									<div class="f-fix">
										<div class="products-textlink clearfix">
											<h2 class="product-name">
												<a href="/demo/suede-loafer-navy.html"
													title="Plaid Cotton Shirt">Plaid Cotton Shirt</a>
											</h2>
											<div class="ratings">
												<div class="rating-box">
													<div class="rating" style="width: 100%"></div>
												</div>
												<p class="rating-links">
													<a
														href="http://alothemes.com/demo/smije/index.php/review/product/list/id/25/">1
														Review(s)</a> <span class="separator">|</span> <a
														href="http://alothemes.com/demo/smije/index.php/review/product/list/id/25/#review-form">Add
														Your Review</a>
												</p>
											</div>



											<div class="price-box">
												<span class="regular-price" id="product-price-25"> <span
													class="price">$185.00</span>
												</span>

											</div>

										</div>
										<div class="desc std">
											<div class="short-description">
												<p>Aliquam condimentum pharetra metus sed posuere. Ut
													euismod nisl sit amet enim consectetur volutpat. Nulla
													vitae magna dictum, adipiscing mauris eu, gravida tellus.
													Nulla tempor, felis feugiat fermentum suscipit.</p>
											</div>
											<!-- <a href="http://alothemes.com/demo/smije/index.php/plaid-cotton-shirt.html" title="" class="link-learn">Learn More</a>-->
										</div>
										<div class="actions-no actions-list">
											<div class="actions">
												<button type="button" title="Add to Cart"
													class="button btn-cart pull-left"
													onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWxpc3Q,/product/25/form_key/3fXQuE9EWz5npGTp/')"
													magiccartEvent="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWxpc3Q,/product/25/form_key/3fXQuE9EWz5npGTp/')">
													<span><span>Add to Cart</span></span>
												</button>

												<ul class="add-to-links pull-left">
													<li class="pull-left"><a
														href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/25/form_key/3fXQuE9EWz5npGTp/"
														class="link-wishlist">Add to Wishlist</a></li>
													<li class="pull-right"><a
														href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/25/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWxpc3Q,/form_key/3fXQuE9EWz5npGTp/"
														class="link-compare">Add to Compare</a></li>
												</ul>
											</div>
										</div>
									</div>
								</div>
							</li>
							<li class="item row  even">
								<div class="col-mobile-12 col-xs-5 col-lg-3 col-md-3 col-sm-3">
									<div class="products-list-container">
										<div class="images-container">
											<div class="product-hover">
												<span class="sticker top-left"><span class="labelnew">New</span></span>
												<a href="/demo/suede-loafer-navy.html"
													title="French Cuff Cotton" class="product-image"> <img
													class="img-responsive"
													src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/2/_/2_3.jpg"
													width="770" height="988" alt="French Cuff Cotton"> <span
													class="product-img-back"> <img class="img-responsive"
														src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/2/-/2-2_1.jpg"
														width="770" height="988" alt="French Cuff Cotton">
												</span>
												</a>
											</div>
										</div>
									</div>
								</div>
								<div
									class="product-shop col-mobile-12 col-xs-7 col-lg-9 col-md-9 col-sm-9">
									<div class="f-fix">
										<div class="products-textlink clearfix">
											<h2 class="product-name">
												<a href="/demo/suede-loafer-navy.html"
													title="French Cuff Cotton">French Cuff Cotton</a>
											</h2>
											<div class="ratings">
												<div class="rating-box">
													<div class="rating" style="width: 60%"></div>
												</div>
												<p class="rating-links">
													<a
														href="http://alothemes.com/demo/smije/index.php/review/product/list/id/26/">1
														Review(s)</a> <span class="separator">|</span> <a
														href="http://alothemes.com/demo/smije/index.php/review/product/list/id/26/#review-form">Add
														Your Review</a>
												</p>
											</div>



											<div class="price-box">
												<span class="regular-price" id="product-price-26"> <span
													class="price">$168.00</span>
												</span>

											</div>

										</div>
										<div class="desc std">
											<div class="short-description">
												<p>Aliquam condimentum pharetra metus sed posuere. Ut
													euismod nisl sit amet enim consectetur volutpat. Nulla
													vitae magna dictum, adipiscing mauris eu, gravida tellus.
													Nulla tempor, felis feugiat fermentum suscipit.</p>
											</div>
											<!-- <a href="http://alothemes.com/demo/smije/index.php/french-cuff-cotton.html" title="" class="link-learn">Learn More</a>-->
										</div>
										<div class="actions-no actions-list">
											<div class="actions">
												<button type="button" title="Add to Cart"
													class="button btn-cart pull-left"
													onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWxpc3Q,/product/26/form_key/3fXQuE9EWz5npGTp/')"
													magiccartEvent="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWxpc3Q,/product/26/form_key/3fXQuE9EWz5npGTp/')">
													<span><span>Add to Cart</span></span>
												</button>

												<ul class="add-to-links pull-left">
													<li class="pull-left"><a
														href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/26/form_key/3fXQuE9EWz5npGTp/"
														class="link-wishlist">Add to Wishlist</a></li>
													<li class="pull-right"><a
														href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/26/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWxpc3Q,/form_key/3fXQuE9EWz5npGTp/"
														class="link-compare">Add to Compare</a></li>
												</ul>
											</div>
										</div>
									</div>
								</div>
							</li>
							<li class="item row  odd">
								<div class="col-mobile-12 col-xs-5 col-lg-3 col-md-3 col-sm-3">
									<div class="products-list-container">
										<div class="images-container">
											<div class="product-hover">
												<span class="sticker top-left"><span class="labelnew">New</span></span>
												<a href="/demo/suede-loafer-navy.html"
													title="Broad St. Flapover" class="product-image"> <img
													class="img-responsive"
													src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/1/8/18_6.jpg"
													width="770" height="988" alt="Broad St. Flapover"> <span
													class="product-img-back"> <img class="img-responsive"
														src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/1/4/14_4.jpg"
														width="770" height="988" alt="Broad St. Flapover">
												</span>
												</a>
											</div>
										</div>
									</div>
								</div>
								<div
									class="product-shop col-mobile-12 col-xs-7 col-lg-9 col-md-9 col-sm-9">
									<div class="f-fix">
										<div class="products-textlink clearfix">
											<h2 class="product-name">
												<a href="/demo/suede-loafer-navy.html"
													title="Broad St. Flapover">Broad St. Flapover</a>
											</h2>
											<div class="ratings">
												<div class="rating-box">
													<div class="rating" style="width: 60%"></div>
												</div>
												<p class="rating-links">
													<a
														href="http://alothemes.com/demo/smije/index.php/review/product/list/id/41/">1
														Review(s)</a> <span class="separator">|</span> <a
														href="http://alothemes.com/demo/smije/index.php/review/product/list/id/41/#review-form">Add
														Your Review</a>
												</p>
											</div>



											<div class="price-box">
												<span class="regular-price" id="product-price-41"> <span
													class="price">$234.00</span>
												</span>

											</div>

										</div>
										<div class="desc std">
											<div class="short-description">
												<p>Aliquam condimentum pharetra metus sed posuere. Ut
													euismod nisl sit amet enim consectetur volutpat. Nulla
													vitae magna dictum, adipiscing mauris eu, gravida tellus.
													Nulla tempor, felis feugiat fermentum suscipit.</p>
											</div>
											<!-- <a href="http://alothemes.com/demo/smije/index.php/broad-st-flapover.html" title="" class="link-learn">Learn More</a>-->
										</div>
										<div class="actions-no actions-list">
											<div class="actions">
												<button type="button" title="Add to Cart"
													class="button btn-cart pull-left"
													onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWxpc3Q,/product/41/form_key/3fXQuE9EWz5npGTp/')"
													magiccartEvent="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWxpc3Q,/product/41/form_key/3fXQuE9EWz5npGTp/')">
													<span><span>Add to Cart</span></span>
												</button>

												<ul class="add-to-links pull-left">
													<li class="pull-left"><a
														href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/41/form_key/3fXQuE9EWz5npGTp/"
														class="link-wishlist">Add to Wishlist</a></li>
													<li class="pull-right"><a
														href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/41/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWxpc3Q,/form_key/3fXQuE9EWz5npGTp/"
														class="link-compare">Add to Compare</a></li>
												</ul>
											</div>
										</div>
									</div>
								</div>
							</li>
							<li class="item row  last even">
								<div class="col-mobile-12 col-xs-5 col-lg-3 col-md-3 col-sm-3">
									<div class="products-list-container">
										<div class="images-container">
											<div class="product-hover">
												<span class="sticker top-left"><span class="labelnew">New</span></span>
												<a href="/demo/suede-loafer-navy.html"
													title="Houston Travel Wallet" class="product-image"> <img
													class="img-responsive"
													src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/1/6/16_5.jpg"
													width="770" height="988" alt="Houston Travel Wallet"> <span
													class="product-img-back"> <img class="img-responsive"
														src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/1/4/14_5.jpg"
														width="770" height="988" alt="Houston Travel Wallet">
												</span>
												</a>
											</div>
										</div>
									</div>
								</div>
								<div
									class="product-shop col-mobile-12 col-xs-7 col-lg-9 col-md-9 col-sm-9">
									<div class="f-fix">
										<div class="products-textlink clearfix">
											<h2 class="product-name">
												<a href="/demo/suede-loafer-navy.html"
													title="Houston Travel Wallet">Houston Travel Wallet</a>
											</h2>
											<div class="ratings">
												<div class="rating-box">
													<div class="rating" style="width: 60%"></div>
												</div>
												<p class="rating-links">
													<a
														href="http://alothemes.com/demo/smije/index.php/review/product/list/id/42/">1
														Review(s)</a> <span class="separator">|</span> <a
														href="http://alothemes.com/demo/smije/index.php/review/product/list/id/42/#review-form">Add
														Your Review</a>
												</p>
											</div>



											<div class="price-box">
												<span class="regular-price" id="product-price-42"> <span
													class="price">$156.00</span>
												</span>

											</div>

										</div>
										<div class="desc std">
											<div class="short-description">
												<p>Aliquam condimentum pharetra metus sed posuere. Ut
													euismod nisl sit amet enim consectetur volutpat. Nulla
													vitae magna dictum, adipiscing mauris eu, gravida tellus.
													Nulla tempor, felis feugiat fermentum suscipit.</p>
											</div>
											<!-- <a href="http://alothemes.com/demo/smije/index.php/houston-travel-wallet.html" title="" class="link-learn">Learn More</a>-->
										</div>
										<div class="actions-no actions-list">
											<div class="actions">
												<button type="button" title="Add to Cart"
													class="button btn-cart pull-left"
													onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWxpc3Q,/product/42/form_key/3fXQuE9EWz5npGTp/')"
													magiccartEvent="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWxpc3Q,/product/42/form_key/3fXQuE9EWz5npGTp/')">
													<span><span>Add to Cart</span></span>
												</button>

												<ul class="add-to-links pull-left">
													<li class="pull-left"><a
														href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/42/form_key/3fXQuE9EWz5npGTp/"
														class="link-wishlist">Add to Wishlist</a></li>
													<li class="pull-right"><a
														href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/42/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWxpc3Q,/form_key/3fXQuE9EWz5npGTp/"
														class="link-compare">Add to Compare</a></li>
												</ul>
											</div>
										</div>
									</div>
								</div>
							</li>
						</ol>
						<script type="text/javascript">decorateList('products-list', 'none-recursive')</script>


						<div class="toolbar-bottom">
							<div class="toolbar">
								<div class="sorter">
									<p class="view-mode">
										<label>View as:</label> <a href="/demo/list1.html"
											title="Grid" class="grid">Grid</a>&nbsp; <strong title="List"
											class="list">List</strong>&nbsp;
									</p>

									<div class="sort-by">
										<label>Sort By</label> <select
											onchange="setLocation(this.value)">
											<option
												value="http://alothemes.com/demo/smije/index.php/newproduct?dir=asc&amp;mode=list&amp;order=position"
												selected="selected">Position</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/newproduct?dir=asc&amp;mode=list&amp;order=name">
												Name</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/newproduct?dir=asc&amp;mode=list&amp;order=price">
												Price</option>
										</select> <a
											href="http://alothemes.com/demo/smije/index.php/newproduct?dir=desc&amp;mode=list&amp;order=position"
											title="Set Descending Direction"><img
											src="http://alothemes.com/demo/smije/skin/frontend/alosmije/smije_fashion/images/i_asc_arrow.gif"
											alt="Set Descending Direction" class="v-middle"></a>
									</div>
									<div class="limiter">
										<label>Show</label> <select onchange="setLocation(this.value)">
											<option
												value="http://alothemes.com/demo/smije/index.php/newproduct?limit=5&amp;mode=list">
												5</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/newproduct?limit=10&amp;mode=list"
												selected="selected">10</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/newproduct?limit=15&amp;mode=list">
												15</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/newproduct?limit=20&amp;mode=list">
												20</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/newproduct?limit=25&amp;mode=list">
												25</option>
										</select>
									</div>
								</div>
								<div class="pager">
									<p class="amount">
										<strong>4 Item(s)</strong>
									</p>







								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- bestseller -->
			</div>
		</div>
	</div>
</div>