<div class="main-container col2-left-layout">
	<div class="container">
		<div class="main">
			<div class="breadcrumbs">
				<ul>
					<li class="home"><a href="<?php echo WEBPATH;?>" title="Home">Home</a></li>
					<li class="magicproduct"><strong>Blog</strong></li>
				</ul>
			</div>


			<div class="row show-grid">
				<div
					class="col-left sidebar col-lg-3 col-md-3 col-sm-3 col-pull-3 hidden-xs">

					<div id="leftcatalogue"></div> <!-- leftcatalogue -->

					<?php 
					     /* ?>
					<div id="bestsellera"></div>
					<!-- bestsellera -->
					  
					<div id="saleproducta"></div>
					<!-- sale product -->
					
					   */ 
                     ?>
                     
					<div id="blockcompare"></div>
					<!-- blockcompare -->
					<div id="populartags"></div>
					<!-- populartags -->

					<div id="containernone"></div>
					<!-- container-none -->

					<p></p>
				</div>

				<!--thay trang chi tiet vao--->
				<div
					class="col-main col-lg-9 col-md-9 col-sm-9 col-push-9 col-xs-12">
					<div id="messages_product_view"></div>
					<div class="blog-toolbar blog-toolbar-top">
						<div class="toolbar">
							<div class="sorter">

								<div class="sort-by">
									<label>Sort By</label> <select
										onchange="setLocation(this.value)">
										<option
											value="http://alothemes.com/demo/smije/index.php/blog/?dir=asc&amp;order=created_time"
											selected="selected">Created At</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/blog/?dir=asc&amp;order=user">
											Added By</option>
									</select> <a
										href="http://alothemes.com/demo/smije/index.php/blog/?dir=desc&amp;order=created_time"
										title="Set Descending Direction"><img
										src="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/images/i_asc_arrow.gif"
										alt="Set Descending Direction" class="v-middle"></a>
								</div>
								<div class="limiter">
									<label>Show</label> <select onchange="setLocation(this.value)">
										<option
											value="http://alothemes.com/demo/smije/index.php/blog/?limit=10">
											10</option>
									</select>
								</div>
							</div>
							<div class="pager">
								<p class="amount">
									<strong>4 Item(s)</strong>
								</p>







							</div>
						</div>
					</div>
					<div class="postWrapper">
						<a href="http://alothemes.com/demo/smije/index.php/blog/viviennewestwood/"><img
							class="img-responsive"
							src="<?php echo BAG_REAL_HTML; ?>/smije/media/magiccart/blog/cache/871x435/blog4-fashion.jpg"></a>
						<div class="postTitle">
							<h2>
								<a href="<?php echo WEBPATH?>/blogdetail/viviennewestwood.html">Vivienne Westwood </a>
							</h2>
						</div>
						<div class="by post-date">
							<div class="postDetails">
								<!--<a href="#commentBox" > </a>-->
								<!--<a href=""></a>-->
								By: <span class="user">Alex Justin Johnson</span>
							</div>
							<div class="number">
								<h3>Saturday, November 22, 2014 9:21:26 PM America/Los_Angeles</h3>
							</div>
							<span class="comments"><span class="comments-text">2 comments</span></span>
						</div>
						<div class="tags"></div>
						<div class="postBookmarks">
							<h4>Bookmark with:</h4>
							<a
								href="http://digg.com/submit?phase=2&amp;url=http://alothemes.com/demo/smije/index.php/blog/viviennewestwood/&amp;title=Vivienne Westwood &amp;bodytext=Vivienne Westwood &amp;topic="
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-digg-com.gif" width="16"
								height="16" alt="">&nbsp;Digg.com
							</a>&nbsp; <a
								href="http://www.stumbleupon.com/submit?url=http://alothemes.com/demo/smije/index.php/blog/viviennewestwood/&amp;title=Vivienne Westwood &amp;newcomment=Vivienne Westwood "
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-stumbleupon-com.gif" width="16"
								height="16" alt="">&nbsp;Stumbleupon.com
							</a>&nbsp; <a
								href="http://del.icio.us/post/?url=http://alothemes.com/demo/smije/index.php/blog/viviennewestwood/&amp;title=Vivienne Westwood &amp;notes=Vivienne Westwood "
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-del-icio-us.gif" width="16"
								height="16" alt="">&nbsp;Del.icio.us
							</a>&nbsp; <a
								href="http://www.facebook.com/sharer.php?u=http://alothemes.com/demo/smije/index.php/blog/viviennewestwood/&amp;t=Vivienne Westwood "
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-www-facebook-com-.gif" width="16"
								height="16" alt="">&nbsp;Facebook
							</a>&nbsp; <a
								href="http://reddit.com/submit?url=http://alothemes.com/demo/smije/index.php/blog/viviennewestwood/&amp;title=Vivienne Westwood "
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-reddit-com.gif" width="16"
								height="16" alt="">&nbsp;Reddit.com
							</a>&nbsp;
						</div>
						<div class="postContent">
							<p>I didn't consider myself a fashion designer at all at the time
								of punk.</p>
							<a class="aw-blog-read-more" href="<?php echo WEBPATH?>/blogdetail/viviennewestwood.html">Read
								More</a>
						</div>
					</div>
					<div class="postWrapper">
						<a
							href="http://alothemes.com/demo/smije/index.php/blog/annielennox/"><img
							class="img-responsive"
							src="<?php echo BAG_REAL_HTML; ?>/smije/media/magiccart/blog/cache/871x435/blog3-fashion.jpg"></a>
						<div class="postTitle">
							<h2>
								<a href="<?php echo WEBPATH?>/blogdetail/viviennewestwood.html">Annie Lennox</a>
							</h2>
						</div>
						<div class="by post-date">
							<div class="postDetails">
								<!--<a href="#commentBox" > </a>-->
								<!--<a href=""></a>-->
								By: <span class="user">Alex Justin Johnson</span>
							</div>
							<div class="number">
								<h3>Saturday, November 22, 2014 9:18:03 PM America/Los_Angeles</h3>
							</div>
							<span class="comments"><span class="comments-text">1 comments</span></span>
						</div>
						<div class="tags"></div>
						<div class="postBookmarks">
							<h4>Bookmark with:</h4>
							<a
								href="http://digg.com/submit?phase=2&amp;url=http://alothemes.com/demo/smije/index.php/blog/annielennox/&amp;title=Annie Lennox&amp;bodytext=Annie Lennox&amp;topic="
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-digg-com.gif" width="16"
								height="16" alt="">&nbsp;Digg.com
							</a>&nbsp; <a
								href="http://www.stumbleupon.com/submit?url=http://alothemes.com/demo/smije/index.php/blog/annielennox/&amp;title=Annie Lennox&amp;newcomment=Annie Lennox"
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-stumbleupon-com.gif" width="16"
								height="16" alt="">&nbsp;Stumbleupon.com
							</a>&nbsp; <a
								href="http://del.icio.us/post/?url=http://alothemes.com/demo/smije/index.php/blog/annielennox/&amp;title=Annie Lennox&amp;notes=Annie Lennox"
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-del-icio-us.gif" width="16"
								height="16" alt="">&nbsp;Del.icio.us
							</a>&nbsp; <a
								href="http://www.facebook.com/sharer.php?u=http://alothemes.com/demo/smije/index.php/blog/annielennox/&amp;t=Annie Lennox"
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-www-facebook-com-.gif" width="16"
								height="16" alt="">&nbsp;Facebook
							</a>&nbsp; <a
								href="http://reddit.com/submit?url=http://alothemes.com/demo/smije/index.php/blog/annielennox/&amp;title=Annie Lennox"
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-reddit-com.gif" width="16"
								height="16" alt="">&nbsp;Reddit.com
							</a>&nbsp;
						</div>
						<div class="postContent">
							<p>We all fight over what the label 'feminism' means but for me
								it's about empowerment.</p>
							<a class="aw-blog-read-more" href="<?php echo WEBPATH?>/blogdetail/viviennewestwood.html">Read
								More</a>
						</div>
					</div>
					<div class="postWrapper">
						<a
							href="http://alothemes.com/demo/smije/index.php/blog/dwaynejohnson/"><img
							class="img-responsive"
							src="<?php echo BAG_REAL_HTML; ?>/smije/media/magiccart/blog/cache/871x435/blog2-fashion.jpg"></a>
						<div class="postTitle">
							<h2>
								<a href="<?php echo WEBPATH?>/blogdetail/viviennewestwood.html">Dwayne Johnson</a>
							</h2>
						</div>
						<div class="by post-date">
							<div class="postDetails">
								<!--<a href="#commentBox" > </a>-->
								<!--<a href=""></a>-->
								<!--<a href=""></a>-->
								By: <span class="user">Alex Justin Johnson</span>
							</div>
							<div class="number">
								<h3>Saturday, November 22, 2014 9:15:29 PM America/Los_Angeles</h3>
							</div>
							<span class="comments"><span class="comments-text">3 comments</span></span>
						</div>
						<div class="tags"></div>
						<div class="postBookmarks">
							<h4>Bookmark with:</h4>
							<a
								href="http://digg.com/submit?phase=2&amp;url=http://alothemes.com/demo/smije/index.php/blog/dwaynejohnson/&amp;title=Dwayne Johnson&amp;bodytext=Dwayne Johnson&amp;topic="
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-digg-com.gif" width="16"
								height="16" alt="">&nbsp;Digg.com
							</a>&nbsp; <a
								href="http://www.stumbleupon.com/submit?url=http://alothemes.com/demo/smije/index.php/blog/dwaynejohnson/&amp;title=Dwayne Johnson&amp;newcomment=Dwayne Johnson"
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-stumbleupon-com.gif" width="16"
								height="16" alt="">&nbsp;Stumbleupon.com
							</a>&nbsp; <a
								href="http://del.icio.us/post/?url=http://alothemes.com/demo/smije/index.php/blog/dwaynejohnson/&amp;title=Dwayne Johnson&amp;notes=Dwayne Johnson"
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-del-icio-us.gif" width="16"
								height="16" alt="">&nbsp;Del.icio.us
							</a>&nbsp; <a
								href="http://www.facebook.com/sharer.php?u=http://alothemes.com/demo/smije/index.php/blog/dwaynejohnson/&amp;t=Dwayne Johnson"
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-www-facebook-com-.gif" width="16"
								height="16" alt="">&nbsp;Facebook
							</a>&nbsp; <a
								href="http://reddit.com/submit?url=http://alothemes.com/demo/smije/index.php/blog/dwaynejohnson/&amp;title=Dwayne Johnson"
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-reddit-com.gif" width="16"
								height="16" alt="">&nbsp;Reddit.com
							</a>&nbsp;
						</div>
						<div class="postContent">
							<p>I love making people laugh and feel good, and that's awesome
								and special for me to be able to do that</p>
							<a class="aw-blog-read-more" href="<?php echo WEBPATH?>/blogdetail/viviennewestwood.html">Read
								More</a>
						</div>
					</div>
					<div class="postWrapper">
						<a
							href="http://alothemes.com/demo/smije/index.php/blog/annehathaway/">
							<img class="img-responsive"
							src="<?php echo BAG_REAL_HTML; ?>/smije/media/magiccart/blog/cache/871x435/blog1-fashion.jpg">
						</a>
						<div class="postTitle">
							<h2>
								<a href="<?php echo WEBPATH?>/blogdetail/viviennewestwood.html">Anne Hathaway</a>
							</h2>
						</div>
						<div class="by post-date">
							<div class="postDetails">
								<!--<a href="#commentBox" > </a>-->
								<!--<a href=""></a>-->
								<!--<a href=""></a>-->
								<!--<a href=""></a>-->
								By: <span class="user">Alex Justin Johnson</span>
							</div>
							<div class="number">
								<h3>Saturday, November 22, 2014 9:11:35 PM America/Los_Angeles</h3>
							</div>
							<span class="comments"><span class="comments-text"> comments</span></span>
						</div>
						<div class="tags">
							<h4>Tags:</h4>
							<ul class="tags">
								<li><a
									href="http://alothemes.com/demo/smije/index.php/blog/tag/News/">News</a></li>
								<li><a
									href="http://alothemes.com/demo/smije/index.php/blog/tag/Furniture/">Furniture</a></li>
								<li><a
									href="http://alothemes.com/demo/smije/index.php/blog/tag/Fashion/">Fashion</a></li>
								<li><a
									href="http://alothemes.com/demo/smije/index.php/blog/tag/magento/">magento</a></li>
							</ul>
						</div>
						<div class="postBookmarks">
							<h4>Bookmark with:</h4>
							<a
								href="http://digg.com/submit?phase=2&amp;url=http://alothemes.com/demo/smije/index.php/blog/annehathaway/&amp;title=Anne Hathaway&amp;bodytext=Anne Hathaway&amp;topic="
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-digg-com.gif" width="16"
								height="16" alt="">&nbsp;Digg.com
							</a>&nbsp; <a
								href="http://www.stumbleupon.com/submit?url=http://alothemes.com/demo/smije/index.php/blog/annehathaway/&amp;title=Anne Hathaway&amp;newcomment=Anne Hathaway"
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-stumbleupon-com.gif" width="16"
								height="16" alt="">&nbsp;Stumbleupon.com
							</a>&nbsp; <a
								href="http://del.icio.us/post/?url=http://alothemes.com/demo/smije/index.php/blog/annehathaway/&amp;title=Anne Hathaway&amp;notes=Anne Hathaway"
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-del-icio-us.gif" width="16"
								height="16" alt="">&nbsp;Del.icio.us
							</a>&nbsp; <a
								href="http://www.facebook.com/sharer.php?u=http://alothemes.com/demo/smije/index.php/blog/annehathaway/&amp;t=Anne Hathaway"
								class="bm"> <img
								src="<?php echo BAG_REAL_HTML; ?>/img/communityIcons/http-www-facebook-com-.gif" width="16"
								height="16" alt="">&nbsp;Facebook
							</a>&nbsp; <a
								href="http://reddit.com/submit?url=http://alothemes.com/demo/smije/index.php/blog/annehathaway/&amp;title=Anne Hathaway"
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-reddit-com.gif" width="16"
								height="16" alt="">&nbsp;Reddit.com
							</a>&nbsp;
						</div>
						<div class="postContent">
							<p>I think fashion is a lot of fun. I love clothes. More than
								fashion or brand labels, I love design.</p>
							<a class="aw-blog-read-more" href="<?php echo WEBPATH?>/blogdetail/viviennewestwood.html">Read
								More</a>
						</div>
					</div>
					<div class="blog-toolbar blog-toolbar-bottom">
						<div class="toolbar">
							<div class="sorter">

								<div class="sort-by">
									<label>Sort By</label> <select
										onchange="setLocation(this.value)">
										<option
											value="http://alothemes.com/demo/smije/index.php/blog/?dir=asc&amp;order=created_time"
											selected="selected">Created At</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/blog/?dir=asc&amp;order=user">
											Added By</option>
									</select> <a
										href="http://alothemes.com/demo/smije/index.php/blog/?dir=desc&amp;order=created_time"
										title="Set Descending Direction"><img
										src="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/images/i_asc_arrow.gif"
										alt="Set Descending Direction" class="v-middle"></a>
								</div>
								<div class="limiter">
									<label>Show</label> <select onchange="setLocation(this.value)">
										<option
											value="http://alothemes.com/demo/smije/index.php/blog/?limit=10">
											10</option>
									</select>
								</div>
							</div>
							<div class="pager">
								<p class="amount">
									<strong>4 Item(s)</strong>
								</p>







							</div>
						</div>
					</div>
				</div>
				<!-- Blogs -->
			</div>
		</div>
	</div>
</div>