<div class="main-container col2-left-layout">
	<div class="container">
		<div class="main">
			<div class="breadcrumbs">
				<ul>
                    <li class="home">
                            <a href="<?php echo WEBPATH;?>" title="Go to Home Page">Home</a>
                        
                        </li>
                    <li class="blog">
                            <a href="<?php echo WEBPATH;?>/blog.html" title="Return to Blog">Blog</a>
                        
                        </li>
                    <li class="blog_page">
                            <strong>Vivienne Westwood </strong>
                                    </li>
                </ul>
			</div>


			<div class="row show-grid">
				<div
					class="col-left sidebar col-lg-3 col-md-3 col-sm-3 col-pull-3 hidden-xs">

					<div id="leftcatalogue"></div>
					<!-- leftcatalogue -->


					<div id="blockcompare"></div>
					<!-- blockcompare -->
					<div id="populartags"></div>
					<!-- populartags -->

					<div id="containernone"></div>
					<!-- container-none -->

					<p></p>
				</div>

				<!--thay trang chi tiet vao--->
				<div
					class="col-main col-lg-9 col-md-9 col-sm-9 col-push-9 col-xs-12">
					<div id="messages_product_view"></div>
					<div class="postWrapper">
						<div class="postTitle">
							<h2>
								<a
									href="http://alothemes.com/demo/smije/index.php/blog/viviennewestwood/">Vivienne
									Westwood </a>
							</h2>
						</div>
						<div class="by post-date">
							<div class="postDetails">
								Posted in <a
									href="http://alothemes.com/demo/smije/index.php/blog/cat/news">News</a>
								<a
									href="http://alothemes.com/demo/smije/index.php/blog/cat/magento">magento</a>
								By <span class="poster user">Alex Justin Johnson</span>
							</div>
							<div class="number">
								<h3>Saturday, November 22, 2014 9:21:26 PM America/Los_Angeles</h3>
							</div>
						</div>
						<div class="tags"></div>
						<div class="postBookmarks">
							<h4>Bookmark with:</h4>
							<a
								href="http://digg.com/submit?phase=2&amp;url=http://alothemes.com/demo/smije/index.php/blog/viviennewestwood/?title=Vivienne Westwood &amp;bodytext=Vivienne Westwood &amp;topic="
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-digg-com.gif" width="16"
								height="16" alt="">&nbsp;Digg.com
							</a>&nbsp; <a
								href="http://www.stumbleupon.com/submit?url=http://alothemes.com/demo/smije/index.php/blog/viviennewestwood/?title=Vivienne Westwood &amp;newcomment=Vivienne Westwood "
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-stumbleupon-com.gif" width="16"
								height="16" alt="">&nbsp;Stumbleupon.com
							</a>&nbsp; <a
								href="http://del.icio.us/post/?url=http://alothemes.com/demo/smije/index.php/blog/viviennewestwood/?title=Vivienne Westwood &amp;notes=Vivienne Westwood "
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-del-icio-us.gif" width="16"
								height="16" alt="">&nbsp;Del.icio.us
							</a>&nbsp; <a
								href="http://www.facebook.com/sharer.php?u=http://alothemes.com/demo/smije/index.php/blog/viviennewestwood/?t=Vivienne Westwood "
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-www-facebook-com-.gif" width="16"
								height="16" alt="">&nbsp;Facebook
							</a>&nbsp; <a
								href="http://reddit.com/submit?url=http://alothemes.com/demo/smije/index.php/blog/viviennewestwood/?title=Vivienne Westwood "
								class="bm"> <img src="<?php echo BAG_REAL_HTML; ?>/img/http-reddit-com.gif" width="16"
								height="16" alt="">&nbsp;Reddit.com
							</a>&nbsp;
						</div>
						<div class="postContent postContent-detail">
							<img
								src="<?php echo BAG_REAL_HTML; ?>/smije/media/wysiwyg/alothemes/static/blog4-fashion.jpg"
								alt=""> I didn't consider myself a fashion designer at all at
							the time of punk. I was just using fashion as a way to express my
							resistance and to be rebellious. I came from the country, and by
							the time I got to London, I considered myself to be very stupid.
							It was my ambition to understand the world I live in.
						</div>
					</div>

					<!-- Comment Section -->

					<!--<div class="postTitle"><a name="commentBox" ></a>
        <h2></h2>
    </div>-->
					<div class="blog-toolbar blog-toolbar-top">
						<div class="toolbar">
							<div class="sorter">

								<div class="sort-by">
									<label>Sort By</label> <select
										onchange="setLocation(this.value)">
										<option
											value="http://alothemes.com/demo/smije/index.php/blog/post/view/identifier/viviennewestwood/?dir=asc&amp;order=created_time"
											selected="selected">Created At</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/blog/post/view/identifier/viviennewestwood/?dir=asc&amp;order=email">
											Added By</option>
									</select> <a
										href="http://alothemes.com/demo/smije/index.php/blog/post/view/identifier/viviennewestwood/?dir=desc&amp;order=created_time"
										title="Set Descending Direction"><img
										src="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/images/i_asc_arrow.gif"
										alt="Set Descending Direction" class="v-middle"></a>
								</div>
								<div class="limiter">
									<label>Show</label> <select onchange="setLocation(this.value)">
										<option
											value="http://alothemes.com/demo/smije/index.php/blog/post/view/identifier/viviennewestwood/?limit=10">
											10</option>
									</select>
								</div>
							</div>
							<div class="pager">
								<p class="amount">
									<strong>2 Item(s)</strong>
								</p>







							</div>
						</div>
					</div>
					<div class="commentWrapper">
						<div class="commentDetails">
							<h4 class="username">Christina</h4>
							posted on Monday, December 1, 2014 7:58:35 PM America/Los_Angeles
						</div>
						<div class="commentContent">The addicting podcast will get a
							real-world update this January.</div>
					</div>
					<div class="commentWrapper">
						<div class="commentDetails">
							<h4 class="username">Angela</h4>
							posted on Monday, December 1, 2014 7:57:27 PM America/Los_Angeles
						</div>
						<div class="commentContent">Great Thing of the Day: Prince Harry
							Reveals His Biggest Secret</div>
					</div>
					<div class="blog-toolbar blog-toolbar-bottom">
						<div class="toolbar">
							<div class="sorter">

								<div class="sort-by">
									<label>Sort By</label> <select
										onchange="setLocation(this.value)">
										<option
											value="http://alothemes.com/demo/smije/index.php/blog/post/view/identifier/viviennewestwood/?dir=asc&amp;order=created_time"
											selected="selected">Created At</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/blog/post/view/identifier/viviennewestwood/?dir=asc&amp;order=email">
											Added By</option>
									</select> <a
										href="http://alothemes.com/demo/smije/index.php/blog/post/view/identifier/viviennewestwood/?dir=desc&amp;order=created_time"
										title="Set Descending Direction"><img
										src="http://alothemes.com/demo/smije/skin/frontend/alosmije/smije_fashion/images/i_asc_arrow.gif"
										alt="Set Descending Direction" class="v-middle"></a>
								</div>
								<div class="limiter">
									<label>Show</label> <select onchange="setLocation(this.value)">
										<option
											value="http://alothemes.com/demo/smije/index.php/blog/post/view/identifier/viviennewestwood/?limit=10">
											10</option>
									</select>
								</div>
							</div>
							<div class="pager">
								<p class="amount">
									<strong>2 Item(s)</strong>
								</p>







							</div>
						</div>
					</div>



					<form action="" class="blog-postbox" id="postComment" method="post">
						<fieldset class="group-select">
							<div class="post-title">
								<h4 class="legend">Submit Comment</h4>
							</div>
							<ul class="form-list">
								<li>
									<div class="input-box">
										<label for="name" class="required">Name<em>*</em></label><br>
										<input name="user" id="user" value="" title="Name"
											class="required-entry input-text" type="text">
									</div>

									<div class="input-box">
										<label for="email" class="required">Email<em>*</em></label><br>
										<input name="email" id="email" value="" title="Email"
											class="required-entry input-text validate-email" type="text">
									</div>

									<div class="clear"></div>

									<div class="input-box aw-blog-comment-area">
										<label for="comment" class="required">Comment<em>*</em></label><br>
										<textarea name="comment" id="comment" title="Comment"
											class="required-entry input-text" cols="50" rows="5"></textarea>
									</div>
								</li>

							</ul>
						</fieldset>
						<div class="button-set">
							<input name="post_id" type="hidden" value="8">
							<button class="button form-button" type="submit">
								<span><span>Submit Comment</span></span>
							</button>
							<p class="required">* Required Fields</p>
						</div>
					</form>
					
                    <p></p>
                    
					<script type="text/javascript">
                var contactForm = new VarienForm('postComment', false);
            </script>
				</div>
				<!-- Blogs details -->
			</div>
		</div>
	</div>
</div>