<div class="block block-list block-compare" style="display: block;">
    <div class="block-title">
        <strong><span>Compare Products             
                <small>(2)</small>
                    </span></strong>
    </div>
    <div class="block-content">
            <ol id="compare-items">
                    <li class="item odd">
                <input type="hidden" class="compare-item-id" value="25">
                <a href="<?php echo WEBPATH?>/catalog/productcompareremove/25/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvcm9sbGVyLXN1aXRjYXNlLmh0bWw" title="Remove This Item" class="btn-remove" onclick="return confirm('Are you sure you would like to remove this item from the compare products?');">Remove This Item</a>
                <p class="product-name"><a href="<?php echo WEBPATH?>/eshopbags/plaid-cotton-shirt.html">Plaid Cotton Shirt</a></p>
            </li>
                    <li class="item last even">
                <input type="hidden" class="compare-item-id" value="30">
                <a href="<?php echo WEBPATH?>/catalog/productcompareremove/30/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvcm9sbGVyLXN1aXRjYXNlLmh0bWw" title="Remove This Item" class="btn-remove" onclick="return confirm('Are you sure you would like to remove this item from the compare products?');">Remove This Item</a>
                <p class="product-name"><a href="<?php echo WEBPATH?>/eshopbags/roller-suitcase.html">Roller Suitcase</a></p>
            </li>
                </ol>
        <script type="text/javascript">decorateList('compare-items')</script>
        <div class="actions">
            <a href="<?php echo WEBPATH?>/catalog/productcompareclearall/0/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvcm9sbGVyLXN1aXRjYXNlLmh0bWw" onclick="return confirm('Are you sure you would like to remove all products from your comparison?');">Clear All</a>
            <button type="button" title="Compare" class="button" onclick="popWin('<?php echo WEBPATH?>/catalogitemscompare/2530/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvcm9sbGVyLXN1aXRjYXNlLmh0bWw','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')"><span><span>Compare</span></span></button>
            <!-- <button type="button" title="Compare" class="button" onclick="popWin('<?php echo WEBPATH?>/catalogitemscompare/25,30/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvcm9sbGVyLXN1aXRjYXNlLmh0bWw','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')"><span><span>Compare</span></span></button>
         -->
        </div>
        </div>
</div>