<p>
<div class="container-none">
	<div id="sfazzxykmm" class="iview">
		<div class="img-responsive image-important"
			data-iview-image="<?php echo BAG_REAL_HTML; ?>/smije/media/magiccart/magicslider/cache/270x413//l/e/left-static-fashion01.png"
			data-iview-transition="slide-in-right,slide-in-left,slide-in-up,slide-in-down,fade">
		</div>
		<div class="img-responsive image-important"
			data-iview-image="<?php echo BAG_REAL_HTML; ?>/smije/media/magiccart/magicslider/cache/270x413//l/e/left-static-fashion02.png"
			data-iview-transition="slide-in-right,slide-in-left,slide-in-up,slide-in-down,fade">
		</div>
		<div class="img-responsive image-important"
			data-iview-image="<?php echo BAG_REAL_HTML; ?>/smije/media/magiccart/magicslider/cache/270x413//l/e/left-static-fashion03.png"
			data-iview-transition="slide-in-right,slide-in-left,slide-in-up,slide-in-down,fade">
		</div>
	</div>
</div>


</p>
<script type="text/javascript">
				//container -none load left menu 
									jQuery(document).ready(function($) {
										$('#sfazzxykmm').iView({
											// pauseTime: 7000,
											// directionNav: false,
											// controlNav: true,
											// controlNavNextPrev: true,
											// controlNavTooltip: true, // Show tooltip image previewer
											// pauseOnHover: true,
											// timerBarStroke: 0, // hide timerBar
											timerOpacity : 0, // hide timerBar
											pauseOnHover : true,
											pauseTime : 7000,
											controlNav : 1,
											controlNavNextPrev : false,
											controlNavTooltip : false,
											directionNav : false,
										});
									});
</script>
