<div class="main-container col1-layout">
	<div class="alo-breadcrumbs">
		<div class="container">
			<div class="main">
				<div class="row show-grid">
					<div class="col-lg-12">
						<div class="breadcrumbs">
							<ul>
								<li class="home"><a href="<?php echo WEBPATH;?>" title="Home">Home</a>

								</li>
								<li class="create_testimonials"><strong>Create Testimonials</strong>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="alo-top">
		<div class="container">
			<div class="main">
				<div class="row show-grid">
					<div class="col-lg-12"></div>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="main">
			<div class="row show-grid">
				<div class="col-main col-lg-12">
					<div class="testimonials-create">
						<div class="page-title">
							<h1>Write Testimonial</h1>
						</div>
						<div class="testimonials-form">
							<form id="testimonialForm" name="testimonialForm" action="http://alothemes.com/demo/smije/index.php/testimonial/index/createpost/"
								method="post" enctype="multipart/form-data">
								<div class="fieldset">
									<label for="name"> Contact Name <span class="required">*</span>
									</label>
									<div class="input-box">
										<input type="text" class=" input-text required-entry" value=""
											name="name" id="name">
									</div>
									<label for="company"> Company </label>
									<div class="input-box">
										<input type="text" class=" input-text" value="" name="company"
											id="company">
									</div>
									<label for="email"> Email <span class="required">*</span>
									</label>
									<div class="input-box">
										<input type="text"
											class=" validate-email input-text required-entry" value=""
											name="email" id="email">
									</div>
									<label for="website"> Website URL </label>
									<div class="input-box">
										<input type="text" class="validate-clean-url input-text"
											value="" name="website" id="website">
									</div>
									<label for="image"> Image </label>
									<div class="input-box">
										<input type="file" class="input-file" name="image" id="image">
									</div>

									<table style="width: 300px">
										<tbody>
											<tr>
												<td class="label"><label for="detailed_rating"
													class="rating">Rating <span class="required">*</span></label></td>
												<td class="value"><span id="detailed_rating">
														<div id="rating_detail">
															<div class="product-review-box">
																<table cellspacing="0" id="product-review-table"
																	width="250">
																	<thead>
																		<tr>
																			<th><span class="nobr"><b>1 star</b> </span></th>
																			<th><span class="nobr"><b>2 stars</b> </span></th>
																			<th><span class="nobr"><b>3 stars</b> </span></th>
																			<th><span class="nobr"><b>4 stars</b> </span></th>
																			<th><span class="nobr"><b>5 stars</b> </span></th>
																		</tr>
																	</thead>
																	<tbody>
																		<tr class="odd last">
																			<td><input type="radio" name="rating_summary"
																				id="rating_1" value="1" checked="checked"></td>
																			<td><input type="radio" name="rating_summary"
																				id="rating_2" value="2" checked="checked"></td>
																			<td><input type="radio" name="rating_summary"
																				id="rating_3" value="3" checked="checked"></td>
																			<td><input type="radio" name="rating_summary"
																				id="rating_4" value="4" checked="checked"></td>
																			<td class="last"><input type="radio"
																				name="rating_summary" id="rating_5" value="5"
																				checked="checked"></td>
																		</tr>
																	</tbody>
																</table>
															</div>
														</div>
												</span></td>
											</tr>
										</tbody>
									</table>

									<label for="text"> Text <span class="required">*</span>
									</label>
									<div class="input-box">
										<textarea class=" required-entry textarea" cols="15" rows="2"
											style="width: 100%; height: 200px;" title="Text" name="text"
											id="text"></textarea>
									</div>
									<div class="buttons-set">
										<button class="button" title="Submit Review" type="submit">
											<span><span>Submit Testimonial</span></span>
										</button>
									</div>
								</div>
							</form>
						</div>
					</div>
					<script type="text/javascript">
//<![CDATA[
    var testimonialForm = new VarienForm('testimonialForm', true);
//]]>
</script>
				</div>
			</div>
		</div>
	</div>
	<div class="alo-bottom">
		<div class="container">
			<div class="main">
				<div class="row show-grid">
					<div class="col-lg-12"></div>
				</div>
			</div>
		</div>
	</div>
</div>