<div class="block block-cart">
	<div class="block-title">
		<strong><span>My Cart</span></strong>
	</div>
	<div class="block-content">
		<div class="summary">
			<p class="amount">
				There are <a
					href="<?php echo WEBPATH?>/checkout/cart/">5
					items</a> in your cart.
			</p>
			<p class="subtotal">
				<span class="label">Cart Subtotal:</span> <span class="price">$1,327.00</span>
			</p>
		</div>
		<div class="actions">
			<button type="button" title="Checkout" class="button"
				onclick="setLocation('<?php echo WEBPATH?>/checkout/onepage/')">
				<span><span>Checkout</span></span>
			</button>
		</div>
		<p class="block-subtitle">Recently added item(s)</p>
		<ol id="cart-sidebar" class="mini-products-list">
			<li class="item"><a
				href="<?php echo WEBPATH?>/dorian-perforated-oxford.html"
				title="Dorian Perforated Oxford" class="product-image"><img
					src="<?php echo BAG_REAL_HTML;?>/smije/media/catalog/product/cache/4/thumbnail/200x250/9df78eab33525d08d6e5fb8d27136e95/1/2/12_6.jpg"
					width="79" height="86" alt="Dorian Perforated Oxford"></a>
				<div class="product-details">
					<p class="product-name">
						<a
							href="<?php echo WEBPATH?>/dorian-perforated-oxford.html">Dorian
							Perforated Oxford</a>
					</p>

					<strong>1</strong> x <span class="price">$345.00</span>


					<div class="clearfix">
						<a
							href="<?php echo WEBPATH?>/checkout/cart/configure/307"
							title="Edit item" class="btn-edit">Edit item</a> <a
							href="<?php echo WEBPATH?>/checkout/cart/delete/307/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvd2lzaGxpc3Qv"
							title="Remove This Item"
							onclick="return confirm('Are you sure you would like to remove this item from the shopping cart?');"
							class="btn-remove btn-remove2">Remove This Item</a>
					</div>
				</div></li>
			<li class="item"><a
				href="<?php echo WEBPATH?>/suede-loafer-navy.html"
				title="Suede Loafer, Navy" class="product-image"><img
					src="<?php echo BAG_REAL_HTML;?>/smije/media/catalog/product/cache/4/thumbnail/200x250/9df78eab33525d08d6e5fb8d27136e95/1/1/11_4.jpg"
					width="79" height="86" alt="Suede Loafer, Navy"></a>
				<div class="product-details">
					<p class="product-name">
						<a
							href="<?php echo WEBPATH?>/suede-loafer-navy.html">Suede
							Loafer, Navy</a>
					</p>

					<strong>1</strong> x <span class="price">$345.00</span>


					<div class="clearfix">
						<a
							href="<?php echo WEBPATH?>/checkout/cart/configure/id/291/"
							title="Edit item" class="btn-edit">Edit item</a> <a
							href="<?php echo WEBPATH?>/checkout/cart/delete/id/291/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvd2lzaGxpc3Qv/"
							title="Remove This Item"
							onclick="return confirm('Are you sure you would like to remove this item from the shopping cart?');"
							class="btn-remove btn-remove2">Remove This Item</a>
					</div>
				</div></li>
			<li class="item"><a
				href="<?php echo WEBPATH?>/plaid-cotton-shirt.html"
				title="Plaid Cotton Shirt" class="product-image"><img
					src="<?php echo BAG_REAL_HTML;?>/smije/media/catalog/product/cache/4/thumbnail/200x250/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1.jpg"
					width="79" height="86" alt="Plaid Cotton Shirt"></a>
				<div class="product-details">
					<p class="product-name">
						<a
							href="<?php echo WEBPATH?>/plaid-cotton-shirt.html">Plaid
							Cotton Shirt</a>
					</p>

					<strong>2</strong> x <span class="price">$185.00</span>


					<div class="clearfix">
						<a
							href="<?php echo WEBPATH?>/checkout/cart/configure/id/290/"
							title="Edit item" class="btn-edit">Edit item</a> <a
							href="<?php echo WEBPATH?>/checkout/cart/delete/id/290/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvd2lzaGxpc3Qv/"
							title="Remove This Item"
							onclick="return confirm('Are you sure you would like to remove this item from the shopping cart?');"
							class="btn-remove btn-remove2">Remove This Item</a>
					</div>
				</div></li>
		</ol>
		<script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
	</div>
</div>