<div class="main-container col2-left-layout">
	<div class="container">
		<div class="main">
			<div class="breadcrumbs">
				<ul>
					<li class="home"><a href="<?php echo WEBPATH;?>" title="Home">Home</a></li>
					<li class="magicproduct"><strong>New Products</strong></li>
				</ul>
			</div>


			<div class="row show-grid">
				<div class="col-left sidebar col-lg-3 col-md-3 col-sm-3 col-pull-3 hidden-xs">

					         <div id="leftcatalogue"> </div><!-- leftcatalogue -->
								
								<div id="bestsellera"></div><!-- bestsellera -->
								
								<div id="saleproducta"></div><!-- sale product -->
								
								<div id="blockcompare"></div><!-- blockcompare -->
								<div id="populartags"></div><!-- populartags -->
								
								<div id="containernone"></div><!-- container-none -->

					<p></p>
				</div>

				<!--thay trang chi tiet vao--->
				<div
					class="col-main col-lg-9 col-md-9 col-sm-9 col-push-9 col-xs-12">


					<div class="category-products">
						<div class="toolbar">
							<div class="sorter">
								<p class="view-mode">
									<label>View as:</label> <strong title="Grid" class="grid">Grid</strong>&nbsp;
									<a href="<?php echo BAG_REAL_HTML; ?>/list.html" title="List" class="list">List</a>&nbsp;
								</p>

								<div class="sort-by">
									<label>Sort By</label> <select
										onchange="setLocation(this.value)">
										<option
											value="http://alothemes.com/demo/smije/index.php/newproduct?dir=asc&amp;mode=grid&amp;order=position"
											selected="selected">Position</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/newproduct?dir=asc&amp;mode=grid&amp;order=name">
											Name</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/newproduct?dir=asc&amp;mode=grid&amp;order=price">
											Price</option>
									</select> <a
										href="http://alothemes.com/demo/smije/index.php/newproduct?dir=desc&amp;mode=grid&amp;order=position"
										title="Set Descending Direction"><img
										src="http://alothemes.com/demo/smije/skin/frontend/alosmije/smije_fashion/images/i_asc_arrow.gif"
										alt="Set Descending Direction" class="v-middle"></a>
								</div>
								<div class="limiter">
									<label>Show</label> <select onchange="setLocation(this.value)">
										<option
											value="http://alothemes.com/demo/smije/index.php/newproduct?limit=8&amp;mode=grid">
											8</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/newproduct?limit=12&amp;mode=grid"
											selected="selected">12</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/newproduct?limit=32&amp;mode=grid">
											32</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/newproduct?limit=40&amp;mode=grid">
											40</option>
									</select>
								</div>
							</div>
							<div class="pager">
								<p class="amount">
									<strong>4 Item(s)</strong>
								</p>







							</div>
						</div>


						<ul class="row show-grid products-grid first last odd">
							<li
								class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-mobile-12 item first">
								<div class="images-container">
									<div class="product-hover">
										<span class="sticker top-left"><span class="labelnew">New</span></span>
										<a href="<?php echo WEBPATH;?>/eshopbags/suede-loafer-navy.html"
											title="Plaid Cotton Shirt" class="product-image"> <img
											class="img-responsive hover-img"
											src="<?php echo BAG_REAL_HTML; ?>/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1.jpg"
											width="770" height="988" alt="Plaid Cotton Shirt"> <span
											class="product-img-back"> <img class="img-responsive"
												src="<?php echo BAG_REAL_HTML; ?>/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/1/-/1-1.jpg"
												width="770" height="988" alt="Plaid Cotton Shirt">
										</span>
										</a>
									</div>
									<div class="actions-no">
										<div class="actions">
											<button type="button" title="Add to Cart"
												class="button btn-cart pull-left"
												onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWdyaWQ,/product/25/form_key/3fXQuE9EWz5npGTp/')"
												magiccartEvent="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWdyaWQ,/product/25/form_key/3fXQuE9EWz5npGTp/')">
												<span><span>Add to Cart</span></span>
											</button>
											<ul class="add-to-links pull-left">
												<li class="pull-left"><a
													href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/25/form_key/3fXQuE9EWz5npGTp/"
													class="link-wishlist">Add to Wishlist</a></li>
												<li class="pull-right"><a
													href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/25/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWdyaWQ,/form_key/3fXQuE9EWz5npGTp/"
													class="link-compare">Add to Compare</a></li>
											</ul>
										</div>
									</div>
								</div>
								<div class="products-textlink clearfix">
									<h2 class="product-name">
										<a href="<?php echo WEBPATH;?>/eshopbags/suede-loafer-navy.html"
											title="Plaid Cotton Shirt">Plaid Cotton Shirt</a>
									</h2>
									<div class="ratings">
										<div class="rating-box">
											<div class="rating" style="width: 100%"></div>
										</div>
										<span class="amount"><a href="#"
											onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/25/'; return false;">1
												Review(s)</a></span>
									</div>



									<div class="price-box">
										<span class="regular-price" id="product-price-25"> <span
											class="price">$185.00</span>
										</span>

									</div>

								</div>
							</li>
							<li
								class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-mobile-12 item">
								<div class="images-container">
									<div class="product-hover">
										<span class="sticker top-left"><span class="labelnew">New</span></span>
										<a href="<?php echo WEBPATH;?>/eshopbags/suede-loafer-navy.html"
											title="French Cuff Cotton" class="product-image"> <img
											class="img-responsive hover-img"
											src="<?php echo BAG_REAL_HTML; ?>/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/2/_/2_3.jpg"
											width="770" height="988" alt="French Cuff Cotton"> <span
											class="product-img-back"> <img class="img-responsive"
												src="<?php echo BAG_REAL_HTML; ?>/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/2/-/2-2_1.jpg"
												width="770" height="988" alt="French Cuff Cotton">
										</span>
										</a>
									</div>
									<div class="actions-no">
										<div class="actions">
											<button type="button" title="Add to Cart"
												class="button btn-cart pull-left"
												onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWdyaWQ,/product/26/form_key/3fXQuE9EWz5npGTp/')"
												magiccartEvent="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWdyaWQ,/product/26/form_key/3fXQuE9EWz5npGTp/')">
												<span><span>Add to Cart</span></span>
											</button>
											<ul class="add-to-links pull-left">
												<li class="pull-left"><a
													href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/26/form_key/3fXQuE9EWz5npGTp/"
													class="link-wishlist">Add to Wishlist</a></li>
												<li class="pull-right"><a
													href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/26/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWdyaWQ,/form_key/3fXQuE9EWz5npGTp/"
													class="link-compare">Add to Compare</a></li>
											</ul>
										</div>
									</div>
								</div>
								<div class="products-textlink clearfix">
									<h2 class="product-name">
										<a href="<?php echo WEBPATH;?>/eshopbags/suede-loafer-navy.html"
											title="French Cuff Cotton">French Cuff Cotton</a>
									</h2>
									<div class="ratings">
										<div class="rating-box">
											<div class="rating" style="width: 60%"></div>
										</div>
										<span class="amount"><a href="#"
											onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/26/'; return false;">1
												Review(s)</a></span>
									</div>



									<div class="price-box">
										<span class="regular-price" id="product-price-26"> <span
											class="price">$168.00</span>
										</span>

									</div>

								</div>
							</li>
							<li
								class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-mobile-12 item">
								<div class="images-container">
									<div class="product-hover">
										<span class="sticker top-left"><span class="labelnew">New</span></span>
										<a href="<?php echo WEBPATH;?>/eshopbags/suede-loafer-navy.html"
											title="Broad St. Flapover" class="product-image"> <img
											class="img-responsive hover-img"
											src="<?php echo BAG_REAL_HTML; ?>/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/1/8/18_6.jpg"
											width="770" height="988" alt="Broad St. Flapover"> <span
											class="product-img-back"> <img class="img-responsive"
												src="<?php echo BAG_REAL_HTML; ?>/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/1/4/14_4.jpg"
												width="770" height="988" alt="Broad St. Flapover">
										</span>
										</a>
									</div>
									<div class="actions-no">
										<div class="actions">
											<button type="button" title="Add to Cart"
												class="button btn-cart pull-left"
												onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWdyaWQ,/product/41/form_key/3fXQuE9EWz5npGTp/')"
												magiccartEvent="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWdyaWQ,/product/41/form_key/3fXQuE9EWz5npGTp/')">
												<span><span>Add to Cart</span></span>
											</button>
											<ul class="add-to-links pull-left">
												<li class="pull-left"><a
													href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/41/form_key/3fXQuE9EWz5npGTp/"
													class="link-wishlist">Add to Wishlist</a></li>
												<li class="pull-right"><a
													href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/41/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWdyaWQ,/form_key/3fXQuE9EWz5npGTp/"
													class="link-compare">Add to Compare</a></li>
											</ul>
										</div>
									</div>
								</div>
								<div class="products-textlink clearfix">
									<h2 class="product-name">
										<a href="<?php echo WEBPATH;?>/eshopbags/suede-loafer-navy.html"
											title="Broad St. Flapover">Broad St. Flapover</a>
									</h2>
									<div class="ratings">
										<div class="rating-box">
											<div class="rating" style="width: 60%"></div>
										</div>
										<span class="amount"><a href="#"
											onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/41/'; return false;">1
												Review(s)</a></span>
									</div>



									<div class="price-box">
										<span class="regular-price" id="product-price-41"> <span
											class="price">$234.00</span>
										</span>

									</div>

								</div>
							</li>
							<li
								class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-mobile-12 item last">
								<div class="images-container">
									<div class="product-hover">
										<span class="sticker top-left"><span class="labelnew">New</span></span>
										<a href="<?php echo WEBPATH;?>/eshopbags/suede-loafer-navy.html"
											title="Houston Travel Wallet" class="product-image"> <img
											class="img-responsive hover-img"
											src="<?php echo BAG_REAL_HTML; ?>/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/1/6/16_5.jpg"
											width="770" height="988" alt="Houston Travel Wallet"> <span
											class="product-img-back"> <img class="img-responsive"
												src="<?php echo BAG_REAL_HTML; ?>/smije/media/catalog/product/cache/4/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/1/4/14_5.jpg"
												width="770" height="988" alt="Houston Travel Wallet">
										</span>
										</a>
									</div>
									<div class="actions-no">
										<div class="actions">
											<button type="button" title="Add to Cart"
												class="button btn-cart pull-left"
												onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWdyaWQ,/product/42/form_key/3fXQuE9EWz5npGTp/')"
												magiccartEvent="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWdyaWQ,/product/42/form_key/3fXQuE9EWz5npGTp/')">
												<span><span>Add to Cart</span></span>
											</button>
											<ul class="add-to-links pull-left">
												<li class="pull-left"><a
													href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/42/form_key/3fXQuE9EWz5npGTp/"
													class="link-wishlist">Add to Wishlist</a></li>
												<li class="pull-right"><a
													href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/42/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbmV3cHJvZHVjdD9tb2RlPWdyaWQ,/form_key/3fXQuE9EWz5npGTp/"
													class="link-compare">Add to Compare</a></li>
											</ul>
										</div>
									</div>
								</div>
								<div class="products-textlink clearfix">
									<h2 class="product-name">
										<a href="<?php echo WEBPATH;?>/eshopbags/suede-loafer-navy.html"
											title="Houston Travel Wallet">Houston Travel Wallet</a>
									</h2>
									<div class="ratings">
										<div class="rating-box">
											<div class="rating" style="width: 60%"></div>
										</div>
										<span class="amount"><a href="#"
											onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/42/'; return false;">1
												Review(s)</a></span>
									</div>



									<div class="price-box">
										<span class="regular-price" id="product-price-42"> <span
											class="price">$156.00</span>
										</span>

									</div>

								</div>
							</li>
						</ul>
						<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>

						<div class="toolbar-bottom">
							<div class="toolbar">
								<div class="sorter">
									<p class="view-mode">
										<label>View as:</label> <strong title="Grid" class="grid">Grid</strong>&nbsp;
										<a href="<?php echo BAG_REAL_HTML; ?>/list.html" title="List" class="list">List</a>&nbsp;
									</p>

									<div class="sort-by">
										<label>Sort By</label> <select
											onchange="setLocation(this.value)">
											<option
												value="http://alothemes.com/demo/smije/index.php/newproduct?dir=asc&amp;mode=grid&amp;order=position"
												selected="selected">Position</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/newproduct?dir=asc&amp;mode=grid&amp;order=name">
												Name</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/newproduct?dir=asc&amp;mode=grid&amp;order=price">
												Price</option>
										</select> <a
											href="http://alothemes.com/demo/smije/index.php/newproduct?dir=desc&amp;mode=grid&amp;order=position"
											title="Set Descending Direction"><img
											src="http://alothemes.com/demo/smije/skin/frontend/alosmije/smije_fashion/images/i_asc_arrow.gif"
											alt="Set Descending Direction" class="v-middle"></a>
									</div>
									<div class="limiter">
										<label>Show</label> <select onchange="setLocation(this.value)">
											<option
												value="http://alothemes.com/demo/smije/index.php/newproduct?limit=8&amp;mode=grid">
												8</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/newproduct?limit=12&amp;mode=grid"
												selected="selected">12</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/newproduct?limit=32&amp;mode=grid">
												32</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/newproduct?limit=40&amp;mode=grid">
												40</option>
										</select>
									</div>
								</div>
								<div class="pager">
									<p class="amount">
										<strong>4 Item(s)</strong>
									</p>


								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>