<div class="main-container col2-left-layout">
	<div class="container">
		<div class="main">
			<div class="breadcrumbs">
				<ul>
					<li class="home"><a href="<?php echo WEBPATH;?>" title="Home">Home</a></li>
					<li class="magicproduct"><strong>Accessories</strong></li>
				</ul>
			</div>


			<div class="row show-grid">
				<div
					class="col-left sidebar col-lg-3 col-md-3 col-sm-3 col-pull-3 hidden-xs">

					<div id="leftcatalogue"></div>
					<!-- leftcatalogue -->

					<div id="bestsellera"></div>
					<!-- bestsellera -->

					<div id="saleproducta"></div>
					<!-- sale product -->

					<div id="blockcompare"></div>
					<!-- blockcompare -->
					<div id="populartags"></div>
					<!-- populartags -->

					<div id="containernone"></div>
					<!-- container-none -->

					<p></p>
				</div>

				<!--thay trang chi tiet vao--->
				<div
					class="col-main col-lg-9 col-md-9 col-sm-9 col-push-9 col-xs-12">
					<div class="page-title category-title">
						<h1>Outerwear</h1>
					</div>






					<div class="category-products">
						<div class="toolbar">
							<div class="sorter">
								<p class="view-mode">
									<label>View as:</label> <strong title="Grid" class="grid">Grid</strong>&nbsp;
									<a href="outerwearlist.html" title="List" class="list">List</a>&nbsp;
								</p>

								<div class="sort-by">
									<label>Sort By</label> <select
										onchange="setLocation(this.value)">
										<option
											value="http://alothemes.com/demo/smije/index.php/outerwear.html?dir=asc&amp;mode=grid&amp;order=position"
											selected="selected">Position</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/outerwear.html?dir=asc&amp;mode=grid&amp;order=name">
											Name</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/outerwear.html?dir=asc&amp;mode=grid&amp;order=price">
											Price</option>
									</select> <a
										href="http://alothemes.com/demo/smije/index.php/outerwear.html?dir=desc&amp;mode=grid&amp;order=position"
										title="Set Descending Direction"><img
										src="http://alothemes.com/demo/smije/skin/frontend/alosmije/smije_fashion/images/i_asc_arrow.gif"
										alt="Set Descending Direction" class="v-middle"></a>
								</div>
								<div class="limiter">
									<label>Show</label> <select onchange="setLocation(this.value)">
										<option
											value="http://alothemes.com/demo/smije/index.php/outerwear.html?limit=8&amp;mode=grid"
											selected="selected">8</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/outerwear.html?limit=12&amp;mode=grid">
											12</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/outerwear.html?limit=32&amp;mode=grid">
											32</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/outerwear.html?limit=40&amp;mode=grid">
											40</option>
									</select>
								</div>
							</div>
							<div class="pager">
								<p class="amount">Items 1 to 8 of 14 total</p>




								<div class="pages">
									<strong>Page:</strong>
									<ol>



										<li class="current">1</li>
										<li><a
											href="http://alothemes.com/demo/smije/index.php/outerwear.html?mode=grid&amp;p=2">2</a></li>




										<li><a class="next i-next"
											href="http://alothemes.com/demo/smije/index.php/outerwear.html?mode=grid&amp;p=2"
											title="Next"> <!--<img src="" alt="" class="v-middle" />--> <i
												class="fa fa-angle-right">&nbsp;</i>
										</a></li>
									</ol>

								</div>



							</div>
						</div>


						<ul class="row show-grid products-grid first odd">
							<li
								class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-mobile-12 item first">
								<div class="images-container">
									<div class="product-hover">
										<span class="sticker top-left"><span class="labelnew">New</span></span>
										<a
											href="/demo/smije/magicshop/quickview/view/path/suede-loafer-navy.html"
											title="Plaid Cotton Shirt" class="product-image"> <img
											class="img-responsive hover-img"
											src="http://alothemes.com/demo/smije/media/catalog/product/cache/5/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1.jpg"
											width="770" height="988" alt="Plaid Cotton Shirt"> <span
											class="product-img-back"> <img class="img-responsive"
												src="http://alothemes.com/demo/smije/media/catalog/product/cache/5/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/1/-/1-1.jpg"
												width="770" height="988" alt="Plaid Cotton Shirt">
										</span>
										</a>
									</div>
									<div class="actions-no">
										<div class="actions">
											<button type="button" title="Add to Cart"
												class="button btn-cart pull-left"
												onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/product/25/form_key/3LeOcysisvo73Bfv/')"
												magiccartEvent="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/product/25/form_key/3LeOcysisvo73Bfv/')">
												<span><span>Add to Cart</span></span>
											</button>
											<ul class="add-to-links pull-left">
												<li class="pull-left"><a
													href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/25/form_key/3LeOcysisvo73Bfv/"
													class="link-wishlist">Add to Wishlist</a></li>
												<li class="pull-right"><a
													href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/25/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/form_key/3LeOcysisvo73Bfv/"
													class="link-compare">Add to Compare</a></li>
											</ul>
										</div>
									</div>
								</div>
								<div class="products-textlink clearfix">
									<h2 class="product-name">
										<a href="/demo/suede-loafer-navy.html"
											title="Plaid Cotton Shirt">Plaid Cotton Shirt</a>
									</h2>
									<div class="ratings">
										<div class="rating-box">
											<div class="rating" style="width: 100%"></div>
										</div>
										<span class="amount"><a href="#"
											onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/25/category/91/'; return false;">1
												Review(s)</a></span>
									</div>



									<div class="price-box">
										<span class="regular-price" id="product-price-25"> <span
											class="price">$185.00</span>
										</span>

									</div>

								</div>
							</li>
							<li
								class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-mobile-12 item">
								<div class="images-container">
									<div class="product-hover">
										<a
											href="/demo/smije/magicshop/quickview/view/path/suede-loafer-navy.html"
											title="Wingtip Cognac Oxford" class="product-image"> <img
											class="img-responsive hover-img"
											src="http://alothemes.com/demo/smije/media/catalog/product/cache/5/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/1/3/13_4.jpg"
											width="770" height="988" alt="Wingtip Cognac Oxford"> <span
											class="product-img-back"> <img class="img-responsive"
												src="http://alothemes.com/demo/smije/media/catalog/product/cache/5/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/1/2/12_5.jpg"
												width="770" height="988" alt="Wingtip Cognac Oxford">
										</span>
										</a>
									</div>
									<div class="actions-no">
										<div class="actions">
											<button type="button" title="Add to Cart"
												class="button btn-cart pull-left"
												onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/product/38/form_key/3LeOcysisvo73Bfv/')"
												magiccartEvent="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/product/38/form_key/3LeOcysisvo73Bfv/')">
												<span><span>Add to Cart</span></span>
											</button>
											<ul class="add-to-links pull-left">
												<li class="pull-left"><a
													href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/38/form_key/3LeOcysisvo73Bfv/"
													class="link-wishlist">Add to Wishlist</a></li>
												<li class="pull-right"><a
													href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/38/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/form_key/3LeOcysisvo73Bfv/"
													class="link-compare">Add to Compare</a></li>
											</ul>
										</div>
									</div>
								</div>
								<div class="products-textlink clearfix">
									<h2 class="product-name">
										<a href="/demo/suede-loafer-navy.html"
											title="Wingtip Cognac Oxford">Wingtip Cognac Oxford</a>
									</h2>
									<div class="ratings">
										<div class="rating-box">
											<div class="rating" style="width: 40%"></div>
										</div>
										<span class="amount"><a href="#"
											onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/38/category/91/'; return false;">1
												Review(s)</a></span>
									</div>



									<div class="price-box">
										<span class="regular-price" id="product-price-38"> <span
											class="price">$267.00</span>
										</span>

									</div>

								</div>
							</li>
							<li
								class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-mobile-12 item">
								<div class="images-container">
									<div class="product-hover">
										<a
											href="/demo/smije/magicshop/quickview/view/path/suede-loafer-navy.html"
											title="Flat Front Trouser" class="product-image"> <img
											class="img-responsive hover-img"
											src="http://alothemes.com/demo/smije/media/catalog/product/cache/5/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/7/-/7-7_3.jpg"
											width="770" height="988" alt="Flat Front Trouser"> <span
											class="product-img-back"> <img class="img-responsive"
												src="http://alothemes.com/demo/smije/media/catalog/product/cache/5/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/7/_/7_1_7.jpg"
												width="770" height="988" alt="Flat Front Trouser">
										</span>
										</a>
									</div>
									<div class="actions-no">
										<div class="actions">
											<button type="button" title="Add to Cart"
												class="button btn-cart pull-left"
												onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/product/37/form_key/3LeOcysisvo73Bfv/')"
												magiccartEvent="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/product/37/form_key/3LeOcysisvo73Bfv/')">
												<span><span>Add to Cart</span></span>
											</button>
											<ul class="add-to-links pull-left">
												<li class="pull-left"><a
													href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/37/form_key/3LeOcysisvo73Bfv/"
													class="link-wishlist">Add to Wishlist</a></li>
												<li class="pull-right"><a
													href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/37/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/form_key/3LeOcysisvo73Bfv/"
													class="link-compare">Add to Compare</a></li>
											</ul>
										</div>
									</div>
								</div>
								<div class="products-textlink clearfix">
									<h2 class="product-name">
										<a href="/demo/suede-loafer-navy.html"
											title="Flat Front Trouser">Flat Front Trouser</a>
									</h2>
									<div class="ratings">
										<div class="rating-box">
											<div class="rating" style="width: 80%"></div>
										</div>
										<span class="amount"><a href="#"
											onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/37/category/91/'; return false;">1
												Review(s)</a></span>
									</div>



									<div class="price-box">
										<span class="regular-price" id="product-price-37"> <span
											class="price">$345.00</span>
										</span>

									</div>

								</div>
							</li>
							<li
								class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-mobile-12 item last">
								<div class="images-container">
									<div class="product-hover">
										<a
											href="/demo/smije/magicshop/quickview/view/path/suede-loafer-navy.html"
											title="Plaid Cotton Shirt" class="product-image"> <img
											class="img-responsive hover-img"
											src="http://alothemes.com/demo/smije/media/catalog/product/cache/5/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/7/_/7_1_6.jpg"
											width="770" height="988" alt="Plaid Cotton Shirt"> <span
											class="product-img-back"> <img class="img-responsive"
												src="http://alothemes.com/demo/smije/media/catalog/product/cache/5/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/7/-/7-7_2.jpg"
												width="770" height="988" alt="Plaid Cotton Shirt">
										</span>
										</a>
									</div>
									<div class="actions-no">
										<div class="actions">
											<button type="button" title="Add to Cart"
												class="button btn-cart pull-left"
												onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/product/36/form_key/3LeOcysisvo73Bfv/')"
												magiccartEvent="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/product/36/form_key/3LeOcysisvo73Bfv/')">
												<span><span>Add to Cart</span></span>
											</button>
											<ul class="add-to-links pull-left">
												<li class="pull-left"><a
													href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/36/form_key/3LeOcysisvo73Bfv/"
													class="link-wishlist">Add to Wishlist</a></li>
												<li class="pull-right"><a
													href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/36/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/form_key/3LeOcysisvo73Bfv/"
													class="link-compare">Add to Compare</a></li>
											</ul>
										</div>
									</div>
								</div>
								<div class="products-textlink clearfix">
									<h2 class="product-name">
										<a href="/demo/suede-loafer-navy.html"
											title="Plaid Cotton Shirt">Plaid Cotton Shirt</a>
									</h2>
									<div class="ratings">
										<div class="rating-box">
											<div class="rating" style="width: 60%"></div>
										</div>
										<span class="amount"><a href="#"
											onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/36/category/91/'; return false;">1
												Review(s)</a></span>
									</div>



									<div class="price-box">
										<span class="regular-price" id="product-price-36"> <span
											class="price">$234.00</span>
										</span>

									</div>

								</div>
							</li>
						</ul>
						<ul class="row show-grid products-grid last even">
							<li
								class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-mobile-12 item first">
								<div class="images-container">
									<div class="product-hover">
										<span class="sticker top-right"><span class="labelsale">-18%</span></span>
										<a
											href="/demo/smije/magicshop/quickview/view/path/suede-loafer-navy.html"
											title="Merino V-neck" class="product-image"> <img
											class="img-responsive hover-img"
											src="http://alothemes.com/demo/smije/media/catalog/product/cache/5/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/8/_/8_4.jpg"
											width="770" height="988" alt="Merino V-neck"> <span
											class="product-img-back"> <img class="img-responsive"
												src="http://alothemes.com/demo/smije/media/catalog/product/cache/5/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/8/-/8-8.jpg"
												width="770" height="988" alt="Merino V-neck">
										</span>
										</a>
									</div>
									<div class="actions-no">
										<div class="actions">
											<button type="button" title="Add to Cart"
												class="button btn-cart pull-left"
												onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/product/35/form_key/3LeOcysisvo73Bfv/')"
												magiccartEvent="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/product/35/form_key/3LeOcysisvo73Bfv/')">
												<span><span>Add to Cart</span></span>
											</button>
											<ul class="add-to-links pull-left">
												<li class="pull-left"><a
													href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/35/form_key/3LeOcysisvo73Bfv/"
													class="link-wishlist">Add to Wishlist</a></li>
												<li class="pull-right"><a
													href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/35/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/form_key/3LeOcysisvo73Bfv/"
													class="link-compare">Add to Compare</a></li>
											</ul>
										</div>
									</div>
								</div>
								<div class="products-textlink clearfix">
									<h2 class="product-name">
										<a href="/demo/suede-loafer-navy.html" title="Merino V-neck">Merino
											V-neck</a>
									</h2>
									<div class="ratings">
										<div class="rating-box">
											<div class="rating" style="width: 60%"></div>
										</div>
										<span class="amount"><a href="#"
											onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/35/category/91/'; return false;">1
												Review(s)</a></span>
									</div>



									<div class="price-box">

										<p class="old-price">
											<span class="price-label">Regular Price:</span> <span
												class="price" id="old-price-35"> $567.00 </span>
										</p>

										<p class="special-price">
											<span class="price-label">Special Price</span> <span
												class="price" id="product-price-35"> $467.00 </span>
										</p>


									</div>

								</div>
							</li>
							<li
								class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-mobile-12 item">
								<div class="images-container">
									<div class="product-hover">
										<a
											href="/demo/smije/magicshop/quickview/view/path/suede-loafer-navy.html"
											title="Tori Tank" class="product-image"> <img
											class="img-responsive hover-img"
											src="http://alothemes.com/demo/smije/media/catalog/product/cache/5/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/6/_/6_5.jpg"
											width="770" height="988" alt="Tori Tank"> <span
											class="product-img-back"> <img class="img-responsive"
												src="http://alothemes.com/demo/smije/media/catalog/product/cache/5/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/6/-/6-6_1.jpg"
												width="770" height="988" alt="Tori Tank">
										</span>
										</a>
									</div>
									<div class="actions-no">
										<div class="actions">
											<button type="button" title="Add to Cart"
												class="button btn-cart pull-left"
												onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/product/34/form_key/3LeOcysisvo73Bfv/')"
												magiccartEvent="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/product/34/form_key/3LeOcysisvo73Bfv/')">
												<span><span>Add to Cart</span></span>
											</button>
											<ul class="add-to-links pull-left">
												<li class="pull-left"><a
													href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/34/form_key/3LeOcysisvo73Bfv/"
													class="link-wishlist">Add to Wishlist</a></li>
												<li class="pull-right"><a
													href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/34/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/form_key/3LeOcysisvo73Bfv/"
													class="link-compare">Add to Compare</a></li>
											</ul>
										</div>
									</div>
								</div>
								<div class="products-textlink clearfix">
									<h2 class="product-name">
										<a href="/demo/suede-loafer-navy.html" title="Tori Tank">Tori
											Tank</a>
									</h2>
									<div class="ratings">
										<div class="rating-box">
											<div class="rating" style="width: 60%"></div>
										</div>
										<span class="amount"><a href="#"
											onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/34/category/91/'; return false;">1
												Review(s)</a></span>
									</div>



									<div class="price-box">
										<span class="regular-price" id="product-price-34"> <span
											class="price">$234.00</span>
										</span>

									</div>

								</div>
							</li>
							<li
								class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-mobile-12 item">
								<div class="images-container">
									<div class="product-hover">
										<span class="sticker top-right"><span class="labelsale">-23%</span></span>
										<a
											href="/demo/smije/magicshop/quickview/view/path/suede-loafer-navy.html"
											title="Chelsea Tee" class="product-image"> <img
											class="img-responsive hover-img"
											src="http://alothemes.com/demo/smije/media/catalog/product/cache/5/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/5/_/5_5.jpg"
											width="770" height="988" alt="Chelsea Tee"> <span
											class="product-img-back"> <img class="img-responsive"
												src="http://alothemes.com/demo/smije/media/catalog/product/cache/5/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/5/-/5-5.jpg"
												width="770" height="988" alt="Chelsea Tee">
										</span>
										</a>
									</div>
									<div class="actions-no">
										<div class="actions">
											<button type="button" title="Add to Cart"
												class="button btn-cart pull-left"
												onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/product/33/form_key/3LeOcysisvo73Bfv/')"
												magiccartEvent="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/product/33/form_key/3LeOcysisvo73Bfv/')">
												<span><span>Add to Cart</span></span>
											</button>
											<ul class="add-to-links pull-left">
												<li class="pull-left"><a
													href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/33/form_key/3LeOcysisvo73Bfv/"
													class="link-wishlist">Add to Wishlist</a></li>
												<li class="pull-right"><a
													href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/33/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/form_key/3LeOcysisvo73Bfv/"
													class="link-compare">Add to Compare</a></li>
											</ul>
										</div>
									</div>
								</div>
								<div class="products-textlink clearfix">
									<h2 class="product-name">
										<a href="/demo/suede-loafer-navy.html" title="Chelsea Tee">Chelsea
											Tee</a>
									</h2>
									<div class="ratings">
										<div class="rating-box">
											<div class="rating" style="width: 80%"></div>
										</div>
										<span class="amount"><a href="#"
											onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/33/category/91/'; return false;">1
												Review(s)</a></span>
									</div>



									<div class="price-box">

										<p class="old-price">
											<span class="price-label">Regular Price:</span> <span
												class="price" id="old-price-33"> $346.00 </span>
										</p>

										<p class="special-price">
											<span class="price-label">Special Price</span> <span
												class="price" id="product-price-33"> $267.00 </span>
										</p>


									</div>

								</div>
							</li>
							<li
								class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-mobile-12 item last">
								<div class="images-container">
									<div class="product-hover">
										<a
											href="/demo/smije/magicshop/quickview/view/path/suede-loafer-navy.html"
											title="Isla Crossbody Handbag" class="product-image"> <img
											class="img-responsive hover-img"
											src="http://alothemes.com/demo/smije/media/catalog/product/cache/5/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/1/4/14_2.jpg"
											width="770" height="988" alt="Isla Crossbody Handbag"> <span
											class="product-img-back"> <img class="img-responsive"
												src="http://alothemes.com/demo/smije/media/catalog/product/cache/5/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/1/6/16_2.jpg"
												width="770" height="988" alt="Isla Crossbody Handbag">
										</span>
										</a>
									</div>
									<div class="actions-no">
										<div class="actions">
											<button type="button" title="Add to Cart"
												class="button btn-cart pull-left"
												onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/product/32/form_key/3LeOcysisvo73Bfv/')"
												magiccartEvent="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/product/32/form_key/3LeOcysisvo73Bfv/')">
												<span><span>Add to Cart</span></span>
											</button>
											<ul class="add-to-links pull-left">
												<li class="pull-left"><a
													href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/32/form_key/3LeOcysisvo73Bfv/"
													class="link-wishlist">Add to Wishlist</a></li>
												<li class="pull-right"><a
													href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/32/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvb3V0ZXJ3ZWFyLmh0bWw_bW9kZT1ncmlk/form_key/3LeOcysisvo73Bfv/"
													class="link-compare">Add to Compare</a></li>
											</ul>
										</div>
									</div>
								</div>
								<div class="products-textlink clearfix">
									<h2 class="product-name">
										<a
											href="/demo/smije/magicshop/quickview/view/path/suede-loafer-navy.html"
											title="Isla Crossbody Handbag">Isla Crossbody Handbag</a>
									</h2>
									<div class="ratings">
										<div class="rating-box">
											<div class="rating" style="width: 60%"></div>
										</div>
										<span class="amount"><a href="#"
											onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/32/category/91/'; return false;">1
												Review(s)</a></span>
									</div>



									<div class="price-box">
										<span class="regular-price" id="product-price-32"> <span
											class="price">$234.00</span>
										</span>

									</div>

								</div>
							</li>
						</ul>
						<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>

						<div class="toolbar-bottom">
							<div class="toolbar">
								<div class="sorter">
									<p class="view-mode">
										<label>View as:</label> <strong title="Grid" class="grid">Grid</strong>&nbsp;
										<a href="outerwearlist.html" title="List" class="list">List</a>&nbsp;
									</p>

									<div class="sort-by">
										<label>Sort By</label> <select
											onchange="setLocation(this.value)">
											<option
												value="http://alothemes.com/demo/smije/index.php/outerwear.html?dir=asc&amp;mode=grid&amp;order=position"
												selected="selected">Position</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/outerwear.html?dir=asc&amp;mode=grid&amp;order=name">
												Name</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/outerwear.html?dir=asc&amp;mode=grid&amp;order=price">
												Price</option>
										</select> <a
											href="http://alothemes.com/demo/smije/index.php/outerwear.html?dir=desc&amp;mode=grid&amp;order=position"
											title="Set Descending Direction"><img
											src="http://alothemes.com/demo/smije/skin/frontend/alosmije/smije_fashion/images/i_asc_arrow.gif"
											alt="Set Descending Direction" class="v-middle"></a>
									</div>
									<div class="limiter">
										<label>Show</label> <select onchange="setLocation(this.value)">
											<option
												value="http://alothemes.com/demo/smije/index.php/outerwear.html?limit=8&amp;mode=grid"
												selected="selected">8</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/outerwear.html?limit=12&amp;mode=grid">
												12</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/outerwear.html?limit=32&amp;mode=grid">
												32</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/outerwear.html?limit=40&amp;mode=grid">
												40</option>
										</select>
									</div>
								</div>
								<div class="pager">
									<p class="amount">Items 1 to 8 of 14 total</p>




									<div class="pages">
										<strong>Page:</strong>
										<ol>



											<li class="current">1</li>
											<li><a
												href="http://alothemes.com/demo/smije/index.php/outerwear.html?mode=grid&amp;p=2">2</a></li>




											<li><a class="next i-next"
												href="http://alothemes.com/demo/smije/index.php/outerwear.html?mode=grid&amp;p=2"
												title="Next"> <!--<img src="" alt="" class="v-middle" />-->
													<i class="fa fa-angle-right">&nbsp;</i>
											</a></li>
										</ol>

									</div>



								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- Outwear -->
			</div>
		</div>
	</div>
</div>