<div class="block block-tags">
	<div class="block-title">
		<strong><span>Popular Tags</span></strong>
	</div>
	<div class="block-content">
		<ul class="tags-list">
			<li><a
				href="http://alothemes.com/demo/smije/index.php/tag/product/list/tagId/9/"
				style="font-size: 100%;">Magento</a></li>
			<li><a
				href="http://alothemes.com/demo/smije/index.php/tag/product/list/tagId/12/"
				style="font-size: 100%;">Men</a></li>
			<li><a
				href="http://alothemes.com/demo/smije/index.php/tag/product/list/tagId/11/"
				style="font-size: 100%;">Shirts</a></li>
			<li><a
				href="http://alothemes.com/demo/smije/index.php/tag/product/list/tagId/15/"
				style="font-size: 100%;">Shoes</a></li>
			<li><a
				href="http://alothemes.com/demo/smije/index.php/tag/product/list/tagId/13/"
				style="font-size: 100%;">Smije</a></li>
			<li><a
				href="http://alothemes.com/demo/smije/index.php/tag/product/list/tagId/14/"
				style="font-size: 100%;">Women</a></li>
		</ul>
		<div class="actions">
			<a href="http://alothemes.com/demo/smije/index.php/tag/list/">View
				All Tags</a>
		</div>
	</div>
</div>
