<div class="main-container col2-left-layout">
	<div class="container">
		<div class="main">
			<div class="breadcrumbs">
				<ul>
                    <li class="home">
                            <a href="<?php echo WEBPATH;?>" title="Home">Home</a>
                        
                        </li>
                    <li class="testimonials">
                            <strong>Testimonials</strong>
                                    </li>
                 </ul>
			</div>


			<div class="row show-grid">
				<div
					class="col-left sidebar col-lg-3 col-md-3 col-sm-3 col-pull-3 hidden-xs">

					<div id="leftcatalogue"></div>
					<!-- leftcatalogue -->


					<div id="blockcompare"></div>
					<!-- blockcompare -->
					<div id="populartags"></div>
					<!-- populartags -->

					<div id="containernone"></div>
					<!-- container-none -->

					<p></p>
				</div>

				<!--thay trang chi tiet vao--->
				<div
					class="col-main col-lg-9 col-md-9 col-sm-9 col-push-9 col-xs-12">

					<div class="customer-testimonials products-list">
						<div class="page-title">
							<h1>Testimonial</h1>
							<div class="submit-testimonial">
								<button class="button"
									onclick="setLocation('<?php echo WEBPATH;?>/creattestimonial')">
									<span> <span> Write Your Testimonial </span>
									</span>
								</button>
							</div>
						</div>

						<div class="pager">

							<p class="amount">
								<strong>2 Item(s)</strong>
							</p>

							<div class="limiter">
								<label>Show</label> <select onchange="setLocation(this.value)">
									<option
										value="<?php echo WEBPATH; ?>/testimonial/9"
										selected="selected">9</option>
									<option
										value="<?php echo WEBPATH; ?>/testimonial/15">
										15</option>
									<option
										value="<?php echo WEBPATH; ?>/testimonial/30">
										30</option>
									<option
										value="<?php echo WEBPATH; ?>/testimonial/45">
										45</option>
									<option
										value="<?php echo WEBPATH; ?>/testimonial/50">
										50</option>
								</select> per page
							</div>


						</div>

						<ul>
							<li class="item customer-testimonials-content first last"
								name="David" id="David">
								<div class="col-mobile-12 col-xs-5 col-lg-3 col-md-3 col-sm-3">
									<div class="customer">
										<img class="avatar"
											src="<?php echo BAG_REAL_HTML; ?>/smije/media/magiccart/testimonial/cache/150x170/David.jpg"
											alt="" title="">
									</div>
								</div>
								<div class="col-mobile-12 col-xs-7 col-lg-9 col-md-9 col-sm-9">
									<h2 class="product-name">David</h2>
									<div class="ratings">
										<div class="rating-box">
											<div class="rating" style="width: 100%;"></div>

										</div>
									</div>
									<div class="testimonial_text desc">
										“Suspendisse dictum ullamcorper diam, in posuere urna
										dignissim id. Mauris pellentesque, sem id dictum porta, lacus
										orci euismod er”&nbsp;...&nbsp; <a
											href="http://alothemes.com/demo/smije/index.php/testimonial/index/view/id/1/">more</a>
									</div>
									<div class="testimonial-source">
										<span class="testimonial-author">David</span> <span
											class="testimonial-date"> November 14, 2014 </span>
									</div>
								</div>
							</li>
						</ul>
						<ul>
							<li class="item customer-testimonials-content" name="Claire"
								id="Claire">
								<div class="col-mobile-12 col-xs-5 col-lg-3 col-md-3 col-sm-3">
									<div class="customer">
										<img class="avatar"
											src="<?php echo BAG_REAL_HTML; ?>/smije/media/magiccart/testimonial/cache/150x170/claire-avatar.jpg"
											alt="" title="">
									</div>
								</div>
								<div class="col-mobile-12 col-xs-7 col-lg-9 col-md-9 col-sm-9">
									<h2 class="product-name">Claire</h2>
									<div class="ratings">
										<div class="rating-box">
											<div class="rating" style="width: 100%;"></div>

										</div>
									</div>
									<div class="testimonial_text desc">
										“ Praesent congue odio id neque vehicula; eget luctus urna
										consectetur. Phasellus augue nunc; tempus et ipsum et, iaculis
										blandit e”&nbsp;...&nbsp; <a
											href="http://alothemes.com/demo/smije/index.php/testimonial/index/view/id/2/">more</a>
									</div>
									<div class="testimonial-source">
										<span class="testimonial-author">Claire</span> <span
											class="testimonial-date"> November 14, 2014 </span>
									</div>
								</div>
							</li>
						</ul>

						<div class="pager">

							<p class="amount">
								<strong>2 Item(s)</strong>
							</p>

							<div class="limiter">
								<label>Show</label> <select onchange="setLocation(this.value)">
									<option
										value="<?php echo WEBPATH; ?>/testimonial/9"
										selected="selected">9</option>
									<option
										value="<?php echo WEBPATH; ?>/testimonial/15">
										15</option>
									<option
										value="<?php echo WEBPATH; ?>/testimonial/30">
										30</option>
									<option
										value="<?php echo WEBPATH; ?>/testimonial/45">
										45</option>
									<option
										value="<?php echo WEBPATH; ?>/testimonial/50">
										50</option>
								</select> per page
							</div>


						</div>

					</div>

				</div>
				<!--  end thay chi tiet -->
			</div>
		</div>
	</div>
</div>