<div class="main-container col2-left-layout">
	<div class="container">
		<div class="main">
			<div class="breadcrumbs">
				<ul>
					<li class="home"><a href="<?php echo WEBPATH;?>" title="Home">Home</a></li>
					<li class="magicproduct"><strong>Accessories</strong></li>
				</ul>
			</div>


			<div class="row show-grid">
				<div
					class="col-left sidebar col-lg-3 col-md-3 col-sm-3 col-pull-3 hidden-xs">

					<div id="leftcatalogue"></div>
					<!-- leftcatalogue -->

					<div id="bestsellera"></div>
					<!-- bestsellera -->

					<div id="saleproducta"></div>
					<!-- sale product -->

					<div id="blockcompare"></div>
					<!-- blockcompare -->
					<div id="populartags"></div>
					<!-- populartags -->

					<div id="containernone"></div>
					<!-- container-none -->

					<p></p>
				</div>

				<!--thay trang chi tiet vao--->
				<div class="col-main col-lg-9 col-md-9 col-sm-9 col-push-9 col-xs-12">
					<div class="page-title category-title">
						<h1>tops</h1>
					</div>






					<div class="category-products">
						<div class="toolbar">
							<div class="sorter">
								<p class="view-mode">
									<label>View as:</label> <strong title="Grid" class="grid">Grid</strong>&nbsp;
									<a href="/demo/toplist.html" title="List" class="list">List</a>&nbsp;
								</p>

								<div class="sort-by">
									<label>Sort By</label> <select
										onchange="setLocation(this.value)">
										<option
											value="http://alothemes.com/demo/smije/index.php/shirts.html?dir=asc&amp;order=position"
											selected="selected">Position</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/shirts.html?dir=asc&amp;order=name">
											Name</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/shirts.html?dir=asc&amp;order=price">
											Price</option>
									</select> <a
										href="http://alothemes.com/demo/smije/index.php/shirts.html?dir=desc&amp;order=position"
										title="Set Descending Direction"><img
										src="http://alothemes.com/demo/smije/skin/frontend/alosmije/smije_fashion/images/i_asc_arrow.gif"
										alt="Set Descending Direction" class="v-middle"></a>
								</div>
								<div class="limiter">
									<label>Show</label> <select onchange="setLocation(this.value)">
										<option
											value="http://alothemes.com/demo/smije/index.php/shirts.html?limit=8">
											8</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/shirts.html?limit=12"
											selected="selected">12</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/shirts.html?limit=32">
											32</option>
										<option
											value="http://alothemes.com/demo/smije/index.php/shirts.html?limit=40">
											40</option>
									</select>
								</div>
							</div>
							<div class="pager">
								<p class="amount">
									<strong>1 Item(s)</strong>
								</p>







							</div>
						</div>


						<ul class="row show-grid products-grid first last odd">

							<li
								class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-mobile-12 item">
								<div class="images-container">
									<div class="product-hover">
										<a
											href="/demo/smije/magicshop/quickview/view/path/suede-loafer-navy.html"
											title="Flat Front Trouser" class="product-image"> <img
											class="img-responsive hover-img"
											src="http://alothemes.com/demo/smije/media/catalog/product/cache/5/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/7/-/7-7_3.jpg"
											width="770" height="988" alt="Flat Front Trouser"> <span
											class="product-img-back"> <img class="img-responsive"
												src="http://alothemes.com/demo/smije/media/catalog/product/cache/5/small_image/770x988/9df78eab33525d08d6e5fb8d27136e95/7/_/7_1_7.jpg"
												width="770" height="988" alt="Flat Front Trouser">
										</span>
										</a>
									</div>
									<div class="actions-no">
										<div class="actions">
											<button type="button" title="Add to Cart"
												class="button btn-cart pull-left"
												onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvc2hpcnRzLmh0bWwv/product/37/form_key/3LeOcysisvo73Bfv/')"
												magiccartEvent="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvc2hpcnRzLmh0bWwv/product/37/form_key/3LeOcysisvo73Bfv/')">
												<span><span>Add to Cart</span></span>
											</button>
											<ul class="add-to-links pull-left">
												<li class="pull-left"><a
													href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/37/form_key/3LeOcysisvo73Bfv/"
													class="link-wishlist">Add to Wishlist</a></li>
												<li class="pull-right"><a
													href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/37/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvc2hpcnRzLmh0bWwv/form_key/3LeOcysisvo73Bfv/"
													class="link-compare">Add to Compare</a></li>
											</ul>
										</div>
									</div>
								</div>
								<div class="products-textlink clearfix">
									<h2 class="product-name">
										<a href="/demo/suede-loafer-navy.html"
											title="Flat Front Trouser">Flat Front Trouser</a>
									</h2>
									<div class="ratings">
										<div class="rating-box">
											<div class="rating" style="width: 80%"></div>
										</div>
										<span class="amount"><a href="#"
											onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/37/category/90/'; return false;">1
												Review(s)</a></span>
									</div>



									<div class="price-box">
										<span class="regular-price" id="product-price-37"> <span
											class="price">$345.00</span>
										</span>

									</div>

								</div>
							</li>


						</ul>


						<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>

						<div class="toolbar-bottom">
							<div class="toolbar">
								<div class="sorter">
									<p class="view-mode">
										<label>View as:</label> <strong title="Grid" class="grid">Grid</strong>&nbsp;
										<a href="/demo/toplist.html" title="List" class="list">List</a>&nbsp;
									</p>

									<div class="sort-by">
										<label>Sort By</label> <select
											onchange="setLocation(this.value)">
											<option
												value="http://alothemes.com/demo/smije/index.php/shirts.html?dir=asc&amp;order=position"
												selected="selected">Position</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/shirts.html?dir=asc&amp;order=name">
												Name</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/shirts.html?dir=asc&amp;order=price">
												Price</option>
										</select> <a
											href="http://alothemes.com/demo/smije/index.php/shirts.html?dir=desc&amp;order=position"
											title="Set Descending Direction"><img
											src="http://alothemes.com/demo/smije/skin/frontend/alosmije/smije_fashion/images/i_asc_arrow.gif"
											alt="Set Descending Direction" class="v-middle"></a>
									</div>
									<div class="limiter">
										<label>Show</label> <select onchange="setLocation(this.value)">
											<option
												value="http://alothemes.com/demo/smije/index.php/shirts.html?limit=8">
												8</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/shirts.html?limit=12"
												selected="selected">12</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/shirts.html?limit=32">
												32</option>
											<option
												value="http://alothemes.com/demo/smije/index.php/shirts.html?limit=40">
												40</option>
										</select>
									</div>
								</div>
								<div class="pager">
									<p class="amount">
										<strong>1 Item(s)</strong>
									</p>







								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- Tops -->
			</div>
		</div>
	</div>
</div>