
<style>
.row.payresult {
	min-height: 300px;
}
</style>
<section>
	<div class="wapper">
		<div class="breadcrumb ">
			<div class="container">
				<div class="row payresult">
					<center>
						<h3>Vaše objednávka informací byla úspěšně odeslána</h3>
						<h3>Zpracujeme Vaši objednávku tak rychle, jak je to možné.</h3>
						<h3>Všechny informace o Vaší objednávky jsme byli fuir na Váš
							e-mail.</h3>
					</center>
				</div>
			</div>
		</div>
	</div>
</section>