<!-- font chu icon http://fortawesome.github.io/Font-Awesome/icons/ -->
<div class="main-container col2-left-layout">
	<div class="container">
		<div class="main">

			<div class="row show-grid">
				<div
					class="col-left sidebar col-lg-3 col-md-3 col-sm-3 col-pull-3 hidden-xs">

					<!--  <div id="leftcatalogue"></div> -->
					<!-- leftcatalogue -->

					<div id="myacountaja"></div>
					<!-- myacountaja -->
					<div id="myproductaja"></div>

					<div id="mycartaja"></div>


					<div id="compareproductaja"></div>
					<!-- compareproductaja -->
					

					<p></p>
				</div>

				<!--thay trang chi tiet vao--->
				<div
					class="col-main col-lg-9 col-md-9 col-sm-9 col-push-9 col-xs-12">
					<div class="pageheader">
						<h1 class="title-admin page-title">
							<i class="glyphicon glyphicon-plus"></i>Add Album Product:
						</h1>
					</div>

					<div id="mutiupload " style="height: 100%;width: 100%;">
<div id="mulitplefileuploader">Upload</div>

<div id="status"></div>
<script>
var id= '<?php echo $id_product; ?>';
var url_domain = '<?php echo WEBPATH;?>';
jQuery(document).ready(function($) {
	//reset update img
	$.ajax({
	    type: "POST",
	    url: url_domain + "/product/index/ajaxsaveimg",
	    data: {id:id,img:0},
	    success: function(data){
	    	       console.log("data clear :"+data);
	            }
	});
	
	
var settings = {
	//domain:"<?php //echo WEBPATH;?>",	
	url: "<?php echo WEBPATH?>/product/index/dragdrop/"+id,
	method: "POST",
	allowedTypes:"jpg,png,gif", //,doc,pdf,zip
	fileName: "myfile",
	multiple: true,
	onSuccess:function(files,data,xhr)
	{
		//console.log("data :"+data);
		$("#status").html("<font color='green'>Upload is success</font>");
		
	},
    afterUploadAll:function()
    {
        //alert("all images uploaded!!");
        var x;
        if (confirm("all images uploaded!!") == true) {
             x = "You pressed OK!";
        	console.log('OK click  :' + x);
        	// tmp delete
     		var img =1; //console.log("img :"+ img);
     		$.ajax({
                 type: "POST",
                 url: url_domain + "/product/index/tmpdeimg",
                 data: {id:id,img:img},
                 success: function(da){
                 	       console.log(da);
                         }
             });

            //update data img
            var img =1;
			$.ajax({
	            type: "POST",
	            url: url_domain + "/product/index/ajaxsaveimg",
	            data: {id:id,img:img},
	            success: function(da){
	            	       console.log("update img all :"+da);
	                    }
	        });
     		
     		//setInterval(function(){ document.location.reload(true); }, 4000);
        	 
        } else {
            x = "You pressed Cancel!";
            console.log('cancel :' + x);
        }
    },
	onError: function(files,status,errMsg)
	{		
		$("#status").html("<font color='red'>Upload is Failed</font>");
	}
}
$("#mulitplefileuploader").uploadFile(settings);

});
</script>



</div><!-- mutiupload end -->
					
					<div class="buttons-set buttons-set2" style="float: right;  margin: 0px;">
							<a href="<?php echo WEBPATH?>/product/index/index">
								<button type="button" name="Manacatalogue"
									title="Share Wishlist" class="butoon button btn-share">
									<span><span>Manage Product</span></span>
								</button>
							</a> <a href="<?php echo WEBPATH?>/product/index/add">
								<button type="button" title="AddNew"
									class="butoon button btn-add">
									<span><span>Add new Product</span></span>
								</button>
							</a>

					</div>
					<div class=""> 
					<?php
					if ( (isset ( $check ) && $check == 1 && $id_product != '' ) ||  (isset ( $check ) && $check == 1 && $this->error == 1))
                    {
						echo '<div class="alert alert-success" role="alert">Product has been Add success.</div>';
					}
					?>
					<?php if(isset($check)&&$check==0){echo '<div class="alert alert-danger" role="alert">Error!!.</div>';}?>
					<?php if(!isset($check) || $check =='NULL'){?>
    <div class="col-sm-6">
     <?php
						$form = $this->Productform;
						//$form->prepare ();
						echo $this->form ()->openTag ( $form );
						?>
    <?php echo $this->formElement($form->get('id')); ?>
    <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('id'));?></span> 
    
     <?php// echo $this->formElement($form->get('rating')); ?>
    <span class="common-error-msg"><?php //echo $this->formElementErrors($form->get('rating'));?></span>     
    
    
    <?php echo $this->formlabel($form->get('name'));?>
    <?php echo $this->formElement($form->get('name')); ?>
    <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('name'));?></span>
    
    <?php echo $this->formlabel($form->get('alias'));?>
    <?php echo $this->formElement($form->get('alias')); ?>
    <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('alias'));?></span>
    
    <?php echo $this->formlabel($form->get('availability'));?>
    <?php echo $this->formElement($form->get('availability')); ?>
    <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('availability'));?></span>
    
     <?php echo $this->formlabel($form->get('descripts'));?>
    <?php echo $this->formElement($form->get('descripts')); ?>
    <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('descripts'));?></span>
    
     <?php echo $this->formlabel($form->get('detail_product'));?>
    <?php echo $this->formElement($form->get('detail_product')); ?>
    <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('detail_product'));?></span>
    
    
      <?php echo $this->formlabel($form->get('promotions'));?>
    <?php echo $this->formElement($form->get('promotions')); ?>
    <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('promotions'));?></span>
   
   <?php echo "</br>";?>
     
     <?php echo $this->formlabel($form->get('cat_id'));?>
    <?php echo $this->formElement($form->get('cat_id')); ?>
    <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('cat_id'));?></span>
    
    
    <?php /*
      <?php echo $this->formlabel($form->get('tag_id'));?>
    <?php echo $this->formElement($form->get('tag_id')); ?>
    <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('tag_id'));?></span>
    
      <?php echo $this->formlabel($form->get('manufacturer_id'));?>
    <?php echo $this->formElement($form->get('manufacturer_id')); ?>
    <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('manufacturer_id'));?></span>
    */?>

							<label for="parent">Choice Hot</label>
							<div class="form-control">
      <?php echo $this->formElement($form->get('hot')); ?>
      <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('hot'));?></span>
							</div>

							<label for="parent">New</label>
							<div class="form-control">
      <?php echo $this->formElement($form->get('new')); ?>
      <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('new'));?></span>
							</div>


							<label for="parent">Status</label>
							<div class="form-control">
      <?php echo $this->formElement($form->get('status')); ?>
      <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('status'));?></span>
							</div>

		 <?php echo $this->formlabel($form->get('about_price'));?>
    <?php echo $this->formElement($form->get('about_price')); ?>
    <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('about_price'));?></span>					


		 <?php echo $this->formlabel($form->get('weekly_featured'));?>
    <?php echo $this->formElement($form->get('weekly_featured')); ?>
    <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('weekly_featured'));?></span>	
    
    

							<p></p>
	<?php //echo $this->formElement($form->get('submit'));?>
     <?php echo $this->form()->closeTag($form);?>
     <p></p>
						</div>
     <?php }?>
</div>




					<!-- end chi tiet -->
				</div>
			</div>
		</div>
	</div>

	<script type="text/javascript">
	function get_alias(){
		var str = (document.getElementById("name").value);
		str= str.toLowerCase();
		str= str.replace(/à|á|ạ|ả|ã|â|ầ|ấ|ậ|ẩ|ẫ|ă|ằ|ắ|ặ|ẳ|ẵ/g,"a");
		str= str.replace(/è|é|ẹ|ẻ|ẽ|ê|ề|ế|ệ|ể|ễ/g,"e");
		str= str.replace(/ì|í|ị|ỉ|ĩ/g,"i");
		str= str.replace(/ò|ó|ọ|ỏ|õ|ô|ồ|ố|ộ|ổ|ỗ|ơ|ờ|ớ|ợ|ở|ỡ/g,"o");
		str= str.replace(/ù|ú|ụ|ủ|ũ|ư|ừ|ứ|ự|ử|ữ/g,"u");
		str= str.replace(/ỳ|ý|ỵ|ỷ|ỹ/g,"y");
		str= str.replace(/đ/g,"d");
		str= str.replace(/!|@|\$|%|\^|\*|\(|\)|\+|\=|\<|\>|\?|\/|,|\.|\:|\'| |\"|\&|\#|\[|\]|~/g,"-");
		str= str.replace(/-+-/g,"-"); //thay thế 2- thành 1-
		str= str.replace(/^\-+|\-+$/g,"");//cắt bỏ ký tự - ở đầu và cuối chuỗi
		document.getElementById("alias").value = str;
		return str;
	}
	</script>