<div>
	<div class="social-icons right" style="margin-top: 100px">
		<a class="socialitems" target="_blank" href="https://www.facebook.com"
			id="facebook-btn"> <span class="social-icon"> <span
				class="social-text">Follow via Facebook</span>
		</span>
		</a> <a class="socialitems" target="_blank"
			href="https://www.twitter.com" id="twitter-btn"> <span
			class="social-icon"> <span class="social-text">Follow via Twitter</span>
		</span>
		</a> <a class="socialitems" target="_blank"
			href="https://www.plus.google.com" id="googleplus-btn"> <span
			class="social-icon"> <span class="social-text">Follow via Google +</span>
		</span>
		</a> <a class="socialitems" target="_blank"
			href="https://www.youtube.com" id="youtube-btn"> <span
			class="social-icon"> <span class="social-text">Follow via Youtube</span>
		</span>
		</a> <a class="socialitems" target="_blank"
			href="https://www.pinterest.com/" id="pinterest-btn"> <span
			class="social-icon"> <span class="social-text">Follow via Pinterest</span>
		</span>
		</a> <a class="socialitems" target="_blank"
			href="mailto:support@alothemes.com" id="mail-btn"> <span
			class="social-icon"> <span class="social-text">Mail To</span>
		</span>
		</a>
	</div>

	<script type="text/javascript">
    jQuery(document).ready(function($) {
        $('.social-icons .social-icon').mouseenter(function () {
            $(this).stop();
            $(this).animate({width: '160'}, 500, 'swing', function () {
            });
        });
        $('.social-icons .social-icon').mouseleave(function () {
            $(this).stop();
            $(this).animate({width: '43'}, 500, 'swing', function () {
            });
        });        
    }); 
</script>
	<div class="page-title title-buttons">
		<h1>Compare Products</h1>
		<a href="#" onclick="window.print(); return false;" class="link-print">Print
			This Page</a>
	</div>
	<table class="data-table compare-table" id="product_comparison">
		<colgroup>
			<col width="1">
			<col width="50%">
			<col width="50%">
		</colgroup>
		<tbody>
			<tr class="product-shop-row first odd">
				<th>&nbsp;</th>
				<td><a class="product-image" href="#"
					onclick="setPLocation('http://alothemes.com/demo/smije/index.php/plaid-cotton-shirt.html', true)"
					title="Plaid Cotton Shirt"><img
						src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/125x125/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1.jpg"
						width="125" height="125" alt="Plaid Cotton Shirt"></a>
					<h2 class="product-name">
						<a href="#"
							onclick="setPLocation('http://alothemes.com/demo/smije/index.php/plaid-cotton-shirt.html', true)"
							title="Plaid Cotton Shirt">Plaid Cotton Shirt</a>
					</h2>
					<div class="ratings">
						<div class="rating-box">
							<div class="rating" style="width: 100%"></div>
						</div>
						<span class="amount"><a href="#"
							onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/25/'; return false;">1
								Review(s)</a></span>
					</div>



					<div class="price-box">
						<span class="regular-price" id="product-price-25-compare-list-top">
							<span class="price">$185.00</span>
						</span>

					</div>

					<p>
						<button type="button" title="Add to Cart" class="button btn-cart"
							onclick="setPLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/product/25/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvcm9sbGVyLXN1aXRjYXNlLmh0bWw,/form_key/jr5RelQdBeKi9ghX/', true)"
							magiccartEvent="setPLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/product/25/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvcm9sbGVyLXN1aXRjYXNlLmh0bWw,/form_key/jr5RelQdBeKi9ghX/', true)">
							<span><span>Add to Cart</span></span>
						</button>
					</p>
					<ul class="add-to-links">
						<li><a
							href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvY3VzdG9tZXIvYWNjb3VudC8_X19fU0lEPVU,/product/25/form_key/jr5RelQdBeKi9ghX/"
							class="link-wishlist">Add to Wishlist</a></li>
					</ul></td>
				<td class="last"><a class="product-image" href="#"
					onclick="setPLocation('http://alothemes.com/demo/smije/index.php/roller-suitcase.html', true)"
					title="Roller Suitcase"><img
						src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/125x125/9df78eab33525d08d6e5fb8d27136e95/1/7/17_2.jpg"
						width="125" height="125" alt="Roller Suitcase"></a>
					<h2 class="product-name">
						<a href="#"
							onclick="setPLocation('http://alothemes.com/demo/smije/index.php/roller-suitcase.html', true)"
							title="Roller Suitcase">Roller Suitcase</a>
					</h2>



					<div class="price-box">
						<span class="regular-price" id="product-price-30-compare-list-top">
							<span class="price">$456.00</span>
						</span>

					</div>

					<p>
						<button type="button" title="Add to Cart" class="button btn-cart"
							onclick="setPLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/product/30/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvcm9sbGVyLXN1aXRjYXNlLmh0bWw,/form_key/jr5RelQdBeKi9ghX/', true)"
							magiccartEvent="setPLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/product/30/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvcm9sbGVyLXN1aXRjYXNlLmh0bWw,/form_key/jr5RelQdBeKi9ghX/', true)">
							<span><span>Add to Cart</span></span>
						</button>
					</p>
					<ul class="add-to-links">
						<li><a
							href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvY3VzdG9tZXIvYWNjb3VudC8_X19fU0lEPVU,/product/30/form_key/jr5RelQdBeKi9ghX/"
							class="link-wishlist">Add to Wishlist</a></li>
					</ul></td>
			</tr>
		</tbody>
		<tbody>
			<tr class="even">
				<th><span class="nobr">Description</span></th>
				<td>
					<div class="std">
						<p>Aliquam condimentum pharetra metus sed posuere. Ut euismod nisl
							sit amet enim consectetur volutpat. Nulla vitae magna dictum,
							adipiscing mauris eu, gravida tellus. Nulla tempor, felis feugiat
							fermentum suscipit, metus justo posuere ligula, at dignissim diam
							lacus a dolor. Quisque non commodo massa, quis varius ipsum!
							Curabitur condimentum ligula sit amet eleifend adipiscing. Nulla
							non ullamcorper lorem. Duis ut sagittis arcu. Phasellus ornare,
							leo in tempor blandit, orci nulla dapibus libero, a congue elit
							nulla non lectus. Duis pellentesque, eros in ullamcorper semper,
							dui lectus facilisis dui, et ultricies odio sem ultricies dui.
							Pellentesque at ultricies est. Quisque suscipit mauris et
							ullamcorper auctor. Etiam vel justo libero?</p>
						<p>Mauris tincidunt diam faucibus lobortis ultricies. Maecenas sed
							sapien ut erat vulputate elementum. Mauris interdum iaculis
							massa, sit amet imperdiet tortor tristique id. Maecenas at nibh
							euismod, consectetur nisi vel, rutrum massa. Donec dictum lacinia
							augue quis imperdiet. Pellentesque id odio commodo, gravida nisl
							sed, pellentesque magna! Nullam dignissim sagittis erat, id
							mattis metus sodales vitae. Aliquam fermentum a dui sit amet
							dignissim! Curabitur ultrices auctor lobortis. Curabitur rhoncus
							pulvinar rhoncus. Etiam leo dolor, porta at ligula vitae, euismod
							vehicula elit. Nunc eu erat felis. Vivamus ac volutpat eros. Ut
							lobortis eget mauris eu sagittis. Cras sed rutrum dui, vitae
							ultrices tellus.</p>
						<p>Morbi vel convallis dui, a eleifend nulla! Integer risus enim,
							dapibus vel auctor nec, vestibulum sit amet sapien. Suspendisse
							eget sollicitudin nisi. Morbi at metus ac diam accumsan
							hendrerit. Etiam dapibus orci in est suscipit ullamcorper. Proin
							luctus tortor eget erat dignissim, non dapibus mi varius.
							Vestibulum hendrerit libero ac arcu interdum; id tincidunt odio
							pharetra. Mauris semper gravida velit, in rutrum velit pulvinar
							in. Vivamus consequat consequat justo; eu fermentum sapien
							hendrerit nec. Pellentesque ultrices, sem nec dignissim
							tincidunt, metus ligula ullamcorper tellus, ultrices aliquet
							metus augue quis arcu. Integer non mauris lacus. Maecenas
							consectetur sit amet purus nec lobortis? Aliquam orci leo,
							venenatis a venenatis at, feugiat ultrices ligula. Nullam ut elit
							dictum, congue quam sed, lobortis elit. Curabitur malesuada
							mauris sed nunc ornare consequat.</p>
					</div>
				</td>
				<td class="last">
					<div class="std">
						<p>Aliquam condimentum pharetra metus sed posuere. Ut euismod nisl
							sit amet enim consectetur volutpat. Nulla vitae magna dictum,
							adipiscing mauris eu, gravida tellus. Nulla tempor, felis feugiat
							fermentum suscipit, metus justo posuere ligula, at dignissim diam
							lacus a dolor. Quisque non commodo massa, quis varius ipsum!
							Curabitur condimentum ligula sit amet eleifend adipiscing. Nulla
							non ullamcorper lorem. Duis ut sagittis arcu. Phasellus ornare,
							leo in tempor blandit, orci nulla dapibus libero, a congue elit
							nulla non lectus. Duis pellentesque, eros in ullamcorper semper,
							dui lectus facilisis dui, et ultricies odio sem ultricies dui.
							Pellentesque at ultricies est. Quisque suscipit mauris et
							ullamcorper auctor. Etiam vel justo libero?</p>
						<p>Mauris tincidunt diam faucibus lobortis ultricies. Maecenas sed
							sapien ut erat vulputate elementum. Mauris interdum iaculis
							massa, sit amet imperdiet tortor tristique id. Maecenas at nibh
							euismod, consectetur nisi vel, rutrum massa. Donec dictum lacinia
							augue quis imperdiet. Pellentesque id odio commodo, gravida nisl
							sed, pellentesque magna! Nullam dignissim sagittis erat, id
							mattis metus sodales vitae. Aliquam fermentum a dui sit amet
							dignissim! Curabitur ultrices auctor lobortis. Curabitur rhoncus
							pulvinar rhoncus. Etiam leo dolor, porta at ligula vitae, euismod
							vehicula elit. Nunc eu erat felis. Vivamus ac volutpat eros. Ut
							lobortis eget mauris eu sagittis. Cras sed rutrum dui, vitae
							ultrices tellus.</p>
						<p>Morbi vel convallis dui, a eleifend nulla! Integer risus enim,
							dapibus vel auctor nec, vestibulum sit amet sapien. Suspendisse
							eget sollicitudin nisi. Morbi at metus ac diam accumsan
							hendrerit. Etiam dapibus orci in est suscipit ullamcorper. Proin
							luctus tortor eget erat dignissim, non dapibus mi varius.
							Vestibulum hendrerit libero ac arcu interdum; id tincidunt odio
							pharetra. Mauris semper gravida velit, in rutrum velit pulvinar
							in. Vivamus consequat consequat justo; eu fermentum sapien
							hendrerit nec. Pellentesque ultrices, sem nec dignissim
							tincidunt, metus ligula ullamcorper tellus, ultrices aliquet
							metus augue quis arcu. Integer non mauris lacus. Maecenas
							consectetur sit amet purus nec lobortis? Aliquam orci leo,
							venenatis a venenatis at, feugiat ultrices ligula. Nullam ut elit
							dictum, congue quam sed, lobortis elit. Curabitur malesuada
							mauris sed nunc ornare consequat.</p>
					</div>
				</td>
			</tr>
			<tr class="odd">
				<th><span class="nobr">Short Description</span></th>
				<td>
					<div class="std">
						<p>Aliquam condimentum pharetra metus sed posuere. Ut euismod nisl
							sit amet enim consectetur volutpat. Nulla vitae magna dictum,
							adipiscing mauris eu, gravida tellus. Nulla tempor, felis feugiat
							fermentum suscipit.</p>
					</div>
				</td>
				<td class="last">
					<div class="std">
						<p>Aliquam condimentum pharetra metus sed posuere. Ut euismod nisl
							sit amet enim consectetur volutpat. Nulla vitae magna dictum,
							adipiscing mauris eu, gravida tellus. Nulla tempor, felis feugiat
							fermentum suscipit.</p>
					</div>
				</td>
			</tr>
			<tr class="even">
				<th><span class="nobr">SKU</span></th>
				<td>
					<div class="std">fashion_01</div>
				</td>
				<td class="last">
					<div class="std">fashion_06</div>
				</td>
			</tr>
			<tr class="odd">
				<th><span class="nobr">Manufacturer</span></th>
				<td>
					<div class="std">Ambella Home</div>
				</td>
				<td class="last">
					<div class="std">Artistica</div>
				</td>
			</tr>
			<tr class="even">
				<th><span class="nobr">Color</span></th>
				<td>
					<div class="std">Black</div>
				</td>
				<td class="last">
					<div class="std">Blue</div>
				</td>
			</tr>
		</tbody>
		<tbody>
			<tr class="add-to-row last odd">
				<th>&nbsp;</th>
				<td>



					<div class="price-box">
						<span class="regular-price"
							id="product-price-25-compare-list-bottom"> <span class="price">$185.00</span>
						</span>

					</div>

					<p>
						<button type="button" title="Add to Cart" class="button btn-cart"
							onclick="setPLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/product/25/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvcm9sbGVyLXN1aXRjYXNlLmh0bWw,/form_key/jr5RelQdBeKi9ghX/', true)"
							magiccartEvent="setPLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/product/25/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvcm9sbGVyLXN1aXRjYXNlLmh0bWw,/form_key/jr5RelQdBeKi9ghX/', true)">
							<span><span>Add to Cart</span></span>
						</button>
					</p>
					<ul class="add-to-links">
						<li><a
							href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvY3VzdG9tZXIvYWNjb3VudC8_X19fU0lEPVU,/product/25/form_key/jr5RelQdBeKi9ghX/"
							class="link-wishlist">Add to Wishlist</a></li>
					</ul>
				</td>
				<td class="last">



					<div class="price-box">
						<span class="regular-price"
							id="product-price-30-compare-list-bottom"> <span class="price">$456.00</span>
						</span>

					</div>

					<p>
						<button type="button" title="Add to Cart" class="button btn-cart"
							onclick="setPLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/product/30/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvcm9sbGVyLXN1aXRjYXNlLmh0bWw,/form_key/jr5RelQdBeKi9ghX/', true)"
							magiccartEvent="setPLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/product/30/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvcm9sbGVyLXN1aXRjYXNlLmh0bWw,/form_key/jr5RelQdBeKi9ghX/', true)">
							<span><span>Add to Cart</span></span>
						</button>
					</p>
					<ul class="add-to-links">
						<li><a
							href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvY3VzdG9tZXIvYWNjb3VudC8_X19fU0lEPVU,/product/30/form_key/jr5RelQdBeKi9ghX/"
							class="link-wishlist">Add to Wishlist</a></li>
					</ul>
				</td>
			</tr>
		</tbody>
	</table>
	<div class="buttons-set">
		<button type="button" title="Close Window" class="button"
			onclick="window.close();">
			<span><span>Close Window</span></span>
		</button>
		<span class="please-wait" id="compare-list-please-wait"
			style="display: none;"> <img
			src="http://alothemes.com/demo/smije/skin/frontend/alosmije/smije_fashion/images/opc-ajax-loader.gif"
			alt="Please wait..." title="Please wait..." class="v-middle"> Please
			wait...
		</span>
	</div>
	<script type="text/javascript">
        decorateTable('product_comparison');

        /**
         * Send remove item request, after that reload windows
         */
        function removeItem(url)
        {
            new Ajax.Request(url, {
                parameters: {isAjax: 1, method: 'POST'},
                onLoading: function(){$('compare-list-please-wait').show();},
                onSuccess: function(transport) {
                    $('compare-list-please-wait').hide();
                    window.location.reload();
                    window.opener.location.reload();
                }
            });
        }
    </script>


</div>