<div class="main-container col2-left-layout">
	<div class="container">
		<div class="main">

			<div class="row show-grid">
				<div
					class="col-left sidebar col-lg-3 col-md-3 col-sm-3 col-pull-3 hidden-xs">

					<div id="leftcatalogue"></div>
					<!-- leftcatalogue -->

					<div id="myacountaja"></div>
					<!-- myacountaja -->

					<div id="mycartaja"></div>


					<div id="compareproductaja"></div>
					<!-- compareproductaja -->
					<div id="populartags"></div>
					<!-- populartags -->

					<div id="containernone"></div>
					<!-- container-none -->

					<p></p>
				</div>

				<!--thay trang chi tiet vao--->
				<div
					class="col-main col-lg-9 col-md-9 col-sm-9 col-push-9 col-xs-12">
					<div class="my-account">
						<div class="my-wishlist">
							<div class="page-title title-buttons">
								<h1>My Wishlist</h1>
							</div>

							<form id="wishlist-view-form" action="<?php echo WEBPATH?>/wishlist/index/update/2" method="post">
								<fieldset>
									<input name="form_key" type="hidden" value="KZc0KWm4WMwXaywX">
									<table class="data-table" id="wishlist-table">
										<thead>
											<tr class="first last">
												<th></th>
												<th>Product Details and Comment</th>
												<th>Add to Cart</th>
												<th></th>
											</tr>
										</thead>
										<tbody>
											<tr id="item_8" class="first odd">
												<td><a class="product-image"
													href="<?php echo WEBPATH?>/suede-loafer-navy.html"
													title="Suede Loafer, Navy"> <img
														src="<?php echo  BAG_REAL_HTML?>/smije/media/catalog/product/cache/4/small_image/113x113/9df78eab33525d08d6e5fb8d27136e95/1/1/11_4.jpg"
														width="113" height="113" alt="Suede Loafer, Navy">
												</a></td>
												<td><h3 class="product-name">
														<a
															href="<?php echo WEBPATH?>/suede-loafer-navy.html"
															title="Suede Loafer, Navy">Suede Loafer, Navy</a>
													</h3>
													<div class="description std">
														<div class="inner">Aliquam condimentum pharetra metus sed
															posuere. Ut euismod nisl sit amet enim consectetur
															volutpat. Nulla vitae magna dictum, adipiscing mauris eu,
															gravida tellus. Nulla tempor, felis feugiat fermentum
															suscipit.</div>
													</div> <textarea name="description[8]" rows="3" cols="5"
														onfocus="focusComment(this)" onblur="focusComment(this)"
														title="Comment">Please, enter your comments...</textarea>
												</td>
												<td><div class="cart-cell">



														<div class="price-box">
															<span class="regular-price" id="product-price-31"> <span
																class="price">$345.00</span>
															</span>

														</div>

														<div class="add-to-cart-alt">
															<input type="text"
																class="input-text qty validate-not-negative-number"
																name="qty[8]" value="1">
															<button type="button" title="Add to Cart"
																onclick="addWItemToCart(8);" class="button btn-cart"
																magiccartEvent="addWItemToCart(8);">
																<span><span>Add to Cart</span></span>
															</button>
														</div>

														<p>
															<a class="link-edit"
																href="<?php echo WEBPATH?>/wishlist/index/configure/8">Edit</a>
														</p>
													</div></td>
												<td class="last"><a
													href="<?php echo WEBPATH?>/wishlist/index/remove/8"
													onclick="return confirmRemoveWishlistItem();"
													title="Remove Item" class="btn-remove btn-remove2">Remove
														item</a></td>
											</tr>
											<tr id="item_9" class="last even">
												<td><a class="product-image"
													href="<?php echo WEBPATH?>/plaid-cotton-shirt.html"
													title="Plaid Cotton Shirt"> <img
														src="<?php echo BAG_REAL_HTML;?>/smije/media/catalog/product/cache/4/small_image/113x113/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1.jpg"
														width="113" height="113" alt="Plaid Cotton Shirt">
												</a></td>
												<td><h3 class="product-name">
														<a
															href="<?php echo WEBPATH?>/plaid-cotton-shirt.html"
															title="Plaid Cotton Shirt">Plaid Cotton Shirt</a>
													</h3>
													<div class="description std">
														<div class="inner">Aliquam condimentum pharetra metus sed
															posuere. Ut euismod nisl sit amet enim consectetur
															volutpat. Nulla vitae magna dictum, adipiscing mauris eu,
															gravida tellus. Nulla tempor, felis feugiat fermentum
															suscipit.</div>
													</div> <textarea name="description[9]" rows="3" cols="5"
														onfocus="focusComment(this)" onblur="focusComment(this)"
														title="Comment">Please, enter your comments...</textarea>
												</td>
												<td><div class="cart-cell">



														<div class="price-box">
															<span class="regular-price" id="product-price-25"> <span
																class="price">$185.00</span>
															</span>

														</div>

														<div class="add-to-cart-alt">
															<input type="text"
																class="input-text qty validate-not-negative-number"
																name="qty[9]" value="1">
															<button type="button" title="Add to Cart"
																onclick="addWItemToCart(9);" class="button btn-cart"
																magiccartEvent="addWItemToCart(9);">
																<span><span>Add to Cart</span></span>
															</button>
														</div>

														<p>
															<a class="link-edit"
																href="<?php echo WEBPATH?>/wishlist/index/configure/9">Edit</a>
														</p>
													</div></td>
												<td class="last"><a
													href="<?php echo WEBPATH?>/wishlist/index/remove/9"
													onclick="return confirmRemoveWishlistItem();"
													title="Remove Item" class="btn-remove btn-remove2">Remove
														item</a></td>
											</tr>
										</tbody>
									</table>
									<script type="text/javascript">
//<![CDATA[
    decorateTable('wishlist-table');

        
        function focusComment(obj) {
            if( obj.value == 'Please, enter your comments...' ) {
                obj.value = '';
            } else if( obj.value == '' ) {
                obj.value = 'Please, enter your comments...';
            }
        }
            
            function addWItemToCart(itemId) {
                var url = '<?php echo WEBPATH?>/wishlist/index/cart/item/%item%/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvd2lzaGxpc3QvaW5kZXgvaW5kZXgvP19fX3N0b3JlPWVuZ2xpc2hfZmFzaGlvbg,,/form_key/KZc0KWm4WMwXaywX/';
                url = url.gsub('%item%', itemId);
                var form = $('wishlist-view-form');
                if (form) {
                    var input = form['qty[' + itemId + ']'];
                    if (input) {
                        var separator = (url.indexOf('?') >= 0) ? '&' : '?';
                        url += separator + input.name + '=' + encodeURIComponent(input.value);
                    }
                }
                setLocation(url);
            }
            
        function confirmRemoveWishlistItem() {
            return confirm('Are you sure you want to remove this product from your wishlist?');
        }
        //]]>
</script>
									<script type="text/javascript">decorateTable('wishlist-table')</script>
									<div class="buttons-set buttons-set2">

										<button type="submit" name="save_and_share"
											title="Share Wishlist" class="button btn-share">
											<span><span>Share Wishlist</span></span>
										</button>

										<button type="button" title="Add All to Cart"
											onclick="addAllWItemsToCart()" class="button btn-add">
											<span><span>Add All to Cart</span></span>
										</button>

										<button type="submit" name="do" title="Update Wishlist"
											class="button btn-update">
											<span><span>Update Wishlist</span></span>
										</button>
									</div>
								</fieldset>
							</form>

							<form id="wishlist-allcart-form" 	action="<?php echo WEBPATH?>/wishlist/index/allcart" method="post">
								<input name="form_key" type="hidden" value="KZc0KWm4WMwXaywX">
								<div class="no-display">
									<input type="hidden" name="wishlist_id" id="wishlist_id"
										value="2"> <input type="hidden" name="qty" id="qty" value="">
								</div>
							</form>

							<script type="text/javascript">
        //<![CDATA[
            var wishlistForm = new Validation($('wishlist-view-form'));
            var wishlistAllCartForm = new Validation($('wishlist-allcart-form'));

            function calculateQty() {
                var itemQtys = new Array();
                $$('#wishlist-view-form .qty').each(
                    function (input, index) {
                        var idxStr = input.name;
                        var idx = idxStr.replace( /[^\d.]/g, '' );
                        itemQtys[idx] = input.value;
                    }
                );

                $$('#qty')[0].value = JSON.stringify(itemQtys);
            }

            function addAllWItemsToCart() {
                calculateQty();
                wishlistAllCartForm.form.submit();
            }
        //]]>
        </script>
						</div>
						<div class="buttons-set">
							<p class="back-link">
								<a
									href="<?php echo WEBPATH?>/account"><small>«
								</small>Back</a>
							</p>
						</div>
					</div>
				</div>
				<!-- end chi tiet -->
			</div>
		</div>
	</div>
</div>