<?php echo $this->doctype(); ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Smije Responsive AloThemes Fashion</title>
<meta name="viewport"
	content="width=device-width, initial-scale=1, maximum-scale=1" />
<meta name="description" content="Default Description" />
<meta name="keywords" content="Magento, Varien, E-commerce" />
<meta name="robots" content="INDEX,FOLLOW" />
<link rel="icon"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/favicon.ico"
	type="image/x-icon" />
<link rel="shortcut icon"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/favicon.ico"
	type="image/x-icon" />
<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo BAG_REAL_HTML; ?>/smije/js/blank.html';
    var BLANK_IMG = '<?php echo BAG_REAL_HTML; ?>/smije/js/spacer.gif';
//]]>
</script>
<![endif]-->
<link
	href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900'
	rel='stylesheet' type='text/css' />
<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700'
	rel='stylesheet' type='text/css' />
<link
	href='http://fonts.googleapis.com/css?family=Roboto:400,100italic,100,300,300italic,400italic,500,500italic,700,700italic,900,900italic'
	rel='stylesheet' type='text/css' />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/js/calendar/calendar-win2k-1.css" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/magiccart/plugin/fontawesome/css/font-awesome.min.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/magiccart/plugin/css/bootstrap/bootstrap.min.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/magiccart/plugin/css/flexisel.hack.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/css/styles.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/base/default/css/widgets.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/magiccart/blog/css/blog.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/magiccart/magicmenu/css/magicmenu.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/magiccart/magicshop/css/ajaxcart.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/magiccart/magicslider/css/iview.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/magiccart/magicslider/css/style.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/magiccart/magicsocial/css/magicsocial.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/magiccart/plugin/css/jquery.fancybox-1.3.4.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/magiccart/plugin/css/animate.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/magiccart/magicshop/css/quickview.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/css/print.css"
	media="print" />
<script type="text/javascript"
	src="<?php echo BAG_REAL_HTML; ?>/smije/media/js/3ab2ed8946de7c8e38c92d7019e570ed.js"></script>
<link href="<?php echo BAG_REAL_HTML; ?>/store_id_4.xml" title="Blog" rel="alternate"
	type="application/rss+xml" />
<!--[if lt IE 9]>
<script type="text/javascript" src="<?php echo BAG_REAL_HTML; ?>/smije/media/js/20c96fd37f0b6d1653065f79884b33b7.js"></script>
<![endif]-->
<!--[if lt IE 8]>
<link rel="stylesheet" type="text/css" href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/css/styles-ie.css" media="all" />
<![endif]-->
<!--[if lt IE 7]>
<script type="text/javascript" src="<?php echo BAG_REAL_HTML; ?>/smije/media/js/431482b026b7ce7b6c58e1c2f5f6a7a7.js"></script>
<![endif]-->
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/css/responsive.css"
	media="all" />

<script type="text/javascript">
	//<![CDATA[
	Mage.Cookies.path = '/bagseshop/smije';
	Mage.Cookies.domain = '.<?php echo BAG_NO_HTTP; ?>'; 
	//]]>
</script>

<script type="text/javascript">
	//<![CDATA[
	optionalZipCountries = [ "HK", "IE", "MO", "PA" ];
	//]]>
</script>
<link rel="stylesheet" type="text/css"
	href="http://fonts.googleapis.com/css?family=Roboto" media="all" />
<style type="text/css">
*,body,h1,h2,h3,h4,h5,h6,.h1,.h2,.h3,.h4,.h5,.h6 {
	font-size: 12px;
	font-family: Roboto;
}

body {
	color: #666666;
}

body {
	background-color: transparent;
}

a {
	color: #666666;
}

a:hover {
	color: #e5685d;
}

a:active {
	color: #e5685d;
}

button.button span {
	color: #ffffff;
}

button.button span:hover {
	color: #ffffff;
}

button.button span {
	background-color: #666666;
}

button.button span:hover {
	background-color: #e5685d;
}

.labelnew {
	color: #ffffff;
}

.labelnew {
	background-color: #e5685d;
}

.labelsale {
	color: #ffffff;
}

.labelsale {
	background-color: #f9bd68;
}
</style>
<script type="text/javascript">
	Themecfg = {
		"general" : {
			"enabled" : "1",
			"jquery" : "1",
			"tooltip" : "0",
			"themecolor" : "",
			"ajaxloading" : "http:\/\/\<?php echo BAG_REAL_HTML; ?>\/smije\/skin\/frontend\/alosmije\/smije_fashion\/images\/opc-ajax-loader.gif"
		},
		"home" : {
			"portrait" : "1",
			"landscape" : "2",
			"tablet" : "3",
			"visibleItems" : "6",
			"height_images" : "250",
			"width_images" : "200"
		},
		"list" : {
			"portrait" : "1",
			"landscape" : "2",
			"tablet" : "3",
			"visibleItems" : "6",
			"margin_columns" : "10",
			"productDelay" : "500",
			"height_images" : "250",
			"width_images" : "200",
			"action" : "cart,compare,wishlist",
			"sort_name" : "asc"
		},
		"detail" : {
			"imageWidth" : "400",
			"zoomWidth" : "290",
			"zoomHeight" : "374",
			"adjustX" : "10",
			"adjustY" : "10",
			"showTitle" : "1",
			"useWrapper" : "0",
			"thumbSlide" : "vertical",
			"relatedSlide" : "vertical",
			"relatedLimit" : "10",
			"upsellSlide" : "horizontal",
			"upsellLimit" : "10",
			"inforTabs" : "1",
			"activeTab" : "box-up-sell"
		},
		"checkout" : {
			"crosssellsSlide" : "1"
		},
		"newsletter" : {
			"enabled" : "1",
			"width" : "949",
			"height" : "818",
			"overlayColor" : "#353535",
			"background_color" : "#fffaff",
			"background_image" : "stores\/4\/fashion-popup-newleter.jpg"
		}
	}
</script>
<script type="text/javascript">
	//<![CDATA[
	if (typeof MC == 'undefined')
		MC = {};
	MC.Quickview = {
		"dialogWidth" : "1000",
		"zoomWidth" : "265",
		"zoomHeight" : "265",
		"vertical" : "1"
	};

	jQuery(document)
			.ready(
					function($) {
						jQuery(document)
								.magiccart(
										{
											"url" : "http:\/\/alothemes.com\<?php echo BAG_REAL_HTML; ?>\/smije\/index.php\/magicshop\/ajax\/index\/",
											"updateUrl" : "http:\/\/alothemes.com\<?php echo BAG_REAL_HTML; ?>\/smije\/index.php\/checkout\/cart\/updatePost\/",
											"src_image_progress" : "\<?php echo BAG_REAL_HTML; ?>\/smije\/skin\/frontend\/alosmije\/smije_fashion\/magiccart\/magicshop\/images\/loading.gif",
											"error" : " \u2191 This is a required field.",
											"isProductView" : 0
										});
					});
	//]]
</script>

<script type="text/javascript">
	//<![CDATA[
	var Translator = new Translate([]);
	//]]>
</script>
</head>
<body class=" cms-index-index cms-home-smije-fashion">
	<div class="social-icons right" style="margin-top: 100px">
		<a class="socialitems" target="_blank" href="https://www.facebook.com"
			id="facebook-btn"> <span class="social-icon"> <span
				class="social-text">Follow via Facebook</span>
		</span>
		</a> <a class="socialitems" target="_blank" href="https://www.twitter.com"
			id="twitter-btn"> <span class="social-icon"> <span
				class="social-text">Follow via Twitter</span>
		</span>
		</a> <a class="socialitems" target="_blank"
			href="https://www.plus.google.com" id="googleplus-btn"> <span
			class="social-icon"> <span class="social-text">Follow
					via Google +</span>
		</span>
		</a> <a class="socialitems" target="_blank" href="https://www.youtube.com"
			id="youtube-btn"> <span class="social-icon"> <span
				class="social-text">Follow via Youtube</span>
		</span>
		</a> <a class="socialitems" target="_blank"
			href="https://www.pinterest.com/" id="pinterest-btn"> <span
			class="social-icon"> <span class="social-text">Follow
					via Pinterest</span>
		</span>
		</a> <a class="socialitems" target="_blank"
			href="mailto:support@alothemes.com" id="mail-btn"> <span
			class="social-icon"> <span class="social-text">Mail To</span>
		</span>
		</a>
	</div>

	<script type="text/javascript">
		jQuery(document).ready(function($) {
			$('.social-icons .social-icon').mouseenter(function() {
				$(this).stop();
				$(this).animate({
					width : '160'
				}, 500, 'swing', function() {
				});
			});
			$('.social-icons .social-icon').mouseleave(function() {
				$(this).stop();
				$(this).animate({
					width : '43'
				}, 500, 'swing', function() {
				});
			});
		});
	</script>
	<div class="wrapper">
		<noscript>
			<div class="global-site-notice noscript">
				<div class="notice-inner">
					<p>
						<strong>JavaScript seems to be disabled in your browser.</strong><br />
						You must have JavaScript enabled in your browser to utilize the
						functionality of this website.
					</p>
				</div>
			</div>
		</noscript>
		<div class="page">
			<div class="header-container">
				<div class="header">
					<div class="header-top">
						<div class="container">
							<div class="main">
								<div class="row">
									<div
										class="header-block1 col-lg-8 col-md-8 col-sm-8 col-xs-12 pull-left">
										<div class="box-support">
											<ul>
												<li class="first">
													<div class="box-phone">
														<span class="pull-left"><em class="fa fa-phone">&nbsp;</em></span>
														<div class="media-body pull-left">
															<p>(+800) 123 456 7890</p>
														</div>
													</div>
												</li>
												<li class="last">
													<div class="box-email">
														<span class="pull-left"><em class="fa fa-envelope">&nbsp;</em></span>
														<div class="media-body pull-left">
															<p>
																<a href="mailto:support@alothemes.com">support@alothemes.com</a>
															</p>
														</div>
													</div>
												</li>
											</ul>
										</div>
									</div>
									<div
										class="header-top-left col-lg-4 col-md-4 col-sm-4 col-xs-12 pull-right">
										<div class="top-form-language">

											<div class="lang-switcher">
												<div class="dropdown-toggle">
													<div>
														<div class="label dropdown-icon flag"
															style="background-image: url(<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/images/flags/english_fashion.png)">&nbsp;</div>
														<div class="value">English</div>
														<div class="caret">&nbsp;</div>
													</div>
												</div>
												<ul class="dropdown-switcher">
													<li class="current"><span class="label dropdown-icon"
														style="background-image: url(<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/images/flags/english_fashion.png);">&nbsp;</span>English</li>
													<li><a
														href="http://alothemes.com/demo/smije/index.php/?___store=french_fashion&amp;___from_store=english_fashion"><span
															class="label dropdown-icon"
															style="background-image: url(<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/images/flags/french_fashion.png);">&nbsp;</span>French</a></li>
												</ul>
											</div>
										</div>
										<div class="currency_top">


											<div class="currency-switcher">
												<div class="dropdown-toggle cover">
													<div>
														<div class="label">Currency:</div>
														<div class="value">USD</div>
														<div class="caret">&nbsp;</div>
													</div>
												</div>
												<ul class="dropdown-switcher">
													<li><a
														href="http://alothemes.com/demo/smije/index.php/directory/currency/switch/currency/EUR/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvP19fX3N0b3JlPWVuZ2xpc2hfZmFzaGlvbg,,/">EUR
															- Euro</a></li>
													<li class="current">USD - US Dollar</li>
												</ul>
											</div>
										</div>

										<!--<p class="welcome-msg"> </p>-->
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="header-content">
						<div class="container">
							<div class="main">
								<div class="row">
									<div class="inner-box clearfix">
										<div
											class="header-content-left col-lg-3 col-md-3 col-sm-3 col-xs-12">
											<a href="http://alothemes.com/demo/smije/index.php/"
												title="Smije ALO Themes " class="logo"><strong>Smije
													ALO Themes </strong><img class="img-responsive"
												src="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/images/logo.png"
												alt="Smije ALO Themes " /></a>
										</div>
										<div
											class="header-content-right col-lg-9 col-md-9 col-sm-9 col-xs-12">
											<div class="header-content-top clearfix">
												<div class="header-top-right pull-right">
													<ul class="links">
														<li class="first"><a
															href="http://alothemes.com/demo/smije/index.php/wishlist/"
															title="My Wishlist">My Wishlist</a></li>
														<li><a
															href="http://alothemes.com/demo/smije/index.php/checkout/"
															title="Checkout" class="top-link-checkout">Checkout</a></li>
														<li><a
															href="http://alothemes.com/demo/smije/index.php/blog/"
															title="Blog">Blog</a></li>
														<li><a
															href="http://alothemes.com/demo/smije/index.php/testimonial/"
															title="Testimonial">Testimonial</a></li>
														<li class=" last"><a
															href="http://alothemes.com/demo/smije/index.php/customer/account/login/"
															title="Log In">Log In</a></li>
													</ul>
													<div class="miniCartWrap">
														<div class="mini-maincart">
															<div class="cartSummary">
																<span class="icon-cart">Cart:</span> <span class="zero">0
																	item -</span> <span><span class="price">$0.00</span></span>
															</div>
															<div class="mini-contentCart" style="display: none">
																<div class="block-content">
																	<p class="empty">You have no items in your shopping
																		cart.</p>
																</div>

															</div>
														</div>

													</div>
												</div>
											</div>
											<div class="header-content-block clearfix">
												<div class="header-block2">
													<div class="alo-support">
														<div class="support">
															<div
																class="box-services box-services1 col-lg-4 col-md-4 col-sm-4 col-xs-12">
																<span class="pull-left"><em class="fa fa-truck">&nbsp;</em></span>
																<div class="media-body">
																	<h3>WORLD DELIVERY</h3>
																	<small>Free delivery on all store items</small>
																</div>
															</div>
															<div
																class="box-services col-lg-4 col-md-4 col-sm-4 col-xs-12">
																<span class="pull-left"><em class="fa fa-refresh">&nbsp;</em></span>
																<div class="media-body">
																	<h3>Return &amp; Exchange</h3>
																	<small>30 Days money back</small>
																</div>
															</div>
															<div
																class="box-services col-lg-4 col-md-4 col-sm-4 col-xs-12">
																<span class="pull-left"><em class="fa fa-phone">&nbsp;</em></span>
																<div class="media-body">
																	<h3>Online Support</h3>
																	<small>(+800) 0123 456 789</small>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
										<div class="box-inner clearfix"></div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="header-bottom clearfix">
						<div class="container custom-menu">
							<div class="main">

								<div class="magicmenu">
									<ul class="nav-desktop ">
										<li class="level0 home"><a class="level-top"
											href="http://alothemes.com/demo/smije/index.php/"><span
												class="icon-home fa fa-home"></span><span class="icon-text">Home</span><span
												class="short_desc">Lorem ipsum dolor</span></a>
											<div class="level-top-mega">
												<div>
													<a
														href="http://alothemes.com/demo/smije/index.php/?___store=english_digital"><span
														class="demo-home">Digital Store</span></a>
												</div>
												<div>
													<a href="http://alothemes.com/demo/smije/index.php/"><span
														class="demo-home">Fashion Store</span></a>
												</div>
												<div>
													<a
														href="http://alothemes.com/demo/smije/index.php/?___store=default"><span
														class="demo-home">Furniture Store</span></a>
												</div>
											</div></li>
										<li class='level0 ext  first'><a class="level-top"
											href="<?php echo BAG_REAL_HTML; ?>/newproduct.html">NEW ARRIVALS <span
												class="short_desc">Commodo consequat</span>
										</a>
											<div class="level-top-mega">
												<div class="caret-down caret-down1">&nbsp;</div>
												<div class="menuextra clearfix">
													<div class="cutom-top menu-extra cutom-hot">
														<div class="banner-inner banner-inner1">
															<a href="#"> <img class="img-responsive"
																src="<?php echo BAG_REAL_HTML; ?>/smije/media/wysiwyg/alothemes/static/img-new.jpg"
																alt="NEW ARRIVALS" />
															</a>
															<div class="block-custom block-custom1">
																<h3>NEW ARRIVAL !</h3>
																<span class="before">&nbsp;</span>
																<h2>SMILE OUTLET WINTER</h2>
																<h2>COLLECTIONS</h2>
																<p>Get a new look with us !</p>
																<a class="view-more" href="#">View more</a>
															</div>
														</div>
													</div>
												</div>
											</div></li>
										<li class='level0 ext  '><a class="level-top"
											href="<?php echo BAG_REAL_HTML; ?>/Bestsellers.html ">Bestsellers <span
												class="cat_label Hot">Hot</span><span class="short_desc">Ullamco
													laboris nisi</span>
										</a></li>
										<li class='level0 ext  '><a class="level-top"
											href="<?php echo BAG_REAL_HTML; ?>/saleproduct.html">Hotsale <span
												class="short_desc">Duis aute maizi irur</span>
										</a>
											<div class="level-top-mega">
												<div class="caret-down caret-down2">&nbsp;</div>
												<div class="menuextra menuextra2 clearfix">
													<div class="cutom-top menu-extra cutom-hot">
														<div class="banner-inner banner-inner2">
															<a href="#"> <img class="img-responsive"
																src="<?php echo BAG_REAL_HTML; ?>/smije/media/wysiwyg/alothemes/static/fashion_menu_hot.jpg"
																alt="Hot Sale" />
															</a>
															<div class="block-custom block-custom1">
																<h3>HOT SALE ITEMS!</h3>
																<span class="before">&nbsp;</span>
																<h2>
																	GET 25% OFF <br />FIRST PURCHASE
																</h2>
																<p>Free Delivery world wide</p>
																<a class="view-more" href="#">View more</a>
															</div>
														</div>
													</div>
												</div>
											</div></li>
										<li class='level0 ext  '><a class="level-top"
											href="<?php echo BAG_REAL_HTML; ?>/index.html/">Extra Menu <span
												class="short_desc">Zin reprehen voluptate</span>
										</a>
											<div class="level-top-mega">
												<div class="caret-down caret-down3">&nbsp;</div>
												<div class="custom-width clearfix">
													<div class="cutom-top menu-extra custommenu">
														<div class="banner-inner banner-inner1">
															<div class="block-custom block-custom11">
																<h3>SAMPLE MENU TITLE</h3>
																<ul class="nav-desktop nav-desktop-custom">
																	<li class="level0 level0-custom first"><a
																		class="level-top" href="#">Lorem ipsum dolor</a></li>
																	<li class="level0 level0-custom"><a
																		class="level-top" href="#">Sit amet</a></li>
																	<li class="level0 level0-custom"><a
																		class="level-top" href="#">Consectetur<span
																			class="cat_label new">New</span></a></li>
																	<li class="level0 level0-custom"><a
																		class="level-top" href="#">Adipisicing elit</a></li>
																	<li class="level0 level0-custom"><a
																		class="level-top" href="#">Do eiusmod tempor</a></li>
																	<li class="level0 level0-custom"><a
																		class="level-top" href="#">Consectetur</a></li>
																	<li class="level0 level0-custom"><a
																		class="level-top" href="#">Sit amet</a></li>
																	<li class="level0 level0-custom"><a
																		class="level-top" href="#">Adipisicing elit<span
																			class="cat_label Hot">Hot</span></a></li>
																	<li class="level0 level0-custom"><a
																		class="level-top" href="#">Do eiusmod tempor</a></li>
																	<li class="level0 level0-custom"><a
																		class="level-top" href="#">Adipisicing elit</a></li>
																	<li class="level0 level0-custom"><a
																		class="level-top" href="#">Do eiusmod tempor<span
																			class="cat_label Hot">Hot</span></a></li>
																	<li class="level0 level0-custom"><a
																		class="level-top" href="#">Consectetur</a></li>
																	<li class="level0 level0-custom view-more"><a
																		class="level-top" href="#">More <em
																			class="fa fa-arrow-circle-right">&nbsp;</em>
																	</a></li>
																</ul>
															</div>
														</div>
														<div class="banner-inner banner-inner2">
															<div class="block-custom block-custom21">
																<a href="#"> <img class="img-responsive"
																	src="<?php echo BAG_REAL_HTML; ?>/smije/media/wysiwyg/alothemes/static/fashion_custom1.jpg"
																	alt="SAMPLE TITLE" />
																</a>
																<div class="text-banner-menu text-banner-menu-1">
																	<h2>CUSTOM BLOCK</h2>
																	<span class="border-bottom">&nbsp;</span>
																</div>
															</div>
														</div>
														<div class="banner-inner banner-inner3">
															<div class="block-custom block-custom31">
																<a href="#"> <img class="img-responsive"
																	src="<?php echo BAG_REAL_HTML; ?>/smije/media/wysiwyg/alothemes/static/fashion_custom2.jpg"
																	alt="SAMPLE TITLE" />
																</a>
																<div class="text-banner-menu text-banner-menu-2">
																	<h2>SAMPLE TITLE</h2>
																	<span class="border-bottom">&nbsp;</span>
																</div>
															</div>
															<div class="block-custom block-custom32">
																<a href="#"> <img class="img-responsive"
																	src="<?php echo BAG_REAL_HTML; ?>/smije/media/wysiwyg/alothemes/static/fashion_custom3.jpg"
																	alt="SAMPLE TITLE" />
																</a>
																<div class="text-banner-menu text-banner-menu-3">
																	<h2>SAMPLE TITLE</h2>
																	<span class="border-bottom">&nbsp;</span>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div></li>
										<li class='level0 ext  last'><a class="level-top"
											href="<?php echo BAG_REAL_HTML; ?>/blog.html/">Blog <span class="short_desc">ALO
													Themes</span>
										</a></li>
									</ul>
								</div>
								<div class="nav-mobile">
									<h3 class="mobi-title">Categories</h3>
									<ul>
										<li class="level-top"><a class="level-top"
											href="http://alothemes.com/demo/smije/index.php/accessories.html/"><span>Accessories
											</span></a>
											<ul>
												<li><a
													href="http://alothemes.com/demo/smije/index.php/accessories/shop-by.html/">Shop
														By <span class="cat_label New">New</span>
												</a>
													<ul>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/shop-by/new-arrivals.html/">New
																Arrivals </a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/shop-by/christmas-gifting.html/">Christmas
																Gifting </a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/shop-by/workwear.html/">Workwear
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/shop-by/brands.html/">Brands
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/shop-by/surf-skate.html/">Surf
																& Skate </a></li>
													</ul></li>
												<li><a
													href="http://alothemes.com/demo/smije/index.php/accessories/clothing.html/">Clothing
												</a>
													<ul>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/clothing/dresses.html/">Dresses
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/clothing/tops.html/">Tops
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/clothing/skirts.html/">Skirts
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/clothing/swimwear.html/">Swimwear
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/clothing/shorts.html/">Shorts
														</a></li>
													</ul></li>
												<li><a
													href="http://alothemes.com/demo/smije/index.php/accessories/shoes.html/">Shoes
														<span class="cat_label Hot !">Hot !</span>
												</a>
													<ul>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/shoes/heels.html/">Heels
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/shoes/sandals.html/">Sandals
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/shoes/flats.html/">Flats
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/shoes/ankle-boots.html/">Ankle
																Boots </a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/shoes/sneakers.html/">Sneakers
														</a></li>
													</ul></li>
												<li><a
													href="http://alothemes.com/demo/smije/index.php/accessories/beauty.html/">Beauty
												</a>
													<ul>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/beauty/perfume.html/">Perfume
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/beauty/make-up.html/">Make
																Up </a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/beauty/hands-feet.html/">Hands
																& Feet </a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/beauty/face.html/">Face
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/beauty/body.html/">Body
														</a></li>
													</ul></li>
												<li><a
													href="http://alothemes.com/demo/smije/index.php/accessories/sports.html/">Sports
														<span class="cat_label New">New</span>
												</a>
													<ul>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/sports/sports-bras.html/">Sports
																Bras </a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/sports/sports-tights.html/">Sports
																Tights </a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/sports/sports-shorts.html/">Sports
																Shorts </a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/sports/sports-tops.html/">Sports
																Tops </a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/sports/sports-hoodies.html/">Sports
																Hoodies </a></li>
													</ul></li>
												<li><a
													href="http://alothemes.com/demo/smije/index.php/accessories/newest-collection.html/">Newest
														Collection </a>
													<ul>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/newest-collection/christmas-shop.html/">Christmas
																shop </a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/newest-collection/movember.html/">Movember
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/newest-collection/woodlanders.html/">Woodlanders
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/newest-collection/tv-advert.html/">Tv
																Advert </a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/accessories/newest-collection/partywear.html/">Partywear
														</a></li>
													</ul></li>
											</ul></li>
										<li class="level-top"><a class="level-top"
											href="http://alothemes.com/demo/smije/index.php/shirts.html/"><span>Shirts
											</span></a></li>
										<li class="level-top"><a class="level-top"
											href="http://alothemes.com/demo/smije/index.php/tops.html/"><span>Tops
											</span></a>
											<ul>
												<li><a
													href="http://alothemes.com/demo/smije/index.php/tops/shop-by.html/">Shop
														By <span class="cat_label New">New</span>
												</a>
													<ul>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/tops/shop-by/new-arrivals.html/">New
																Arrivals </a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/tops/shop-by/christmas-gifting.html/">Christmas
																Gifting </a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/tops/shop-by/workwear.html/">Workwear
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/tops/shop-by/brands.html/">Brands
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/tops/shop-by/surf-skate.html/">Surf
																& Skate </a></li>
													</ul></li>
												<li><a
													href="http://alothemes.com/demo/smije/index.php/tops/clothing.html/">Clothing
												</a>
													<ul>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/tops/clothing/dresses.html/">Dresses
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/tops/clothing/tops.html/">Tops
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/tops/clothing/skirts.html/">Skirts
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/tops/clothing/swimwear.html/">Swimwear
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/tops/clothing/shorts.html/">Shorts
														</a></li>
													</ul></li>
												<li><a
													href="http://alothemes.com/demo/smije/index.php/tops/shoes.html/">Shoes
														<span class="cat_label Hot !">Hot !</span>
												</a>
													<ul>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/tops/shoes/heels.html/">Heels
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/tops/shoes/sandals.html/">Sandals
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/tops/shoes/flats.html/">Flats
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/tops/shoes/ankle-boots.html/">Ankle
																Boots </a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/tops/shoes/sneakers.html/">Sneakers
														</a></li>
													</ul></li>
												<li><a
													href="http://alothemes.com/demo/smije/index.php/tops/accessories.html/">Accessories
												</a>
													<ul>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/tops/accessories/bags.html/">Bags
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/tops/accessories/jewellery.html/">Jewellery
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/tops/accessories/sunglasses.html/">Sunglasses
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/tops/accessories/scarves.html/">Scarves
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/tops/accessories/watches.html/">Watches
														</a></li>
													</ul></li>
											</ul></li>
										<li class="level-top"><a class="level-top"
											href="http://alothemes.com/demo/smije/index.php/outerwear.html/"><span>Outerwear
											</span></a></li>
										<li class="level-top"><a class="level-top"
											href="http://alothemes.com/demo/smije/index.php/bottoms.html/"><span>Bottoms
											</span></a>
											<ul>
												<li><a
													href="http://alothemes.com/demo/smije/index.php/bottoms/shoes.html/">Shoes
												</a>
													<ul>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/bottoms/shoes/heels.html/">Heels
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/bottoms/shoes/sandals.html/">Sandals
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/bottoms/shoes/flats.html/">Flats
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/bottoms/shoes/ankle-boots.html/">Ankle
																Boots </a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/bottoms/shoes/sneakers.html/">Sneakers
														</a></li>
													</ul></li>
												<li><a
													href="http://alothemes.com/demo/smije/index.php/bottoms/accessories.html/">Accessories
												</a>
													<ul>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/bottoms/accessories/bags.html/">Bags
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/bottoms/accessories/jewellery.html/">Jewellery
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/bottoms/accessories/sunglasses.html/">Sunglasses
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/bottoms/accessories/scarves.html/">Scarves
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/bottoms/accessories/watches.html/">Watches
														</a></li>
													</ul></li>
												<li><a
													href="http://alothemes.com/demo/smije/index.php/bottoms/beauty.html/">Beauty
												</a>
													<ul>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/bottoms/beauty/perfume.html/">Perfume
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/bottoms/beauty/make-up.html/">Make
																Up </a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/bottoms/beauty/hands-feet.html/">Hands
																& Feet </a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/bottoms/beauty/face.html/">Face
														</a></li>
														<li class="nav "><a
															href="http://alothemes.com/demo/smije/index.php/bottoms/beauty/body.html/">Body
														</a></li>
													</ul></li>
											</ul></li>
										<li class="level-top"><a class="level-top"
											href="http://alothemes.com/demo/smije/index.php/denim.html/"><span>Denim
											</span></a></li>
										<li class="level-top"><a class="level-top"
											href="http://alothemes.com/demo/smije/index.php/luxury-shoes.html/"><span>Luxury
													Shoes </span></a></li>
										<li class="level-top"><a class="level-top"
											href="http://alothemes.com/demo/smije/index.php/handbags.html/"><span>Handbags
											</span></a></li>
										<li class="level-top"><a class="level-top"
											href="http://alothemes.com/demo/smije/index.php/gifts.html/"><span>Gifts
											</span></a></li>
									</ul>
								</div>
								<div class="quick-access">
									<form id="search_mini_form"
										action="http://alothemes.com/demo/smije/index.php/catalogsearch/result/"
										method="get">
										<div class="form-search clearfix">
											<label for="search">Search:</label>
											<button type="submit" title="Search" class="button">
												<span><span><i class="fa fa-search"></i></span></span>
											</button>
											<input id="search" type="text" name="q" value=""
												class="input-text" maxlength="128" />
											<div id="search_autocomplete" class="search-autocomplete"></div>
											<script type="text/javascript">
												//<![CDATA[
												var searchForm = new Varien.searchForm(
														'search_mini_form',
														'search',
														'Search entire store here...');
												searchForm
														.initAutocomplete(
																'http://alothemes.com/demo/smije/index.php/catalogsearch/ajax/suggest/',
																'search_autocomplete');
												//]]>
											</script>
										</div>
									</form>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
			
			
			
			
			<?php echo $this->content; ?>
			
			
						<div class="footer-container">
				<div class="alo-brands">
					<div class="container">
						<div class="main">
							<div class="row show-grid">
								<div class="col-lg-12">
									<div>
										<div id="upcjhlljmp">
											<ul class="magicbrand">
												<li><img class="brand img-responsive"
													src="<?php echo BAG_REAL_HTML; ?>/smije/media//magiccart/magicbrand/cache/242x111/brands.png"
													alt="Brands1" title="Brands1" /></li>
												<li><img class="brand img-responsive"
													src="<?php echo BAG_REAL_HTML; ?>/smije/media//magiccart/magicbrand/cache/242x111/brands1.png"
													alt="2" title="2" /></li>
												<li><img class="brand img-responsive"
													src="<?php echo BAG_REAL_HTML; ?>/smije/media//magiccart/magicbrand/cache/242x111/brands2.png"
													alt="3" title="3" /></li>
												<li><img class="brand img-responsive"
													src="<?php echo BAG_REAL_HTML; ?>/smije/media//magiccart/magicbrand/cache/242x111/brands3.png"
													alt="4" title="4" /></li>
												<li><img class="brand img-responsive"
													src="<?php echo BAG_REAL_HTML; ?>/smije/media//magiccart/magicbrand/cache/242x111/brands_1.png"
													alt="5" title="5" /></li>
												<li><img class="brand img-responsive"
													src="<?php echo BAG_REAL_HTML; ?>/smije/media//magiccart/magicbrand/cache/242x111/brands1_1.png"
													alt="6" title="6" /></li>
											</ul>
										</div>

										<script type="text/javascript">
											jQuery(document)
													.ready(
															function($) {
																(function(
																		selector) {
																	var $content = $(selector);
																	var $slider = $(
																			'.magicbrand',
																			$content);
																	$slider
																			.flexisel({
																				moveSlide : 1,
																				animationSpeed : 1000,
																				autoPlay : 1,
																				autoPlaySpeed : 4000,
																				clone : 1,
																				enableResponsiveBreakpoints : 1,
																				pauseOnHover : 1,
																				visibleItems : 4,
																				responsiveBreakpoints : {
																					portrait : {
																						changePoint : 480,
																						visibleItems : 1
																					},
																					landscape : {
																						changePoint : 640,
																						visibleItems : 2
																					},
																					tablet : {
																						changePoint : 768,
																						visibleItems : 3
																					},
																				}
																			});

																})
																		("#upcjhlljmp");
															});
										</script>

									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="block-footer-top">
					<div class="container">
						<div class="main">
							<div class="row show-grid">
								<div class="footer">
									<div class="container">
										<div class="row">
											<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
												<div class="block-static2 static-alo">
													<div class="logo-footer">
														<img class="icon-about"
															src="<?php echo BAG_REAL_HTML; ?>/smije/media/wysiwyg/alothemes/static/logo-footer-fashion.png"
															alt="Sunshine" />
														<p>Sed ut perspiciatis unde omnis iste natus
															voluptatem accusantium doloremque lauda totam rem aperiam
															sunshine love.</p>
													</div>
													<div class="social-links icon-wrapper">
														<a class="icon-twitter" href="#"><em
															class="fa fa-twitter">&nbsp;</em></a> <a class="icon-github"
															href="#"><em class="fa fa-github">&nbsp;</em></a> <a
															class="icon-rss" href="#"><em class="fa fa-rss">&nbsp;</em></a>
														<a class="icon-google-plus" href="#"><em
															class="fa fa-google-plus">&nbsp;</em></a> <a
															class="icon-facebook" href="#"><em
															class="fa fa-facebook">&nbsp;</em></a>
													</div>
												</div>
											</div>
											<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
												<div class="block-static1 static-alo">
													<div class="block-title-tabs">
														<h3 class="block-title heading">
															<span>Contact Us</span>
														</h3>
													</div>
													<div class="block1 block-content-statick">
														<ul>
															<li class="map"><span class="fa fa-map-marker">&nbsp;</span>
																<address>
																	<span>Address:</span>
																</address>
																<p>415 Water St.New York, NY 10003, USA</p></li>
															<li class="phone"><span class="fa fa-phone">&nbsp;</span>
																<span>Phone:</span>
																<p>(+800) 0123 456 789</p></li>
															<li class="email"><span class="fa  fa-envelope">&nbsp;</span><span>Email:</span>
																<p>
																	<a href="mailto:support@alothemes.com">support@alothemes.com</a>
																</p></li>
														</ul>
													</div>
												</div>
											</div>
											<div class="customer col-lg-3 col-md-3 col-sm-3 col-xs-12">
												<div class="block-static3 static-alo">
													<div class="block block-creare-twitter">
														<div class="block-title">
															<strong><span>Our Latest Tweets</span></strong>
														</div>
														<div class="block-content">
															<ul>
																<li class="clearfix">
																	<div class="alo-twitter">
																		<div class="twitter-pic pull-left">
																			<a href="https://twitter.com/alothemes"><img
																				class="img-responsive"
																				src="<?php echo BAG_REAL_HTML; ?>/img/j7c9SpAr_normal.png"
																				alt="twitter icon" /></a>
																		</div>
																		<div class="twitter-links pull-left">
																			<div class="pull-left-none">
																				<span class="tweetprofilelink"> <strong><a
																						href="https://twitter.com/alothemes">alothemes</a></strong>
																					<a href="https://twitter.com/alothemes">@alothemes</a>
																				</span>
																				<p>Orenmode - Responsive Magento Theme
																					http://t.co/b3AaqXFSks</p>
																			</div>
																			<div class="date">41 days ago</div>
																		</div>
																	</div>
																</li>
																<li class="clearfix">
																	<div class="alo-twitter">
																		<div class="twitter-pic pull-left">
																			<a href="https://twitter.com/alothemes"><img
																				class="img-responsive"
																				src="http://pbs.twimg.com/profile_images/536002680057913345/j7c9SpAr_normal.png"
																				alt="twitter icon" /></a>
																		</div>
																		<div class="twitter-links pull-left">
																			<div class="pull-left-none">
																				<span class="tweetprofilelink"> <strong><a
																						href="https://twitter.com/alothemes">alothemes</a></strong>
																					<a href="https://twitter.com/alothemes">@alothemes</a>
																				</span>
																				<p>Owlshop - Responsive Magento Theme
																					http://t.co/aZgY52qE8K</p>
																			</div>
																			<div class="date">72 days ago</div>
																		</div>
																	</div>
																</li>
															</ul>
														</div>
													</div>



												</div>
											</div>
											<div class="customer col-lg-3 col-md-3 col-sm-3 col-xs-12">
												<div class="block-static4 static-alo">
													<div class="block block-subscribe">
														<div class="block-title">
															<strong><span>Newsletter</span></strong>
														</div>
														<form
															action="http://alothemes.com/demo/smije/index.php/newsletter/subscriber/new/"
															method="post" id="newsletter-validate-detail">
															<div class="block-content">
																<div class="form-subscribe-header">
																	<label for="newsletter">Sign Up for Our
																		Newsletter:</label>
																</div>
																<div class="input-box">
																	<input type="text" name="email" id="newsletter"
																		title="Sign up for our newsletter"
																		class="input-text required-entry validate-email" />
																</div>
																<div class="actions">
																	<button type="submit" title="Subscribe" class="button">
																		<span><span>Subscribe</span></span>
																	</button>
																</div>
															</div>
														</form>
														<script type="text/javascript">
															//<![CDATA[
															var newsletterSubscriberFormDetail = new VarienForm(
																	'newsletter-validate-detail');
															//]]>
														</script>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="block-footer-bottom">
					<div class="container">
						<div class="main">
							<div class="footer">
								<div class="container-">
									<div class="row">
										<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
											<div class="block-static1 static-alo">
												<h3 class="block-title heading">OUR SERVICES</h3>
												<div class="block2 block-content-statick">
													<ul>
														<li><a href="#">Order History</a></li>
														<li><a
															href="http://alothemes.com/demo/smije/index.php/sales/guest/form/">Returns</a></li>
														<li><a href="#">Libero Sed rhoncus</a></li>
														<li><a href="#">Venenatis augue tellus</a></li>
														<li><a href="#">My vouchers</a></li>
													</ul>
												</div>
											</div>
										</div>
										<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
											<div class="block-static2 static-alo">
												<h3 class="block-title heading">MY ACCOUNT</h3>
												<div class="block2 block-content-statick">
													<ul>
														<li><a
															href="http://alothemes.com/demo/smije/index.php/about">About
																Us</a></li>
														<li><a
															href="http://alothemes.com/demo/smije/index.php/customer-service">Customer
																Service</a></li>
														<li><a
															href="http://alothemes.com/demo/smije/index.php/privacy-policy-cookie-restriction-mode">Privacy
																Policy</a></li>
														<li><a
															href="http://alothemes.com/demo/smije/index.php/catalog/seo_sitemap/category/">Site
																Map</a></li>
														<li><a
															href="http://alothemes.com/demo/smije/index.php/catalogsearch/term/popular/">Search
																Terms</a></li>
													</ul>
												</div>
											</div>
										</div>
										<div class="userful col-lg-3 col-md-3 col-sm-3 col-xs-12">
											<div class="block-static3 static-alo">
												<h3 class="block-title heading">INFORMATION</h3>
												<div class="block3 block-content-statick">
													<ul>
														<li><a href="#">Order History</a></li>
														<li><a
															href="http://alothemes.com/demo/smije/index.php/sales/guest/form/">Returns</a></li>
														<li><a href="#">Libero Sed rhoncus</a></li>
														<li><a href="#">Venenatis augue tellus</a></li>
														<li><a href="#">My vouchers</a></li>
													</ul>
												</div>
											</div>
										</div>
										<div class="customer col-lg-3 col-md-3 col-sm-3 col-xs-12">
											<div class="block-static4 static-alo">
												<h3 class="block-title heading">WHY BUY FROM US</h3>
												<div class="block-linkservice block-content-statick">
													<ul>
														<li><a href="#">Shipping &amp; Returns</a></li>
														<li><a href="#">Secure Shopping</a></li>
														<li><a href="#">International Shipping</a></li>
														<li><a href="#">Affiliates</a></li>
														<li><a href="#">Contact</a></li>
													</ul>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="block-footer-copyright">
					<div class="container">
						<div class="footer">
							<div class="main">
								<div class="row show-grid">
									<div class="container">
										<address>
											Copyright © 2014 <a class="active"
												href="http://alothemes.com/demo/smije/"
												title="Magento Themes">Magento Themes</a> by Alothemes.com.
											All rights reserved.
										</address>
										<div class="store-switcher">
											<label for="select-store">Select Store:</label> <select
												id="select-store" title="Select Store"
												onchange="location.href=this.value">
												<option
													value="http://alothemes.com/demo/smije/index.php/?___store=english_digital">Digital
													Store</option>
												<option value="" selected="selected">Fashion Store</option>
												<option
													value="http://alothemes.com/demo/smije/index.php/?___store=default">Furniture
													Store</option>
											</select>
										</div>
										<div class="paypal">
											<p>
												<img class="img-responsive"
													src="<?php echo BAG_REAL_HTML; ?>/smije/media/wysiwyg/alothemes/static/paypal.png"
													alt="" />
											</p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<a href="#" id="backtotop"><span class="fa fa-angle-up"></span><span
					class="back-to-top">Back to Top</span></a>
			</div>


		</div>
	</div>
	
		<script type="text/javascript">
		     var domain ='<?php echo WEBPATH;?>';var glob=2;
			 jQuery(document).ready(function($) {
				 e = location.pathname;
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/loadleftcataogue",
		               data: {idcode:e,page:glob},
		               success: function(data){
			               //alert(data);console.log( $('.leftcatalogue').html(data));
		                            $('#leftcatalogue').html(data);
		                             glob++;
		                       }
		         });

				 $.ajax({
		               type: "POST",
		               url: domain + "/main/saleproduct",
		               data: {idcode:e,page:glob},
		               success: function(data){
			               //alert("saleproducta "+data);console.log( $('#saleproducta').html(data));
		                            $('#saleproducta').html(data);
		                       }
		         });

		         //bestsellera
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/bestseller",
		               data: {idcode:e,page:glob},
		               success: function(data){
		            	   //alert("bestsellera " + data);console.log( $('#bestsellera').html(data));
		                            $('#bestsellera').html(data);
		                       }
		         });

		         //compareblock
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/compareblock",
		               data: {idcode:e,page:glob},
		               success: function(data){
		            	   //alert("bestsellera " + data);console.log( $('#bestsellera').html(data));
		                            $('#blockcompare').html(data);
		                       }
		         });


		         //populartags
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/populartags",
		               data: {idcode:e,page:glob},
		               success: function(data){
			                  $('#populartags').html(data);
		                       }
		         });

		         //containernone
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/containernone",
		               data: {idcode:e,page:glob},
		               success: function(data){
			                  $('#containernone').html(data);
		                       }
		         });
		         
			 });
				</script>	
				
				<script type="text/javascript">
				//container -none load left menu 
									jQuery(document).ready(function($) {
										$('#sfazzxykmm').iView({
											// pauseTime: 7000,
											// directionNav: false,
											// controlNav: true,
											// controlNavNextPrev: true,
											// controlNavTooltip: true, // Show tooltip image previewer
											// pauseOnHover: true,
											// timerBarStroke: 0, // hide timerBar
											timerOpacity : 0, // hide timerBar
											pauseOnHover : true,
											pauseTime : 7000,
											controlNav : 1,
											controlNavNextPrev : false,
											controlNavTooltip : false,
											directionNav : false,
										});
									});
								</script>
</body>
</html>
			
			
			