<div class="row">
	<div class="col s12 m12 l12">
		<div class="card-panel">
			<div class="row">
			<?php $check=$this->layout()->check;
            if(!$check){?>
				<form action="<?php echo WEBPATH;?>/forgotpasswordmaster"  method="post" class="col s12">
					<h4 class="header2">Forgot Password</h4>
					<div class="row">
						<div class="input-field col s12 m12 l12" style=" z-index: 9090; ">
							<i class="mdi-communication-email prefix active"></i> 
							<input name="email" placeholder="john@mydomain.com" id="icon_email" type="email"
								class="validate"> <label for="icon_email" class="active">Email</label>
						</div>
						<div class="input-field">
							<div class="input-field ">
								<button class="btn cyan waves-effect waves-light" type="submit"
									name="action">
									<i class="mdi-action-perm-identity"></i> Register
								</button>
							</div>
						</div>
					</div>
				</form>
				<?php }else{ $err=$this->layout()->err; $email=$this->layout()->email;?>
				<?php if($err){?> 
				<div class="alert alert-warning"><?php echo "Email ".$email." not yet register";?></div>
				<?php }else{?>
				<div class="alert alert-info"> Login to your email <?php echo $email;?> to receive password</div>
				<?php }}?>
			</div>
		</div>
	</div>
</div>