
<table class="table table-bordered">
	<tr>
		<td colspan="6"><a
			href="<?php echo $this->url('Product', array('controller' => 'index', 'action' => 'add-news')); ?>">Add</a></td>
	</tr>
	<tr>
		<td>ID</td>
		<td>Country</td>
		<td>Code</td>
		<td>Price</td>
		<td>Hot String</td>
		<td>Desktop CPM Unique</td>
		<td>Desktop CPM Raw</td>
		<td>Mobile CPM Unique</td>
		<td>Mobile CPM Raw</td>
        <td>Status</td>
        <td>Action Change Status</td>
		<td>Edit</td>
		<td>Delete</td>
	</tr>
    <?php
   
    for ($i = 0; $i < count($listNews); $i++) { ?>
        <tr>
		<td><?php echo $listNews[$i]->id; ?></td>
		<td><?php echo $listNews[$i]->namepackge; ?></td>
		<td><?php echo $listNews[$i]->code; ?></td>
		<td><?php echo $listNews[$i]->price; ?></td>
		<td><?php echo $listNews[$i]->hotstring; ?></td>
		<td><?php echo $listNews[$i]->DKCpmUni; ?></td>
		<td><?php echo $listNews[$i]->DKCpmRaw?></td>
		<td><?php echo $listNews[$i]->MBCpmUni?></td>
		<td><?php echo $listNews[$i]->MBCpmRaw?></td>
		<td>
		    <?php if($listNews[$i]->status == 1) { echo '<span class="label label-success">Active</span>'; } ?>
		    <?php if($listNews[$i]->status == 0) { echo '<span class="label label-important">Not Active</span>'; } ?>
		   
		</td>
       <td>
         <a href="<?php echo WEBPATH.$this->url('Product', array('controller' => 'index', 'action' => 'status', 'id' => $listNews[$i]->id ,'status' => '1')); ?>"> Change Active </a>
         | <a href="<?php echo WEBPATH.$this->url('Product', array('controller' => 'index', 'action' => 'status', 'id' => $listNews[$i]->id ,'status' => '0')); ?>"> Change Not Active</a>
	   
	   </td>

		<td><a
			href="<?php echo $this->url('Product', array('controller' => 'index', 'action' => 'edit-news', 'id' => $listNews[$i]->id)); ?>">Edit</a></td>
		<td><a
			href="<?php echo $this->url('Product', array('controller' => 'index', 'action' => 'delete-news', 'id' => $listNews[$i]->id)); ?>">Delete</a></td>
	</tr>
    <?php } ?>
    <tr>
		<td colspan="6">
            <?php
												echo $this->paginationControl ( $paginator, 'Sliding', 'layout/paginatorindex', array (
														'name' => 'Product',
														'controller' => 'index',
														'action' => 'list-news' 
												) );
												?>
        </td>
	</tr>
</table>