<?php
$title = 'Delete catalogue';
$this->headTitle($title);
?>
<!-- font chu icon http://fortawesome.github.io/Font-Awesome/icons/ -->
<div class="main-container col2-left-layout">
	<div class="container">
		<div class="main">

			<div class="row show-grid">
				<div
					class="col-left sidebar col-lg-3 col-md-3 col-sm-3 col-pull-3 hidden-xs">

					<!--  <div id="leftcatalogue"></div> -->
					<!-- leftcatalogue -->

					<div id="myacountaja"></div>
					<!-- myacountaja -->
					<div id="myproductaja"></div>

					<div id="mycartaja"></div>


					<div id="compareproductaja"></div>
					<!-- compareproductaja -->
					

					<p></p>
				</div>

				<!--thay trang chi tiet vao--->
				<div
					class="col-main col-lg-9 col-md-9 col-sm-9 col-push-9 col-xs-12">
					<div class="pageheader">
						 <h2 class="title-admin"><i class="glyphicon glyphicon-user"></i> Status Edit Product</h2>
					</div>
					
					<div class="buttons-set buttons-set2" style="float: right;  margin: 0px;">
							<a href="<?php echo WEBPATH?>/product/index/index">
								<button type="button" name="Manacatalogue"
									title="Share Wishlist" class="butoon button btn-share">
									<span><span>Manage Product</span></span>
								</button>
							</a> <a href="<?php echo WEBPATH?>/product/index/add">
								<button type="button" title="AddNew"
									class="butoon button btn-add">
									<span><span>Add new Product</span></span>
								</button>
							</a>

					</div>
					
					<div class="pageheader">
   
</div>
<div class="content">
<?php if(isset($check)&&$check==1){echo '<div class="alert alert-success" role="alert">Status Edit Product succcess.</div>';}?>
<?php if(isset($check)&&$check==0){echo '<div class="alert alert-danger" role="alert">Status Edit Product failed.</div>';}?>
</div>    
					<!-- end chi tiet -->
				</div>
			</div>
		</div>
	</div>