<article>
            <div class="container-fluid toi-trongsuot">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12 row-content-top">
                            <div class="col-sm-2 menudoc-conten-left">
                                <ul id="tab-menu">
                                    <li ><a class="box-khuyenmai" href="#box-khuyenmai"> <span class="botron-icon"><i class="fa fa-bullhorn"></i></span> KHUYẾN MÃI TẠI ABC</a></li>
                                    <li ><a href="#box-tivi-video"> <span class="botron-icon"><i class="fa fa-desktop"></i></span> TIVI, VIDEO, ÂM THANH</a></li>
                                    <li><a href="#box-dienthoai-tablet"> <span class="botron-icon"><i class="fa fa-laptop"></i></span>  ĐIỆN THOẠI, TABLET</a></li>
                                    <li><a href="#box-maytinh-laptop"> <span class="botron-icon-dienthoai_me"><i class="fa fa-tablet"></i></span> MÁY TÍNH & LAPTOPS</a></li>
                                    <li><a href="#box-mayanh-mayuayphim"> <span class="botron-icon"><i class="fa fa-camera"></i></span> MÁY ẢNH & MÁY UAY PHIM</a></li>
                                    <li><a href="#box-me-be"> <span class="botron-icon"><i class="fa fa-heart-o"></i></span> MẸ & BÉ</a></li>
                                    <li><a href="#box-nhacua-doisong"> <span class="botron-icon-dienthoai_me"><i class="fa fa-home"></i></span> NHÀ CỬA & ĐỜI SỐNG</a></li>
                                    <li><a href="#box-thoitrang-phukien"> <span class="botron-icon"><i class="fa fa-suitcase"></i></span> THỜI TRANG & PHỤ KIỆN</a></li>
                                    <li><a href="#box-phukien-otoxemay"> <span class="botron-icon"><i class="fa fa-soccer-ball-o"></i></span> OTO, XE MÁY & PHỤ KIỆN</a></li>
                                    <li><a href="#box-suckhoe-sacdep"> <span class="botron-icon"><i class="fa fa-smile-o"></i></span> SỨC KHỎE & SẮC ĐẸP</a></li>
								</ul>
							</div>
							
                            <div class="col-sm-8 div-tab" id="box-khuyenmai">
                                <div class="col-sm-12 nopading-width50">
                                    <div class="col-sm-3 box-tablet-50">
                                        <ul id="nav"  >
                                            <li><a href="#"> Special Promotions</a></li>
											
                                            <li><a href="#">Stuhrling Watch </a></li>
                                            <li><a href="#">Diaper - 30% Off  </a></li>
                                            <li><a href="#">Máy Lạnh, Máy Giặt, Tủ Lạnh Giá Sốc</a></li>
                                            <li><a href="#">Tân Trang Nhà Cửa - Giảm Đến 50%</a></li>
                                            <li><a href="#">Hàng Thể Thao- Giảm Đến 50%</a></li>
                                            <li><a href="#">Hàng Oto Xe Máy- Giảm Đến 50%</a></li>
                                            <li><a href="#">Trả Góp Lãi Suất 0%</a></li>
										</ul>
										
									</div>
                                    <div class="col-sm-9"></div>
								</div>
							</div>
                            <div class="col-sm-8 div-tab " id="box-tivi-video">
                                <div class="col-sm-12 nopading-width50">
                                    <div class="col-sm-3 box-tablet-50">
                                        <ul id="nav">
											
                                            <li><a href="#" class="sub" tabindex="1">Hệ Thống Âm Thanh <i class="fa fa-angle-double-down"></i></a><img src="images/up.gif" alt="" />
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Tai nghe</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Loa máy tính</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Đầu karaoke</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Máy MP3 và iPod</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Phụ kiện âm thanh</a></li>
												</ul>
											</li>
                                            <li><a href="#">Tivi Gía Đặc Biệt </a></li>
                                            <li><a href="#" class="sub" tabindex="1">TV & Đầu Đĩa <i class="fa fa-angle-double-down"></i></a><img src="images/up.gif" alt="" />
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Phụ kiện (Cáp, Remote..)</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Tivi</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Đầu đĩa DVD & Máy chiếu</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Game (Chuột, Bàn Phím..)</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Máy chơi game</a></li>
												</ul>
											</li>
											
                                            <li><a href="#">Tivi Gía Đặc Biệt </a></li>
											
										</ul>
                                        <div class="col-sm-12 box-an-980">
                                            <img src="img/li.tivi_video_amthanh/bt1.jpg" class="img-responsive" alt="#"/>
										</div>
										
                                        <div class="col-sm-12 box-an-980">
                                            <img src="img/li.tivi_video_amthanh/bt2.jpg" class="img-responsive" alt="#"/>
										</div>
										
										
										
									</div>
                                    <div class="col-sm-9"></div>
								</div>
							</div>
							
							
                            <div class="col-sm-8 div-tab " id="box-maytinh-laptop">
                                <div class="col-sm-12 nopading-width50">
                                    <div class="col-sm-3 box-tablet-50">
                                        <ul id="nav">
											
                                            <li><a href="#" class="sub" tabindex="1">Laptop</a><img src="images/up.gif" alt="" />
												
											</li>
                                            <li><a href="#">Máy Tính Để Bàn </a></li>
                                            <li><a href="#" class="sub" tabindex="1">Phụ Kiện Máy Tính <i class="fa fa-angle-double-down"></i></a><img src="images/up.gif" alt="" />
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Ổ Cứng Gắn Ngoài</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> USB</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Chuột</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Bàn Phím</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Màn Hình</a></li>
												</ul>
											</li>
											
                                            <li><a href="#">Linh Kiện Máy Tính </a></li>
                                            <li><a href="#">Thiết Bị Mạng </a></li>
                                            <li><a href="#">Máy In & Mực In </a></li>
                                            <li><a href="#" class="sub" tabindex="1">Thương Hiệu Nổi Tiếng <i class="fa fa-angle-double-down"></i></a>
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Laptop Asus</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Laptop Acer</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Laptop Dell</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Laptop HP</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Laptop Lenovo</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Laptop Macbook</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Laptop Sony</a></li>
													
												</ul>
											</li>
											
										</ul>
                                        <div class="col-sm-12 box-an-980">
                                            <img src="img/li.vitinh_laptop/1.jpg" class="img-responsive" alt="#"/>
										</div>
										
										
										
										
										
									</div>
                                    <div class="col-sm-9"></div>
								</div>
							</div>
                            <div class="col-sm-8 div-tab " id="box-mayanh-mayuayphim">
                                <div class="col-sm-12 nopading-width50">
                                    <div class="col-sm-3 box-tablet-50">
                                        <ul id="nav">
											
                                            <li><a href="#" class="sub" tabindex="1">Máy Ảnh Du Lịch </a><img src="images/up.gif" alt="" />
												
											</li>
                                            <li><a href="#">Máy Ảnh Cao Cấp </a></li>
                                            <li><a href="#">Máy Ảnh Chụp Lấy Ngay</a></li>
											
											
                                            <li><a href="#">Máy Ảnh Không Ngương Lật </a></li>
                                            <li><a href="#">Máy Ảnh DSL/SLR </a></li>
                                            <li><a href="#">Các Loại Máy Ảnh Khác </a></li>
                                            <li><a href="#">Máy Quay Phim </a></li>
                                            <li><a href="#" class="sub" tabindex="1">Phụ Kiện <i class="fa fa-angle-double-down"></i></a>
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Chân máy ảnh (Tripod)</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Đèn flash</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Ống kính</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Kính lọc</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Pin Máy Ảnh</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Túi đựng máy ảnh</a></li>
													
													
												</ul>
											</li>
											
										</ul>
                                        <div class="col-sm-12 box-an-980">
                                            <img src="img/li.mayanh_mayuayphim/bt1.jpg" class="img-responsive" alt="#"/>
										</div>
										
										
										
										
										
									</div>
                                    <div class="col-sm-9"></div>
								</div>
							</div>
							
                            <div class="col-sm-8 div-tab " id="box-me-be">
                                <div class="col-sm-12 nopading-width50">
                                    <div class="col-sm-3 box-tablet-50">
                                        <ul id="nav">
											
											
                                            <li><a href="#">Xả Hàng Cuối Năm </a></li>
                                            <li><a href="#">Khuyến Mãi Giá Tốt HOT</a></li>
											
											
                                            <li><a href="#">Sản Phẩm Bán Chạy </a></li>
											
											
                                            <li><a href="#" class="sub" tabindex="1">Lần Đầu Làm Mẹ <i class="fa fa-angle-double-down"></i> </a>
                                                <ul>
                                                    <li><a href="#"> Chăm sóc bà mẹ mang thai</a></li>
												</ul>
											</li>
                                            <li><a href="#" class="sub" tabindex="1">Trẻ Sơ Sinh <i class="fa fa-angle-double-down"></i></a>
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Tã và dụng cụ vệ sinh</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Đồ dùng bú sữa & ăn dặm</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Sữa & thức ăn dặm</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Xe đẩy, địu, ghế ăn</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Đồ dùng phòng ngủ</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Tắm & chăm sóc trẻ sơ sinh</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Quần áo trẻ sơ sinh</a></li>
													
												</ul>
											</li>
                                            <li><a href="#" class="sub" tabindex="1">Đồ Chơi <i class="fa fa-angle-double-down"></i></a>
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Đồ chơi lắp ráp & xây dựng</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Đồ chơi giáo dục</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Đồ chơi gỗ</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Thủ công & Nghệ thuật</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Xe mô hình và điều khiển</a></li>
													
													
												</ul>
											</li>
                                            <li><a href="#" class="sub" tabindex="1">Thương Hiệu Hàng Đầu <i class="fa fa-angle-double-down"></i></a>
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Huggies</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Bobby</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Lego</a></li>
													
													
													
												</ul>
											</li>
											
										</ul>
                                        <div class="col-sm-12 box-an-980">
                                            <img src="img/li.me_be/200x355.jpg" class="img-responsive" alt="#"/>
										</div>
										
										
										
										
										
									</div>
                                    <div class="col-sm-9"></div>
								</div>
							</div>
							
                            <div class="col-sm-8 div-tab " id="box-nhacua-doisong">
                                <div class="col-sm-12 nopading-width50">
                                    <div class="col-sm-3 box-tablet-50">
                                        <ul id="nav">
											
											
                                            <li><a href="#">Tham Quan Mua Sắm </a></li>
                                            <li><a href="#">Khuyến Mãi Đặc Biệt </a></li>
											
											
											
											
                                            <li><a href="#" class="sub" tabindex="1">Bếp & Phòng Ăn <i class="fa fa-angle-double-down"></i></a>
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Đồ dùng nấu bếp</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Đồ dùng bàn ăn</a></li>
													
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Phụ kiện & dụng cụ nhà bếp</a></li>
													
													
													
												</ul>
											</li>
                                            <li><a href="#" class="sub" tabindex="1">Tân Trang Nhà Cửa <i class="fa fa-angle-double-down"></i> </a>
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Dụng cụ & thiết bị</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Dụng cụ cầm tay</a></li>
													
													
												</ul>
											</li>
                                            <li><a href="#">Chăn Ra Gối Nệm</a></li>
                                            <li><a href="#">Ngoài Trời & Sân Vườn</a></li>
                                            <li><a href="#">Trang Trí Nhà Cửa</a></li>
                                            <li><a href="#">Đồ Dùng Phòng Tắm</a></li>
                                            <li><a href="#">Tủ Đựng & Sắp Xếp Đồ</a></li>
                                            <li><a href="#">Văn Phòng Phẩm</a></li>
                                            <li><a href="#">100 Sản Phẩm Bán Chạy</a></li>
                                            <li><a href="#" class="sub" tabindex="1">Thương Hiệu Hàng Đầu  <i class="fa fa-angle-double-down"></i></a>
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Luminarc</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Edena</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Moriitalia</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Skil</a></li>
												</ul>
											</li>
											
											
										</ul>
                                        <div class="col-sm-12 box-an-980">
                                            <img src="img/li.nhacua_doisong/bt6.jpg" class="img-responsive" alt="#"/>
										</div>
										
										
									</div>
                                    <div class="col-sm-9"></div>
								</div>
							</div>
							
                            <div class="col-sm-8 div-tab " id="box-thoitrang-phukien">
                                <div class="col-sm-12 nopading-width50">
                                    <div class="col-sm-3 box-tablet-50">
                                        <ul id="nav">
											
											
                                            <li><a href="#">Xu Hướng Thời Trang</a></li>
											
											
											
											
											
                                            <li><a href="#" class="sub" tabindex="1">Thời Trang Nữ <i class="fa fa-angle-double-down"></i></a>
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Túi xách nữ</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Trang phục lót</a></li>
													
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Trang phục nữ</a></li>
													
													
													
												</ul>
											</li>
                                            <li><a href="#" class="sub" tabindex="1">Giày Nữ <i class="fa fa-angle-double-down"></i></a>
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Giày cao gót</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Giày đế bằng</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Giày đế xuồng</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Xăng đan & Dép</a></li>
													
												</ul>
											</li>
                                            <li><a href="#" class="sub" tabindex="1">Thời Trang Nam <i class="fa fa-angle-double-down"></i></a>
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Hàng mới về</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Trang phục lót</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Túi xách nam</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Xăng đan & Dép</a></li>
													
												</ul>
											</li>
											
                                            <li><a href="#" class="sub" tabindex="1">Giày Nam <i class="fa fa-angle-double-down"></i></a>
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Giày Casual</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Xăng đan & Dép</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Giày đế bằng</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Phong cách phái mạnh</a></li>
												</ul>
											</li>
											
											
										</ul>
                                        <div class="col-sm-12 box-an-980">
                                            <img src="img/li.thoitrang_phukien/200x355.jpg" class="img-responsive" alt="#"/>
										</div>
										
										
									</div>
                                    <div class="col-sm-9"></div>
								</div>
							</div> 
							
                            <div class="col-sm-8 div-tab " id="box-phukien-otoxemay">
                                <div class="col-sm-12 nopading-width50">
                                    <div class="col-sm-3 box-tablet-50">
                                        <ul id="nav">
											
                                            <li><a href="#" class="sub" tabindex="1">Khuyến Mãi HOT <i class="fa fa-angle-double-down"></i></a>
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Phụ kiện Ô tô Xe máy HOT nhất</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Xe đẹp rước nàng</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Mũ bảo hiểm</a></li>
												</ul>
											</li>
                                            <li><a href="#" class="sub" tabindex="1">Xe Máy <i class="fa fa-angle-double-down"></i></a>
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Đồ bảo hộ mô tô, xe máy</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Khóa chống trộm xe máy</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Phụ tùng xe máy</a></li>
													
													
												</ul>
											</li>
                                            <li><a href="#" class="sub" tabindex="1">Ô Tô <i class="fa fa-angle-double-down"></i></a>
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Thiết bị định vị, dẫn đường </a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Hỗ trợ khởi động & pin cầm tay</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Dụng cụ khẩn cấp cho xe</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Bơm lốp xe</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Đèn & Phụ kiện</a></li>
													
													
													
												</ul>
											</li>
                                            <li><a href="#">Camera hành trình & Thiết bị điện tử</a></li>
                                            <li><a href="#">Chăm sóc xe hơi</a></li>
                                            <li><a href="#">Đồ chơi xe hơi</a></li>
                                            <li><a href="#">Nội thất ô tô</a></li>
                                            <li><a href="#">Thế giới mùi thơm</a></li>
											
											
										</ul>
                                        <div class="col-sm-12 box-an-980">
                                            <img src="img/li.oto-xemay/bt6.jpg" class="img-responsive" alt="#"/>
										</div>
										
										
									</div>
                                    <div class="col-sm-9"></div>
								</div>
							</div>
							
                            <div class="col-sm-8 div-tab " id="box-suckhoe-sacdep">
                                <div class="col-sm-12 nopading-width50">
                                    <div class="col-sm-3 box-tablet-50">
                                        <ul id="nav">
                                            <li><a href="#" class="sub" tabindex="1">Trang Điểm <i class="fa fa-angle-double-down"></i></a>
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Chăm sóc da mặt </a></li>
												</ul>
											</li>
                                            <li><a href="#" class="sub" tabindex="1"> Chăm Sóc Mặt <i class="fa fa-angle-double-down"></i> </a>
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Chăm sóc da vùng mắt </a></li>
												</ul>
											</li>
                                            <li><a href="#" class="sub" tabindex="1">Chăm Sóc Tóc <i class="fa fa-angle-double-down"></i></a>
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Nước hoa dành cho nữ </a></li>
												</ul>
											</li>
                                            <li><a href="#" class="sub" tabindex="1">Nước Hoa <i class="fa fa-angle-double-down"></i></a>
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Nước hoa dành cho nam </a></li>
												</ul>
											</li>
                                            <li><a href="#">Bộ Quà Tặng</a></li>
                                            <li><a href="#">Tắm & Chăm Sóc Cơ Thể</a></li>
                                            <li><a href="#">Dành Cho Nam Giới</a></li>
                                            <li><a href="#">Chăm Sóc Cá Nhân & Sức Khỏe</a></li>
                                            <li><a href="#">Dụng Cụ Chăm Sóc Sức Khỏe & Sắc Đẹp</a></li>
                                            <li><a href="#">Thực Phẩm Chức Năng & Kiểm Soát Cân Nặng Mới</a></li>
                                            <li><a href="#">Sản Phẩm Hỗ Trợ Tình Dục</a></li>
                                            <li><a href="#">Thiết Bị Y Tế</a></li>
                                            <li><a href="#">Đồ Định Hình</a></li>
											
											
										</ul>
										
										
										
									</div>
                                    <div class="col-sm-9"></div>
								</div>
							</div>
							
                            <div class="col-sm-8 div-tab" id="box-dienthoai-tablet">
                                <div class="col-sm-12 nopading-width50">
                                    <div class="col-sm-3 box-tablet-50">
                                        <ul id="nav"  >
                                            <li><a href="#">
												<img src="img/big-sale1.png"  alt="#"/> 
												New Daily Deals
											</a></li>
                                            <li><a href="#">Smartphones</a></li>
                                            <li><a href="#">Điện Thoại Phổ Thông</a></li>
                                            <li><a href="#" class="sub" tabindex="1">Máy Tinh Bảng  <i class="fa fa-angle-double-down"></i></a>
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Hỗ trợ chức năng thoại</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Không hỗ trợ thoại</a></li>
													
												</ul>
											</li>
											
                                            <li><a href="#" class="sub" tabindex="1"> Phụ Kiện Điện Thoại <i class="fa fa-angle-double-down"></i></a>
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Vỏ & Bao điện thoại</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Pin & Bộ sạc</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Thẻ nhớ</a></li>
													
												</ul>
											</li>
											
                                            <li><a href="#">Phụ Kiện Máy Tính Bảng </a></li>
                                            <li><a href="#" class="sub" tabindex="1">Điện Thoại Bàn <i class="fa fa-angle-double-down"></i></a>
                                                <ul>
                                                    <li><a href="#"> <i class="fa fa-angle-double-right"></i> Sam Sung</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> Asus</a></li>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> BlackBerry</a></li>
													
												</ul>
											</li>
                                            <li><a href="#" class="sub" tabindex="1">Thương Hiệu Nổi Tiếng <i class="fa fa-angle-double-down"></i></a>
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-angle-double-right"></i> HTC</a></li>
                                                    <li><a href="#"><i class="fa-angle-double-right"></i> Apple(iPhone, iPad)</a></li>
                                                    <li><a href="#"><i class="fa-angle-double-right"></i> Nokia</a></li>
													
												</ul>
											</li>
											
										</ul>
                                        <div class="col-sm-12 box-an-980">
                                            <img src="img/li.dienthoai_tablet/VN.2015-04-(6).jpg" class="img-responsive" alt="#"/>
										</div>
										
										
									</div>
                                    <div class="col-sm-9"></div>
								</div>
							</div>
                            <div class="col-sm-2  menu-right-content">
								
							</div>
						</div>
					</div>
				</div>
			</div>
            <div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="clearfix marginBottom10px">
							<div class="heading_success">
								<span class="heading_success_content">
								Đơn hàng của quý khách đã được đặt thành công với thời gian dự kiến giao hàng từ 3 - 6 ngày làm việc (<b>tùy khu vực giao hàng</b>)   </span>
							</div>
						</div>
						<div class="payment_desc padding20px">
							<!--- Start CMS checkout_success_cashondelivery_info-->
							
							<p><b>Thanh toán khi nhận hàng</b></p> 
							<p>1. Quý khách hoàn toàn kiểm tra được tình trạng đơn hàng tại  <a href="#" target="_blank"> </a></p> 
							<p>2. Quý khách cũng có thể tham khảo một số câu hỏi thường gặp tại  <a href="#" target="_blank"> </a> </p> 
							<p>3.&ensp;Mọi thắc mắc hoặc hỗ trợ khác, quý khách vui lòng để lại lời nhắn tại  <a href="#" target="_blank"> </a> </p> 
							<p>4. Nếu quý khách có nhu cầu xuất hóa đơn, vui lòng gửi thông tin tại <a href="#" target="_blank"> </a> (gồm tên công ty, địa chỉ công ty, mã số thuế) ngay sau khi đặt hàng thành công tại website. </p>
							<p><b>Hiện tại chúng tôi chỉ xuất hóa đơn cho sản phẩm được bán và giao hàng bởi Apotraviny. Chúng tôi chưa hỗ trợ cho sản phẩm của đối tác bán hàng.</b></p>
							<p><b>Lưu ý:</b> Đơn hàng của quý khách có thể sẽ được giao thành nhiều kiện nếu có sản phẩm được bán bởi các đơn vị Thương nhân khác nhau. </p>
						</div>
						
					</div>
				</div>
				
				<div class="row">
					<div class="col-md-12">
						<div class="wapper_dathang">
							<span class="ktdhang"> * Bạn có thể kiếm tra đơn hàng qua trang <a href="#">Kiểm tra đơn hàng</a></span>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						
						<div class="button_buy">
                                                    <a href="<?php echo WEBPATH ?>/lazada/index">
							<button class="btn btn-info"> TIẾP TỤC MUA HÀNG <i class="fa fa-angle-double-right"></i></button>
                                                    </a>
                                                </div>
					</div>
				</div>
				
						
						
					</div>
					
					
				</article>