
<style>
    .cke_contents { height: 500px !important; }
  </style>
<section id="content">

    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper" class=" grey lighten-3">
        <div class="container">
            <div class="container">
                <div class="row">
                    <div class="col s12 m6 l5">
                        <h5 class="breadcrumbs-title">Mana Email</h5>
                        <ol class="breadcrumb">
                            <li><a href="<?php echo WEBPATH; ?>/materialize/">Dashboard</a></li>
                            <li><a href="<?php echo WEBPATH; ?>/customer/listemail">Email</a></li>

                        </ol>

                    </div>
                    <div class="col s12 m6 l7 btn-manage">
                        <a href="<?php echo WEBPATH; ?>/customer/listemail" class="waves-effect waves-light  btn">Manager Email</a>
                        <a href="<?php echo WEBPATH; ?>/customer/sendall" class="waves-effect waves-light  btn">Send All Email</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!--breadcrumbs end-->


    <!--start container-->
    <div class="container">
        <div class="section">        
            <div class="divider"></div>
            <!--Basic Form-->
            <div id="basic-form" class="section">
                <div class="row">
                    <div class="col s12 m12 l12">
                        <div class="card-panel">
                            <!--<h4 class="header2">Basic Form</h4>-->
                            <div class="row">

                                <form action="" method="post" name="Tags" class="form-horizontal" enctype="multipart/form-data" id="Tags">     
                                    <div class="row">                              
                                        <div class="input-field col s12">
                                            <p>Send To: <?php echo $data_email['email']?></p>
                                        </div>
                                        <div class="input-field col s12">
                                             
                                            <input type="text" name="title" required="required" class="form-control" id="alias" value=""> 
                                            <label for="alias">Title</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="file-field input-field col s12">
                                            <textarea name="content" id="ck" class="materialize-textarea form-control ckeditor" id="descripts"></textarea>
                                            <label for="descripts" class="">Content</label>
                                        </div>
                                    </div>



                                    <div class="row">
                                        <div class="input-field col s12">
                                            <button class="btn cyan waves-effect waves-light right" type="submit" name="action">Submit
                                                <i class="mdi-content-send right"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form> 
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <!-- Form with placeholder -->

        </div>
    </div>

    <!-- Form with icon prefixes -->

</div>

<!-- end section -->
</div>
<!--end container-->
</section>
