<section id="content">
     <div id="breadcrumbs-wrapper" class=" grey lighten-3">
        <div class="container">
            <div class="row">
                    <div class="col s12 m6 l6">
                        <h5 class="breadcrumbs-title">Mana Customer</h5>
                        <ol class="breadcrumb">
                            <li><a href="<?php echo WEBPATH; ?>/materialize/">Dashboard</a></li>
                        <li><a href="<?php echo WEBPATH; ?>/customer">Customer</a></li>
                        
                    </ol>

                </div>
                <div class="col s12 m6 l6 btn-manage">
                    <a href="<?php echo WEBPATH; ?>/customer" class="waves-effect waves-light  btn">Manager Customer</a>
                   
                </div>
            </div>
        </div>
    </div>
    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper" class="lighten-3">
        <div class="container">
           
               
                <div class="row">
                    <div class="col s12 m4 l3">
                    <p>Customer :</p>
                    </div>
                   <div class="col s12 m8 l9">
                    <?php                    
                    echo '<p>' . $data_detail['fullname'] . '</p>'
                     ?>    
                   </div>
                </div>
                 <div class="row">
                    <div class="col s12 m4 l3">
                    <p>Email :</p>
                    </div>
                   <div class="col s12 m8 l9">
                    <?php                    
                    echo '<p>' . $data_detail['email'] . '</p>'
                     ?>    
                   </div>
                </div>
                <div class="row">
                    <div class="col s12 m4 l3">
                    <p>Phone :</p>
                    </div>
                   <div class="col s12 m8 l9">
                    <?php                    
                    echo '<p>' . $data_detail['phone'] . '</p>'
                     ?>    
                   </div>
                </div>
                 <div class="row">
                    <div class="col s12 m4 l3">
                    <p>Adress :</p>
                    </div>
                   <div class="col s12 m8 l9">
                    <?php                    
                    echo '<p>' . $data_detail['address'] . '</p>'
                     ?>    
                   </div>
                </div>
                <div class="row">
                    <div class="col s12 m4 l3">
                    <p>Date :</p>
                    </div>
                   <div class="col s12 m8 l9">
                    <?php                    
                    echo '<p>' . date('d-m-Y', strtotime($data_detail['date'])) . '</p>'
                     ?>    
                   </div>
                </div>
                 <div class="row">
                    <div class="col s12 m4 l3">
                    <p>Skype :</p>
                    </div>
                   <div class="col s12 m8 l9">
                    <?php                    
                    echo '<p>' . $data_detail['skype'] . '</p>'
                     ?>    
                   </div>
                </div>
                <div class="row">
                    <div class="col s12 m4 l3">
                    <p>Yahoo :</p>
                    </div>
                   <div class="col s12 m8 l9">
                    <?php                    
                    echo '<p>' . $data_detail['yahoo'] . '</p>'
                     ?>    
                   </div>
                </div>
                 <div class="row">
                    <div class="col s12 m4 l3">
                    <p>Facebook :</p>
                    </div>
                   <div class="col s12 m8 l9">
                    <?php                    
                    echo '<p>' . $data_detail['facebook'] . '</p>'
                     ?>    
                   </div>                                   
                </div>
                
            </div>
        </div>
    </div>
</section> 
<style>
    .bg:nth-child(even){
        background: #e3e3e3;
    }
    .load{
        display: none;
    }
</style>
<script>
function changestatus_oder(){
    $('.load').fadeIn();
   var id_oder=$('#id_oder').val();
   var status=$('#status').val();
   var select=$('#status');
    var selectedItem = select.find(':selected');    
    var selectedText = selectedItem.text();
   var values='id_oder='+ id_oder +'&status='+status;
   var URL=" <?php echo WEBPATH ?>/invoice/order/updatestatus";
    $.ajax({
        url: URL,
        type: "post",
        data: values,
        cache: false,
        success: function (data) {
            console.log(data);
            $('#st').html(selectedText);
            $('#chang_status').html('<div class="alert alert-success" id="chang_status" role="alert">'+data+'</div>');
		$('.load').fadeOut();
    },
        error: function () {
            alert("failure");
		}
	});
}
</script>