
<div class="mage-magictabs mc-90">
                            <ul class="flexisel-content products-grid 90 zoomOut play">
                        
                <li style="-webkit-animation-delay:0ms;-moz-animation-delay:0ms;-o-animation-delay:0ms;animation-delay:0ms;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
						    <div class="product-hover">
																<a href="http://alothemes.com/demo/smije/index.php/wingtip-cognac-oxford.html" title="Wingtip Cognac Oxford" class="product-image">
									<img class="img-responsive" src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/1/3/13_4.jpg" width="290" height="372" alt="Wingtip Cognac Oxford" />
								
								   										<span class="product-img-back">
											<img class="img-responsive" src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/1/2/12_5.jpg" width="290" height="372" alt="Wingtip Cognac Oxford" />
										</span>
																	</a>
							</div>
                            <div class="actions-no">
                                                            <div class="actions">
                                                                                                                        <button type="button" title="Add to Cart" class="pull-left button btn-cart" onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNjYXRlZ29yeS9pbmRleC9hamF4Lw,,/product/38/form_key/Z9IuKHJORkq6jWdh/')"><span><span>Add to Cart</span></span></button>
                                                                                                                <ul class="add-to-links pull-left">
                                                                                                                                    <li class="pull-left"><a href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/38/form_key/Z9IuKHJORkq6jWdh/" title="Add to Wishlist" class="link-wishlist">Add to Wishlist</a></li>
                                                                                                                                                                                                                        <li class="pull-right"><span class="separator">|</span> <a href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/38/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNjYXRlZ29yeS9pbmRleC9hamF4Lw,,/form_key/Z9IuKHJORkq6jWdh/" title="Add to Compare" class="link-compare">Add to Compare</a></li>
                                                                                                                        </ul>
                                </div>
                            </div>
                        </div>
                        <div class="products-textlink clearfix">
                            <h2 class="product-name">
                                <a href="http://alothemes.com/demo/smije/index.php/wingtip-cognac-oxford.html" title="Wingtip Cognac Oxford">Wingtip Cognac Oxford</a>
                            </h2>
                                                                <div class="ratings">
                    <div class="rating-box">
                <div class="rating" style="width:40%"></div>
            </div>
                <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/38/'; return false;">1 Review(s)</a></span>
    </div>
                                                        

                        
    <div class="price-box">
                                                                <span class="regular-price" id="product-price-38">
                                            <span class="price">$267.00</span>                                    </span>
                        
        </div>

                         </div>
                        				</div>
                </li>
                                        
                <li style="-webkit-animation-delay:500ms;-moz-animation-delay:500ms;-o-animation-delay:500ms;animation-delay:500ms;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
						    <div class="product-hover">
																<a href="http://alothemes.com/demo/smije/index.php/flat-front-trouser.html" title="Flat Front Trouser" class="product-image">
									<img class="img-responsive" src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/7/-/7-7_3.jpg" width="290" height="372" alt="Flat Front Trouser" />
								
								   										<span class="product-img-back">
											<img class="img-responsive" src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/7/_/7_1_7.jpg" width="290" height="372" alt="Flat Front Trouser" />
										</span>
																	</a>
							</div>
                            <div class="actions-no">
                                                            <div class="actions">
                                                                                                                        <button type="button" title="Add to Cart" class="pull-left button btn-cart" onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNjYXRlZ29yeS9pbmRleC9hamF4Lw,,/product/37/form_key/Z9IuKHJORkq6jWdh/')"><span><span>Add to Cart</span></span></button>
                                                                                                                <ul class="add-to-links pull-left">
                                                                                                                                    <li class="pull-left"><a href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/37/form_key/Z9IuKHJORkq6jWdh/" title="Add to Wishlist" class="link-wishlist">Add to Wishlist</a></li>
                                                                                                                                                                                                                        <li class="pull-right"><span class="separator">|</span> <a href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/37/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNjYXRlZ29yeS9pbmRleC9hamF4Lw,,/form_key/Z9IuKHJORkq6jWdh/" title="Add to Compare" class="link-compare">Add to Compare</a></li>
                                                                                                                        </ul>
                                </div>
                            </div>
                        </div>
                        <div class="products-textlink clearfix">
                            <h2 class="product-name">
                                <a href="http://alothemes.com/demo/smije/index.php/flat-front-trouser.html" title="Flat Front Trouser">Flat Front Trouser</a>
                            </h2>
                                                                <div class="ratings">
                    <div class="rating-box">
                <div class="rating" style="width:80%"></div>
            </div>
                <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/37/'; return false;">1 Review(s)</a></span>
    </div>
                                                        

                        
    <div class="price-box">
                                                                <span class="regular-price" id="product-price-37">
                                            <span class="price">$345.00</span>                                    </span>
                        
        </div>

                         </div>
                        				</div>
                </li>
                                        
                <li style="-webkit-animation-delay:1000ms;-moz-animation-delay:1000ms;-o-animation-delay:1000ms;animation-delay:1000ms;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
						    <div class="product-hover">
																<a href="http://alothemes.com/demo/smije/index.php/plaid-cotton-shirt-54.html" title="Plaid Cotton Shirt" class="product-image">
									<img class="img-responsive" src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/7/_/7_1_6.jpg" width="290" height="372" alt="Plaid Cotton Shirt" />
								
								   										<span class="product-img-back">
											<img class="img-responsive" src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/7/-/7-7_2.jpg" width="290" height="372" alt="Plaid Cotton Shirt" />
										</span>
																	</a>
							</div>
                            <div class="actions-no">
                                                            <div class="actions">
                                                                                                                        <button type="button" title="Add to Cart" class="pull-left button btn-cart" onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNjYXRlZ29yeS9pbmRleC9hamF4Lw,,/product/36/form_key/Z9IuKHJORkq6jWdh/')"><span><span>Add to Cart</span></span></button>
                                                                                                                <ul class="add-to-links pull-left">
                                                                                                                                    <li class="pull-left"><a href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/36/form_key/Z9IuKHJORkq6jWdh/" title="Add to Wishlist" class="link-wishlist">Add to Wishlist</a></li>
                                                                                                                                                                                                                        <li class="pull-right"><span class="separator">|</span> <a href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/36/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNjYXRlZ29yeS9pbmRleC9hamF4Lw,,/form_key/Z9IuKHJORkq6jWdh/" title="Add to Compare" class="link-compare">Add to Compare</a></li>
                                                                                                                        </ul>
                                </div>
                            </div>
                        </div>
                        <div class="products-textlink clearfix">
                            <h2 class="product-name">
                                <a href="http://alothemes.com/demo/smije/index.php/plaid-cotton-shirt-54.html" title="Plaid Cotton Shirt">Plaid Cotton Shirt</a>
                            </h2>
                                                                <div class="ratings">
                    <div class="rating-box">
                <div class="rating" style="width:60%"></div>
            </div>
                <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/36/'; return false;">1 Review(s)</a></span>
    </div>
                                                        

                        
    <div class="price-box">
                                                                <span class="regular-price" id="product-price-36">
                                            <span class="price">$234.00</span>                                    </span>
                        
        </div>

                         </div>
                        				</div>
                </li>
                                        
                <li style="-webkit-animation-delay:1500ms;-moz-animation-delay:1500ms;-o-animation-delay:1500ms;animation-delay:1500ms;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
						    <div class="product-hover">
								<span class="sticker top-right"><span class="labelsale">-18%</span></span>								<a href="http://alothemes.com/demo/smije/index.php/merino-v-neck.html" title="Merino V-neck" class="product-image">
									<img class="img-responsive" src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/8/_/8_4.jpg" width="290" height="372" alt="Merino V-neck" />
								
								   										<span class="product-img-back">
											<img class="img-responsive" src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/8/-/8-8.jpg" width="290" height="372" alt="Merino V-neck" />
										</span>
																	</a>
							</div>
                            <div class="actions-no">
                                                            <div class="actions">
                                                                                                                        <button type="button" title="Add to Cart" class="pull-left button btn-cart" onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNjYXRlZ29yeS9pbmRleC9hamF4Lw,,/product/35/form_key/Z9IuKHJORkq6jWdh/')"><span><span>Add to Cart</span></span></button>
                                                                                                                <ul class="add-to-links pull-left">
                                                                                                                                    <li class="pull-left"><a href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/35/form_key/Z9IuKHJORkq6jWdh/" title="Add to Wishlist" class="link-wishlist">Add to Wishlist</a></li>
                                                                                                                                                                                                                        <li class="pull-right"><span class="separator">|</span> <a href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/35/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNjYXRlZ29yeS9pbmRleC9hamF4Lw,,/form_key/Z9IuKHJORkq6jWdh/" title="Add to Compare" class="link-compare">Add to Compare</a></li>
                                                                                                                        </ul>
                                </div>
                            </div>
                        </div>
                        <div class="products-textlink clearfix">
                            <h2 class="product-name">
                                <a href="http://alothemes.com/demo/smije/index.php/merino-v-neck.html" title="Merino V-neck">Merino V-neck</a>
                            </h2>
                                                                <div class="ratings">
                    <div class="rating-box">
                <div class="rating" style="width:60%"></div>
            </div>
                <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/35/'; return false;">1 Review(s)</a></span>
    </div>
                                                        

                        
    <div class="price-box">
                                            
                    <p class="old-price">
                <span class="price-label">Regular Price:</span>
                <span class="price" id="old-price-35">
                    $567.00                </span>
            </p>

                            <p class="special-price">
                    <span class="price-label">Special Price</span>
                <span class="price" id="product-price-35">
                    $467.00                </span>
                </p>
                    
    
        </div>

                         </div>
                        				</div>
                </li>
                                        
                <li style="-webkit-animation-delay:2000ms;-moz-animation-delay:2000ms;-o-animation-delay:2000ms;animation-delay:2000ms;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
						    <div class="product-hover">
																<a href="http://alothemes.com/demo/smije/index.php/tori-tank.html" title="Tori Tank" class="product-image">
									<img class="img-responsive" src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/6/_/6_5.jpg" width="290" height="372" alt="Tori Tank" />
								
								   										<span class="product-img-back">
											<img class="img-responsive" src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/6/-/6-6_1.jpg" width="290" height="372" alt="Tori Tank" />
										</span>
																	</a>
							</div>
                            <div class="actions-no">
                                                            <div class="actions">
                                                                                                                        <button type="button" title="Add to Cart" class="pull-left button btn-cart" onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNjYXRlZ29yeS9pbmRleC9hamF4Lw,,/product/34/form_key/Z9IuKHJORkq6jWdh/')"><span><span>Add to Cart</span></span></button>
                                                                                                                <ul class="add-to-links pull-left">
                                                                                                                                    <li class="pull-left"><a href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/34/form_key/Z9IuKHJORkq6jWdh/" title="Add to Wishlist" class="link-wishlist">Add to Wishlist</a></li>
                                                                                                                                                                                                                        <li class="pull-right"><span class="separator">|</span> <a href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/34/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNjYXRlZ29yeS9pbmRleC9hamF4Lw,,/form_key/Z9IuKHJORkq6jWdh/" title="Add to Compare" class="link-compare">Add to Compare</a></li>
                                                                                                                        </ul>
                                </div>
                            </div>
                        </div>
                        <div class="products-textlink clearfix">
                            <h2 class="product-name">
                                <a href="http://alothemes.com/demo/smije/index.php/tori-tank.html" title="Tori Tank">Tori Tank</a>
                            </h2>
                                                                <div class="ratings">
                    <div class="rating-box">
                <div class="rating" style="width:60%"></div>
            </div>
                <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/34/'; return false;">1 Review(s)</a></span>
    </div>
                                                        

                        
    <div class="price-box">
                                                                <span class="regular-price" id="product-price-34">
                                            <span class="price">$234.00</span>                                    </span>
                        
        </div>

                         </div>
                        				</div>
                </li>
                                        
                <li style="-webkit-animation-delay:2500ms;-moz-animation-delay:2500ms;-o-animation-delay:2500ms;animation-delay:2500ms;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
						    <div class="product-hover">
								<span class="sticker top-right"><span class="labelsale">-23%</span></span>								<a href="http://alothemes.com/demo/smije/index.php/chelsea-tee.html" title="Chelsea Tee" class="product-image">
									<img class="img-responsive" src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/5/_/5_5.jpg" width="290" height="372" alt="Chelsea Tee" />
								
								   										<span class="product-img-back">
											<img class="img-responsive" src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/5/-/5-5.jpg" width="290" height="372" alt="Chelsea Tee" />
										</span>
																	</a>
							</div>
                            <div class="actions-no">
                                                            <div class="actions">
                                                                                                                        <button type="button" title="Add to Cart" class="pull-left button btn-cart" onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNjYXRlZ29yeS9pbmRleC9hamF4Lw,,/product/33/form_key/Z9IuKHJORkq6jWdh/')"><span><span>Add to Cart</span></span></button>
                                                                                                                <ul class="add-to-links pull-left">
                                                                                                                                    <li class="pull-left"><a href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/33/form_key/Z9IuKHJORkq6jWdh/" title="Add to Wishlist" class="link-wishlist">Add to Wishlist</a></li>
                                                                                                                                                                                                                        <li class="pull-right"><span class="separator">|</span> <a href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/33/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNjYXRlZ29yeS9pbmRleC9hamF4Lw,,/form_key/Z9IuKHJORkq6jWdh/" title="Add to Compare" class="link-compare">Add to Compare</a></li>
                                                                                                                        </ul>
                                </div>
                            </div>
                        </div>
                        <div class="products-textlink clearfix">
                            <h2 class="product-name">
                                <a href="http://alothemes.com/demo/smije/index.php/chelsea-tee.html" title="Chelsea Tee">Chelsea Tee</a>
                            </h2>
                                                                <div class="ratings">
                    <div class="rating-box">
                <div class="rating" style="width:80%"></div>
            </div>
                <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/33/'; return false;">1 Review(s)</a></span>
    </div>
                                                        

                        
    <div class="price-box">
                                            
                    <p class="old-price">
                <span class="price-label">Regular Price:</span>
                <span class="price" id="old-price-33">
                    $346.00                </span>
            </p>

                            <p class="special-price">
                    <span class="price-label">Special Price</span>
                <span class="price" id="product-price-33">
                    $267.00                </span>
                </p>
                    
    
        </div>

                         </div>
                        				</div>
                </li>
                                        
                <li style="-webkit-animation-delay:3000ms;-moz-animation-delay:3000ms;-o-animation-delay:3000ms;animation-delay:3000ms;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
						    <div class="product-hover">
																<a href="http://alothemes.com/demo/smije/index.php/linen-blazer.html" title="Linen Blazer" class="product-image">
									<img class="img-responsive" src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/4/_/4_4.jpg" width="290" height="372" alt="Linen Blazer" />
								
								   										<span class="product-img-back">
											<img class="img-responsive" src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/4/-/4-4.jpg" width="290" height="372" alt="Linen Blazer" />
										</span>
																	</a>
							</div>
                            <div class="actions-no">
                                                            <div class="actions">
                                                                                                                        <button type="button" title="Add to Cart" class="pull-left button btn-cart" onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNjYXRlZ29yeS9pbmRleC9hamF4Lw,,/product/28/form_key/Z9IuKHJORkq6jWdh/')"><span><span>Add to Cart</span></span></button>
                                                                                                                <ul class="add-to-links pull-left">
                                                                                                                                    <li class="pull-left"><a href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/28/form_key/Z9IuKHJORkq6jWdh/" title="Add to Wishlist" class="link-wishlist">Add to Wishlist</a></li>
                                                                                                                                                                                                                        <li class="pull-right"><span class="separator">|</span> <a href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/28/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNjYXRlZ29yeS9pbmRleC9hamF4Lw,,/form_key/Z9IuKHJORkq6jWdh/" title="Add to Compare" class="link-compare">Add to Compare</a></li>
                                                                                                                        </ul>
                                </div>
                            </div>
                        </div>
                        <div class="products-textlink clearfix">
                            <h2 class="product-name">
                                <a href="http://alothemes.com/demo/smije/index.php/linen-blazer.html" title="Linen Blazer">Linen Blazer</a>
                            </h2>
                                                                <div class="ratings">
                    <div class="rating-box">
                <div class="rating" style="width:60%"></div>
            </div>
                <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/28/'; return false;">1 Review(s)</a></span>
    </div>
                                                        

                        
    <div class="price-box">
                                                                <span class="regular-price" id="product-price-28">
                                            <span class="price">$234.00</span>                                    </span>
                        
        </div>

                         </div>
                        				</div>
                </li>
                                        
                <li style="-webkit-animation-delay:3500ms;-moz-animation-delay:3500ms;-o-animation-delay:3500ms;animation-delay:3500ms;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
						    <div class="product-hover">
																<a href="http://alothemes.com/demo/smije/index.php/slim-fit-dobby-oxford-shirt.html" title="Slim fit Dobby Oxford Shirt" class="product-image">
									<img class="img-responsive" src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/3/_/3_4.jpg" width="290" height="372" alt="Slim fit Dobby Oxford Shirt" />
								
								   										<span class="product-img-back">
											<img class="img-responsive" src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/3/-/3-3_1.jpg" width="290" height="372" alt="Slim fit Dobby Oxford Shirt" />
										</span>
																	</a>
							</div>
                            <div class="actions-no">
                                                            <div class="actions">
                                                                                                                        <button type="button" title="Add to Cart" class="pull-left button btn-cart" onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNjYXRlZ29yeS9pbmRleC9hamF4Lw,,/product/27/form_key/Z9IuKHJORkq6jWdh/')"><span><span>Add to Cart</span></span></button>
                                                                                                                <ul class="add-to-links pull-left">
                                                                                                                                    <li class="pull-left"><a href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/27/form_key/Z9IuKHJORkq6jWdh/" title="Add to Wishlist" class="link-wishlist">Add to Wishlist</a></li>
                                                                                                                                                                                                                        <li class="pull-right"><span class="separator">|</span> <a href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/27/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNjYXRlZ29yeS9pbmRleC9hamF4Lw,,/form_key/Z9IuKHJORkq6jWdh/" title="Add to Compare" class="link-compare">Add to Compare</a></li>
                                                                                                                        </ul>
                                </div>
                            </div>
                        </div>
                        <div class="products-textlink clearfix">
                            <h2 class="product-name">
                                <a href="http://alothemes.com/demo/smije/index.php/slim-fit-dobby-oxford-shirt.html" title="Slim fit Dobby Oxford Shirt">Slim fit Dobby Oxford Shirt</a>
                            </h2>
                                                                                                                    

                        
    <div class="price-box">
                                                                <span class="regular-price" id="product-price-27">
                                            <span class="price">$250.00</span>                                    </span>
                        
        </div>

                         </div>
                        				</div>
                </li>
                                        
                <li style="-webkit-animation-delay:4000ms;-moz-animation-delay:4000ms;-o-animation-delay:4000ms;animation-delay:4000ms;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
						    <div class="product-hover">
								<span class="sticker top-left"><span class="labelnew">New</span></span>								<a href="http://alothemes.com/demo/smije/index.php/french-cuff-cotton.html" title="French Cuff Cotton" class="product-image">
									<img class="img-responsive" src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/2/_/2_3.jpg" width="290" height="372" alt="French Cuff Cotton" />
								
								   										<span class="product-img-back">
											<img class="img-responsive" src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/2/-/2-2_1.jpg" width="290" height="372" alt="French Cuff Cotton" />
										</span>
																	</a>
							</div>
                            <div class="actions-no">
                                                            <div class="actions">
                                                                                                                        <button type="button" title="Add to Cart" class="pull-left button btn-cart" onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNjYXRlZ29yeS9pbmRleC9hamF4Lw,,/product/26/form_key/Z9IuKHJORkq6jWdh/')"><span><span>Add to Cart</span></span></button>
                                                                                                                <ul class="add-to-links pull-left">
                                                                                                                                    <li class="pull-left"><a href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/26/form_key/Z9IuKHJORkq6jWdh/" title="Add to Wishlist" class="link-wishlist">Add to Wishlist</a></li>
                                                                                                                                                                                                                        <li class="pull-right"><span class="separator">|</span> <a href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/26/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNjYXRlZ29yeS9pbmRleC9hamF4Lw,,/form_key/Z9IuKHJORkq6jWdh/" title="Add to Compare" class="link-compare">Add to Compare</a></li>
                                                                                                                        </ul>
                                </div>
                            </div>
                        </div>
                        <div class="products-textlink clearfix">
                            <h2 class="product-name">
                                <a href="http://alothemes.com/demo/smije/index.php/french-cuff-cotton.html" title="French Cuff Cotton">French Cuff Cotton</a>
                            </h2>
                                                                <div class="ratings">
                    <div class="rating-box">
                <div class="rating" style="width:60%"></div>
            </div>
                <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/26/'; return false;">1 Review(s)</a></span>
    </div>
                                                        

                        
    <div class="price-box">
                                                                <span class="regular-price" id="product-price-26">
                                            <span class="price">$168.00</span>                                    </span>
                        
        </div>

                         </div>
                        				</div>
                </li>
                                        
                <li style="-webkit-animation-delay:4500ms;-moz-animation-delay:4500ms;-o-animation-delay:4500ms;animation-delay:4500ms;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
						    <div class="product-hover">
								<span class="sticker top-left"><span class="labelnew">New</span></span>								<a href="http://alothemes.com/demo/smije/index.php/plaid-cotton-shirt.html" title="Plaid Cotton Shirt" class="product-image">
									<img class="img-responsive" src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1.jpg" width="290" height="372" alt="Plaid Cotton Shirt" />
								
								   										<span class="product-img-back">
											<img class="img-responsive" src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/1/-/1-1.jpg" width="290" height="372" alt="Plaid Cotton Shirt" />
										</span>
																	</a>
							</div>
                            <div class="actions-no">
                                                            <div class="actions">
                                                                                                                        <button type="button" title="Add to Cart" class="pull-left button btn-cart" onclick="setLocation('http://alothemes.com/demo/smije/index.php/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNjYXRlZ29yeS9pbmRleC9hamF4Lw,,/product/25/form_key/Z9IuKHJORkq6jWdh/')"><span><span>Add to Cart</span></span></button>
                                                                                                                <ul class="add-to-links pull-left">
                                                                                                                                    <li class="pull-left"><a href="http://alothemes.com/demo/smije/index.php/wishlist/index/add/product/25/form_key/Z9IuKHJORkq6jWdh/" title="Add to Wishlist" class="link-wishlist">Add to Wishlist</a></li>
                                                                                                                                                                                                                        <li class="pull-right"><span class="separator">|</span> <a href="http://alothemes.com/demo/smije/index.php/catalog/product_compare/add/product/25/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNjYXRlZ29yeS9pbmRleC9hamF4Lw,,/form_key/Z9IuKHJORkq6jWdh/" title="Add to Compare" class="link-compare">Add to Compare</a></li>
                                                                                                                        </ul>
                                </div>
                            </div>
                        </div>
                        <div class="products-textlink clearfix">
                            <h2 class="product-name">
                                <a href="http://alothemes.com/demo/smije/index.php/plaid-cotton-shirt.html" title="Plaid Cotton Shirt">Plaid Cotton Shirt</a>
                            </h2>
                                                                <div class="ratings">
                    <div class="rating-box">
                <div class="rating" style="width:100%"></div>
            </div>
                <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='http://alothemes.com/demo/smije/index.php/review/product/list/id/25/'; return false;">1 Review(s)</a></span>
    </div>
                                                        

                        
    <div class="price-box">
                                                                <span class="regular-price" id="product-price-25">
                                            <span class="price">$185.00</span>                                    </span>
                        
        </div>

                         </div>
                        				</div>
                </li>
                        </ul>
</div>


