-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.5.8 - MySQL Community Server (GPL)
-- Server OS:                    Win32
-- HeidiSQL Version:             9.2.0.4947
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping database structure for host5_bagseshop
CREATE DATABASE IF NOT EXISTS `host5_bagseshop` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `host5_bagseshop`;


-- Dumping structure for table host5_bagseshop.slideshow
CREATE TABLE IF NOT EXISTS `slideshow` (
  `id` int(255) NOT NULL AUTO_INCREMENT,
  `img` text,
  `text` text,
  `link` varchar(255) DEFAULT NULL,
  `status` int(10) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

-- Dumping data for table host5_bagseshop.slideshow: ~3 rows (approximately)
/*!40000 ALTER TABLE `slideshow` DISABLE KEYS */;
INSERT INTO `slideshow` (`id`, `img`, `text`, `link`, `status`) VALUES
	(1, 'slideshow_1435543718.jpg', '   <div class="iview-caption caption5" data-x="573" data-y="43" data-height="20" data-transition="fade" style="opacity: 1; top: 43px; left: 573px; width: 125px; height: 20px;"><div class="caption-contain" style="position: relative; width: 125px; height: 20px; opacity: 1; top: 0px; left: 0px;">Are\r\n                                                you Ready ?</div></div>\r\n                                            <div class="iview-caption caption1 blackcaption" data-x="509" data-y="104" style="opacity: 1; top: 104px; left: 509px; width: 260px; height: 69px;"><div class="caption-contain" style="position: relative; width: 260px; height: 69px; opacity: 1; top: 0px; left: 0px;">Sweater*</div></div>\r\n                                            <div class="iview-caption caption3 blackcaption" data-x="468" data-y="170" data-height="26" data-width="500" style="opacity: 1; top: 170px; left: 468px; width: 500px; height: 26px;"><div class="caption-contain" style="position: relative; width: 500px; height: 26px; opacity: 1; top: 0px; left: 0px;">Biggest Arrival of the Month</div></div>\r\n                                            <div class="iview-caption caption4 blackcaption" data-x="537" data-y="208" data-height="28" style="opacity: 1; top: 208px; left: 537px; width: 203px; height: 28px;"><div class="caption-contain" style="position: relative; width: 203px; height: 28px; opacity: 1; top: 0px; left: 0px;">*Hurry\r\n                                                in December 10th - 16th !</div></div>\r\n                                            <div class="iview-caption caption6 blackcaption" data-x="579" data-y="255" data-height="43" data-width="200" style="opacity: 1; top: 255px; left: 579px; width: 200px; height: 43px;"><div class="caption-contain" style="position: relative; width: 200px; height: 43px; opacity: 1; top: 0px; left: 0px;">View more</div></div>\r\n                                        ', 'http://rohlik.cz.localhost:20134/main/index', 1),
	(2, 'slideshow_1435543700.jpg', '   <div class="iview-caption caption5" data-x="573" data-y="43" data-height="20" data-transition="fade" style="opacity: 1; top: 43px; left: 573px; width: 125px; height: 20px;"><div class="caption-contain" style="position: relative; width: 125px; height: 20px; opacity: 1; top: 0px; left: 0px;">Are\r\n                                                you Ready ?</div></div>\r\n                                            <div class="iview-caption caption1 blackcaption" data-x="509" data-y="104" style="opacity: 1; top: 104px; left: 509px; width: 260px; height: 69px;"><div class="caption-contain" style="position: relative; width: 260px; height: 69px; opacity: 1; top: 0px; left: 0px;">Sweater*</div></div>\r\n                                            <div class="iview-caption caption3 blackcaption" data-x="468" data-y="170" data-height="26" data-width="500" style="opacity: 1; top: 170px; left: 468px; width: 500px; height: 26px;"><div class="caption-contain" style="position: relative; width: 500px; height: 26px; opacity: 1; top: 0px; left: 0px;">Biggest Arrival of the Month</div></div>\r\n                                            <div class="iview-caption caption4 blackcaption" data-x="537" data-y="208" data-height="28" style="opacity: 1; top: 208px; left: 537px; width: 203px; height: 28px;"><div class="caption-contain" style="position: relative; width: 203px; height: 28px; opacity: 1; top: 0px; left: 0px;">*Hurry\r\n                                                in December 10th - 16th !</div></div>\r\n                                            <div class="iview-caption caption6 blackcaption" data-x="579" data-y="255" data-height="43" data-width="200" style="opacity: 1; top: 255px; left: 579px; width: 200px; height: 43px;"><div class="caption-contain" style="position: relative; width: 200px; height: 43px; opacity: 1; top: 0px; left: 0px;">View more</div></div>\r\n                                        ', 'http://rohlik.cz.localhost:20134/main/index', 1),
	(3, 'slideshow_1435543679.jpg', ' <div class="iview-caption caption5" data-x="573" data-y="43" data-height="20" data-transition="fade" style="opacity: 1; top: 43px; left: 573px; width: 114px; height: 20px;"><div class="caption-contain" style="position: relative; width: 114px; height: 20px; opacity: 1; top: 0px; left: 0px;">New\r\n                                                Arrivals !</div></div>\r\n                                            <div class="iview-caption caption1 blackcaption" data-x="489" data-y="104" data-width="500" style="opacity: 1; top: 104px; left: 489px; width: 500px; height: 69px;"><div class="caption-contain" style="position: relative; width: 500px; height: 69px; opacity: 1; top: 0px; left: 0px;">JK-\r\n                                                Outet*</div></div>\r\n                                            <div class="iview-caption caption3 blackcaption" data-x="448" data-y="170" data-height="26" data-width="500" style="opacity: 1; top: 170px; left: 448px; width: 500px; height: 26px;"><div class="caption-contain" style="position: relative; width: 500px; height: 26px; opacity: 1; top: 0px; left: 0px;">Take cover - latest Accessories</div></div>\r\n                                            <div class="iview-caption caption4 blackcaption" data-x="537" data-y="208" data-height="28" style="opacity: 1; top: 208px; left: 537px; width: 206px; height: 28px;"><div class="caption-contain" style="position: relative; width: 206px; height: 28px; opacity: 1; top: 0px; left: 0px;">*Hurry\r\n                                                in December 10th - 16th !</div></div>\r\n                                            <div class="iview-caption caption6 blackcaption" data-x="579" data-y="255" data-height="43" data-width="200" style="opacity: 1; top: 255px; left: 579px; width: 200px; height: 43px;"><div class="caption-contain" style="position: relative; width: 200px; height: 43px; opacity: 1; top: 0px; left: 0px;">View more</div></div>\r\n                                       ', 'http://rohlik.cz.localhost:20134/main/index', 1);
/*!40000 ALTER TABLE `slideshow` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
