<?php if (!$this->layout()->getuser) die("Error") ?>
    <section id="content">

        <!--breadcrumbs start-->
        <div id="breadcrumbs-wrapper" class=" grey lighten-3">
            <div class="container">
                <div class="row">
                    <div class="col s12 m6 l6">
                        <h5 class="breadcrumbs-title">Mana Maste product</h5>
                        <ol class="breadcrumb">
                            <li><a href="<?php echo WEBPATH; ?>/materialize/">Dashboard</a></li>
                        <li><a href="<?php echo WEBPATH; ?>/masteproduct/index">Maste product</a></li>
                        <li class="active">Manager</li>
                    </ol>
                </div>
                <div class="col s12 m6 l6 btn-manage">
                    <a href="<?php echo WEBPATH; ?>/masteproduct/index/index" class="waves-effect waves-light  btn">Manager Product</a>
                    <a href="<?php echo WEBPATH; ?>/masteproduct/index/add" class="waves-effect waves-light  btn">Add New Product</a>
                </div>
            </div>
        </div>
    </div>
    <!--breadcrumbs end-->


    <!--start container-->
    <div class="container">
        <div class="section">        
            <p class="alert-error">
                <?php
                $error = $this->error;
                if (isset($error)) {
                    echo $error;
                }
                ?>
            </p>
            <div class="divider"></div>
            <!--Basic Form-->
            <div id="basic-form" class="section">
                <div class="row">
                    <div class="col s12 m12 l12">
                        <div class="card-panel"> 
                            <?php
                            if ((isset($check) && $check == 1 and $id_product != '') || (isset($check) && $check == 1 and $Error != 1)) {
                                echo '<div class="alert alert-success" role="alert">Catalog has been Add success.</div>';
                            }
                            ?>
                            <?php
                            if (isset($check) && $check == 0) {
                                echo '<div class="alert alert-danger" role="alert">Error!!.</div>';
                            }
                            ?>
                            <?php if (!isset($check) || $check == 'NULL') { ?>
                                <div class="row">
                                    <?php
                                    $data_catalog = $this->data_catalog;
                                    $data = $this->data_tags;
                                    $form = $this->Masterialproductform;
                                    echo $this->form()->openTag($form);
                                    ?>

                                    <div class="row">
                                        <div class="input-field col s6">
                                            <?php echo $this->formElement($form->get('name')); ?>
                                            <?php echo $this->formlabel($form->get('name')); ?>

                                        </div>

                                        <div class="input-field col s6">                        
                                            <?php echo $this->formElement($form->get('alias')); ?>
                                            <?php echo $this->formlabel($form->get('alias')); ?>
                                        </div>
                                    </div>
                                    <div class="row">    
                                        <div class="input-field col s6">
                                            <?php echo $this->formElement($form->get('descripts')); ?>
                                            <?php echo $this->formlabel($form->get('descripts')); ?>                              
                                        </div>
                                        <div class="input-field col s6">
                                            <?php echo $this->formElement($form->get('detail_product')); ?>   
                                            <?php echo $this->formlabel($form->get('detail_product')); ?>

                                        </div>

                                    </div>
                                    <div class="row">                      
                                        <div class="input-field col s6">
                                            <?php echo $this->formElement($form->get('availability')); ?>
                                            <?php echo $this->formlabel($form->get('availability')); ?>                                
                                        </div> 
                                        <div class="input-field col s6">
                                            <?php echo $this->formElement($form->get('promotions')); ?>
                                            <?php echo $this->formlabel($form->get('promotions')); ?>                          

                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s6">
                                            <?php //echo $this->formElement($form->get('cat_id')); ?>
                                            <?php //echo $this->formlabel($form->get('cat_id'));  ?>
                                            <select name="cat_id" >
                                                <option value="0"></option>
                                                <?php
                                                foreach ($data_catalog as $key_cat => $value_cat) {
                                                    if ($value_cat->parent == NULL || $value_cat == 0) {
                                                        $sub_cat = $this->sub_cat[$value_cat->id];
                                                        ?>
                                                        <option value="<?php echo $value_cat->id ?>"><?php echo $value_cat->name ?></option>
                                                        <?php
                                                        foreach ($sub_cat as $key_s => $value_s) {
                                                            $sub_cat_s = $this->sub_cat[$value_s->id];
                                                            echo '<option value="' . $value_s->id . '">-- ' . $value_s->name . '</option>';
                                                            foreach ($sub_cat_s as $key_s_1 => $value_s_1) {
                                                                echo '<option value="' . $value_s_1->id . '">---- ' . $value_s_1->name . '</option>';
                                                            }
                                                        }
                                                        ?>
                                                        <?php
                                                    }
                                                }
                                                ?>
                                            </select>
                                            <label>Parent</label>
                                        </div>                        
                                        <div class="input-field col s6">
                                            <?php //echo $this->formElement($form->get('tag_id')); ?>
                                            <?php //echo $this->formlabel($form->get('tag_id'));  ?>
                                            <select name="tag_id" >
                                                <option value="0"></option>
                                                <?php
                                                foreach ($data as $key => $value) {
                                                    if ($value->parent == NULL || $value == 0) {
                                                        $tags = $this->tags[$value->id];
                                                        ?>
                                                        <option value="<?php echo $value->id ?>"><?php echo $value->name ?></option>
                                                        <?php
                                                        foreach ($tags as $keys => $values) {
                                                            $tags_1 = $this->tags[$values->id];
                                                            echo '<option value="' . $values->id . '">-- ' . $values->name . '</option>';
                                                            foreach ($tags_1 as $keys_1 => $values_1) {
                                                                echo '<option value="' . $values_1->id . '">---- ' . $values_1->name . '</option>';
                                                            }
                                                        }
                                                        ?>
                                                        <?php
                                                    }
                                                }
                                                ?>
                                            </select>
                                            <label>Tags</label>
                                        </div>

                                    </div>

                                    <div class="row">
                                        <div class="input-field col s6">                          
                                            <?php echo $this->formElement($form->get('price')); ?>
                                            <?php echo $this->formlabel($form->get('price')); ?>        
                                        </div>
                                        <div class="input-field col s6">                          
                                            <?php echo $this->formElement($form->get('about_price')); ?>
                                            <?php echo $this->formlabel($form->get('about_price')); ?>        
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="file-field input-field col s12 set-label">
                                            <?php echo $this->formLabel($form->get('img')); ?>
                                            <input class="file-path validate" readonly="" type="text"/>
                                            <div class="btn">
                                                <span>IMG</span>
                                                <?php echo $this->formFile($form->get('img')); ?>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="row">
                                        <div class="input-field col s6 ">
                                            <div class="col s12 m12 l12">
                                                <label for="parent">Choice Hot</label>
                                                <div class="row">
                                                    <div class="col s12 m12 l3 offset-l3">
                                                        <input name="hot" type="radio" value="0" id="test1" checked > <label for="test1">No hot</label>
                                                        <p></p>
                                                    </div>
                                                    <div class="col s12 m12 l6">
                                                        <input name="hot" type="radio" value="1" id="test2" > <label for="test2">Hot</label>
                                                        <p></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="input-field col s6 ">
                                            <div class="col s12 m12 l12">
                                                <label for="parent">New</label>
                                                <div class="row">
                                                    <div class="col s12 m12 l3 offset-l3">
                                                        <input name="new" type="radio" value="0" id="new" > <label for="new">No new</label>
                                                        <p></p>
                                                    </div>
                                                    <div class="col s12 m12 l6">
                                                        <input name="new" type="radio" value="1" id="new1" checked > <label for="new1">New</label>
                                                        <p></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s6 ">
                                            <div class="col s12 m12 l12">
                                                <label for="parent">Status</label>
                                                <div class="row">
                                                    <div class="col s12 m12 l3 offset-l3">
                                                        <input name="status" type="radio" value="0" id="status"> <label for="status">Pause</label>
                                                        <p></p>
                                                    </div>
                                                    <div class="col s12 m12 l6">
                                                        <input name="status" type="radio" value="1" id="status1" checked > <label for="status1">Active</label>
                                                        <p></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="input-field col s6 ">
                                            <div class="col s12 m12 l12">
                                                <label for="parent">Weekly featured</label>
                                                <div class="row">
                                                    <div class="col s12 m12 l3 offset-l3">
                                                        <input name="weekly_featured" type="radio" value="0" id="weekly_featured" checked> <label for="weekly_featured">No</label>
                                                        <p></p>
                                                    </div>
                                                    <div class="col s12 m12 l6">
                                                        <input name="weekly_featured" type="radio" value="1" id="weekly_featured1" > <label for="weekly_featured1">Yes</label>
                                                        <p></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s6 ">
                                            <div class="col s12 m12 l12">
                                                <label for="parent">Featured Products</label>
                                                <div class="row">
                                                    <div class="col s12 m12 l3 offset-l3">
                                                        <input name="featured_products" type="radio" value="0" id="featured_products" checked> <label for="featured_products">No</label>
                                                        <p></p>
                                                    </div>
                                                    <div class="col s12 m12 l6">
                                                        <input name="featured_products" type="radio" value="1"  id="featured_products1"> <label for="featured_products1">Yes</label>
                                                        <p></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="input-field col s6 ">
                                            <div class="col s12 m12 l12">
                                                <label for="parent">New Products</label>
                                                <div class="row">
                                                    <div class="col s12 m12 l3 offset-l3">
                                                        <input name="new_products" type="radio" value="0" id="new_products"> <label for="new_products">No</label>
                                                        <p></p>
                                                    </div>
                                                    <div class="col s12 m12 l6">
                                                        <input name="new_products" type="radio" value="1"  id="new_products1" checked> <label for="new_products1">Yes</label>
                                                        <p></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s6 ">
                                            <div class="col s12 m12 l12">
                                                <label for="parent">Sale Products</label>
                                                <div class="row">
                                                    <div class="col s12 m12 l3 offset-l3">
                                                        <input name="sale_products" type="radio" value="0" id="sale_products" checked> <label for="sale_products">No</label>
                                                        <p></p>
                                                    </div>
                                                    <div class="col s12 m12 l6">
                                                        <input name="sale_products" type="radio" value="1"  id="sale_products1"> <label for="sale_products1">Yes</label>
                                                        <p></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>                     
                                    </div>                    
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <button class="btn cyan waves-effect waves-light right" type="submit" name="action">Submit
                                                <i class="mdi-content-send right"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                <?php
                                echo $this->form()->closeTag($form);
                                ?>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
            <!-- Form with placeholder -->

        </div>
    </div>

    <!-- Form with icon prefixes -->

</div>






</div>
</section>


<script type="text/javascript">
    function get_alias() {
        var str = (document.getElementById("name").value);
        str = str.toLowerCase();
        str = str.replace(/à|á|ạ|ả|ã|â|ầ|ấ|ậ|ẩ|ẫ|ă|ằ|ắ|ặ|ẳ|ẵ/g, "a");
        str = str.replace(/è|é|ẹ|ẻ|ẽ|ê|ề|ế|ệ|ể|ễ/g, "e");
        str = str.replace(/ì|í|ị|ỉ|ĩ/g, "i");
        str = str.replace(/ò|ó|ọ|ỏ|õ|ô|ồ|ố|ộ|ổ|ỗ|ơ|ờ|ớ|ợ|ở|ỡ/g, "o");
        str = str.replace(/ù|ú|ụ|ủ|ũ|ư|ừ|ứ|ự|ử|ữ/g, "u");
        str = str.replace(/ỳ|ý|ỵ|ỷ|ỹ/g, "y");
        str = str.replace(/đ/g, "d");
        str = str.replace(/!|@|\$|%|\^|\*|\(|\)|\+|\=|\<|\>|\?|\/|,|\.|\:|\'| |\"|\&|\#|\[|\]|~/g, "-");
        str = str.replace(/-+-/g, "-"); //thay thế 2- thành 1-
        str = str.replace(/^\-+|\-+$/g, "");//cắt bỏ ký tự - ở đầu và cuối chuỗi
        document.getElementById("alias").value = str;
        return str;
    }
</script>

<script type="text/javascript">
    var domainnew = '<?php echo WEBPATH; ?>';
    var glob = 2;
    jQuery(document).ready(function () {
        e = location.pathname;
        $.ajax({
            type: "POST",
            url: domainnew + "/main/myproduct",
            data: {idcode: e, page: glob},
            success: function (data) {
                //alert(data);console.log( $('.leftcatalogue').html(data));
                $('#myproductaja').html(data);
                glob++;
            }
        });
    });
</script>
<style>
    .alert-error{
        font-size: 14px;
        background: #b3f99f;
        line-height: 60px;
        padding-left: 20px;
    }

</style>