<section id="content">
<!--breadcrumbs start-->
<div id="breadcrumbs-wrapper" class=" grey lighten-3">
    <div class="container">
        <div class="row">
            <div class="col s12 m6 l6">
                <h5 class="breadcrumbs-title">Mana Maste product</h5>
                <ol class="breadcrumb">
                    <li><a href="<?php echo WEBPATH; ?>/materialize/">Dashboard</a></li>
                    <li><a href="<?php echo WEBPATH; ?>/masteproduct/index">Maste product</a></li>
                    <li class="active">Manager</li>
                </ol>
            </div>
            <div class="col s12 m6 l6 btn-manage">
                <a href="<?php echo WEBPATH; ?>/masteproduct/index/index" class="waves-effect waves-light  btn">Manager Product</a>
                <a href="<?php echo WEBPATH; ?>/masteproduct/index/add" class="waves-effect waves-light  btn">Add New Product</a>
            </div>
        </div>
    </div>
</div>
<!--breadcrumbs end
<div class="pageheader">
    <h1 class="title-admin page-title">
        <i class="glyphicon glyphicon-plus"></i>Add Album Product:
    </h1>
</div>
-->
<div class="col s12 m12 l11 offset-l1" style="margin: 15px 0px 0px 15px">
<div id="mutiupload " style="height: 100%;width: 100%;">
    <div id="mulitplefileuploader">Upload</div>

    <div id="status"></div>

    <script>
        function addalbum() {
            var id = '<?php echo $id_product; ?>';
            var url_domain = '<?php echo WEBPATH; ?>';

            //reset update img
            $.ajax({
                type: "POST",
                url: url_domain + "/product/index/ajaxsaveimg",
                data: {id: id, img: 0},
                success: function (data) {
                    console.log("data clear :" + data);
                }
            });


            var settings = {
                //domain:"<?php //echo WEBPATH;    ?>",	
                url: "<?php echo WEBPATH ?>/product/index/dragdrop/" + id,
                method: "POST",
                allowedTypes: "jpg,png,gif", //,doc,pdf,zip
                fileName: "myfile",
                multiple: true,
                onSuccess: function (files, data, xhr)
                {
                    //console.log("data :"+data);
                    $("#status").html("<font color='green'>Upload is success</font>");

                },
                afterUploadAll: function ()
                {
                    //alert("all images uploaded!!");
                    var x;
                    if (confirm("all images uploaded!!") == true) {
                        x = "You pressed OK!";
                        console.log('OK click  :' + x);
                        // tmp delete
                        var img = 1; //console.log("img :"+ img);
                        $.ajax({
                            type: "POST",
                            url: url_domain + "/product/index/tmpdeimg",
                            data: {id: id, img: img},
                            success: function (da) {
                                console.log(da);
                            }
                        });

                        //update data img
                        var img = 1;
                        $.ajax({
                            type: "POST",
                            url: url_domain + "/product/index/ajaxsaveimg",
                            data: {id: id, img: img},
                            success: function (da) {
                                console.log("update img all :" + da);
                            }
                        });

                        //setInterval(function(){ document.location.reload(true); }, 4000);

                    } else {
                        x = "You pressed Cancel!";
                        console.log('cancel :' + x);
                    }
                },
                onError: function (files, status, errMsg)
                {
                    $("#status").html("<font color='red'>Upload is Failed</font>");
                }
            };
            $("#mulitplefileuploader").uploadFile(settings);

        }
        ;
    </script>


</div>
</div><!-- mutiupload end -->

<div class="container">
    <div class="section">        

        <div class="divider"></div>
        <!--Basic Form-->
        <div id="basic-form" class="section">
            <div class="row">
                <div class="col s12 m12 l12">
                    <div class="card-panel"> 
                        <?php
                        if ((isset($check) && $check == 1 and $id_product != '') || (isset($check) && $check == 1 and $Error != 1)) {
                            echo '<div class="alert alert-success" role="alert">Catalog has been Add success.</div>';
                        }
                        ?>
                        <?php
                        if (isset($check) && $check == 0) {
                            echo '<div class="alert alert-danger" role="alert">Error!!.</div>';
                        }
                        ?>
                        <?php if (!isset($check) || $check == 'NULL') { ?>
                            <div class="row">
                                <?php
                                // Data Radio
                                $data_product = $this->data_product;
                                $hot = $data_product->hot;
                                $status = $data_product->status;
                                $new = $data_product->new;
                                $featured_products = $data_product->featured_products;
                                $new_products = $data_product->new_products;
                                $sale_products = $data_product->sale_products;
                                $weekly_featured = $data_product->weekly_featured;
                                //-------------

                                $form = $this->Masterialproductform;
                                echo $this->form()->openTag($form);
                                ?>
                                <?php echo $this->formElement($form->get('id')); ?>
                                <div class="row">
                                    <div class="input-field col s6">
                                        <?php echo $this->formElement($form->get('name')); ?>
                                        <?php echo $this->formlabel($form->get('name')); ?>
                                    </div>

                                    <div class="input-field col s6">                        
                                        <?php echo $this->formElement($form->get('alias')); ?>
                                        <?php echo $this->formlabel($form->get('alias')); ?>
                                    </div>
                                </div>
                                <div class="row">    
                                    <div class="input-field col s6">
                                        <?php echo $this->formElement($form->get('descripts')); ?>
                                        <?php echo $this->formlabel($form->get('descripts')); ?>                              
                                    </div>
                                    <div class="input-field col s6">
                                        <?php echo $this->formElement($form->get('detail_product')); ?>   
                                        <?php echo $this->formlabel($form->get('detail_product')); ?>

                                    </div>

                                </div>
                                <div class="row">                      
                                    <div class="input-field col s6">
                                        <?php echo $this->formElement($form->get('availability')); ?>
                                        <?php echo $this->formlabel($form->get('availability')); ?>                                
                                    </div> 
                                    <div class="input-field col s6">
                                        <?php echo $this->formElement($form->get('promotions')); ?>
                                        <?php echo $this->formlabel($form->get('promotions')); ?>                          

                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s6">
                                        <?php echo $this->formElement($form->get('cat_id')); ?>
                                        <?php echo $this->formlabel($form->get('cat_id')); ?>

                                    </div>                        
                                    <div class="input-field col s6">
                                        <?php echo $this->formElement($form->get('tag_id')); ?>
                                        <?php echo $this->formlabel($form->get('tag_id')); ?>

                                    </div>

                                </div>

                                <div class="row">
                                    <div class="input-field col s6">                          
                                        <?php echo $this->formElement($form->get('price')); ?>
                                        <?php echo $this->formlabel($form->get('price')); ?>        
                                    </div>
                                    <div class="input-field col s6">                          
                                        <?php echo $this->formElement($form->get('about_price')); ?>
                                        <?php echo $this->formlabel($form->get('about_price')); ?>        
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="file-field input-field col s6 set-label">
                                        <?php echo $this->formLabel($form->get('img')); ?>
                                        <input class="file-path validate" readonly="" type="text"/>
                                        <div class="btn">
                                            <span>IMG</span>
                                            <?php echo $this->formFile($form->get('img')); ?>
                                        </div>
                                    </div>
                                    <div class="col s6">  
                                        <?php if ($this->img_thumb != '' || $this->img_thumb != NULL) { ?>                                    
                                            <img class="img-responsive"
                                                 src="<?php echo WEBPATH_UPLOAD_PATH_IMG_THUNB_ . '\\' . $this->img_thumb; ?>" />

                                        <?php } ?>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="input-field col s6 ">
                                        <div class="col s12 m12 l12">
                                            <label for="parent">Choice Hot</label>
                                            <div class="row">
                                                <div class="col s12 m12 l3 offset-l3">
                                                    <input name="hot" type="radio" value="0" id="test1" <?php
                                                    if ($hot == 0) {
                                                        echo 'checked';
                                                    }
                                                    ?> > <label for="test1">No hot</label>
                                                    <p></p>
                                                </div>
                                                <div class="col s12 m12 l6">
                                                    <input name="hot" type="radio" value="1" id="test2" <?php
                                                    if ($hot == 1) {
                                                        echo 'checked';
                                                    }
                                                    ?>> <label for="test2">Hot</label>
                                                    <p></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="input-field col s6 ">
                                        <div class="col s12 m12 l12">
                                            <label for="parent">New</label>
                                            <div class="row">
                                                <div class="col s12 m12 l3 offset-l3">
                                                    <input name="new" type="radio" value="0" id="new" <?php
                                                    if ($new == 0) {
                                                        echo 'checked';
                                                    }
                                                    ?>> <label for="new">No new</label>
                                                    <p></p>
                                                </div>
                                                <div class="col s12 m12 l6">
                                                    <input name="new" type="radio" value="1" id="new1" <?php
                                                    if ($new == 1) {
                                                        echo 'checked';
                                                    }
                                                    ?> > <label for="new1">New</label>
                                                    <p></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s6 ">
                                        <div class="col s12 m12 l12">
                                            <label for="parent">Status</label>
                                            <div class="row">
                                                <div class="col s12 m12 l3 offset-l3">
                                                    <input name="status" type="radio" value="0" id="status" <?php
                                                    if ($status == 0) {
                                                        echo 'checked';
                                                    }
                                                    ?>> <label for="status">Pause</label>
                                                    <p></p>
                                                </div>
                                                <div class="col s12 m12 l6">
                                                    <input name="status" type="radio" value="1" id="status1" <?php
                                                    if ($status == 1) {
                                                        echo 'checked';
                                                    }
                                                    ?>> <label for="status1">Active</label>
                                                    <p></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="input-field col s6 ">
                                        <div class="col s12 m12 l12">
                                            <label for="parent">Weekly featured</label>
                                            <div class="row">
                                                <div class="col s12 m12 l3 offset-l3">
                                                    <input name="weekly_featured" type="radio" value="0" id="weekly_featured" <?php
                                                    if ($weekly_featured == 0) {
                                                        echo 'checked';
                                                    }
                                                    ?>> <label for="weekly_featured">No</label>
                                                    <p></p>
                                                </div>
                                                <div class="col s12 m12 l6">
                                                    <input name="weekly_featured" type="radio" value="1" id="weekly_featured1" <?php
                                                    if ($weekly_featured == 1) {
                                                        echo 'checked';
                                                    }
                                                    ?>> <label for="weekly_featured1">Yes</label>
                                                    <p></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s6 ">
                                        <div class="col s12 m12 l12">
                                            <label for="parent">Featured Products</label>
                                            <div class="row">
                                                <div class="col s12 m12 l3 offset-l3">
                                                    <input name="featured_products" type="radio" value="0" id="featured_products" <?php
                                                    if ($featured_products == 0) {
                                                        echo 'checked';
                                                    }
                                                    ?>> <label for="featured_products">No</label>
                                                    <p></p>
                                                </div>
                                                <div class="col s12 m12 l6">
                                                    <input name="featured_products" type="radio" value="1"  id="featured_products1" <?php
                                                    if ($weekly_featured == 1) {
                                                        echo 'checked';
                                                    }
                                                    ?>> <label for="featured_products1">Yes</label>
                                                    <p></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="input-field col s6 ">
                                        <div class="col s12 m12 l12">
                                            <label for="parent">New Products</label>
                                            <div class="row">
                                                <div class="col s12 m12 l3 offset-l3">
                                                    <input name="new_products" type="radio" value="0" id="new_products" <?php
                                                    if ($new_products == 0) {
                                                        echo 'checked';
                                                    }
                                                    ?>> <label for="new_products">No</label>
                                                    <p></p>
                                                </div>
                                                <div class="col s12 m12 l6">
                                                    <input name="new_products" type="radio" value="1"  id="new_products1" <?php
                                                    if ($new_products == 1) {
                                                        echo 'checked';
                                                    }
                                                    ?>> <label for="new_products1">Yes</label>
                                                    <p></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s6 ">
                                        <div class="col s12 m12 l12">
                                            <label for="parent">Sale Products</label>
                                            <div class="row">
                                                <div class="col s12 m12 l3 offset-l3">
                                                    <input name="sale_products" type="radio" value="0" id="sale_products" <?php
                                                    if ($sale_products == 0) {
                                                        echo 'checked';
                                                    }
                                                    ?>> <label for="sale_products">No</label>
                                                    <p></p>
                                                </div>
                                                <div class="col s12 m12 l6">
                                                    <input name="sale_products" type="radio" value="1"  id="sale_products1" <?php
                                                    if ($sale_products == 1) {
                                                        echo 'checked';
                                                    }
                                                    ?>> <label for="sale_products1">Yes</label>
                                                    <p></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>                     
                                </div>                  
                               
                            </div>
                            <?php
                            echo $this->form()->closeTag($form);
                            ?>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
        <!-- Form with placeholder -->

    </div>
</div>
</section>
<script type="text/javascript">
    function get_alias() {
        var str = (document.getElementById("name").value);
        str = str.toLowerCase();
        str = str.replace(/à|á|ạ|ả|ã|â|ầ|ấ|ậ|ẩ|ẫ|ă|ằ|ắ|ặ|ẳ|ẵ/g, "a");
        str = str.replace(/è|é|ẹ|ẻ|ẽ|ê|ề|ế|ệ|ể|ễ/g, "e");
        str = str.replace(/ì|í|ị|ỉ|ĩ/g, "i");
        str = str.replace(/ò|ó|ọ|ỏ|õ|ô|ồ|ố|ộ|ổ|ỗ|ơ|ờ|ớ|ợ|ở|ỡ/g, "o");
        str = str.replace(/ù|ú|ụ|ủ|ũ|ư|ừ|ứ|ự|ử|ữ/g, "u");
        str = str.replace(/ỳ|ý|ỵ|ỷ|ỹ/g, "y");
        str = str.replace(/đ/g, "d");
        str = str.replace(/!|@|\$|%|\^|\*|\(|\)|\+|\=|\<|\>|\?|\/|,|\.|\:|\'| |\"|\&|\#|\[|\]|~/g, "-");
        str = str.replace(/-+-/g, "-"); //thay thế 2- thành 1-
        str = str.replace(/^\-+|\-+$/g, "");//cắt bỏ ký tự - ở đầu và cuối chuỗi
        document.getElementById("alias").value = str;
        return str;
    }
</script>