<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Zend\\' => array($vendorDir . '/zendframework/zendframework/library'),
    'ZendXml' => array($vendorDir . '/zendframework/zendxml/library'),
	'Symfony\\Component\\Console\\' => array($vendorDir . '/symfony/console'),
	'Symfony\\Component\\DomCrawler\\' => array($vendorDir . '/symfony/DomCrawler'),
	'Symfony\\Component\\CssSelector\\' => array($vendorDir . '/symfony/CssSelector'),
);
