 <div id="breadcrumbs-wrapper" class=" grey lighten-3">
            <div class="container">
                <div class="row">
                    <div class="col s12 m9 l9">
                    <h5 class="breadcrumbs-title">Mana Crolwer</h5>
                    <ol class="breadcrumb">
                        <li><a href="<?php echo WEBPATH; ?>/materialize/">Dashboard</a></li>
                        <li><a href="<?php echo WEBPATH; ?>/crowler/index">Crolwer</a></li>
                        <li class="active">Manager</li>
                    </ol>
                </div>
                <div class="col s12 m3 l3 btn-manage">
                    <a href="<?php echo WEBPATH; ?>/crowler/index" class="waves-effect waves-light  btn">Manager Product</a>

                </div>
            </div>
        </div>
    </div>
<div class="main-container col2-left-layout">
	<div class="container">
		<div class="main">

			<div class="row show-grid">
				<div
					class="col-left sidebar col-lg-3 col-md-3 col-sm-3 col-pull-3 hidden-xs">

					<!--  <div id="leftcatalogue"></div> -->
					<!-- leftcatalogue -->

					<div id="myacountaja"></div>
					<!-- myacountaja -->
					<div id="myproductaja"></div>

					<div id="mycartaja"></div>


					<div id="compareproductaja"></div>
					<!-- compareproductaja -->
					

					<p></p>
				</div>

				<!--thay trang chi tiet vao--->
				<div
					class="col-main col-lg-9 col-md-9 col-sm-9 col-push-9 col-xs-12">
					
					<div id=""formdelete>
					<?php if (!isset ( $check )) {?>
					  <p>Are you sure that you want to delete Product Name is : <span style="font-style: bold;">'<?php echo $this->escapeHtml($this->product->name); ?>' </span>?
						</p>
						<h5>Note: If you delete this list, it will affect the list containing it. Or do you think more carefully before deleting</h5>
						<?php 
						$url = $this->url('Crowler', array('controller'=>'index','action' => 'delete', 'id'=>$this->id)); ?>
						<form action="<?php echo $url; ?>" method="post">
						<div>
						  <input type="hidden" name="id" value="<?php echo (int)$this->product->id; ?>" />
						  <input type="submit" name="del" value="Yes" class="btn btn-primary" />
						  <input type="submit" name="del" value="No" class="btn btn-primary" />
						</div>
						</form>
					</div><!-- end form delete -->
					<?php } // if (!isset ( $check )?>
					<?php
					
					if (isset ( $check ) && $check == 1 ) {
						echo '<div class="alert alert-success" role="alert">Product has been Delete success.</div>';
					}
					?>
					<?php if(isset($check)&&$check==0){echo '<div class="alert alert-danger" role="alert">Error Delete!!.</div>';}?>
					
					<!-- end chi tiet -->
				</div>
			</div>
		</div>
	</div>