<section id="content">

        <!--breadcrumbs start-->
        <div id="breadcrumbs-wrapper" class=" grey lighten-3">
            <div class="container">
                <div class="row">
                    <div class="col s12 m9 l9">
					<h5 class="breadcrumbs-title">Mana Crolwer</h5>
					<ol class="breadcrumb">
						<li><a href="<?php echo WEBPATH;?>/materialize/">Dashboard</a></li>
						<li><a href="<?php echo WEBPATH;?>/crowler/index">Crolwer</a></li>
						<li class="active">Manager</li>
					</ol>
				</div>
                             <div class="col s12 m3 l3 btn-manage">
                    <a href="<?php echo WEBPATH; ?>/crowler/index" class="waves-effect waves-light  btn">Manager Product</a>
                    
                </div>
            </div>
        </div>
    </div>
    <!--breadcrumbs end-->
    
 <div class="container">
     <div class="divider"></div>
<?php if(isset($check)&&$check==1){echo '<div class="alert alert-success" role="alert">Status Edit Product succcess.</div>';}?>
<?php if(isset($check)&&$check==0){echo '<div class="alert alert-danger" role="alert">Status Edit Product failed.</div>';}?>
</div>    
					<!-- end chi tiet -->
 </section>