<div class="get">
	<div class="container">
		<p>
			<b>Jen pro vás: <a class="registration" title="Zaregistrujte se právě teď a získáte výhody"
				href="<?php echo WEBPATH;?>/lazada/index">100 Kč a doprava zdarma na první nákup</a></b>
		</p>

		<p class="button">
			<a class="registration"
				title="Zaregistrujte se právě teď a získáte výhody"
				href="<?php echo WEBPATH;?>/lazada/index">Získat</a>
		</p>
	</div>
</div>
<div class="why" id="why">
	<div class="container">
		<h2>Proč nakupovat potraviny online?</h2>
		<ul>
			<li class="orange"><strong>Žádné fronty nebo čekání</strong> <span>Otevřeno
					máme&nbsp;nonstop</span></li>
			<li class="green"><strong>Konec tahání těžkých tašek</strong> <span>Nákup
					vyneseme až k&nbsp;vašim dveřím</span></li>
			<li class="blue"><strong>Doručení už za&nbsp;30&nbsp;minut</strong> <span>7
					dní v&nbsp;týdnu <a href="#delivery" class="scrollToWithAnimation"
					title="Doručení už za 30 minut">Více&nbsp;informací</a>
			</span></li>
			<li class="brown"><strong>Velký výběr sortimentu</strong> <span>Téměř
					4000 položek skladem</span></li>
		</ul>
	</div>
</div>

<div class="how" id="how">
	<div class="container">
		<h2>Jak to celé funguje?</h2>
		<ol>
			<li class="a">Jednoduše si naklikáte <span>nákup a odešlete
					objednávku</span></li>
			<li class="b">Na našem skladu <span>vše pečlivě zabalíme</span></li>
			<li class="c">Už za 30 minut <span>budete mít nákup u dveří</span></li>
		</ol>
	</div>
</div>
<div class="reviews">
	<div class="container">
		<p>
			Blesková rychlost, milý a ochotný kurýr, vše dopraveno v pořádku, ani
			jeden brambůrek se během přepravy nepomačkal! <i>Lenka M., facebook</i>
		</p>
	</div>
</div>
<div class="miss">
	<h2>Co z&nbsp;nabídky nesmíte minout</h2>

	<div class="slider">
		<div class="slide">
			<div class="img">
				<img
					src="<?php echo ROHLIK_LANGDINGPAGE; ?>/images/landingpage/v1/extra/pecivo.png"
					alt="Teplé a čerstvé pečivo celý den">
			</div>
			<div class="text">
				<h3>Teplé a&nbsp;čerstvé pečivo celý den</h3>

				<p>Pokud si objednáte pečivo “právě rozpečeno”, připravíme ho přímo
					pro vás a&nbsp;dorazí ještě teplé. Kdykoli po celý den.</p>

				<p>Zbylé pečivo odebíráme z&nbsp;malé pekárny PAC Hořovice.</p>
				<h6>
					<a title="Zobrazit nabídku pečiva" href="<?php echo WEBPATH?>/apotraviny/index">Zobrazit nabídku pečiva</a>
				</h6>
			</div>
		</div>
	</div>
</div>
<div class="delivery" id="delivery">
	<div class="container">
		<h2>Doprava a&nbsp;platba</h2>

		<div class="item green">
			<h3>
				Nákup dovezeme už za <b>30 minut</b>
			</h3>

			<div class="text">
				<p>Pokud si ho objednáte mezi 8.30 a&nbsp;21.30, dovezeme vám nákup
					do 30&nbsp;minut.</p>

				<p>Nebo si můžete zvolit jakýkoli čas až několik dní dopředu.</p>
			</div>
		</div>
		<div class="item blue">
			<h3>
				O nákup se <b>staráme</b>
			</h3>

			<div class="text">
				<p>Vše je v&nbsp;taškách pečlivě roztříděné a&nbsp;uložené tak, aby
					nedošlo k&nbsp;žádnému poškození během přepravy.</p>

				<p>Kurýr nákup doručí až ke dveřím do bytu a&nbsp;projde ho
					s&nbsp;vámi.</p>
			</div>
		</div>
		<div class="item orange">
			<h3>
				Zaplatit můžete až <b>za 14 dní</b>
			</h3>

			<div class="text">
				<p>
					Za svůj nákup můžete zaplatit <strong>hotově</strong> kurýrovi, <strong>kartou</strong>
					online nebo až za 14 dní kartou či převodem.
				</p>

				<p>Teď už vyzkoušení Rohlíku vážně nic nebrání!</p>
			</div>
		</div>
		<div class="item brown">
			<h3>
				Co stojí a&nbsp;kam vozí <b>doprava</b>
			</h3>

			<div class="text">
				<p>
					Nákup vám dovezeme <strong>od 0 do 99 Kč</strong> podle výše
					objednávky, času doručení a místa, kam ho povezeme.
				</p>

				<p>
					V tuto chvíli rozvážíme v&nbsp;Praze. Přesnou cenu dopravy
					a&nbsp;ověření, jestli vám budeme moci nákup doručit, zjístíte na <a
						title="Cena dopravy, rozvoz" href="#">této stránce</a>.
				</p>
			</div>
		</div>
	</div>
</div>
<div class="money" id="guarantee">
	<div class="container">
		<h3>Pokud nebudete spokojeni, vrátíme vám peníze</h3>

		<p>Naše zákaznická linka, email nebo živý chat jsou dostupné během
			celé rozvážkové doby a&nbsp;připraveny řešit vaše problémy.</p>

		<p>Pokud bude s nákupem něco špatně, problém rychle vyřešíme
			a&nbsp;vrátíme vám peníze.</p>
		<img
			src="<?php echo ROHLIK_LANGDINGPAGE; ?>/images/landingpage/v1/garance-spokojenosti.png"
			alt="Garance spokojenosti">
	</div>
</div>
<div class="recipes">
	<div class="container">
		<h3>Desítky skvělých receptů</h3>

		<p>
			Několik desítek skvělých receptů od známých českých foodblogerů. <span>Na
				všechny nakoupíte pár kliknutími.</span>
		</p>

		<p class="button">
			<a title="Přejít na recepty" href="#">Přejít na recepty</a>
		</p>
	</div>
	<div class="bg">
		<span></span>
	</div>
</div>
<div class="easy">
	<div class="container">
		<h3>Začněte žít jednodušší život</h3>
		<h6>
			<a title="Vyrazit do obchodu"
				href="<?php echo WEBPATH;?>/lazada/index">Vyrazit do obchodu</a>
		</h6>
	</div>
</div>

<div class="bigVideo">
	<div class="video">
		<div class="relative">
			<iframe id="videoPlayer" width="920" height="518" src=""
				frameborder="0" allowfullscreen></iframe>

			<a class="close" href="javascript:;">&times;</a>
		</div>
	</div>
</div>

<div class="overlay black"></div>

<div id="snippet-popupControl-popup">
	<div id="registrationLightbox" class="popup registration dontShow">
		<a href="javascript:;" class="close hide" title="zavřít">&times;</a>

		<div class="content">
			<div class="head">
				<h2>100&nbsp;Kč na nákup a doprava zdarma</h2>
				<p>Zaregistrujte se právě teď a získáte 100&nbsp;Kč a dopravu zdarma
					na první objednávku</p>
			</div>

			<div class="cols">
				<div class="col" id="snippet-popupControl-registration">
					<div id="snippet-popupControl-registration-">
						<h3>Registrace přes e-mail</h3>
						<div class="box overlay-on-ajax">
							<div id="snippet-popupControl-registration-flashMessages"></div>
							<form class="ajax" action="/vitejte" method="post"
								novalidate="novalidate"
								id="frm-popupControl-registration-registrationForm"
								data-name="popupControl-registration-registrationForm">
								<label
									for="frm-popupControl-registration-registrationForm-email"><input
									type="email" name="email" placeholder="E-mail" title="E-mail"
									id="frm-popupControl-registration-registrationForm-email"
									required
									data-nette-rules='[{"op":":filled","msg":"Pole \"E-mail\" je povinné."},{"op":":email","msg":"Pole \"E-mail\" neobsahuje platný e-mail."}]'
									class="email"></label> <label
									for="frm-popupControl-registration-registrationForm-password"><input
									type="password" name="password" autocomplete="off"
									placeholder="Heslo" title="Heslo"
									id="frm-popupControl-registration-registrationForm-password"
									required
									data-nette-rules='[{"op":":filled","msg":"Pole \"Heslo\" je povinné."},{"op":":minLength","msg":"Pole \"Heslo\" musí mít minimální délku 4 znaky.","arg":4}]'
									class="password"></label> <label
									for="frm-popupControl-registration-registrationForm-phone"><input
									type="tel" name="phone" placeholder="Telefon" title="Telefon"
									id="frm-popupControl-registration-registrationForm-phone"
									required
									data-nette-rules='[{"op":":filled","msg":"Pole \"Telefon\" je povinné."},{"op":":filled","rules":[{"op":"Damejidlo\\Forms\\BaseForm::checkPhoneNumber","msg":"V telefonním čísle (%value) u položky „Telefon“ máte nějaký překlep, zadejte ho ve správném formátu prosím (+420 777 888 999)."}],"control":"phone"}]'
									class="phone"></label><br>
								<button type="submit" name="_submit" value="Zaregistrovat se">Pokračovat</button>
								<input type="hidden" name="do"
									value="popupControl-registration-registrationForm-submit">
							</form>
							<p>V příštím kroku ověříme váš telefon</p>
						</div>
					</div>
				</div>
				<div class="col snd">
					<h3>Registrace přes Facebook</h3>

					<div class="box">
						<p class="fb">
							<a
								href="<?php echo ROHLIK_LANGDINGPAGE; ?>/homepage/facebook-login"
								title="Zaregistrovat přes Facebook">Zaregistrovat přes facebook</a>
						</p>

						<p>V příštím kroku ověříme váš telefon</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-65717071-1', 'auto');
  ga('send', 'pageview');

</script>