<div class="pageheader">
    <h2 class="title-admin"><i class="glyphicon glyphicon-user"></i> Status Edit Contact</h2>
</div>
<div class="content">
<?php if(isset($check)&&$check==1){echo '<div class="alert alert-success" role="alert">Status Edit Contact succcess.</div>';}?>
<?php if(isset($check)&&$check==0){echo '<div class="alert alert-danger" role="alert">Status Edit Contact failed.</div>';}?>
</div>    