<?php echo $this->doctype(); ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Smije Responsive AloThemes Fashion</title>
<meta name="viewport"
	content="width=device-width, initial-scale=1, maximum-scale=1" />
<meta name="description" content="Default Description" />
<meta name="keywords" content="Magento, Varien, E-commerce" />
<meta name="robots" content="INDEX,FOLLOW" />
<link rel="icon"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/favicon.ico"
	type="image/x-icon" />
<link rel="shortcut icon"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/favicon.ico"
	type="image/x-icon" />
	

	
	
<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo BAG_REAL_HTML; ?>/smije/js/blank.html';
    var BLANK_IMG = '<?php echo BAG_REAL_HTML; ?>/smije/js/spacer.gif';
//]]>
</script>
<![endif]-->
<link
	href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900'
	rel='stylesheet' type='text/css' />
<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700'
	rel='stylesheet' type='text/css' />
<link
	href='http://fonts.googleapis.com/css?family=Roboto:400,100italic,100,300,300italic,400italic,500,500italic,700,700italic,900,900italic'
	rel='stylesheet' type='text/css' />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/js/calendar/calendar-win2k-1.css" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/magiccart/plugin/fontawesome/css/font-awesome.min.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/magiccart/plugin/css/bootstrap/bootstrap.min.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/magiccart/plugin/css/flexisel.hack.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/css/styles.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/base/default/css/widgets.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/magiccart/blog/css/blog.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/magiccart/magicmenu/css/magicmenu.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/magiccart/magicshop/css/ajaxcart.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/magiccart/magicslider/css/iview.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/magiccart/magicslider/css/style.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/magiccart/magicsocial/css/magicsocial.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/magiccart/plugin/css/jquery.fancybox-1.3.4.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/magiccart/plugin/css/animate.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/magiccart/magicshop/css/quickview.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/css/print.css"
	media="print" />
<script type="text/javascript"
	src="<?php echo BAG_REAL_HTML; ?>/smije/media/js/3ab2ed8946de7c8e38c92d7019e570ed.js"></script>
<link href="<?php echo BAG_REAL_HTML; ?>/store_id_4.xml" title="Blog" rel="alternate" type="application/rss+xml" />
<!--[if lt IE 9]>
<script type="text/javascript" src="<?php echo BAG_REAL_HTML; ?>/smije/media/js/20c96fd37f0b6d1653065f79884b33b7.js"></script>
<![endif]-->
<!--[if lt IE 8]>
<link rel="stylesheet" type="text/css" href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/css/styles-ie.css" media="all" />
<![endif]-->
<!--[if lt IE 7]>
<script type="text/javascript" src="<?php echo BAG_REAL_HTML; ?>/smije/media/js/431482b026b7ce7b6c58e1c2f5f6a7a7.js"></script>
<![endif]-->
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/css/responsive.css"
	media="all" />

	
	<!-- drag -->
	    <style type="text/css">
      img {border-width: 0}
      * {font-family:'Lucida Grande', sans-serif;}
    </style>
<link href="<?php echo BAG_REAL_HTML; ?>/css/uploadfilemulti.css" rel="stylesheet">
<!-- <script src="<?php echo BAG_REAL_HTML; ?>/js/jquery-1.8.0.min.js"></script> -->
<script>
/*!
 * jQuery Upload File Plugin
 * version: 3.1.2
 * @requires jQuery v1.5 or later & form plugin
 * Copyright (c) 2013 Ravishanker Kusuma
 * http://hayageek.com/
 */
(function(b) {
    if (b.fn.ajaxForm == undefined) {
        b.getScript("<?php echo WEBPATH?>/js/jquery.form.js")
		//http://malsup.github.io/jquery.form.js
    }
    var a = {};
    a.fileapi = b("<input type='file'/>").get(0).files !== undefined;
    a.formdata = window.FormData !== undefined;
    b.fn.uploadFile = function(t) {
        var r = b.extend({
            url: "",
            method: "POST",
            enctype: "multipart/form-data",
            formData: null,
            returnType: null,
            allowedTypes: "*",
            fileName: "file",
            formData: {},
            dynamicFormData: function() {
                return {}
            },
            maxFileSize: -1,
            maxFileCount: 10,//-1,
            multiple: true,
            dragDrop: true,
            autoSubmit: true,
            showCancel: true,
            showAbort: true,
            showDone: true,
            showDelete: false,
            showError: true,
            showStatusAfterSuccess: true,
            showStatusAfterError: true,
            showFileCounter: true,
            fileCounterStyle: "). ",
            showProgress: false,
            onSelect: function(s) {
                return true
            },
            onSubmit: function(s, u) {},
            onSuccess: function(u, s, v) {},
            onError: function(v, s, u) {},
            deleteCallback: false,
            afterUploadAll: false,
            uploadButtonClass: "upload",
            dragDropStr: "<span><b>Drag &amp; Drop Files</b></span>",
            abortStr: "Abort",
            cancelStr: "Cancel",
            deletelStr: "Delete",
            doneStr: "Done",
            multiDragErrorStr: "Multiple File Drag &amp; Drop is not allowed.",
            extErrorStr: "is not allowed. Allowed extensions: ",
            sizeErrorStr: "is not allowed. Allowed Max size: ",
            uploadErrorStr: "Upload is not allowed",
            maxFileCountErrorStr: " is not allowed. Maximum allowed files are:"
        }, t);
        this.fileCounter = 1;
        this.selectedFiles = 0;
        this.fCounter = 0;
        this.sCounter = 0;
        this.tCounter = 0;
        var d = "upload-" + (new Date().getTime());
        this.formGroup = d;
        this.hide();
        this.errorLog = b("<div></div>");
        this.after(this.errorLog);
        this.responses = [];
        if (!a.formdata) {
            r.dragDrop = false
        }
        if (!a.formdata) {
            r.multiple = false
        }
        var m = this;
        var e = b("<div>" + b(this).html() + "</div>");
        b(e).addClass(r.uploadButtonClass);
        (function k() {
            if (b.fn.ajaxForm) {
                if (r.dragDrop) {
                    var s = b('<div class="ajax-upload-dragdrop" style="vertical-align:top;"></div>');
                    b(m).before(s);
                    b(s).append(e);
                    b(s).append(b(r.dragDropStr));
                    f(m, r, s)
                } else {
                    b(m).before(e)
                }
                q(m, d, r, e)
            } else {
                window.setTimeout(k, 10)
            }
        })();
        this.startUpload = function() {
            b("." + this.formGroup).each(function(u, s) {
                if (b(this).is("form")) {
                    b(this).submit()
                }
            })
        };
        this.stopUpload = function() {
            b(".upload-red").each(function(u, s) {
                if (b(this).hasClass(m.formGroup)) {
                    b(this).click()
                }
            })
        };
        this.getResponses = function() {
            return this.responses
        };
        var g = false;

        function j() {
            if (r.afterUploadAll && !g) {
                g = true;
                (function s() {
                    if (m.sCounter != 0 && (m.sCounter + m.fCounter == m.tCounter)) {
                        r.afterUploadAll(m);
                        g = false
                    } else {
                        window.setTimeout(s, 100)
                    }
                })()
            }
        }

        function f(w, u, v) {
            v.on("dragenter", function(s) {
                s.stopPropagation();
                s.preventDefault();
                b(this).css("border", "2px solid #000000")
            });
            v.on("dragover", function(s) {
                s.stopPropagation();
                s.preventDefault()
            });
            v.on("drop", function(x) {
                b(this).css("border", "2px solid #000000");
                x.preventDefault();
                w.errorLog.html("");
                var s = x.originalEvent.dataTransfer.files;
                if (!u.multiple && s.length > 1) {
                    if (u.showError) {
                        b("<div style='color:red;'>" + u.multiDragErrorStr + "</div>").appendTo(w.errorLog)
                    }
                    return
                }
                if (u.onSelect(s) == false) {
                    return
                }
                l(u, w, s)
            });
            b(document).on("dragenter", function(s) {
                s.stopPropagation();
                s.preventDefault()
            });
            b(document).on("dragover", function(s) {
                s.stopPropagation();
                s.preventDefault();
                v.css("border", "2px solid #000000")
            });
            b(document).on("drop", function(s) {
                s.stopPropagation();
                s.preventDefault();
                v.css("border", "2px solid #000000")
            })
        }

        function i(s) {
            var v = "";
            var u = s / 1024;
            if (parseInt(u) > 1024) {
                var w = u / 1024;
                v = w.toFixed(2) + " MB"
            } else {
                v = u.toFixed(2) + " KB"
            }
            return v
        }

        function o(x) {
            var y = [];
            if (jQuery.type(x) == "string") {
                y = x.split("&")
            } else {
                y = b.param(x).split("&")
            }
            var u = y.length;
            var s = [];
            var w, v;
            for (w = 0; w < u; w++) {
                y[w] = y[w].replace(/\+/g, " ");
                v = y[w].split("=");
                s.push([decodeURIComponent(v[0]), decodeURIComponent(v[1])])
            }
            return s
        }

        function l(H, B, u) {
            for (var C = 0; C < u.length; C++) {
                if (!c(B, H, u[C].name)) {
                    if (H.showError) {
                        b("<div style='color:red;'><b>" + u[C].name + "</b> " + H.extErrorStr + H.allowedTypes + "</div>").appendTo(B.errorLog)
                    }
                    continue
                }
                if (H.maxFileSize != -1 && u[C].size > H.maxFileSize) {
                    if (H.showError) {
                        b("<div style='color:red;'><b>" + u[C].name + "</b> " + H.sizeErrorStr + i(H.maxFileSize) + "</div>").appendTo(B.errorLog)
                    }
                    continue
                }
                if (H.maxFileCount != -1 && B.selectedFiles >= H.maxFileCount) {
                    if (H.showError) {
                        b("<div style='color:red;'><b>" + u[C].name + "</b> " + H.maxFileCountErrorStr + H.maxFileCount + "</div>").appendTo(B.errorLog)
                    }
                    continue
                }
                B.selectedFiles++;
                var D = H;
                var w = new FormData();
                var A = H.fileName.replace("[]", "");
                w.append(A, u[C]);
                var y = H.formData;
                if (y) {
                    var F = o(y);
                    for (var z = 0; z < F.length; z++) {
                        if (F[z]) {
                            w.append(F[z][0], F[z][1])
                        }
                    }
                }
                D.fileData = w;
                var E = new p(B, H);
                var G = "";
                if (H.showFileCounter) {
                    G = B.fileCounter + H.fileCounterStyle + u[C].name
                } else {
                    G = u[C].name
                }
                E.filename.html(G);
                var v = b("<form style='display:block; position:absolute;left: 150px;' class='" + B.formGroup + "' method='" + H.method + "' action='" + H.url + "' enctype='" + H.enctype + "'></form>");
                v.appendTo("body");
                var x = [];
                x.push(u[C].name);
                n(v, D, E, x, B);
                B.fileCounter++
            }
        }

        function c(w, v, y) {
            var x = v.allowedTypes.toLowerCase().split(",");
            var u = y.split(".").pop().toLowerCase();
            if (v.allowedTypes != "*" && jQuery.inArray(u, x) < 0) {
                return false
            }
            return true
        }

        function h(u, w) {
            if (u.showFileCounter) {
                var v = b(".upload-filename").length;
                w.fileCounter = v + 1;
                b(".upload-filename").each(function(A, y) {
                    var s = b(this).html().split(u.fileCounterStyle);
                    var x = parseInt(s[0]) - 1;
                    var z = v + u.fileCounterStyle + s[1];
                    b(this).html(z);
                    v--
                })
            }
        }

        function q(y, B, D, u) {
            var A = "ajax-upload-id-" + (new Date().getTime());
            var w = b("<form method='" + D.method + "' action='" + D.url + "' enctype='" + D.enctype + "'></form>");
            var v = "<input type='file' id='" + A + "' name='" + D.fileName + "'/>";
            if (D.multiple) {
                if (D.fileName.indexOf("[]") != D.fileName.length - 2) {
                    D.fileName += "[]"
                }
                v = "<input type='file' id='" + A + "' name='" + D.fileName + "' multiple/>"
            }
            var z = b(v).appendTo(w);
            z.change(function() {
                y.errorLog.html("");
                var K = D.allowedTypes.toLowerCase().split(",");
                var G = [];
                if (this.files) {
                    for (H = 0; H < this.files.length; H++) {
                        G.push(this.files[H].name)
                    }
                    if (D.onSelect(this.files) == false) {
                        return
                    }
                } else {
                    var I = b(this).val();
                    var F = [];
                    G.push(I);
                    if (!c(y, D, I)) {
                        if (D.showError) {
                            b("<div style='color:red;'><b>" + I + "</b> " + D.extErrorStr + D.allowedTypes + "</div>").appendTo(y.errorLog)
                        }
                        return
                    }
                    F.push({
                        name: I,
                        size: "NA"
                    });
                    if (D.onSelect(F) == false) {
                        return
                    }
                }
                h(D, y);
                u.unbind("click");
                w.hide();
                q(y, B, D, u);
                w.addClass(B);
                if (a.fileapi && a.formdata) {
                    w.removeClass(B);
                    var J = this.files;
                    l(D, y, J)
                } else {
                    var E = "";
                    for (var H = 0; H < G.length; H++) {
                        if (D.showFileCounter) {
                            E += y.fileCounter + D.fileCounterStyle + G[H] + "<br>"
                        } else {
                            E += G[H] + "<br>"
                        }
                        y.fileCounter++
                    }
                    if (D.maxFileCount != -1 && (y.selectedFiles + G.length) > D.maxFileCount) {
                        if (D.showError) {
                            b("<div style='color:red;'><b>" + E + "</b> " + D.maxFileCountErrorStr + D.maxFileCount + "</div>").appendTo(y.errorLog)
                        }
                        return
                    }
                    y.selectedFiles += G.length;
                    var s = new p(y, D);
                    s.filename.html(E);
                    n(w, D, s, G, y)
                }
            });
            w.css({
                margin: 0,
                padding: 0
            });
            var C = b(u).width() + 10;
            if (C == 10) {
                C = 120
            }
            var x = u.height() + 10;
            if (x == 10) {
                x = 35
            }
            u.css({
                position: "relative",
                overflow: "hidden",
                cursor: "default"
            });
            z.css({
                position: "absolute",
                cursor: "pointer",
                top: "0px",
                width: C,
                height: x,
                left: "0px",
                "z-index": "100",
                opacity: "0.0",
                filter: "alpha(opacity=0)",
                "-ms-filter": "alpha(opacity=0)",
                "-khtml-opacity": "0.0",
                "-moz-opacity": "0.0"
            });
            w.appendTo(u)
        }

        function p(v, u) {
            this.statusbar = b("<div class='upload-statusbar'></div>");
            this.filename = b("<div class='upload-filename'></div>").appendTo(this.statusbar);
            this.progressDiv = b("<div class='upload-progress'>").appendTo(this.statusbar).hide();
            this.progressbar = b("<div class='upload-bar " + v.formGroup + "'></div>").appendTo(this.progressDiv);
            this.abort = b("<div class='upload-red " + v.formGroup + "'>" + u.abortStr + "</div>").appendTo(this.statusbar).hide();
            this.cancel = b("<div class='upload-red'>" + u.cancelStr + "</div>").appendTo(this.statusbar).hide();
            this.done = b("<div class='upload-green'>" + u.doneStr + "</div>").appendTo(this.statusbar).hide();
            this.del = b("<div class='upload-red'>" + u.deletelStr + "</div>").appendTo(this.statusbar).hide();
            v.errorLog.after(this.statusbar);
            return this
        }

        function n(z, y, u, w, A) {
            var x = null;
            var v = {
                cache: false,
                contentType: false,
                processData: false,
                forceSync: false,
                data: y.formData,
                formData: y.fileData,
                dataType: y.returnType,
                beforeSubmit: function(F, C, E) {
                    if (y.onSubmit.call(this, w) != false) {
                        var B = y.dynamicFormData();
                        if (B) {
                            var s = o(B);
                            if (s) {
                                for (var D = 0; D < s.length; D++) {
                                    if (s[D]) {
                                        if (y.fileData != undefined) {
                                            E.formData.append(s[D][0], s[D][1])
                                        } else {
                                            E.data[s[D][0]] = s[D][1]
                                        }
                                    }
                                }
                            }
                        }
                        A.tCounter += w.length;
                        j();
                        return true
                    }
                    u.statusbar.append("<div style='color:red;'>" + y.uploadErrorStr + "</div>");
                    u.cancel.show();
                    z.remove();
                    u.cancel.click(function() {
                        u.statusbar.remove()
                    });
                    return false
                },
                beforeSend: function(B, s) {
                    u.progressDiv.show();
                    u.cancel.hide();
                    u.done.hide();
                    if (y.showAbort) {
                        u.abort.show();
                        u.abort.click(function() {
                            B.abort();
                            A.selectedFiles -= w.length
                        })
                    }
                    if (!a.formdata) {
                        u.progressbar.width("5%")
                    } else {
                        u.progressbar.width("1%")
                    }
                },
                uploadProgress: function(E, s, D, C) {
                    if (C > 98) {
                        C = 98
                    }
                    var B = C + "%";
                    if (C > 1) {
                        u.progressbar.width(B)
                    }
                    if (y.showProgress) {
                        u.progressbar.html(B);
                        u.progressbar.css("text-align", "center")
                    }
                },
                success: function(B, s, C) {
                    A.responses.push(B);
                    u.progressbar.width("100%");
                    if (y.showProgress) {
                        u.progressbar.html("100%");
                        u.progressbar.css("text-align", "center")
                    }
                    u.abort.hide();
                    y.onSuccess.call(this, w, B, C);
                    if (y.showStatusAfterSuccess) {
                        if (y.showDone) {
                            u.done.show();
                            u.done.click(function() {
                                u.statusbar.hide("slow");
                                u.statusbar.remove()
                            })
                        } else {
                            u.done.hide()
                        }
                        if (y.showDelete) {
                            u.del.show();
                            u.del.click(function() {
                                u.statusbar.hide().remove();
                                if (y.deleteCallback) {
                                    y.deleteCallback.call(this, B, u)
                                }
                                A.selectedFiles -= w.length;
                                h(y, A)
                            })
                        } else {
                            u.del.hide()
                        }
                    } else {
                        u.statusbar.hide("slow");
                        u.statusbar.remove()
                    }
                    z.remove();
                    A.sCounter += w.length
                },
                error: function(C, s, B) {
                    u.abort.hide();
                    if (C.statusText == "abort") {
                        u.statusbar.hide("slow").remove();
                        h(y, A)
                    } else {
                        y.onError.call(this, w, s, B);
                        if (y.showStatusAfterError) {
                            u.progressDiv.hide();
                            u.statusbar.append("<span style='color:red;'>ERROR: " + B + "</span>")
                        } else {
                            u.statusbar.hide();
                            u.statusbar.remove()
                        }
                        A.selectedFiles -= w.length
                    }
                    z.remove();
                    A.fCounter += w.length
                }
            };
            if (y.autoSubmit) {
                z.ajaxSubmit(v)
            } else {
                if (y.showCancel) {
                    u.cancel.show();
                    u.cancel.click(function() {
                        z.remove();
                        u.statusbar.remove();
                        A.selectedFiles -= w.length;
                        h(y, A)
                    })
                }
                z.ajaxForm(v)
            }
        }
        return this
    }
}(jQuery));
</script><!-- end mutiupload form -->




	
<script type="text/javascript">
	//<![CDATA[
	Mage.Cookies.path = '/bagseshop/smije';
	Mage.Cookies.domain = '.<?php echo BAG_NO_HTTP; ?>'; 
	//]]>
</script>

<script type="text/javascript">
	//<![CDATA[
	optionalZipCountries = [ "HK", "IE", "MO", "PA" ];
	//]]>
</script>
<link rel="stylesheet" type="text/css"
	href="http://fonts.googleapis.com/css?family=Roboto" media="all" />
<style type="text/css">
*,body,h1,h2,h3,h4,h5,h6,.h1,.h2,.h3,.h4,.h5,.h6 {
	font-size: 12px;
	font-family: Roboto;
}

body {
	color: #666666;
}

body {
	background-color: transparent;
}

a {
	color: #666666;
}

a:hover {
	color: #e5685d;
}

a:active {
	color: #e5685d;
}

button.button span {
	color: #ffffff;
}

button.button span:hover {
	color: #ffffff;
}

button.button span {
	background-color: #666666;
}

button.button span:hover {
	background-color: #e5685d;
}

.labelnew {
	color: #ffffff;
}

.labelnew {
	background-color: #e5685d;
}

.labelsale {
	color: #ffffff;
}

.labelsale {
	background-color: #f9bd68;
}
</style>
<script type="text/javascript">
	Themecfg = {
		"general" : {
			"enabled" : "1",
			"jquery" : "1",
			"tooltip" : "0",
			"themecolor" : "",
			"ajaxloading" : "http:\/\/\<?php echo BAG_REAL_HTML; ?>\/smije\/skin\/frontend\/alosmije\/smije_fashion\/images\/opc-ajax-loader.gif"
		},
		"home" : {
			"portrait" : "1",
			"landscape" : "2",
			"tablet" : "3",
			"visibleItems" : "6",
			"height_images" : "250",
			"width_images" : "200"
		},
		"list" : {
			"portrait" : "1",
			"landscape" : "2",
			"tablet" : "3",
			"visibleItems" : "6",
			"margin_columns" : "10",
			"productDelay" : "500",
			"height_images" : "250",
			"width_images" : "200",
			"action" : "cart,compare,wishlist",
			"sort_name" : "asc"
		},
		"detail" : {
			"imageWidth" : "400",
			"zoomWidth" : "290",
			"zoomHeight" : "374",
			"adjustX" : "10",
			"adjustY" : "10",
			"showTitle" : "1",
			"useWrapper" : "0",
			"thumbSlide" : "vertical",
			"relatedSlide" : "vertical",
			"relatedLimit" : "10",
			"upsellSlide" : "horizontal",
			"upsellLimit" : "10",
			"inforTabs" : "1",
			"activeTab" : "box-up-sell"
		},
		"checkout" : {
			"crosssellsSlide" : "1"
		},
		"newsletter" : {
			"enabled" : "1",
			"width" : "949",
			"height" : "818",
			"overlayColor" : "#353535",
			"background_color" : "#fffaff",
			"background_image" : "stores\/4\/fashion-popup-newleter.jpg"
		}
	}
</script>
<script type="text/javascript">
	//<![CDATA[
	if (typeof MC == 'undefined')
		MC = {};
	MC.Quickview = {
		"dialogWidth" : "1000",
		"zoomWidth" : "265",
		"zoomHeight" : "265",
		"vertical" : "1"
	};

	jQuery(document)
			.ready(
					function($) {
						jQuery(document)
								.magiccart(
										{
											"url" : "<?php echo WEBPATH; ?>\/magicshop\/ajax\/index",
											"updateUrl" : "<?php echo WEBPATH; ?>\/checkout\/cart\/updatepost",
											"src_image_progress" : "\<?php echo BAG_REAL_HTML; ?>\/smije\/skin\/frontend\/alosmije\/smije_fashion\/magiccart\/magicshop\/images\/loading.gif",
											"error" : " \u2191 This is a required field.",
											"isProductView" : 0
										});
					});
	//]]
</script>

<script type="text/javascript">
	//<![CDATA[
	var Translator = new Translate([]);
	//]]>
</script>
</head>
<body class=" cms-index-index cms-home-smije-fashion">
	<div class="social-icons right" style="margin-top: 100px">
		<a class="socialitems" target="_blank" href="https://www.facebook.com"
			id="facebook-btn"> <span class="social-icon"> <span
				class="social-text">Follow via Facebook</span>
		</span>
		</a> <a class="socialitems" target="_blank"
			href="https://www.twitter.com" id="twitter-btn"> <span
			class="social-icon"> <span class="social-text">Follow via Twitter</span>
		</span>
		</a> <a class="socialitems" target="_blank"
			href="https://www.plus.google.com" id="googleplus-btn"> <span
			class="social-icon"> <span class="social-text">Follow via Google +</span>
		</span>
		</a> <a class="socialitems" target="_blank"
			href="https://www.youtube.com" id="youtube-btn"> <span
			class="social-icon"> <span class="social-text">Follow via Youtube</span>
		</span>
		</a> <a class="socialitems" target="_blank"
			href="https://www.pinterest.com/" id="pinterest-btn"> <span
			class="social-icon"> <span class="social-text">Follow via Pinterest</span>
		</span>
		</a> <a class="socialitems" target="_blank"
			href="mailto:support@alothemes.com" id="mail-btn"> <span
			class="social-icon"> <span class="social-text">Mail To</span>
		</span>
		</a>
	</div>

	<script type="text/javascript">
		jQuery(document).ready(function($) {
			$('.social-icons .social-icon').mouseenter(function() {
				$(this).stop();
				$(this).animate({
					width : '160'
				}, 500, 'swing', function() {
				});
			});
			$('.social-icons .social-icon').mouseleave(function() {
				$(this).stop();
				$(this).animate({
					width : '43'
				}, 500, 'swing', function() {
				});
			});
		});
	</script>
	<div class="wrapper">
		<noscript>
			<div class="global-site-notice noscript">
				<div class="notice-inner">
					<p>
						<strong>JavaScript seems to be disabled in your browser.</strong><br />
						You must have JavaScript enabled in your browser to utilize the
						functionality of this website.
					</p>
				</div>
			</div>
		</noscript>
		<div class="page">
			<div class="header-container">
				<div class="header">
					<div class="header-top">
						<div class="container">
							<div class="main">
								<div class="row">
									<div
										class="header-block1 col-lg-8 col-md-8 col-sm-8 col-xs-12 pull-left">
										<div class="box-support">
											<ul>
												<li class="first">
													<div class="box-phone">
														<span class="pull-left"><em class="fa fa-phone">&nbsp;</em></span>
														<div class="media-body pull-left">
															<p>(+800) 123 456 7890</p>
														</div>
													</div>
												</li>
												<li class="last">
													<div class="box-email">
														<span class="pull-left"><em class="fa fa-envelope">&nbsp;</em></span>
														<div class="media-body pull-left">
															<p>
																<a href="mailto:support@alothemes.com">support@alothemes.com</a>
															</p>
														</div>
													</div>
												</li>
											</ul>
										</div>
									</div>
									<div
										class="header-top-left col-lg-4 col-md-4 col-sm-4 col-xs-12 pull-right">
										<div class="top-form-language">

											<div class="lang-switcher">
												<div class="dropdown-toggle">
													<div>
														<div class="label dropdown-icon flag"
															style="background-image: url(<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/images/flags/english_fashion.png)">&nbsp;</div>
														<div class="value">English</div>
														<div class="caret">&nbsp;</div>
													</div>
												</div>
												<ul class="dropdown-switcher">
													<li class="current"><span class="label dropdown-icon"
														style="background-image: url(<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/images/flags/english_fashion.png);">&nbsp;</span>English</li>
													<li><a
														href="<?php echo WEBPATH;?>/?___store=french_fashion&amp;___from_store=english_fashion"><span
															class="label dropdown-icon"
															style="background-image: url(<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/images/flags/french_fashion.png);">&nbsp;</span>French</a></li>
												</ul>
											</div>
										</div>
										<div class="currency_top">


											<div class="currency-switcher">
												<div class="dropdown-toggle cover">
													<div>
														<div class="label">Currency:</div>
														<div class="value">USD</div>
														<div class="caret">&nbsp;</div>
													</div>
												</div>
												<ul class="dropdown-switcher">
													<li><a
														href="<?php echo WEBPATH;?>/directory/currency/switch/currency/EUR/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvP19fX3N0b3JlPWVuZ2xpc2hfZmFzaGlvbg,,/">EUR
															- Euro</a></li>
													<li class="current">USD - US Dollar</li>
												</ul>
											</div>
										</div>

										<!--<p class="welcome-msg"> </p>-->
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="header-content">
						<div class="container">
							<div class="main">
								<div class="row">
									<div class="inner-box clearfix">
										<div
											class="header-content-left col-lg-3 col-md-3 col-sm-3 col-xs-12">
											<a href="<?php echo WEBPATH;?>/" title="Smije ALO Themes "
												class="logo"><strong>Smije ALO Themes </strong><img
												class="img-responsive"
												src="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/images/logo.png"
												alt="Smije ALO Themes " /></a>
										</div>
										<div
											class="header-content-right col-lg-9 col-md-9 col-sm-9 col-xs-12">
											<div class="header-content-top clearfix">
												<div class="header-top-right pull-right">
													<ul class="links">
														<li class="first"><a href="<?php echo WEBPATH;?>/wishlist"
															title="My Wishlist">My Wishlist</a></li>
														<li><a href="<?php echo WEBPATH;?>/checkout"
															title="Checkout" class="top-link-checkout">Checkout</a></li>
														<li><a href="<?php echo WEBPATH;?>/blog.html" title="Blog">Blog</a></li>
														<li><a href="<?php echo WEBPATH;?>/testimonial"
															title="Testimonial">Testimonial</a></li>
														<li class=" last"><a href="<?php echo WEBPATH;?>/login/"
															title="Log In">Log In</a></li>
													</ul>
													<div class="miniCartWrap">
														<!--  
														<div class="mini-maincart">
															<div class="cartSummary">
																<span class="icon-cart">Cart:</span> <span class="zero">0
																	item -</span> <span><span class="price">$0.00</span></span>
															</div>
															<div class="mini-contentCart" style="display: none">
																<div class="block-content">
																	<p class="empty">You have no items in your shopping
																		cart.</p>
																</div>

															</div>
														</div>
														-->
														<div class="mini-maincart">
															<div class="cartSummary">
																<span class="icon-cart">Cart:</span> <span class="item">2
																	item(s) -</span> <span><span class="price">$641.00</span></span>
															</div>
															<div class="mini-contentCart" style="display: none;">
																<div class="block-content">
																	<p class="block-subtitle">Recently added item(s)</p>
																	<ol id="cart-sidebar"
																		class="mini-products-list clearfix">
																		<li class="item odd"><a
																			href="http://alothemes.com/demo/smije/index.php/roller-suitcase.html"
																			title="Roller Suitcase" class="product-image"><img
																				src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/thumbnail/200x250/9df78eab33525d08d6e5fb8d27136e95/1/7/17_2.jpg"
																				width="79" height="86" alt="Roller Suitcase"></a>
																			<div class="product-details">
																				<p class="product-name">
																					<a
																						href="http://alothemes.com/demo/smije/index.php/roller-suitcase.html">Roller
																						Suitcase</a>
																				</p>

																				<strong>1</strong> x <span class="price">$456.00</span>


																				<div class="clearfix">
																					<a
																						href="http://alothemes.com/demo/smije/index.php/checkout/cart/configure/id/294/"
																						title="Edit item" class="btn-edit">Edit item</a> <a
																						href="http://alothemes.com/demo/smije/index.php/checkout/cart/delete/id/294/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvY3VzdG9tZXIvYWNjb3VudC9mb3Jnb3RwYXNzd29yZC8,/"
																						title="Remove This Item"
																						onclick="return confirm('Are you sure you would like to remove this item from the shopping cart?');"
																						class="btn-remove btn-remove2">Remove This Item</a>
																				</div>
																			</div></li>
																		<li class="item last even"><a
																			href="http://alothemes.com/demo/smije/index.php/plaid-cotton-shirt.html"
																			title="Plaid Cotton Shirt" class="product-image"><img
																				src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/thumbnail/200x250/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1.jpg"
																				width="79" height="86" alt="Plaid Cotton Shirt"></a>
																			<div class="product-details">
																				<p class="product-name">
																					<a
																						href="http://alothemes.com/demo/smije/index.php/plaid-cotton-shirt.html">Plaid
																						Cotton Shirt</a>
																				</p>

																				<strong>1</strong> x <span class="price">$185.00</span>


																				<div class="clearfix">
																					<a
																						href="http://alothemes.com/demo/smije/index.php/checkout/cart/configure/id/293/"
																						title="Edit item" class="btn-edit">Edit item</a> <a
																						href="http://alothemes.com/demo/smije/index.php/checkout/cart/delete/id/293/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvY3VzdG9tZXIvYWNjb3VudC9mb3Jnb3RwYXNzd29yZC8,/"
																						title="Remove This Item"
																						onclick="return confirm('Are you sure you would like to remove this item from the shopping cart?');"
																						class="btn-remove btn-remove2">Remove This Item</a>
																				</div>
																			</div></li>
																	</ol>
																	<p class="subtotal">
																		<span class="label">Cart Subtotal:</span> <span
																			class="price">$641.00</span>
																	</p>
																	<div class="actions">
																		<a
																			href="http://alothemes.com/demo/smije/index.php/checkout/cart/"
																			class="view-cart"> View cart </a> <a
																			href="http://alothemes.com/demo/smije/index.php/checkout/onepage/">Checkout</a>
																	</div>
																	<script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
																</div>


															</div>
														</div>

													</div>
												</div>
											</div>
											<div class="header-content-block clearfix">
												<div class="header-block2">
													<div class="alo-support">
														<div class="support">
															<div
																class="box-services box-services1 col-lg-4 col-md-4 col-sm-4 col-xs-12">
																<span class="pull-left"><em class="fa fa-truck">&nbsp;</em></span>
																<div class="media-body">
																	<h3>WORLD DELIVERY</h3>
																	<small>Free delivery on all store items</small>
																</div>
															</div>
															<div
																class="box-services col-lg-4 col-md-4 col-sm-4 col-xs-12">
																<span class="pull-left"><em class="fa fa-refresh">&nbsp;</em></span>
																<div class="media-body">
																	<h3>Return &amp; Exchange</h3>
																	<small>30 Days money back</small>
																</div>
															</div>
															<div
																class="box-services col-lg-4 col-md-4 col-sm-4 col-xs-12">
																<span class="pull-left"><em class="fa fa-phone">&nbsp;</em></span>
																<div class="media-body">
																	<h3>Online Support</h3>
																	<small>(+800) 0123 456 789</small>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
										<div class="box-inner clearfix"></div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="header-bottom clearfix">
						<div class="container custom-menu">
							<div class="main">

								<div class="magicmenu">
									<ul class="nav-desktop ">
										<li class="level0 home"><a class="level-top"
											href="<?php echo WEBPATH;?>"><span
												class="icon-home fa fa-home"></span><span class="icon-text">Home</span><span
												class="short_desc">Lorem ipsum dolor</span> </a>
												<!--  
												<div class="level-top-mega">
													<div>
														<a href="<?php echo WEBPATH;?>"><span class="demo-home">Digital
																Store</span></a>
													</div>
													<div>
														<a href="<?php echo WEBPATH;?>"><span class="demo-home">Fashion
																Store</span></a>
													</div>
													<div>
														<a href="<?php echo WEBPATH;?>"><span class="demo-home">Furniture
																Store</span></a>
													</div>
												</div>
												-->
											</li>
										<li class='level0 ext  first'><a class="level-top"
											href="<?php echo WEBPATH; ?>/newproduct">NEW ARRIVALS <span
												class="short_desc">Commodo consequat</span>
										</a>
											<div class="level-top-mega">
												<div class="caret-down caret-down1">&nbsp;</div>
												<div class="menuextra clearfix">
													<div class="cutom-top menu-extra cutom-hot">
														<div class="banner-inner banner-inner1">
															<a href="#"> <img class="img-responsive"
																src="<?php echo BAG_REAL_HTML; ?>/smije/media/wysiwyg/alothemes/static/img-new.jpg"
																alt="NEW ARRIVALS" />
															</a>
															<div class="block-custom block-custom1">
																<h3>NEW ARRIVAL !</h3>
																<span class="before">&nbsp;</span>
																<h2>SMILE OUTLET WINTER</h2>
																<h2>COLLECTIONS</h2>
																<p>Get a new look with us !</p>
																<a class="view-more" href="#">View more</a>
															</div>
														</div>
													</div>
												</div>
											</div></li>
										<li class='level0 ext  '><a class="level-top"
											href="<?php echo WEBPATH; ?>/bestsellers">Bestsellers <span
												class="cat_label Hot">Hot</span><span class="short_desc">Ullamco
													laboris nisi</span>
										</a></li>
										<li class='level0 ext  '><a class="level-top"
											href="<?php echo WEBPATH; ?>/saleproduct">Hotsale <span
												class="short_desc">Duis aute maizi irur</span>
										</a>
											<div class="level-top-mega">
												<div class="caret-down caret-down2">&nbsp;</div>
												<div class="menuextra menuextra2 clearfix">
													<div class="cutom-top menu-extra cutom-hot">
														<div class="banner-inner banner-inner2">
															<a href="#"> <img class="img-responsive"
																src="<?php echo BAG_REAL_HTML; ?>/smije/media/wysiwyg/alothemes/static/fashion_menu_hot.jpg"
																alt="Hot Sale" />
															</a>
															<div class="block-custom block-custom1">
																<h3>HOT SALE ITEMS!</h3>
																<span class="before">&nbsp;</span>
																<h2>
																	GET 25% OFF <br />FIRST PURCHASE
																</h2>
																<p>Free Delivery world wide</p>
																<a class="view-more" href="#">View more</a>
															</div>
														</div>
													</div>
												</div>
											</div></li>
										<li class='level0 ext  '><a class="level-top"
											href="<?php echo WEBPATH;?>">Extra Menu <span
												class="short_desc">Zin reprehen voluptate</span>
										</a>
											<div class="level-top-mega">
												<div class="caret-down caret-down3">&nbsp;</div>
												<div class="custom-width clearfix">
													<div class="cutom-top menu-extra custommenu">
														<div class="banner-inner banner-inner1">
															<div class="block-custom block-custom11">
																<h3>SAMPLE MENU TITLE</h3>
																<ul class="nav-desktop nav-desktop-custom">
																	<li class="level0 level0-custom first"><a
																		class="level-top" href="#">Lorem ipsum dolor</a></li>
																	<li class="level0 level0-custom"><a class="level-top"
																		href="#">Sit amet</a></li>
																	<li class="level0 level0-custom"><a class="level-top"
																		href="#">Consectetur<span class="cat_label new">New</span></a></li>
																	<li class="level0 level0-custom"><a class="level-top"
																		href="#">Adipisicing elit</a></li>
																	<li class="level0 level0-custom"><a class="level-top"
																		href="#">Do eiusmod tempor</a></li>
																	<li class="level0 level0-custom"><a class="level-top"
																		href="#">Consectetur</a></li>
																	<li class="level0 level0-custom"><a class="level-top"
																		href="#">Sit amet</a></li>
																	<li class="level0 level0-custom"><a class="level-top"
																		href="#">Adipisicing elit<span class="cat_label Hot">Hot</span></a></li>
																	<li class="level0 level0-custom"><a class="level-top"
																		href="#">Do eiusmod tempor</a></li>
																	<li class="level0 level0-custom"><a class="level-top"
																		href="#">Adipisicing elit</a></li>
																	<li class="level0 level0-custom"><a class="level-top"
																		href="#">Do eiusmod tempor<span class="cat_label Hot">Hot</span></a></li>
																	<li class="level0 level0-custom"><a class="level-top"
																		href="#">Consectetur</a></li>
																	<li class="level0 level0-custom view-more"><a
																		class="level-top" href="#">More <em
																			class="fa fa-arrow-circle-right">&nbsp;</em>
																	</a></li>
																</ul>
															</div>
														</div>
														<div class="banner-inner banner-inner2">
															<div class="block-custom block-custom21">
																<a href="#"> <img class="img-responsive"
																	src="<?php echo BAG_REAL_HTML; ?>/smije/media/wysiwyg/alothemes/static/fashion_custom1.jpg"
																	alt="SAMPLE TITLE" />
																</a>
																<div class="text-banner-menu text-banner-menu-1">
																	<h2>CUSTOM BLOCK</h2>
																	<span class="border-bottom">&nbsp;</span>
																</div>
															</div>
														</div>
														<div class="banner-inner banner-inner3">
															<div class="block-custom block-custom31">
																<a href="#"> <img class="img-responsive"
																	src="<?php echo BAG_REAL_HTML; ?>/smije/media/wysiwyg/alothemes/static/fashion_custom2.jpg"
																	alt="SAMPLE TITLE" />
																</a>
																<div class="text-banner-menu text-banner-menu-2">
																	<h2>SAMPLE TITLE</h2>
																	<span class="border-bottom">&nbsp;</span>
																</div>
															</div>
															<div class="block-custom block-custom32">
																<a href="#"> <img class="img-responsive"
																	src="<?php echo BAG_REAL_HTML; ?>/smije/media/wysiwyg/alothemes/static/fashion_custom3.jpg"
																	alt="SAMPLE TITLE" />
																</a>
																<div class="text-banner-menu text-banner-menu-3">
																	<h2>SAMPLE TITLE</h2>
																	<span class="border-bottom">&nbsp;</span>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div></li>
										<li class='level0 ext  last'><a class="level-top"
											href="<?php echo WEBPATH; ?>/blog.html">Blog <span
												class="short_desc">ALO Themes</span>
										</a></li>
									</ul>
								</div>
								<div class="nav-mobile">
									<h3 class="mobi-title">Categories</h3>
									<ul>
										<li class="level-top"><a class="level-top"
											href="<?php echo WEBPATH;?>/accessories"><span>Accessories </span>
										</a>
											<ul>
												<li><a href="<?php echo WEBPATH;?>/accessories/shop-by.html">Shop
														By <span class="cat_label New">New</span>
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/shop-by/new-arrivals.html">New
																Arrivals </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/shop-by/christmas-gifting.html">Christmas
																Gifting </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/shop-by/workwear.html">Workwear
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/shop-by/brands.html">Brands
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/shop-by/surf-skate.html">Surf
																& Skate </a></li>
													</ul></li>
												<li><a
													href="<?php echo WEBPATH;?>/accessories/clothing.html">Clothing
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/clothing/dresses.html">Dresses
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/clothing/tops.html">Tops
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/clothing/skirts.html">Skirts
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/clothing/swimwear.html">Swimwear
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/clothing/shorts.html">Shorts
														</a></li>
													</ul></li>
												<li><a href="<?php echo WEBPATH;?>/accessories/shoes.html">Shoes
														<span class="cat_label Hot !">Hot !</span>
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/shoes/heels.html">Heels
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/shoes/sandals.html">Sandals
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/shoes/flats.html">Flats
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/shoes/ankle-boots.html">Ankle
																Boots </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/shoes/sneakers.html">Sneakers
														</a></li>
													</ul></li>
												<li><a href="<?php echo WEBPATH;?>/accessories/beauty.html">Beauty
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/beauty/perfume.html">Perfume
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/beauty/make-up.html">Make
																Up </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/beauty/hands-feet.html">Hands
																& Feet </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/beauty/face.html">Face
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/beauty/body.html">Body
														</a></li>
													</ul></li>
												<li><a href="<?php echo WEBPATH;?>/accessories/sports.html">Sports
														<span class="cat_label New">New</span>
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/sports/sports-bras.html">Sports
																Bras </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/sports/sports-tights.html">Sports
																Tights </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/sports/sports-shorts.html">Sports
																Shorts </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/sports/sports-tops.html">Sports
																Tops </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/sports/sports-hoodies.html">Sports
																Hoodies </a></li>
													</ul></li>
												<li><a
													href="<?php echo WEBPATH;?>/accessories/newest-collection.html">Newest
														Collection </a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/newest-collection/christmas-shop.html">Christmas
																shop </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/newest-collection/movember.html">Movember
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/newest-collection/woodlanders.html">Woodlanders
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/newest-collection/tv-advert.html">Tv
																Advert </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/newest-collection/partywear.html">Partywear
														</a></li>
													</ul></li>
											</ul></li>
										<li class="level-top"><a class="level-top"
											href="<?php echo WEBPATH;?>/shirts.html"><span>Shirts </span></a></li>
										<li class="level-top"><a class="level-top"
											href="<?php echo WEBPATH;?>/tops.html"><span>Tops </span></a>
											<ul>
												<li><a href="<?php echo WEBPATH;?>/tops/shop-by.html">Shop
														By <span class="cat_label New">New</span>
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/shop-by/new-arrivals.html">New
																Arrivals </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/shop-by/christmas-gifting.html">Christmas
																Gifting </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/shop-by/workwear.html">Workwear
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/shop-by/brands.html">Brands
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/shop-by/surf-skate.html">Surf
																& Skate </a></li>
													</ul></li>
												<li><a href="<?php echo WEBPATH;?>/tops/clothing.html">Clothing
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/clothing/dresses.html">Dresses
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/clothing/tops.html">Tops
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/clothing/skirts.html">Skirts
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/clothing/swimwear.html">Swimwear
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/clothing/shorts.html">Shorts
														</a></li>
													</ul></li>
												<li><a href="<?php echo WEBPATH;?>/tops/shoes.html">Shoes <span
														class="cat_label Hot !">Hot !</span>
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/shoes/heels.html">Heels
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/shoes/sandals.html">Sandals
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/shoes/flats.html">Flats
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/shoes/ankle-boots.html">Ankle
																Boots </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/shoes/sneakers.html">Sneakers
														</a></li>
													</ul></li>
												<li><a href="<?php echo WEBPATH;?>/tops/accessories.html">Accessories
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/accessories/bags.html">Bags
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/accessories/jewellery.html">Jewellery
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/accessories/sunglasses.html">Sunglasses
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/accessories/scarves.html">Scarves
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/accessories/watches.html">Watches
														</a></li>
													</ul></li>
											</ul></li>
										<li class="level-top"><a class="level-top"
											href="<?php echo WEBPATH;?>/outerwear.html"><span>Outerwear </span></a></li>
										<li class="level-top"><a class="level-top"
											href="<?php echo WEBPATH;?>/bottoms.html"><span>Bottoms </span></a>
											<ul>
												<li><a href="<?php echo WEBPATH;?>/bottoms/shoes.html">Shoes
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/shoes/heels.html">Heels
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/shoes/sandals.html">Sandals
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/shoes/flats.html">Flats
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/shoes/ankle-boots.html">Ankle
																Boots </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/shoes/sneakers.html">Sneakers
														</a></li>
													</ul></li>
												<li><a href="<?php echo WEBPATH;?>/bottoms/accessories.html">Accessories
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/accessories/bags.html">Bags
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/accessories/jewellery.html">Jewellery
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/accessories/sunglasses.html">Sunglasses
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/accessories/scarves.html">Scarves
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/accessories/watches.html">Watches
														</a></li>
													</ul></li>
												<li><a href="<?php echo WEBPATH;?>/bottoms/beauty.html">Beauty
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/beauty/perfume.html">Perfume
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/beauty/make-up.html">Make
																Up </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/beauty/hands-feet.html">Hands
																& Feet </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/beauty/face.html">Face
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/beauty/body.html">Body
														</a></li>
													</ul></li>
											</ul></li>
										<li class="level-top"><a class="level-top"
											href="<?php echo WEBPATH;?>/denim.html"><span>Denim </span></a></li>
										<li class="level-top"><a class="level-top"
											href="<?php echo WEBPATH;?>/luxury-shoes.html"><span>Luxury
													Shoes </span></a></li>
										<li class="level-top"><a class="level-top"
											href="<?php echo WEBPATH;?>/handbags.html"><span>Handbags </span></a></li>
										<li class="level-top"><a class="level-top"
											href="<?php echo WEBPATH;?>/gifts.html"><span>Gifts </span></a></li>
									</ul>
								</div>
								<div class="quick-access">
									<form id="search_mini_form"
										action="<?php echo WEBPATH;?>/catalogsearch/result/"
										method="get">
										<div class="form-search clearfix">
											<label for="search">Search:</label>
											<button type="submit" title="Search" class="button">
												<span><span><i class="fa fa-search"></i></span></span>
											</button>
											<input id="search" type="text" name="q" value=""
												class="input-text" maxlength="128" />
											<div id="search_autocomplete" class="search-autocomplete"></div>
											<script type="text/javascript">
												//<![CDATA[
												var searchForm = new Varien.searchForm(
														'search_mini_form',
														'search',
														'Search entire store here...');
												searchForm
														.initAutocomplete(
																'<?php echo WEBPATH;?>/catalogsearch/ajax/suggest/',
																'search_autocomplete');
												//]]>
											</script>
										</div>
									</form>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
			
			
			
			
			<?php echo $this->content; ?>
			
			
						<div class="footer-container">
				<div class="alo-brands">
					<div class="container">
						<div class="main">
							<div class="row show-grid">
								<div class="col-lg-12">
									<div>
										<div id="upcjhlljmp">
											<ul class="magicbrand">
												<li><img class="brand img-responsive"
													src="<?php echo BAG_REAL_HTML; ?>/smije/media//magiccart/magicbrand/cache/242x111/brands.png"
													alt="Brands1" title="Brands1" /></li>
												<li><img class="brand img-responsive"
													src="<?php echo BAG_REAL_HTML; ?>/smije/media//magiccart/magicbrand/cache/242x111/brands1.png"
													alt="2" title="2" /></li>
												<li><img class="brand img-responsive"
													src="<?php echo BAG_REAL_HTML; ?>/smije/media//magiccart/magicbrand/cache/242x111/brands2.png"
													alt="3" title="3" /></li>
												<li><img class="brand img-responsive"
													src="<?php echo BAG_REAL_HTML; ?>/smije/media//magiccart/magicbrand/cache/242x111/brands3.png"
													alt="4" title="4" /></li>
												<li><img class="brand img-responsive"
													src="<?php echo BAG_REAL_HTML; ?>/smije/media//magiccart/magicbrand/cache/242x111/brands_1.png"
													alt="5" title="5" /></li>
												<li><img class="brand img-responsive"
													src="<?php echo BAG_REAL_HTML; ?>/smije/media//magiccart/magicbrand/cache/242x111/brands1_1.png"
													alt="6" title="6" /></li>
											</ul>
										</div>

										<script type="text/javascript">
											jQuery(document)
													.ready(
															function($) {
																(function(
																		selector) {
																	var $content = $(selector);
																	var $slider = $(
																			'.magicbrand',
																			$content);
																	$slider
																			.flexisel({
																				moveSlide : 1,
																				animationSpeed : 1000,
																				autoPlay : 1,
																				autoPlaySpeed : 4000,
																				clone : 1,
																				enableResponsiveBreakpoints : 1,
																				pauseOnHover : 1,
																				visibleItems : 4,
																				responsiveBreakpoints : {
																					portrait : {
																						changePoint : 480,
																						visibleItems : 1
																					},
																					landscape : {
																						changePoint : 640,
																						visibleItems : 2
																					},
																					tablet : {
																						changePoint : 768,
																						visibleItems : 3
																					},
																				}
																			});

																})
																		("#upcjhlljmp");
															});
										</script>

									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="block-footer-top">
					<div class="container">
						<div class="main">
							<div class="row show-grid">
								<div class="footer">
									<div class="container">
										<div class="row">
											<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
												<div class="block-static2 static-alo">
													<div class="logo-footer">
														<img class="icon-about"
															src="<?php echo BAG_REAL_HTML; ?>/smije/media/wysiwyg/alothemes/static/logo-footer-fashion.png"
															alt="Sunshine" />
														<p>Sed ut perspiciatis unde omnis iste natus voluptatem
															accusantium doloremque lauda totam rem aperiam sunshine
															love.</p>
													</div>
													<div class="social-links icon-wrapper">
														<a class="icon-twitter" href="#"><em class="fa fa-twitter">&nbsp;</em></a>
														<a class="icon-github" href="#"><em class="fa fa-github">&nbsp;</em></a>
														<a class="icon-rss" href="#"><em class="fa fa-rss">&nbsp;</em></a>
														<a class="icon-google-plus" href="#"><em
															class="fa fa-google-plus">&nbsp;</em></a> <a
															class="icon-facebook" href="#"><em class="fa fa-facebook">&nbsp;</em></a>
													</div>
												</div>
											</div>
											<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
												<div class="block-static1 static-alo">
													<div class="block-title-tabs">
														<h3 class="block-title heading">
															<span>Contact Us</span>
														</h3>
													</div>
													<div class="block1 block-content-statick">
														<ul>
															<li class="map"><span class="fa fa-map-marker">&nbsp;</span>
																<address>
																	<span>Address:</span>
																</address>
																<p>415 Water St.New York, NY 10003, USA</p></li>
															<li class="phone"><span class="fa fa-phone">&nbsp;</span>
																<span>Phone:</span>
																<p>(+800) 0123 456 789</p></li>
															<li class="email"><span class="fa  fa-envelope">&nbsp;</span><span>Email:</span>
																<p>
																	<a href="mailto:support@alothemes.com">support@alothemes.com</a>
																</p></li>
														</ul>
													</div>
												</div>
											</div>
											<div class="customer col-lg-3 col-md-3 col-sm-3 col-xs-12">
												<div class="block-static3 static-alo">
													<div class="block block-creare-twitter">
														<div class="block-title">
															<strong><span>Our Latest Tweets</span></strong>
														</div>
														<div class="block-content">
															<ul>
																<li class="clearfix">
																	<div class="alo-twitter">
																		<div class="twitter-pic pull-left">
																			<a href="https://twitter.com/alothemes"><img
																				class="img-responsive"
																				src="<?php echo BAG_REAL_HTML; ?>/img/j7c9SpAr_normal.png"
																				alt="twitter icon" /></a>
																		</div>
																		<div class="twitter-links pull-left">
																			<div class="pull-left-none">
																				<span class="tweetprofilelink"> <strong><a
																						href="https://twitter.com/alothemes">alothemes</a></strong>
																					<a href="https://twitter.com/alothemes">@alothemes</a>
																				</span>
																				<p>Orenmode - Responsive Magento Theme
																					http://t.co/b3AaqXFSks</p>
																			</div>
																			<div class="date">41 days ago</div>
																		</div>
																	</div>
																</li>
																<li class="clearfix">
																	<div class="alo-twitter">
																		<div class="twitter-pic pull-left">
																			<a href="https://twitter.com/alothemes"><img
																				class="img-responsive"
																				src="http://pbs.twimg.com/profile_images/536002680057913345/j7c9SpAr_normal.png"
																				alt="twitter icon" /></a>
																		</div>
																		<div class="twitter-links pull-left">
																			<div class="pull-left-none">
																				<span class="tweetprofilelink"> <strong><a
																						href="https://twitter.com/alothemes">alothemes</a></strong>
																					<a href="https://twitter.com/alothemes">@alothemes</a>
																				</span>
																				<p>Owlshop - Responsive Magento Theme
																					http://t.co/aZgY52qE8K</p>
																			</div>
																			<div class="date">72 days ago</div>
																		</div>
																	</div>
																</li>
															</ul>
														</div>
													</div>



												</div>
											</div>
											<div class="customer col-lg-3 col-md-3 col-sm-3 col-xs-12">
												<div class="block-static4 static-alo">
													<div class="block block-subscribe">
														<div class="block-title">
															<strong><span>Newsletter</span></strong>
														</div>
														<form
															action="<?php echo WEBPATH;?>/newsletter/subscriber/new/"
															method="post" id="newsletter-validate-detail">
															<div class="block-content">
																<div class="form-subscribe-header">
																	<label for="newsletter">Sign Up for Our Newsletter:</label>
																</div>
																<div class="input-box">
																	<input type="text" name="email" id="newsletter"
																		title="Sign up for our newsletter"
																		class="input-text required-entry validate-email" />
																</div>
																<div class="actions">
																	<button type="submit" title="Subscribe" class="button">
																		<span><span>Subscribe</span></span>
																	</button>
																</div>
															</div>
														</form>
														<script type="text/javascript">
															//<![CDATA[
															var newsletterSubscriberFormDetail = new VarienForm(
																	'newsletter-validate-detail');
															//]]>
														</script>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="block-footer-bottom">
					<div class="container">
						<div class="main">
							<div class="footer">
								<div class="container-">
									<div class="row">
										<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
											<div class="block-static1 static-alo">
												<h3 class="block-title heading">OUR SERVICES</h3>
												<div class="block2 block-content-statick">
													<ul>
														<li><a href="#">Order History</a></li>
														<li><a href="<?php echo WEBPATH;?>/sales/guest/form/">Returns</a></li>
														<li><a href="#">Libero Sed rhoncus</a></li>
														<li><a href="#">Venenatis augue tellus</a></li>
														<li><a href="#">My vouchers</a></li>
													</ul>
												</div>
											</div>
										</div>
										<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
											<div class="block-static2 static-alo">
												<h3 class="block-title heading">MY ACCOUNT</h3>
												<div class="block2 block-content-statick">
													<ul>
														<li><a href="<?php echo WEBPATH;?>/about">About Us</a></li>
														<li><a href="<?php echo WEBPATH;?>/customer-service">Customer
																Service</a></li>
														<li><a
															href="<?php echo WEBPATH;?>/privacy-policy-cookie-restriction-mode">Privacy
																Policy</a></li>
														<li><a
															href="<?php echo WEBPATH;?>/catalog/seo_sitemap/category/">Site
																Map</a></li>
														<li><a
															href="<?php echo WEBPATH;?>/catalogsearch/term/popular/">Search
																Terms</a></li>
													</ul>
												</div>
											</div>
										</div>
										<div class="userful col-lg-3 col-md-3 col-sm-3 col-xs-12">
											<div class="block-static3 static-alo">
												<h3 class="block-title heading">INFORMATION</h3>
												<div class="block3 block-content-statick">
													<ul>
														<li><a href="#">Order History</a></li>
														<li><a href="<?php echo WEBPATH;?>/sales/guest/form/">Returns</a></li>
														<li><a href="#">Libero Sed rhoncus</a></li>
														<li><a href="#">Venenatis augue tellus</a></li>
														<li><a href="#">My vouchers</a></li>
													</ul>
												</div>
											</div>
										</div>
										<div class="customer col-lg-3 col-md-3 col-sm-3 col-xs-12">
											<div class="block-static4 static-alo">
												<h3 class="block-title heading">WHY BUY FROM US</h3>
												<div class="block-linkservice block-content-statick">
													<ul>
														<li><a href="#">Shipping &amp; Returns</a></li>
														<li><a href="#">Secure Shopping</a></li>
														<li><a href="#">International Shipping</a></li>
														<li><a href="#">Affiliates</a></li>
														<li><a href="#">Contact</a></li>
													</ul>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="block-footer-copyright">
					<div class="container">
						<div class="footer">
							<div class="main">
								<div class="row show-grid">
									<div class="container">
										<address>
											Copyright © 2014 <a class="active"
												href="http://alothemes.com/demo/smije/"
												title="Magento Themes">Magento Themes</a> by Alothemes.com.
											All rights reserved.
										</address>
										<div class="store-switcher">
											<label for="select-store">Select Store:</label> <select
												id="select-store" title="Select Store"
												onchange="location.href=this.value">
												<option
													value="<?php echo WEBPATH;?>/?___store=english_digital">Digital
													Store</option>
												<option value="" selected="selected">Fashion Store</option>
												<option value="<?php echo WEBPATH;?>/?___store=default">Furniture
													Store</option>
											</select>
										</div>
										<div class="paypal">
											<p>
												<img class="img-responsive"
													src="<?php echo BAG_REAL_HTML; ?>/smije/media/wysiwyg/alothemes/static/paypal.png"
													alt="" />
											</p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<a href="#" id="backtotop"><span class="fa fa-angle-up"></span><span
					class="back-to-top">Back to Top</span></a>
			</div>


		</div>
	</div>

	<script type="text/javascript">
		     var domain ='<?php echo WEBPATH;?>';var glob=2;
			 jQuery(document).ready(function($) {
				 e = location.pathname;
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/loadleftcataogue",
		               data: {idcode:e,page:glob},
		               success: function(data){
			               //alert(data);console.log( $('.leftcatalogue').html(data));
		                            $('#leftcatalogue').html(data);
		                             glob++;
		                       }
		         });

				 $.ajax({
		               type: "POST",
		               url: domain + "/main/loadsaleproduct",
		               data: {idcode:e,page:glob},
		               success: function(data){
			               //alert("saleproducta "+data);console.log( $('#saleproducta').html(data));
		                            $('#saleproducta').html(data);
		                       }
		         });

		         //bestsellera
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/bestseller",
		               data: {idcode:e,page:glob},
		               success: function(data){
		            	   //alert("bestsellera " + data);console.log( $('#bestsellera').html(data));
		                            $('#bestsellera').html(data);
		                       }
		         });

		         //compareblock
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/compareblock",
		               data: {idcode:e,page:glob},
		               success: function(data){
		            	   //alert("bestsellera " + data);console.log( $('#bestsellera').html(data));
		                            $('#blockcompare').html(data);
		                       }
		         });


		         //populartags
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/populartags",
		               data: {idcode:e,page:glob},
		               success: function(data){
			                  $('#populartags').html(data);
		                       }
		         });

		         //containernone
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/containernone",
		               data: {idcode:e,page:glob},
		               success: function(data){
			                  $('#containernone').html(data);
		                       }
		         });

		         //myacount
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/myacount",
		               data: {idcode:e,page:glob},
		               success: function(data){
			                  $('#myacountaja').html(data);
		                       }
		         });

				//mycart
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/mycart",
		               data: {idcode:e,page:glob},
		               success: function(data){
			                  $('#mycartaja').html(data);
		                       }
		         });

		         //compareproduct
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/compareproduct",
		               data: {idcode:e,page:glob},
		               success: function(data){
			                  $('#compareproductaja').html(data);
		                       }
		         });
		         
			 });
				</script>


</body>
</html>


