<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="msapplication-tap-highlight" content="no">
  <meta name="description" content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google. ">
  <meta name="keywords" content="materialize, admin template, dashboard template, flat admin template, responsive admin template,">
  <title>Login Page | Materialize - Material Design Admin Template</title>

  <!-- Favicons-->
  <link rel="icon" href="<?php echo APOTRAVINY_ADMIN?>/images/favicon/favicon-32x32.png" sizes="32x32">
  <!-- Favicons-->
  <link rel="apple-touch-icon-precomposed" href="<?php echo APOTRAVINY_ADMIN?>/images/favicon/apple-touch-icon-152x152.png">
  <!-- For iPhone -->
  <meta name="msapplication-TileColor" content="#00bcd4">
  <meta name="msapplication-TileImage" content="<?php echo APOTRAVINY_ADMIN?>/images/favicon/mstile-144x144.png">
  <!-- For Windows Phone -->


  <!-- CORE CSS-->
  
  <link href="<?php echo APOTRAVINY_ADMIN?>/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection">
  <link href="<?php echo APOTRAVINY_ADMIN?>/css/style.css" type="text/css" rel="stylesheet" media="screen,projection">
  <link href="<?php echo APOTRAVINY_ADMIN?>/css/page-center.css" type="text/css" rel="stylesheet" media="screen,projection">

  <!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
  <link href="<?php echo APOTRAVINY_ADMIN?>/css/prism.css" type="text/css" rel="stylesheet" media="screen,projection">
  <link href="<?php echo APOTRAVINY_ADMIN?>/js/plugins/perfect-scrollbar/perfect-scrollbar.css" type="text/css" rel="stylesheet" media="screen,projection">
  
</head>

<body class="cyan">
  <!-- Start Page Loading -->
  <div id="loader-wrapper">
      <div id="loader"></div>        
      <div class="loader-section section-left"></div>
      <div class="loader-section section-right"></div>
  </div>
  <!-- End Page Loading -->




<?php echo $this->content; ?>



<!-- ================================================
    Scripts
    ================================================ -->

  <!-- jQuery Library -->
  <script type="text/javascript" src="<?php echo APOTRAVINY_ADMIN?>/js/jquery-1.11.2.min.js"></script>
  <script type="text/javascript" src="<?php echo APOTRAVINY_ADMIN?>/js/jquery.validate.js"></script>  
  <!--materialize js-->
  <script type="text/javascript" src="<?php echo APOTRAVINY_ADMIN?>/js/materialize.js"></script>
  <!--prism-->
  <script type="text/javascript" src="<?php echo APOTRAVINY_ADMIN?>/js/prism.js"></script>
  <!--scrollbar-->
  <script type="text/javascript" src="<?php echo APOTRAVINY_ADMIN?>/js/plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>

  <!--plugins.js - Some Specific JS codes for Plugin Settings-->
  <script type="text/javascript" src="<?php echo APOTRAVINY_ADMIN?>/js/plugins.js"></script>

</body>

</html>
