<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="description" content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google. ">
    <meta name="keywords" content="materialize, admin template, dashboard template, flat admin template, responsive admin template,">
    <title>apotraviny.cz Design Admin Template a</title>

    <!-- Favicons-->
    <link rel="icon" href="<?php echo APOTRAVINY_ADMIN?>/images/favicon/favicon-32x32.png" sizes="32x32">
    <!-- Favicons-->
    <link rel="apple-touch-icon-precomposed" href="<?php echo APOTRAVINY_ADMIN?>/images/favicon/apple-touch-icon-152x152.png">
    <!-- For iPhone -->
    <meta name="msapplication-TileColor" content="#00bcd4">
    <meta name="msapplication-TileImage" content="<?php echo APOTRAVINY_ADMIN?>/images/favicon/mstile-144x144.png">
    <!-- For Windows Phone -->


    <!-- CORE CSS-->    
    <link href="<?php echo APOTRAVINY_ADMIN?>/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="<?php echo APOTRAVINY_ADMIN?>/css/style.css" type="text/css" rel="stylesheet" media="screen,projection">


    <!-- INCLUDED PLUGIN CSS ON THIS PAGE -->    
    <link href="<?php echo APOTRAVINY_ADMIN?>/css/perfect-scrollbar.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="<?php echo APOTRAVINY_ADMIN?>/css/jquery-jvectormap.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="<?php echo APOTRAVINY_ADMIN?>/css/chartist.min.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="<?php echo APOTRAVINY_ADMIN?>/css/prism.css" type="text/css" rel="stylesheet" media="screen,projection">
  
   <link href="<?php echo APOTRAVINY_ADMIN?>/css/cssadmin.css" type="text/css" rel="stylesheet" media="screen,projection">
        
</head>

<body>
    <!-- Start Page Loading -->
    <div id="loader-wrapper">
        <div id="loader"></div>        
        <div class="loader-section section-left"></div>
        <div class="loader-section section-right"></div>
    </div>
    <!-- End Page Loading -->

    <!-- //////////////////////////////////////////////////////////////////////////// -->

    <!-- START HEADER -->
    <header id="header" class="page-topbar">
        <!-- start header nav-->
        <div class="navbar-fixed">
            <nav class="cyan">
                <div class="nav-wrapper">
                
                    <h1 class="logo-wrapper"><a href="<?php echo WEBPATH;?>/materialize/" class="brand-logo darken-1"><img src="<?php echo APOTRAVINY_ADMIN?>/images/materialize-logo.png"  style="height: 54px;  width: 72%; " alt="materialize logo"></a> <span class="logo-text">Apotraviny.cz</span></h1>
                    <ul class="right hide-on-med-and-down">
                        <li class="search-out">
                            <input type="text" class="search-out-text">
                        </li>
                        <li>    
                            <a href="javascript:void(0);" class="waves-effect waves-block waves-light show-search"><i class="mdi-action-search"></i></a>                              
                        </li>
                        <li><a href="javascript:void(0);" class="waves-effect waves-block waves-light toggle-fullscreen"><i class="mdi-action-settings-overscan"></i></a>
                        </li>
                        <li><a href="javascript:void(0);" class="waves-effect waves-block waves-light"><i class="mdi-social-notifications"></i></a>
                        </li>
                        <!-- Dropdown Trigger -->                        
                        <li><a href="#" data-activates="chat-out" class="waves-effect waves-block waves-light chat-collapse"><i class="mdi-communication-chat"></i></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <!-- end header nav-->
    </header>
    <!-- END HEADER -->
    
    <!-- START MAIN -->
    <div id="main">
        <!-- START WRAPPER -->
        <div class="wrapper">

            <!-- START LEFT SIDEBAR NAV-->
            <aside id="left-sidebar-nav">
                <ul id="slide-out" class="side-nav fixed leftside-navigation">
                    <li class="user-details cyan darken-2">
                        <div class="row">
                            <div class="col col s4 m4 l4">
                            <?php 
				                $getuser = $this->layout()->getuser;
				               $avantar_img='';
				               $avantar = $getuser->avatar;
				               if( $avantar =='' || $avantar == null) { 
				                   $avantar_img =  APOTRAVINY_ADMIN.'/images/avatar.jpg'; 
				                   //$this->staticLink('avatar.jpg', StaticLink\View\Helper\StaticLink::ADMINTHEME, array('images'));
                               }
				               else {
				               	 $avantar_img = APOTRAVINY_ADMIN.$avantar;
				               }
				               
				               /*
				                *  <img style="  max-width: 100px; max-height: 100px;" src="<?php echo $avantar_img;?>" alt="" 
				                                class="circle responsive-img valign profile-image">
				                * */
               
                              ?>
                                <img src="<?php echo $avantar_img;?>" alt="" class="circle responsive-img activator card-profile-image">
                            </div>
                            <div class="col col s8 m8 l8">
                                <ul id="profile-dropdown" class="dropdown-content">
                                    <li><a href="#"><i class="mdi-action-face-unlock"></i> Profile</a>
                                    </li>
                                    <li><a href="#"><i class="mdi-action-settings"></i> Settings</a>
                                    </li>
                                    <li><a href="#"><i class="mdi-communication-live-help"></i> Help</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li><a href="#"><i class="mdi-action-lock-outline"></i> Lock</a>
                                    </li>
                                    <li><a href="<?php echo WEBPATH?>/logout"><i class="mdi-hardware-keyboard-tab"></i> Logout</a>
                                    </li>
                                </ul>
                                <a class="btn-flat dropdown-button waves-effect waves-light white-text profile-btn" href="#" data-activates="profile-dropdown"><?php echo $getuser->username;?><i class="mdi-navigation-arrow-drop-down right"></i></a>
                                <?php 
                                if($getuser->group =='supperadmin') { echo '<p class="user-roal">Administrator</p>'; }
                                else { echo '<p class="user-roal">'.$getuser->group.'</p>'; }
                                ?>
                            </div>
                        </div>
                    </li>
                    <li class="bold"><a href="<?php echo WEBPATH;?>/materialize/" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Dashboard</a> </li>
                    <li class="bold"><a href="<?php echo WEBPATH;?>/catalog/manacatalo" class="waves-effect waves-cyan"><i class="mdi-device-now-widgets"></i> Catalogue <span class="new badge">4</span></a> </li>
                      <li class="bold"><a href="<?php echo WEBPATH;?>/invoice/order/index" class="waves-effect waves-cyan"><i class="mdi-device-now-widgets"></i> Mana Oder </a> </li>  
                        
                    <li class="no-padding">
                        <ul class="collapsible collapsible-accordion">
                            <li class="bold"><a class="collapsible-header  waves-effect waves-cyan"><i class="mdi-action-account-child"></i> Mana Customer</a>
	                                <div class="collapsible-body">
	                                    <ul>
                                            <li><a href="<?php echo WEBPATH;?>/customer">Customer</a>  </li>
	                                        <li><a href="<?php echo WEBPATH;?>/customer/listemail">Email</a> </li>
	                                        
	                                    </ul>
	                                </div>
	                          </li>
                             <li class="bold"><a class="collapsible-header  waves-effect waves-cyan"><i class="mdi-action-settings-input-component"></i> Manufacturer</a>
	                                <div class="collapsible-body">
	                                    <ul>
                                            <li><a href="<?php echo WEBPATH;?>/manufacture">Mana Manufacturer</a>  </li>
	                                        <li><a href="<?php echo WEBPATH;?>/manufacture/add">Add Manufacturer</a> </li>
	                                        
	                                    </ul>
	                                </div>
	                          </li>
	                         <li class="bold"><a class="collapsible-header  waves-effect waves-cyan"><i class="mdi-editor-insert-comment"></i> Tags</a>
	                                <div class="collapsible-body">
	                                    <ul>
                                            <li><a href="<?php echo WEBPATH;?>/tags/masterindex">Mana Tags</a>  </li>
	                                        <li><a href="<?php echo WEBPATH;?>/tags/masteradd">Add Tags</a> </li>
	                                        
	                                    </ul>
	                                </div>
	                          </li>
                              <li class="bold"><a class="collapsible-header  waves-effect waves-cyan"><i class="mdi-image-palette"></i> Product</a>
	                                <div class="collapsible-body">
	                                    <ul>
	                                        <li><a href="<?php echo WEBPATH?>/masteproduct/index/index">Mana Product</a>  </li>
	                                        <li><a href="<?php echo WEBPATH?>/masteproduct/index/add">Add New Product</a> </li>
	                                        <li><a href="#">Seach Product</a> </li> 
	                                    </ul>
	                                </div>
	                          </li>
                            <li class="bold"><a class="collapsible-header waves-effect waves-cyan"><i class="mdi-action-invert-colors"></i> Crowler</a>
                                <div class="collapsible-body">
                                    <ul>
                                        <li><a href="<?php echo WEBPATH?>/crowler/crowler/declarationsite">Declaration site</a>  </li>
                                        <li><a href="<?php echo WEBPATH?>/crowler/crowler/index">Get Crowler</a>  </li>
                                        <li><a href="<?php echo WEBPATH?>/crowler/name/index">Name</a>
                                        </li>
                                        <!--  
                                        <li><a href="css-shadow.html">Shadow</a>
                                        </li>
                                        <li><a href="css-media.html">Media</a>
                                        </li>
                                        <li><a href="css-sass.html">Sass</a>
                                        </li>
                                        -->
                                    </ul>
                                </div>
                            </li>
                           
                           <li class="bold"><a class="collapsible-header  waves-effect waves-cyan"><i class="mdi-editor-insert-comment"></i> Theme</a>
	                                <div class="collapsible-body">
	                                    <ul>
                                            <li><a href="<?php echo WEBPATH;?>">Index Apotraviny </a>  </li>
	                                        <li><a href="<?php echo WEBPATH;?>/lazada/index">Estore Desktop</a> </li>
	                                        <li><a href="<?php echo WEBPATH;?>/apotraviny/index">Estore Mobile</a> </li>
	                                        <li><a href="<?php echo WEBPATH;?>/main/index">Estore Exp</a> </li>
	                                    </ul>
	                                </div>
	                          </li>
                            
                            <li class="bold"><a class="collapsible-header  waves-effect waves-cyan"><i class="mdi-action-settings"></i> Setting Site</a>
	                                <div class="collapsible-body">
	                                    <ul>
                                            <li><a href="<?php echo WEBPATH;?>/setting-site">SEO - KeyWord</a>  </li>
	                                        <li><a href="#">Img-Logo-Ico</a> </li>
	                                        <li><a href="#">Infor Site</a> </li>
	                                        <li><a href="#">Other</a> </li>
	                                    </ul>
	                                </div>
	                          </li>
                           
                        </ul>
                    </li>
                </ul>
                <a href="#" data-activates="slide-out" class="sidebar-collapse btn-floating btn-medium waves-effect waves-light hide-on-large-only darken-2"><i class="mdi-navigation-menu" ></i></a>
            </aside>
            <!-- END LEFT SIDEBAR NAV-->

            <!-- //////////////////////////////////////////////////////////////////////////// -->
            
            
    
    <?php echo $this->content; ?>
    
    
    
     <!-- //////////////////////////////////////////////////////////////////////////// -->
            <!-- START RIGHT SIDEBAR NAV-->
            <aside id="right-sidebar-nav">
                <ul id="chat-out" class="side-nav rightside-navigation">
                    <li class="li-hover">
                    <a href="#" data-activates="chat-out" class="chat-close-collapse right"><i class="mdi-navigation-close"></i></a>
                    <div id="right-search" class="row">
                        <form class="col s12">
                            <div class="input-field">
                                <i class="mdi-action-search prefix"></i>
                                <input id="icon_prefix" type="text" class="validate">
                                <label for="icon_prefix">Search</label>
                            </div>
                        </form>
                    </div>
                    </li>
                    <li class="li-hover">
                        <ul class="chat-collapsible" data-collapsible="expandable">
                        <li>
                            <div class="collapsible-header teal white-text active"><i class="mdi-social-whatshot"></i>Recent Activity</div>
                            <div class="collapsible-body recent-activity">
                                <div class="recent-activity-list chat-out-list row">
                                    <div class="col s3 recent-activity-list-icon"><i class="mdi-action-add-shopping-cart"></i>
                                    </div>
                                    <div class="col s9 recent-activity-list-text">
                                        <a href="#">just now</a>
                                        <p>Jim Doe Purchased new equipments for zonal office.</p>
                                    </div>
                                </div>
                                <div class="recent-activity-list chat-out-list row">
                                    <div class="col s3 recent-activity-list-icon"><i class="mdi-device-airplanemode-on"></i>
                                    </div>
                                    <div class="col s9 recent-activity-list-text">
                                        <a href="#">Yesterday</a>
                                        <p>Your Next flight for USA will be on 15th August 2015.</p>
                                    </div>
                                </div>
                                <div class="recent-activity-list chat-out-list row">
                                    <div class="col s3 recent-activity-list-icon"><i class="mdi-action-settings-voice"></i>
                                    </div>
                                    <div class="col s9 recent-activity-list-text">
                                        <a href="#">5 Days Ago</a>
                                        <p>Natalya Parker Send you a voice mail for next conference.</p>
                                    </div>
                                </div>
                                <div class="recent-activity-list chat-out-list row">
                                    <div class="col s3 recent-activity-list-icon"><i class="mdi-action-store"></i>
                                    </div>
                                    <div class="col s9 recent-activity-list-text">
                                        <a href="#">Last Week</a>
                                        <p>Jessy Jay open a new store at S.G Road.</p>
                                    </div>
                                </div>
                                <div class="recent-activity-list chat-out-list row">
                                    <div class="col s3 recent-activity-list-icon"><i class="mdi-action-settings-voice"></i>
                                    </div>
                                    <div class="col s9 recent-activity-list-text">
                                        <a href="#">5 Days Ago</a>
                                        <p>Natalya Parker Send you a voice mail for next conference.</p>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="collapsible-header light-blue white-text active"><i class="mdi-editor-attach-money"></i>Sales Repoart</div>
                            <div class="collapsible-body sales-repoart">
                                <div class="sales-repoart-list  chat-out-list row">
                                    <div class="col s8">Target Salse</div>
                                    <div class="col s4"><span id="sales-line-1"></span>
                                    </div>
                                </div>
                                <div class="sales-repoart-list chat-out-list row">
                                    <div class="col s8">Payment Due</div>
                                    <div class="col s4"><span id="sales-bar-1"></span>
                                    </div>
                                </div>
                                <div class="sales-repoart-list chat-out-list row">
                                    <div class="col s8">Total Delivery</div>
                                    <div class="col s4"><span id="sales-line-2"></span>
                                    </div>
                                </div>
                                <div class="sales-repoart-list chat-out-list row">
                                    <div class="col s8">Total Progress</div>
                                    <div class="col s4"><span id="sales-bar-2"></span>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="collapsible-header red white-text"><i class="mdi-action-stars"></i>Favorite Associates</div>
                            <div class="collapsible-body favorite-associates">
                                <div class="favorite-associate-list chat-out-list row">
                                    <div class="col s4"><img src="<?php echo APOTRAVINY_ADMIN?>/images/avatar.jpg" alt="" class="circle responsive-img online-user valign profile-image">
                                    </div>
                                    <div class="col s8">
                                        <p>Eileen Sideways</p>
                                        <p class="place">Los Angeles, CA</p>
                                    </div>
                                </div>
                                <div class="favorite-associate-list chat-out-list row">
                                    <div class="col s4"><img src="<?php echo APOTRAVINY_ADMIN?>/images/avatar.jpg" alt="" class="circle responsive-img online-user valign profile-image">
                                    </div>
                                    <div class="col s8">
                                        <p>Zaham Sindil</p>
                                        <p class="place">San Francisco, CA</p>
                                    </div>
                                </div>
                                <div class="favorite-associate-list chat-out-list row">
                                    <div class="col s4"><img src="<?php echo APOTRAVINY_ADMIN?>/images/avatar.jpg" alt="" class="circle responsive-img offline-user valign profile-image">
                                    </div>
                                    <div class="col s8">
                                        <p>Renov Leongal</p>
                                        <p class="place">Cebu City, Philippines</p>
                                    </div>
                                </div>
                                <div class="favorite-associate-list chat-out-list row">
                                    <div class="col s4"><img src="<?php echo APOTRAVINY_ADMIN?>/images/avatar.jpg" alt="" class="circle responsive-img online-user valign profile-image">
                                    </div>
                                    <div class="col s8">
                                        <p>Weno Carasbong</p>
                                        <p>Tokyo, Japan</p>
                                    </div>
                                </div>
                                <div class="favorite-associate-list chat-out-list row">
                                    <div class="col s4"><img src="<?php echo APOTRAVINY_ADMIN?>/images/avatar.jpg" alt="" class="circle responsive-img offline-user valign profile-image">
                                    </div>
                                    <div class="col s8">
                                        <p>Nusja Nawancali</p>
                                        <p class="place">Bangkok, Thailand</p>
                                    </div>
                                </div>
                            </div>
                        </li>
                        </ul>
                    </li>
                </ul>
            </aside>
            <!-- LEFT RIGHT SIDEBAR NAV-->

        </div>
        <!-- END WRAPPER -->

    </div>
    <!-- END MAIN -->
    
    <!-- //////////////////////////////////////////////////////////////////////////// -->

    <!-- START FOOTER -->
    <footer class="page-footer">
       
        <div class="footer-copyright">
            <div class="container">
                Copyright © 2015 <a class="grey-text text-lighten-4" href="#" target="_blank">Alatca</a> All rights reserved.
                <span class="right"> Design and Developed by <a class="grey-text text-lighten-4" href="#">Alatca</a></span>
            </div>
        </div>
    </footer>
    <!-- END FOOTER -->


    <!-- ================================================
    Scripts
    ================================================ -->
    
    <!-- jQuery Library -->
    <script type="text/javascript" src="<?php echo APOTRAVINY_ADMIN?>/js/jquery-1.11.2.min.js"></script>    
  
    <!--materialize js-->
    <script type="text/javascript" src="<?php echo APOTRAVINY_ADMIN?>/js/materialize.min.js"></script>
    <!--scrollbar-->
    <script type="text/javascript" src="<?php echo APOTRAVINY_ADMIN?>/js/perfect-scrollbar.min.js"></script>
     <script type="text/javascript" src="<?php echo APOTRAVINY_ADMIN?>/js/chartist.min.js"></script> 
    <!--prism-->
    <script type="text/javascript" src="<?php echo APOTRAVINY_ADMIN?>/js/prism.js"></script>

    <!-- sparkline -->
    <script type="text/javascript" src="<?php echo APOTRAVINY_ADMIN?>/js/jquery.sparkline.min.js"></script>
    <script type="text/javascript" src="<?php echo APOTRAVINY_ADMIN?>/js/sparkline-script.js"></script>
    
    <!--jvectormap-->
    <script type="text/javascript" src="<?php echo APOTRAVINY_ADMIN?>/js/jquery-jvectormap-1.2.2.min.js"></script>
    <script type="text/javascript" src="<?php echo APOTRAVINY_ADMIN?>/js/jquery-jvectormap-world-mill-en.js"></script>
    <script type="text/javascript" src="<?php echo APOTRAVINY_ADMIN?>/js/vectormap-script.js"></script>
    
    
    <!--plugins.js - Some Specific JS codes for Plugin Settings-->
    <script type="text/javascript" src="<?php echo APOTRAVINY_ADMIN?>/js/plugins.js"></script>
    <!-- Toast Notification -->
    <script type="text/javascript">
    // Toast Notification
    $(window).load(function() {
        setTimeout(function() {
            Materialize.toast('<span>Hiya! I am a toast.</span>', 1500);
        }, 3000);
        setTimeout(function() {
            Materialize.toast('<span>You can swipe me too!</span>', 3000);
        }, 5500);
        setTimeout(function() {
            Materialize.toast('<span>You have new order.</span><a class="btn-flat yellow-text" href="#">Read<a>', 3000);
        }, 18000);
    });
    
	 var validNavigation = false;

function endSession() {    
    $.get(document.location.origin+'/logout');   
}

function wireUpEvents() {    
    window.onbeforeunload = function () {
        if (!validNavigation) {
            endSession();
        }
    };
   
    $('document').bind('keypress', function (e) {
        if (e.keyCode == 116) {
            validNavigation = true;
        }
    });
   
    $("a").bind("click", function () {
        validNavigation = true;
    });

   
    $("form").bind("submit", function () {
        validNavigation = true;
    });

    
    $("input[type=submit]").bind("click", function () {
        validNavigation = true;
    });

}

$(document).ready(function () {
    wireUpEvents();   
    
});
    </script>
    
    <script type="text/javascript">
    $(document).ready(function(){
        $('.tooltipped').tooltip({delay: 50});
      });
    </script>
<script type="text/javascript" src="<?php echo APOTRAVINY_ADMIN?>/js/crawler.js"></script></body>
<script src="<?php echo WEBPATH ?>/include/ckeditor/ckeditor.js"></script>
</html>
    
    