<?php echo $this->doctype(); ?>
<!DOCTYPE html>
<html>
  <head>
   <title>Upload Img Mutiupload</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <style type="text/css">
      img {border-width: 0}
      * {font-family:'Lucida Grande', sans-serif;}
    </style>
    <link href="<?php echo BAG_REAL_HTML; ?>/css/uploadfilemulti.css" rel="stylesheet">
<script src="<?php echo BAG_REAL_HTML; ?>/js/jquery-1.8.0.min.js"></script>
<script src="<?php echo BAG_REAL_HTML; ?>/js/jquery.fileuploadmulti.min.js"></script>

  </head>
  <body>
 <div id="mulitplefileuploader">Upload</div>

<div id="status"></div>
<script>

$(document).ready(function()
{

var settings = {
	url: "http://127.0.0.1/testuploadmutifile/upload-multiple-images-jquery-ajax-using-php/upload.php",
	method: "POST",
	allowedTypes:"jpg,png,gif,doc,pdf,zip",
	fileName: "myfile",
	multiple: true,
	onSuccess:function(files,data,xhr)
	{
		$("#status").html("<font color='green'>Upload is success</font>");
		
	},
    afterUploadAll:function()
    {
        alert("all images uploaded!!");
    },
	onError: function(files,status,errMsg)
	{		
		$("#status").html("<font color='red'>Upload is Failed</font>");
	}
}
$("#mulitplefileuploader").uploadFile(settings);

});
</script>
</body>
</html>
