<?php echo $this->doctype(); ?>
<?php 
use Zend\Session\Container; 
$setting = $this->layout()->setting; 
$setting_session = new Container('setting');

$container = new Container('shopcart_lazada');
$arraycart = $container->cart_lazada;

?>
<!DOCTYPE html>
<!--
	To change this license header, choose License Headers in Project Properties.
	To change this template file, choose Tools | Templates
	and open the template in the editor.
-->
<html>
	<head>
		 <title><?php echo $setting_session->name;?></title>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
		<meta name="description" content="<?php echo $setting_session->seo_description;?>" />
		<meta name="keywords" content="<?php echo $setting_session->seo_keywords;?>" />
		<meta name="robots" content="INDEX,FOLLOW" />
                <meta charset="UTF-8">
                <link rel="icon" href="<?php echo WEBPATH_UPLOAD_PATH_IMG.'/'.$setting_session->ico;?>" type="image/x-icon" />
		<link rel="shortcut icon" href="<?php echo WEBPATH_UPLOAD_PATH_IMG.'/'.$setting_session->ico;?>" type="image/x-icon" />
		<script src="<?php echo ROHLIK_LAZADA;?>/lazadanew/js/jquery-2.1.3.js" type="text/javascript"></script>
		<script src="<?php echo ROHLIK_LAZADA;?>/lazadanew/js/bootstrap.min.js" type="text/javascript"></script>
		<link href="<?php echo ROHLIK_LAZADA;?>/lazadanew/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
		<link href="<?php echo ROHLIK_LAZADA;?>/lazadanew/fonts/font-awesome.css" rel="stylesheet" type="text/css"/>
		<link href="<?php echo ROHLIK_LAZADA;?>/lazadanew/css/style.css" rel="stylesheet" type="text/css"/>
		<link href="<?php echo ROHLIK_LAZADA;?>/lazadanew/css/style-lop1.css" rel="stylesheet" type="text/css"/>
                  <script>
            $(document).ready(function () {              
             var domains = '<?php echo WEBPATH; ?>';
             sessionStorage.domain=domains;
         });
        </script>
        <script type="text/javascript" src="<?php echo ROHLIK_LAZADA;?>/lazadanew/js/jquery.validate.js"></script>
        <script src="<?php echo ROHLIK_LAZADA;?>/lazadanew/js/time.js" type="text/javascript"></script>
                 
        </head>
	<body>
		<header>
			<div class="container-fluid logo-timkiem-mua-fluid">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="logo_dh">
								<a href="<?php echo WEBPATH?>/lazada/index" class="header__logo">
									<img alt="#" class="img-responsive anhlogo" src="<?php echo ROHLIK_LAZADA;?>/lazadanew/img/header/vn.png">
								</a>
							</div>
							<div class="steps-progress toclear">
								<div class="steps step-1 on_progress current">
									<span class="step-txt toclear">
										<span class="icon-wrap"><i class="icon icon-lock"></i></span>
										<span class="step-number">1.</span>
										<span class="step-name">Email ID</span>
									</span>
								</div>
								<div class="steps step-2">
									<span class="step-txt toclear">
										<span class="icon-wrap"><i class="icon icon-lorry"></i></span>
										<span class="step-number">2.</span>
										<span class="step-name">Vận chuyển</span>
									</span>
								</div>
								<div class="step-last steps step-3">
									<span class="step-txt toclear">
										<span class="icon-wrap"><i class="icon icon-wallet"></i></span>
										<span class="step-number">3.</span>
										<span class="step-name">Thanh toán</span>
									</span>
								</div>
							</div>
						</div>
					</div>
				</div>
				
				
			</div>
			
		</header>
		<div class="conten">
			<div class="container">
				<div class="row">
					<?php echo $this->content;  ?>
					<div class="col-md-4">
						<div class="conter_right_f">
							<div class="tittle-conter-right">
								<p><b>Thông Tin sản phẩm </b></p>
							</div>
							<div class="order-detail">
                                                            <b>Bạn có <?php echo count($arraycart);?> sản phẩm trong giỏ hàng.</b>
								<p style="font-size:12px;">Thanh toán bằng thẻ tín dụng/ghi nợ hoặc ATM nội địa để giảm thêm 10.000 VND trên tổng giá trị đơn hàng (*)</p>
								<table class="table" style="font-size:12px;"> 
									<tbody>
										<tr>
											<th class="left_align">Sản phẩm</th>
											<th class="qty">Số lượng</th>
											<th class="right_align">Giá</th>
										</tr>
                                                                                <?php foreach ($listproduct as $key=>$value){
                                                                                    $qty=$arraycart[$value['id']];
                                                                                     if($value['sale_products']==1){
                                                                                        $price_s = $value['price']-($value['price']*$value['promotions']/100);
                                                                                        }else{
                                                                                        $price_s = $value['price'];
                                                                                        }
                                                                                    $total_money +=$qty*$price_s;
                                                                                    ?>
										<tr class="first_item  no-border  ">
											<td class="no-padding-bottom">
												<div class="product"><?php echo $value['name']?></div>
											</td>
											<td class="qty no-padding-bottom">
											<?php echo $qty; ?>   </td>
											<td class="right_align no-padding-bottom sel-cart-item-total-SO993ELAEN3BVNAMZ-226627">
											<?php echo $qty*$price_s;?>                                                            </td>
										</tr>
                                                                                <?php } ?>
										<tr>
											<td colspan="2" class="subtotal sel-subtotal">Tổng cộng</td>
											<td  class="right_align"><?php echo $total_money;?></td>
										</tr>
										<tr class="total ">
                                                                                   
											<td class="total" colspan="2">
												<b>Thành tiền </b></br>
												<span class="vat-minicart">(Đã bao gồm VAT)</span>
											</td>
											<td  class="total right_align sel-total">
											<?php echo $total_money;?>              </td>
										</tr>
										<tr>
											<td width="115" align="center" valign="top">
												<a href="javascript:void(0)" class="jan_verisign"></a>
											</td>
											<td width="115" align="center" valign="top">
												<span class="seal_verisign"></span>
											</td>
										</tr>
										</tbody>
									
								</table>
							</div>
							
						</div>
					</div>
					
				</div>
				<div class="row">
				<div class="col-md-6">
				<p> Bạn cần hỗ trợ? Gọi Hotline <b>08 3942 1188 hoặc 04 7300 1188 </b></p>
				</div>
				<div class="col-md-6">
				<ul class="footerul_li">
				<li><a> FAQ</a></li>
					<li><a>Chính Sách  Thanh Toán</a></li>
						<li><a> Điều Khoản sử dụng</a></li>
					</ul>
					<p class="copy"> © Copyright 2015</p>
				</div>
				</div>
				
			</div>
			
                    <span id="thoigian-oclock" style="display: none"></span>
		</div>
		
		
		
		
	</body>
</html>