<?php echo $this->doctype(); ?>
<?php 
use Zend\Session\Container; 
$setting = $this->layout()->setting; 
$setting_session = new Container('setting');

?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title><?php echo $setting_session->name;?></title>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
		<meta name="description" content="<?php echo $setting_session->seo_description;?>" />
		<meta name="keywords" content="<?php echo $setting_session->seo_keywords;?>" />
		<meta name="robots" content="INDEX,FOLLOW" />
		<link rel="icon" href="<?php echo WEBPATH_UPLOAD_PATH_IMG.'/'.$setting_session->ico;?>" type="image/x-icon" />
		<link rel="shortcut icon" href="<?php echo WEBPATH_UPLOAD_PATH_IMG.'/'.$setting_session->ico;?>" type="image/x-icon" />
        <link href="<?php echo ROHLIK_LAZADA;?>/css/jquery.mmenu.all.css" rel="stylesheet" type="text/css"/>
        <script src="<?php echo ROHLIK_LAZADA;?>/js/jquery-2.1.3.js" type="text/javascript"></script>
        <script src="<?php echo ROHLIK_LAZADA;?>/js/bootstrap.min.js" type="text/javascript"></script>
        <link href="<?php echo ROHLIK_LAZADA;?>/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo ROHLIK_LAZADA;?>/fonts/font-awesome.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo ROHLIK_LAZADA;?>/css/style.css" rel="stylesheet" type="text/css"/>


        <script src="<?php echo ROHLIK_LAZADA;?>/js/jquery.mmenu.min.all.js" type="text/javascript"></script>


        <script>
   
            function scrollWin(x, y) {
                window.scrollBy(x, y);
            }
        </script>

        <script type="text/javascript">

            $(function () {
                $("#menu")
                        .mmenu({
                        })
                        .on("click", "a[href=\"#\"]",
                                function () {
                                    //alert("Thank you for clicking, but that's a demo link.");
                                    return false;
                                }
                        );
            });
        </script>

        <script>
            $(function () {
                $('#house a').click(function () {
                    $('.box-danngnhap').toggle();
                });
            });

            $(function () {

                /*$('.video-tv').click(function(){
                 $(".box-khuyenmai").hide();
                 $('.box-tivi-video').show();
                 });*/
                $('#tab-menu li a').hover(function () {
                    $('#tab-menu li a').removeAttr('class');
                    $('.div-tab').hide();
                    var showtab = $(this).attr("rel");
                    console.log(showtab);
                    var active = showtab.replace("#", "");
                    //alert(active);
                    $(this).addClass('active-box');
                    $(showtab).show();
                });
                $('.show-div').click(function () {

                });
            });



            /*   --------------------------------------------------- */


            /*   --------------------------------------------------- */
            function showdiv(key) {
                $('html, body').animate({scrollTop: $('#tang-' + key).position().top - 30}, 'slow');


            }

            /*   --------------------------------------------------- */
            function showDiv() {
                if ($(window).scrollTop() > 100) {
                    $(".logo-timkiem-mua-fluid").css({"position": "fixed", "top": "0px"});
                } else {
                    $(".logo-timkiem-mua-fluid").css({"position": "relative", "top": "0px"});
                }
            }
            $(window).scroll(showDiv);
            showDiv();
        </script>
    </head>
    <body>

        <nav id="menu">
            <ul>
                <li><a href="#about"> <i class="fa fa-bullhorn"></i> KHUYẾN MÃI TẠI ABC</a>
                    <ul>
                        <li><a href="#about/history">Khuyến Mãi Đặc Biệt</a></li>
                        <li><a href="#about/team">Stuhrling - Giảm Sốc </a>                        </li>
                        <li><a href="#about/address">Tã Giấy - Giảm 30% </a></li>
                        <li><a href="#about/address">Khuyến Mãi Lớn Cho Mọi Nhà </a></li>
                        <li><a href="#about/address">Máy Lạnh, Máy Giặt, Tủ Lạnh Giá Sốc </a></li>
                        <li><a href="#about/address">Hàng Thể Thao Giảm Đến 50%</a></li>
                        <li><a href="#about/address">Hàng Ô Tô Xe Máy Giảm Đến 50%</a></li>
                        <li><a href="#about/address">Đẹp Tiết Kiệm - Tại Sao Không?</a></li>
                    </ul>
                </li>
                <li><a href="#about"><i class="fa fa-mobile"></i> ĐIỆN THOẠI & TABLET</a>
                    <ul>
                        <li><a href="#about/history">Smartphones</a></li>
                        <li><a href="#about/history">Điện Thoại Phổ Thông</a></li>

                        <li><a href="#about/team">Máy Tính Bảng</a>
                            <ul>
                                <li><a href="#">Máy tính bảng (hỗ trợ chức năng thoại)</a></li>
                                <li><a href="#about/team/sales">Máy tính bảng (không hỗ trợ chức năng thoại)</a></li>

                            </ul>
                        </li>
                        <li><a href="#about/team">Phụ Kiện Điện Thoại</a>
                            <ul>
                                <li><a href="#about/team/management">Vỏ & bao điện thoại</a></li>
                                <li><a href="#about/team/sales">Pin & Bộ sạc</a></li>
                                <li><a href="#about/team/sales">Thẻ nhớ</a></li>

                            </ul>
                        </li>
                        <li><a href="#about/history">Phụ Kiện Máy Tính Bảng</a></li>
                        <li><a href="#about/team">Điện Thoại Bàn</a>
                            <ul>
                                <li><a href="#about/team/management">Điện thoại SamSung</a></li>
                                <li><a href="#about/team/sales">Điện thoại Asus (Zenfone...)</a></li>
                                <li><a href="#about/team/sales">BlackBerry</a></li>

                            </ul>
                        </li>
                        <li><a href="#about/team">Thương Hiệu Nổi Bật</a>
                            <ul>
                                <li><a href="#about/team/management">HTC</a></li>
                                <li><a href="#about/team/sales">Apple (iPhone, iPad)</a></li>
                                <li><a href="#about/team/sales">Điện thoại Nokia</a></li>

                            </ul>
                        </li>

                    </ul>
                </li>
                <li><a href="#about"><i class="fa fa-microphone"></i> TIVI, VIDEO & ÂM THANH</a>
                    <ul>

                        <li><a href="#about/team">Hệ Thống Âm Thanh</a>

                            <ul>
                                <li><a href="#about/team/management">Tai nghe (Có dây, bluetooth)</a></li>
                                <li><a href="#about/team/sales">Loa máy tính</a></li>
                                <li><a href="#about/team/development">Dàn loa, Đầu Karaoke...</a></li>
                                <li><a href="#about/team/development">Máy MP3 và iPod</a></li>
                                <li><a href="#about/team/development">Phụ kiện âm thanh</a></li>
                            </ul>
                        </li>
                        <li><a href="#about/address">Tivi Giá Đặc Biệt Dành Cho Khách Hàng TP.HCM </a></li>
                        <li><a href="#about/team">TV & Đầu Đĩa</a>

                            <ul>
                                <li><a href="#about/team/management">Phụ kiện (Cáp, Remote, TV Box, Micro...)</a></li>
                                <li><a href="#about/team/sales">Tivi</a></li>
                                <li><a href="#about/team/development">Đầu đĩa DVD, Blu-ray & HD</a></li>
                                <li><a href="#about/team/development">Máy chiếu</a></li>

                            </ul>
                        </li>
                        <li><a href="#about/team">Game (Chuột, Bàn Phím, Đĩa Game...)</a>

                            <ul>
                                <li><a href="#about/team/management">Máy chơi Game</a></li>


                            </ul>
                        </li>
                        <li><a href="#about/team">Thiết Bị Điện Tử Tiện Ích</a>

                            <ul>
                                <li><a href="#about/team/management">Đồng hồ thông minh</a></li>
                                <li><a href="#about/team/management">Thuốc lá điện tử</a></li>
                                <li><a href="#about/team/management">Khác </a></li>


                            </ul>
                        </li>

                    </ul>
                </li>
                <li><a href="#about"><i class="fa fa-laptop"></i>  MÁY VI TÍNH & LAPTOP</a>
                    <ul>
                        <li><a href="#about/history">Laptop</a></li>
                        <li><a href="#about/history">Máy Tính Để Bàn</a></li>
                        <li><a href="#about/team">Phụ Kiện Máy Tính (Chuột, Bàn Phím, Usb, Túi Xách...)</a>
                            <ul>
                                <li><a href="#about/team/management">Ổ Cứng Gắn Ngoài</a></li>
                                <li><a href="#about/team/sales">USB</a></li>
                                <li><a href="#about/team/development">Chuột</a></li>
                                <li><a href="#about/team/development">Bàn phím</a></li>
                                <li><a href="#about/team/development">Màn hình</a></li>
                            </ul>
                        </li>
                        <li><a href="#about/address">Linh Kiện Máy Tính (Ram, Bo Mạch, Quạt...)</a></li>
                        <li><a href="#about/address">Thiết Bị Mạng (USB 3G, Router Wifi...)</a></li>
                        <li><a href="#about/address">Máy In & Mực In</a></li>
                        <li><a href="#about/team">Thương Hiệu Nổi Bật</a>
                            <ul>
                                <li><a href="#about/team/management">Laptop Asus</a></li>
                                <li><a href="#about/team/sales">Laptop Acer</a></li>
                                <li><a href="#about/team/development">Laptop Dell</a></li>
                                <li><a href="#about/team/development">Laptop HP</a></li>
                                <li><a href="#about/team/development">Laptop Lenovo</a></li>
                                <li><a href="#about/team/development">Laptop Macbook</a></li>
                                <li><a href="#about/team/development">Laptop Sony</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li><a href="#about"><i class="fa fa-archive"></i> ĐỒ GIA DỤNG</a>
                    <ul>

                        <li><a href="#about/team">Đồ Gia Dụng Nhà Bếp</a>
                            <ul>
                                <li><a href="#about/team/management">Máy xay & ép trái cây</a></li>
                                <li><a href="#about/team/sales">Các loại nồi điện</a></li>
                                <li><a href="#about/team/development">Nồi áp suất điện</a></li>
                                <li><a href="#about/team/development">Ấm siêu tốc</a></li>

                            </ul>
                        </li>
                        <li><a href="#about/team">Đồ Gia Dụng Lớn</a>
                            <ul>
                                <li><a href="#about/team/management">Lò vi sóng & Lò nướng</a></li>
                                <li><a href="#about/team/sales">Tủ lạnh</a></li>
                                <li><a href="#about/team/development">Máy giặt</a></li>


                            </ul>
                        </li>
                        <li><a href="#about/address">Hướng Dẫn Mua Hàng </a></li>

                        <li><a href="#about/team">Dụng Cụ & Thiết Bị Gia Đình</a>
                            <ul>
                                <li><a href="#about/team/management">Máy hút bụi cầm tay</a></li>
                                <li><a href="#about/team/sales">Máy hút bụi có túi & không túih</a></li>
                                <li><a href="#about/team/development">Chổi & Cây lau sàn</a></li>


                            </ul>
                        </li>
                        <li><a href="#about/team">Thiết Bị Chăm Sóc Quần Áo</a>
                            <ul>
                                <li><a href="#about/team/management">Bàn ủi</a></li>
                                <li><a href="#about/team/sales">Máy may</a></li>
                                <li><a href="#about/team/development">Quạt</a></li>


                            </ul>
                        </li>
                        <li><a href="#about/team">Quạt & Máy Nóng Lạnh</a>
                            <ul>
                                <li><a href="#about/team/management">Máy lạnh</a></li>
                                <li><a href="#about/team/sales">Máy nước nóng</a></li>



                            </ul>
                        </li>
                    </ul>
                </li>
                <li><a href="#about"><i class="fa fa-camera"></i> MÁY ẢNH & MÁY QUAY PHIM</a>
                    <ul>
                        <li><a href="#about/history">Máy Ảnh Du Lịch</a></li>
                        <li><a href="#about/history">Máy Ảnh Cao Cấp</a></li>
                        <li><a href="#about/history">Máy Ảnh Chụp Lấy Ngay</a></li>
                        <li><a href="#about/history">Máy Ảnh Không Gương Lật</a></li>
                        <li><a href="#about/history">Máy Ảnh DSLR/SLR</a></li>
                        <li><a href="#about/history">Các Loại Máy Ảnh Khác</a></li>
                        <li><a href="#about/history">Máy Quay Phim</a></li>
                        <li><a href="#about/team">Phụ Kiện</a>
                            <ul>
                                <li><a href="#about/team/management">Chân máy ảnh (Tripod)</a></li>
                                <li><a href="#about/team/sales">Đèn flash</a></li>
                                <li><a href="#about/team/development">Ống kính</a></li>
                                <li><a href="#about/team/development">Kính lọc</a></li>
                                <li><a href="#about/team/development">Pin Máy Ảnh</a></li>
                                <li><a href="#about/team/development">Túi đựng máy ảnh</a></li>
                            </ul>
                        </li>

                    </ul>
                </li>
                <li><a href="#contact"><i class="fa fa-home"></i> NHÀ CỬA & ĐỜI SỐNG </a>
                    <ul>
                        <li><a href="#about/history">Tham Quan Mua Sắm</a></li>
                        <li><a href="#about/history">Khuyến Mãi Đặc Biệt </a></li>
                        <li><a href="#about/team">Bếp & Phòng Ăn</a>
                            <ul>
                                <li><a href="#about/team/management">Đồ dùng nấu bếp</a></li>
                                <li><a href="#about/team/sales">Đồ dùng bàn ăn</a></li>
                                <li><a href="#about/team/development">Phụ kiện & dụng cụ nhà bếp</a></li>
                            </ul>
                        </li>
                        <li><a href="#about/team">Tân Trang Nhà Cửa</a>
                            <ul>
                                <li><a href="#about/team/management">Dụng cụ & thiết bị</a></li>
                                <li><a href="#about/team/sales">Dụng cụ cầm tay</a></li>

                            </ul>
                        </li>
                        <li><a href="#about/address">Chăn Ra Gối Nệm</a></li>
                        <li><a href="#about/address">Ngoài Trời & Sân Vườn</a></li>
                        <li><a href="#about/address">Trang Trí Nhà Cửa</a></li>
                        <li><a href="#about/address">Đồ Dùng Phòng Tắm</a></li>
                        <li><a href="#about/address">Tủ Đựng & Sắp Xếp Đồ</a></li>
                        <li><a href="#about/address">Văn Phòng Phẩm</a></li>
                        <li><a href="#about/address">100 Sản Phẩm Bán Chạy</a></li>
                        <li><a href="#about/team">Thương Hiệu Hàng Đầu</a>
                            <ul>
                                <li><a href="#about/team/management">Luminarc</a></li>
                                <li><a href="#about/team/management">Edena</a></li>
                                <li><a href="#about/team/management">Moriitalia</a></li>
                                <li><a href="#about/team/sales">Skil</a></li>

                            </ul>
                        </li>
                    </ul>
                </li>
                <li><a href="#contact"><i class="fa fa-suitcase"></i> THỜI TRANG PHỤ KIỆN </a>
                    <ul>
                        <li><a href="#about/history">Xu Hướng Thời Trang</a></li>
                        <li><a href="#about/team">Thời Trang Nữ</a>
                            <ul>
                                <li><a href="#about/team/management">Túi xách nữ</a></li>
                                <li><a href="#about/team/sales">Trang phục lót</a></li>
                                <li><a href="#about/team/development">Trang phục nữ</a></li>
                            </ul>
                        </li>
                        <li><a href="#about/team">Giày Nữ</a>
                            <ul>
                                <li><a href="#about/team/management">Giày cao gót</a></li>
                                <li><a href="#about/team/sales">Giày đế bằng</a></li>
                                <li><a href="#about/team/development">Giày đế xuồng</a></li>
                                <li><a href="#about/team/development">Xăng đan & Dép</a></li>
                            </ul>
                        </li>
                        <li><a href="#about/team">Thời Trang Nam</a>
                            <ul>
                                <li><a href="#about/team/management">Hàng mới về</a></li>
                                <li><a href="#about/team/sales">Trang phục lót</a></li>
                                <li><a href="#about/team/development">Túi xách nam</a></li>
                            </ul>
                        </li>
                        <li><a href="#about/team">Giày Nam</a>
                            <ul>
                                <li><a href="#about/team/management">Giày Casual</a></li>
                                <li><a href="#about/team/sales">Xăng đan & Dép</a></li>
                                <li><a href="#about/team/development">Giày đế bằng</a></li>
                                <li><a href="#about/team/development">Phong cách phái mạnh</a></li>
                            </ul>
                        </li>

                    </ul>
                </li>
                <li><a href="#contact"><i class="fa fa-heart-o"></i> MẸ & BÉ </a>
                    <ul>
                        <li><a href="#about/history">Xả Hàng Cuối Năm</a></li>
                        <li><a href="#about/history">Khuyến Mãi Giá Tốt HOT</a></li>
                        <li><a href="#about/history">Sản Phẩm Bán Chạy</a></li>

                        <li><a href="#about/team">Lần Đầu Làm Mẹ</a>
                            <ul>
                                <li><a href="#about/team/management">Chăm sóc bà mẹ mang thai</a></li>

                            </ul>
                        </li>

                        <li><a href="#about/team">Trẻ Sơ Sinh</a>
                            <ul>
                                <li><a href="#about/team/management">Tã và dụng cụ vệ sinh</a></li>
                                <li><a href="#about/team/management">Đồ dùng bú sữa & ăn dặm</a></li>
                                <li><a href="#about/team/management">Sữa & thức ăn dặm</a></li>
                                <li><a href="#about/team/management">Xe đẩy, địu, ghế ăn</a></li>
                                <li><a href="#about/team/management">Đồ dùng phòng ngủ</a></li>
                                <li><a href="#about/team/management">Tắm & chăm sóc trẻ sơ sinh</a></li>
                                <li><a href="#about/team/management">Quần áo trẻ sơ sinh</a></li>

                            </ul>
                        </li>
                        <li><a href="#about/team">Đồ Chơi</a>
                            <ul>
                                <li><a href="#about/team/management">Đồ chơi lắp ráp & xây dựng</a></li>
                                <li><a href="#about/team/management">Đồ chơi giáo dục</a></li>
                                <li><a href="#about/team/management">Đồ chơi gỗ</a></li>
                                <li><a href="#about/team/management">Thủ công & Nghệ thuật</a></li>
                                <li><a href="#about/team/management">Xe mô hình và điều khiển</a></li>
                            </ul>
                        </li>
                        <li><a href="#about/team">Thương Hiệu Hàng Đầu</a>
                            <ul>
                                <li><a href="#about/team/management">Huggies</a></li>
                                <li><a href="#about/team/management">Bobby</a></li>
                                <li><a href="#about/team/management">Lego</a></li>

                            </ul>
                        </li>

                    </ul>
                </li>
                <li><a href="#contact"><i class="fa fa-smile-o"></i> SỨC KHỎE & SẮC ĐẸP</a>
                    <ul>

                        <li><a href="#about/team">Trang Điểm</a>
                            <ul>
                                <li><a href="#about/team/management">Chăm sóc da mặt</a></li>
                            </ul>
                        </li>
                        <li><a href="#about/team">Chăm Sóc Mặt</a>
                            <ul>
                                <li><a href="#about/team/management">Chăm sóc da vùng mắt</a></li>
                            </ul>
                        </li>
                        <li><a href="#about/team">Chăm Sóc Tóc</a>
                            <ul>
                                <li><a href="#about/team/management">Nước hoa dành cho nữ</a></li>
                            </ul>
                        </li>
                        <li><a href="#about/team">Nước Hoa</a>
                            <ul>
                                <li><a href="#about/team/management">Nước hoa dành cho nam</a></li>
                            </ul>
                        </li>
                        <li><a href="#about/address">Bộ Quà Tặng</a></li>
                        <li><a href="#about/address">Tắm & Chăm Sóc Cơ Thể</a></li>
                        <li><a href="#about/address">Dành Cho Nam Giới</a></li>
                        <li><a href="#about/address">Chăm Sóc Cá Nhân & Sức Khỏe</a></li>
                        <li><a href="#about/address">Dụng Cụ Chăm Sóc Sức Khỏe & Sắc Đẹp</a></li>
                        <li><a href="#about/address">Thực Phẩm Chức Năng & Kiểm Soát Cân Nặng Mới</a></li>
                        <li><a href="#about/address">Sản Phẩm Hỗ Trợ Tình Dục</a></li>
                        <li><a href="#about/address">Thiết Bị Y Tế</a></li>
                        <li><a href="#about/address">Đồ Định Hình</a></li>
                    </ul>
                </li>
                <li><a href="#contact"><i class="fa fa-automobile"></i> OTO, XE MÁY & PHỤ KIỆN </a>
                    <ul>

                        <li><a href="#about/team">Khuyến Mãi HOT</a>
                            <ul>
                                <li><a href="#about/team/management">Phụ kiện Ô tô Xe máy HOT nhất</a></li>
                                <li><a href="#about/team/sales">Xe đẹp rước nàng</a></li>
                                <li><a href="#about/team/development">Mũ bảo hiểm</a></li>
                            </ul>
                        </li>
                        <li><a href="#about/team">Xe Máy</a>
                            <ul>
                                <li><a href="#about/team/management">Đồ bảo hộ mô tô, xe máy</a></li>
                                <li><a href="#about/team/sales">Khóa chống trộm xe máy</a></li>
                                <li><a href="#about/team/development">Phụ tùng xe máy</a></li>
                            </ul>
                        </li>
                        <li><a href="#about/team">Ô Tô</a>
                            <ul>
                                <li><a href="#about/team/management">Thiết bị định vị, dẫn đường</a></li>
                                <li><a href="#about/team/sales">Hỗ trợ khởi động & pin cầm tay</a></li>
                                <li><a href="#about/team/development">Dụng cụ khẩn cấp cho xe</a></li>
                                <li><a href="#about/team/development">Bơm lốp xe</a></li>
                                <li><a href="#about/team/development">Đèn & Phụ kiện</a></li>
                                <li><a href="#about/team/development">Camera hành trình & Thiết bị điện tử</a></li>
                                <li><a href="#about/team/development">Chăm sóc xe hơi</a></li>
                                <li><a href="#about/team/development">Đồ chơi xe hơi</a></li>
                                <li><a href="#about/team/development">Nội thất ô tô</a></li>
                                <li><a href="#about/team/development">Thế giới mùi thơm</a></li>
                            </ul>
                        </li>

                    </ul>
                </li>
                <li><a href="#contact"><i class="fa fa-gamepad"></i> THỂ THAO & DÃ NGOẠI </a>
                    <ul>
                        <li><a href="#about/history">Khuyễn Mãi Đặc Biệt</a></li>
                        <li><a href="#about/team">Yoga & Thể Hình</a>
                            <ul>
                                <li><a href="#about/team/management">Yoga</a></li>
                                <li><a href="#about/team/sales">Máy Tập Thể Hình</a></li>
                                <li><a href="#about/team/development">Máy Tập Thể Lực</a></li>
                            </ul>
                        </li>
                        <li><a href="#about/team">Giày Và Trang Phục</a>
                            <ul>
                                <li><a href="#about/team/management">Dành Cho Nữ</a></li>
                                <li><a href="#about/team/sales">Dành Cho Nam</a></li>

                            </ul>
                        </li>
                        <li><a href="#about/team">Tập Luyện Cá Nhân</a>
                            <ul>
                                <li><a href="#about/team/management">Tennis</a></li>
                                <li><a href="#about/team/sales">Bóng Bàn</a></li>
                                <li><a href="#about/team/development">Cầu Lông</a></li>
                                <li><a href="#about/team/development">Golf</a></li>
                                <li><a href="#about/team/development">Bơi Lội</a></li>
                                <li><a href="#about/team/development">Boxing</a></li>
                            </ul>
                        </li>
                        <li><a href="#about/team">Thể Thao Đồng Đội</a>
                            <ul>
                                <li><a href="#about/team/management">Bóng Đá</a></li>
                                <li><a href="#about/team/sales">Bóng Rổ</a></li>
                                <li><a href="#about/team/development">Bóng Chuyền</a></li>
                            </ul>
                        </li>
                        <li><a href="#about/team">Hoạt Động Dã Ngoại</a>
                            <ul>
                                <li><a href="#about/team/management">Dã Ngoại & Leo Núi</a></li>
                                <li><a href="#about/team/sales">Xe Đạp</a></li>
                                <li><a href="#about/team/development">Thể Thao Dưới Nước</a></li>
                            </ul>
                        </li>

                    </ul>
                </li>

            </ul>
        </nav>
        <header>

            <nav class="navbar navbar-default thaydoinavbar">
                <div class="container-fluid domaumenufluid">
                    <div class="container">
                        <div class="row row-menu-top">
                            <div class="col-sm-12 menu-top-top">
                                <div class="col-sm-3 header-top-left"></div>

                                <div class="col-sm-9 header-top-right">
                                    <div class="container-fluid">
                                        <!-- Brand and toggle get grouped for better mobile display -->
                                        <div class="navbar-header header-trencung-mobi">
                                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                                <span class="sr-only">Toggle navigation</span>
                                                <span class="icon-bar"></span>
                                                <span class="icon-bar"></span>
                                                <span class="icon-bar"></span>
                                            </button>
                                            <a class="navbar-brand" href="#">
                                                <img alt="Brand name" src="<?php echo ROHLIK_LAZADA;?>/img/header/logo_nho.png"  />
                                            </a>
                                        </div>

                                        <!-- Collect the nav links, forms, and other content for toggling -->
                                        <div class="collapse navbar-collapse menu-container" id="bs-example-navbar-collapse-1">
                                            <ul class="nav navbar-nav ulmenu">

                                                <li class="dropdown">
                                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">CHĂM SÓC KHÁCH HÀNG <span class="caret"></span></a>
                                                    <ul class="dropdown-menu" role="menu">
                                                        <li><a href="#"><i class="fa fa-caret-right"></i> Trung tâm hỗ trợ</a></li>
                                                        <li><a href="#"><i class="fa fa-caret-right"></i> Đơn hàng & Thanh toán</a></li>
                                                        <li><a href="#"><i class="fa fa-caret-right"></i> Giao hàng & Nhận hàng</a></li>
                                                        <li><a href="#"><i class="fa fa-caret-right"></i> Đổi trả hàng & Hoàn tiền <button class="btn-danger">Mới</button></a></li>
                                                    </ul>
                                                </li>
                                                <li class="dropdown" id="house">
                                                    <a href="#" class="dropdown"  data-toggle="dropdown" role="button" >KIỂM TRA ĐƠN HÀNG <span class="caret"></span></a>


                                                    <div class="box-danngnhap">
                                                        <div class="col-sm-12 margin-top-bottom">
                                                            <div class="col-sm-12 box-tieude-login">
                                                                <span class="text-tieude-login">  ĐĂNG NHẬP</span>
                                                            </div>
                                                            <div class="col-sm-12 margin-top">
                                                                <span class="text-thuong">Vui lòng nhập mã đơn hàng:</span>
                                                            </div>
                                                            <div class="col-sm-12">
                                                                <input type="text" class="form-control">
                                                            </div>
                                                            <div class="col-sm-12 margin-top">
                                                                <span class="text-thuong"> Vui lòng nhập địa chỉ email:</span>
                                                            </div>
                                                            <div class="col-sm-12">
                                                                <input type="text" class="form-control">
                                                            </div>
                                                            <div class="col-sm-12 margin-top">
                                                                <span class="text-thuong">  Nếu bạn có thắc mắc nào khác, <a href="#"><span class="maudo">Nhấn vào đây</span></a></span>
                                                            </div>
                                                            <div class="col-sm-12 margin-top">
                                                                <button class="btn btn-success btnkiemtra">  Kiểm tra</button>
                                                            </div>


                                                        </div>
                                                    </div>       



                                                </li>

                                                <li class="dropdown">

                                                    <!-- Large modal -->
                                                    <a data-toggle="modal" data-target=".popup_dangki">ĐĂNG KÍ<span class="caret"></span></a>

                                                    <div class="modal fade bs-example-modal-lg popup_dangki" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                                                        <div class="modal-dialog modal-lg">
                                                            <div class="modal-content dangki-vuavua">
                                                                <div class="row">
                                                                    <div class="col-sm-12 margin-top-bottom">
                                                                        <div class="col-sm-12 box-tieude-login">
                                                                            <span class="text-tieude-login">ĐĂNG KÍ</span>
                                                                        </div>
                                                                        <div class="col-sm-12 margin-top">
                                                                            <div class="col-sm-3 box-text-label">Họ Tên : <span class="maudo">*</span> </div>
                                                                            <div class="col-sm-9">
                                                                                <input type="text" class="form-control" id="inputSuccess1">
                                                                            </div>
                                                                        </div>
                                                                        <div class="col-sm-12 margin-top">
                                                                            <div class="col-sm-3 box-text-label">Email : <span class="maudo">*</span> </div>
                                                                            <div class="col-sm-9">
                                                                                <input type="text" class="form-control" id="inputSuccess1">
                                                                            </div>
                                                                        </div>
                                                                        <div class="col-sm-12 margin-top">
                                                                            <div class="col-sm-3 box-text-label">Mật Khẩu : <span class="maudo">*</span> </div>
                                                                            <div class="col-sm-9">
                                                                                <input type="text" class="form-control" id="inputSuccess1">
                                                                            </div>
                                                                        </div>
                                                                        <div class="col-sm-12">
                                                                            <div class="col-sm-3"></div>
                                                                            <div class="col-sm-9">
                                                                                <span>ít nhất gồm 6 kí tự gồm chữ và số</span>
                                                                            </div>
                                                                        </div>
                                                                        <div class="col-sm-12 margin-top">
                                                                            <div class="col-sm-3 box-text-label">Nhập lại MK : <span class="maudo">*</span></div>
                                                                            <div class="col-sm-9">
                                                                                <input type="text" class="form-control" id="inputSuccess1">
                                                                            </div>
                                                                        </div>
                                                                        <div class="col-sm-12 margin-top">
                                                                            <div class="col-sm-3 box-text-label">Ngày sinh :</div>
                                                                            <div class="col-sm-3"> 
                                                                                <select class="form-control">

                                                                                    <option>1950</option>
                                                                                    <option>1951</option>
                                                                                    <option>1952</option>
                                                                                    <option>1953</option>
                                                                                    <option>1954</option>
                                                                                    <option>1955</option>
                                                                                    <option>1956</option>
                                                                                    <option>1957</option>
                                                                                    <option>1958</option>
                                                                                    <option>1959</option>
                                                                                    <option>1960</option>
                                                                                    <option>1961</option>
                                                                                    <option>1962</option>
                                                                                    <option>1963</option>
                                                                                    <option>1964</option>
                                                                                    <option>1965</option>
                                                                                    <option>1966</option>
                                                                                    <option>1967</option>
                                                                                    <option>1968</option>
                                                                                    <option>1969</option>
                                                                                    <option>1970</option>
                                                                                    <option>1971</option>
                                                                                    <option>1972</option>
                                                                                    <option>1973</option>
                                                                                    <option>1974</option>
                                                                                    <option>1975</option>
                                                                                    <option>1976</option>
                                                                                    <option>1977</option>
                                                                                    <option>1978</option>
                                                                                    <option>1979</option>
                                                                                    <option>1980</option>
                                                                                    <option>1981</option>
                                                                                    <option>1982</option>
                                                                                    <option>1983</option>
                                                                                    <option>1984</option>
                                                                                    <option>1985</option>
                                                                                    <option>1986</option>
                                                                                    <option>1987</option>
                                                                                    <option>1988</option>
                                                                                    <option>1989</option>
                                                                                    <option>1990</option>
                                                                                    <option>1991</option>
                                                                                    <option>1992</option>
                                                                                    <option>1993</option>
                                                                                    <option>1994</option>
                                                                                    <option>1995</option>
                                                                                    <option>1996</option>
                                                                                    <option>1997</option>
                                                                                    <option>1998</option>
                                                                                    <option>1999</option>
                                                                                    <option>2000</option>
                                                                                    <option>2001</option>
                                                                                    <option>2002</option>
                                                                                    <option>2003</option>
                                                                                    <option>2004</option>
                                                                                    <option>2005</option>
                                                                                    <option>2006</option>
                                                                                </select>
                                                                            </div>
                                                                            <div class="col-sm-3 media-margin">
                                                                                <select class="form-control">
                                                                                    <option>January</option>
                                                                                    <option>February</option>
                                                                                    <option>March</option>
                                                                                    <option>April</option>
                                                                                    <option>May</option>
                                                                                    <option>June</option>
                                                                                    <option>July</option>
                                                                                    <option>August</option>
                                                                                    <option>September</option>
                                                                                    <option>October</option>
                                                                                    <option>November</option>
                                                                                    <option>December</option>
                                                                                </select>
                                                                            </div>
                                                                            <div class="col-sm-3 media-margin">
                                                                                <select class="form-control">
                                                                                    <option>01</option>
                                                                                    <option>02</option>
                                                                                    <option>03</option>
                                                                                    <option>04</option>
                                                                                    <option>05</option>
                                                                                    <option>06</option>
                                                                                    <option>07</option>
                                                                                    <option>08</option>
                                                                                    <option>09</option>
                                                                                    <option>10</option>
                                                                                    <option>11</option>
                                                                                    <option>12</option>
                                                                                    <option>13</option>
                                                                                    <option>14</option>
                                                                                    <option>15</option>
                                                                                    <option>16</option>
                                                                                    <option>17</option>
                                                                                    <option>18</option>
                                                                                    <option>19</option>
                                                                                    <option>21</option>
                                                                                    <option>22</option>
                                                                                    <option>23</option>
                                                                                    <option>24</option>
                                                                                    <option>25</option>
                                                                                    <option>26</option>
                                                                                    <option>27</option>
                                                                                    <option>28</option>
                                                                                    <option>29</option>
                                                                                    <option>30</option>

                                                                                </select>
                                                                            </div>
                                                                        </div>

                                                                        <div class="col-sm-12 margin-top">
                                                                            <div class="col-sm-3 box-text-label">Giới Tính :</div>
                                                                            <div class="col-sm-9">
                                                                                <select class="form-control">
                                                                                    <option>Nam</option>
                                                                                    <option>Nữ</option>
                                                                                </select>
                                                                            </div>
                                                                        </div>

                                                                        <div class="col-sm-12 margin-top">
                                                                            <div class="col-sm-3"></div>
                                                                            <div class="col-sm-6">
                                                                                <span class="text-thuong">  Tôi đã đọc và đồng ý với <span class="maudo">các điều khoản của ABC</span></span>
                                                                            </div>
                                                                            <div class="col-sm-3">

                                                                                <span class="text-thuong"> (<span class="maudo">*</span>) Thông tin bắt buộc</span>
                                                                            </div>

                                                                        </div>
                                                                        <div class="col-sm-12 margin-top">
                                                                            <div class="col-sm-3"></div>
                                                                            <div class="col-sm-9">
                                                                                <button class="btn btn-danger">Đăng Kí</button>
                                                                            </div>
                                                                        </div>

                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </li>

                                                <li class="dropdown">

                                                    <a data-toggle="modal" data-target=".bs-example-modal-sm">ĐĂNG NHẬP<span class="caret"></span></a>

                                                    <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                                                        <div class="modal-dialog modal-sm">
                                                            <div class="modal-content dangnhap-reponsive">
                                                                <div class="row">
                                                                    <div class="col-sm-12 margin-top-bottom">
                                                                        <div class="col-sm-12 box-tieude-login">
                                                                            <span class="text-tieude-login">ĐĂNG NHẬP</span>
                                                                        </div>
                                                                        <div class="col-sm-12 margin-top-nopading">
                                                                            <div class="col-sm-4 box-text-label">Email: <span class="maudo">*</span></div>
                                                                            <div class="col-sm-8">
                                                                                <input type="text" class="form-control" id="inputSuccess1">
                                                                            </div>
                                                                        </div>
                                                                        <div class="col-sm-12 margin-top-nopading">
                                                                            <div class="col-sm-4 box-text-label">Mật Khẩu:<span class="maudo">*</span></div>
                                                                            <div class="col-sm-8">
                                                                                <input type="text" class="form-control" id="inputSuccess1">
                                                                            </div>
                                                                        </div>
                                                                        <div class="col-sm-12 margin-top">
                                                                            <div class="col-sm-3"></div>
                                                                            <div class="col-sm-5 box-wuenmatkhau-dangnhap">
                                                                                <a href="#">Quên mật khẩu?</a>
                                                                            </div>
                                                                            <div class="col-sm-4 box-wuenmatkhau-dangnhap">
                                                                                <a href="#"> Đăng Kí</a>
                                                                            </div>
                                                                        </div>
                                                                        <div class="col-sm-12 margin-top-nopading">
                                                                            <div class="col-sm-4"></div>
                                                                            <div class="col-sm-8">
                                                                                <button class="btn btn-danger">ĐĂNG NHẬP</button>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </li>

                                            </ul>


                                        </div><!-- /.navbar-collapse -->
                                    </div>
                                </div><!-- /.container-fluid -->

                            </div>
                        </div>
                    </div>
                </div>
            </nav>
            <div class="container-fluid logo-timkiem-mua-fluid">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12 menu-top-giua">
                            <div class="col-sm-2 box-chua_logo">
                                <img src="<?php echo ROHLIK_LAZADA;?>/img/header/vn.png"  class="img-responsive anhlogo" alt="#">
                            </div>
                            <div class="col-sm-6 box-chua-search">
                                <div class="input-group input-group-lg">
                                    <input type="text" class="form-control input-search" placeholder="Tìm kiếm theo sản phẩm, danh mục...." aria-describedby="sizing-addon1">
                                    <span class="input-group-addon button-timkiem" id="sizing-addon1"><span class="timkiem_an">Tìm kiếm</span><i class="fa fa-search fa-timkiem"></i></span>

                                </div>
                            </div>
                            <div class="col-sm-2 box-chua_thanhtoan">
                                <div class="box-thanhtoan">
                                    <span class="text-giohang">1</span>
                                    <img src="<?php echo ROHLIK_LAZADA;?>/img/header/thanhtoan.png"  class="anh-thanhtoan" alt="#">

                                </div>
                            </div>
                            <div class="col-sm-2 oclock-header">

                                <div class="thoigian-oclock">08:48:53</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-fluid menu-top-nho-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12 menu-group-menu-header-bottom"> 
                            <div class="col-sm-2">

                            </div>
                            <div class="col-sm-8 menu-header-bottom">
                                <menu>
                                    <ul>
                                        <li> <a href="#">Xu hướng</a></li>
                                        <li><a href="#">Voucher</a></li>
                                        <li><a href="#">Tai nghe</a></li>
                                        <li><a href="#">Đồng hồ</a></li>
                                        <li><a href="#">Iphone 6</a></li>
                                        <li><a href="#">Iphone 4s</a></li>
                                        <li><a href="#">Nokia</a></li>
                                        <li><a href="#">Loa vi tính</a></li>
                                    </ul>
                                </menu>
                            </div>
                            <div class="col-sm-2">
                                <span class="text-header-bottom-right">Daily Deals mới, khám phá ngay <i class="fa fa-arrow-circle-o-right"></i></span>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </header>
        
        
        
        	<?php echo $this->content; ?>
        	
       <footer>
            <div class="container box-an-360">
                <div class="row margin-top">
                    <div class="col-sm-3">
                        <div class="col-sm-12 Ten-muc-footer-top">CHĂM SÓC KHÁCH HÀNG</div>
                        <div class="col-sm-12 menu-footer-chua-link">
                            <ul>
                                <li><a href="#">Trung tâm hỗ trợ</a></li>
                                <li><a href="#">Thanh toán</a></li>
                                <li><a href="#">Hướng dẫn đặt hàng</a></li>
                                <li><a href="#">Giao hàng & Nhận hàng</a></li>
                                <li><a href="#">Hướng dẫn đổi trả hàng</a></li>
                                <li><a href="#">Bảo hành</a></li>
                            </ul>
                        </div>
                        <div class="col-sm-12 menu-footer-khong-chua-link">
                            <ul>
                                <li>HCM (08) 3942 xxxx </li>
                                <li>HN (04) 7300 xxxx</li>
                                <li>Thứ 2 - thứ 6: 7h - 20h</li>
                                <li>Thứ 7, CN & ngày lễ: 8h - 17h</li>
                                <li>Hoặc gửi yêu cầu <a href="#">tại đây</a></li>
                                <li>Thông báo hàng giả (08) 7300 xxxx</li>

                            </ul>
                        </div>
                    </div> 
                    <div class="col-sm-3">
                        <div class="col-sm-12 Ten-muc-footer-top">ABC VIỆT NAM</div>
                        <div class="col-sm-12 menu-footer-chua-link">
                            <ul>
                                <li><a href="#">Về abc Việt Nam</a></li>
                                <li><a href="#">Chương trình abc</a></li>
                                <li><a href="#">Tuyển dụng</a></li>
                                <li><a href="#">Điều khoản mua bán hàng hóa</a></li>
                                <li><a href="#">Chính sách bảo mật</a></li>
                                <li><a href="#">Báo chí</a></li>
                                <li><a href="#">Bán hàng cùng abc</a></li>
                                <li><a href="#">Thương hiệu tại abc</a></li>
                                <li><a href="#">Danh mục sản phẩm</a></li>
                                <li><a href="#"> Phát hiện hàng giả </a></li>
                            </ul>
                        </div>
                    </div> 
                    <div class="col-sm-3">
                        <div class="col-sm-12 Ten-muc-footer-top">ĐĂNG KÍ NHẬN TIN</div>
                        <div class="col-sm-12 menu-footer-chua-link">
                            <div class="col-sm-12 box-dangki-tin">Đăng ký nhận tin từ abc và nhận voucher 50.000 VND</div>
                            <div class="col-sm-12 box-dangki-tin">Email:</div>
                            <div class="col-sm-12 box-dangki-tin">
                                <input type="text" class="form-control" placeholder="Địa chỉ email của bạn">
                            </div>
                            <div class="col-sm-12 margin-top-bottom-nopadding">
                                <div class="col-sm-6">
                                    <button class="btn btn-danger button-footer">Nam</button>

                                </div>
                                <div class="col-sm-6">
                                    <button class="btn btn-danger button-footer">Nữ</button>
                                </div>
                            </div>
                            <div class="col-sm-12 box-dangki-tin">
                                Thông tin của bạn sẽ được giữ kín tuyệt đối, và bạn có thể hủy đăng ký bất cứ lúc nào. Mỗi khách hàng chỉ tham gia chương trình 1 lần. Chương trình chỉ dành cho khách hàng mới.
                            </div>
                            <div class="col-sm-12 box-dangki-tin">
                                Bằng việc đăng ký nhận tin từ abc, bạn xác nhận rằng bạn đã đọc và hiểu <a href="#">chính sách bảo mật</a> của chúng tôi.
                            </div>

                        </div>
                    </div> 
                    <div class="col-sm-3">
                        <div class="col-sm-12 Ten-muc-footer-top">TẢI NGAY ỨNG DỤNG</div>
                        <div class="col-sm-12 margin-top-nopading">
                            <img src="<?php echo ROHLIK_LAZADA;?>/img/footer/ungdung1.png"  class="img-responsive" alt="#"/>
                        </div>
                        <div class="col-sm-12 margin-top-nopading">
                            <img src="<?php echo ROHLIK_LAZADA;?>/img/footer/ungdung2.png"  class="img-responsive" alt="#"/>
                        </div>
                    </div> 
                    <div class="col-sm-12"><div class="col-sm-12 border-footer"></div></div>
                </div>
                <div class="row">
                    <div class="col-sm-12 nopading">
                        <div class="col-sm-2 border-dotted-right">
                            <div class="col-sm-12 Ten-muc-footer-top">CÁCH THỨC THANH TOÁN</div>
                            <div class="col-sm-12">
                                <img src="<?php echo ROHLIK_LAZADA;?>/img/footer/visa.png" class="img-responsive" alt="#"/>
                            </div> 
                        </div>

                        <div class="col-sm-3 border-dotted-right">
                            <div class="col-sm-12 Ten-muc-footer-top">ĐƯỢC CHỨNG NHẬN</div>
                            <div class="col-sm-6 nopading">
                                <img src="<?php echo ROHLIK_LAZADA;?>/img/footer/clcik.png" class="img-responsive" alt="#"/>
                            </div>
                            <div class="col-sm-6">
                                <a href="#">  <img src="<?php echo ROHLIK_LAZADA;?>/img/footer/tindung.png" class="img-responsive" alt="#"/></a>
                            </div>
                            <div class="col-sm-12 Ten-muc-footer-top">DỊCH VỤ THANH TOÁN</div>
                            <div class="col-sm-12  nopading">
                                <img src="<?php echo ROHLIK_LAZADA;?>/img/footer/kery.png" class="img-responsive" alt="#"/>
                            </div>
                        </div>
                        <div class="col-sm-7">
                            <div class="col-sm-12 Ten-muc-footer-top">SẢN PHẨM NỔI BẬT</div>
                            <div class="col-sm-12 menu-footer-khong-chua-link">
                                <ul>
                                    <li>Điện thoại: Nokia, Samsung, Oppo, BlackBerry, Sony, Smartphone, iPhone 4s, iPhone 4, iPhone 6, iPhone 5</li>
                                    <li>Máy tính bảng: iPad mini, iPad air, iPad air 2, iPad mini 2, iPad mini 3, Máy tính bảng Samsung, Máy tính bảng Acer, Máy tính bảng Lenovo</li>
                                    <li>
                                        Tivi: Tivi Sony, Tivi LG, Tivi Toshiba, Tivi LED, Tivi LCD, Smart Tivi, Tivi TCL, Tivi Sharp, Tivi Led Sony, Tivi Led Samsung, Tivi 3D, Tivi Samsung
                                    </li>
                                    <li>Tủ lạnh: Tủ lạnh mini, Tủ lạnh Sanyo, Tủ lạnh Electrolux, Tủ lạnh Panasonic, Tủ lạnh Toshiba, Tủ lạnh Samsung</li>
                                    <li>Máy giặt: Máy giặt Electrolux, Máy giặt Sanyo, Máy giặt Toshiba, Máy giặt LG,</li>
                                    <li>Lò vi sóng: Lò vi sóng Sharp, Lò vi sóng Electrolux, Lò vi sóng Sanyo</li>
                                    <li>Laptop: Laptop Dell, Laptop Asus, Laptop Apple, Laptop Sony, Laptop Lenovo, Laptop Acer</li>
                                    <li>Máy ảnh: Canon, Nikon, Máy ảnh Sony, Fujifilm, Máy ảnh chuyên nghiệp, Máy ảnh DSLR, Camera</li>
                                    <li>Thời trang nam: Áo khoác nam, Áo thun trơn, Áo sơ mi nam, Áo thun nam, Túi đeo chéo, Giày lười nam</li>
                                    <li>Thời trang nữ: Áo sơ mi nữ, Áo khoác nữ, Đầm công sở, Quần legging, Chân váy, Bikini, Đồ lót nữ, Giày thể thao nữ, Giày mọi nữ, Giày Oxford nữ, Quần jean nữ, Giày búp bê, Giày cao gót</li>
                                    <li>Trang điểm: Bộ trang điểm, The face shop, Maybelline, Shiseido, Skinfood, Lancome, L'Oreal, Innisfree, Nature Republic, NYX, Bourjois, Essence, Mascara, Son môi, Mặt nạ</li>
                                    <li>Collagen, Bao cao su, Sữa ong chúa, Vitamin, Tẩy tế bào chết, Máy sấy tóc, Chăm sóc da mặt, Xịt khoáng</li>
                                    <li>Nước hoa, Nước hoa nam, Nước hoa nữ, Kem chống nắng, Máy cạo râu, Gel bôi trơn</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12"> <div class="col-sm-12 border-footer-moi"></div></div>

                </div>
                <div class="row">

                    <div class="col-sm-12">    <div class="col-sm-12 Ten-muc-footer-top">ABC - KÊNH MUA SẮM TRỰC TUYẾN HÀNG ĐẦU VIỆT NAM!</div></div>
                    <div class="col-sm-12 box-text-bt">
                        <span class="text-dam">    Mua hàng trực tuyến (mua hàng online)</span> mang lại sự tiện lợi, lựa chọn đa dạng hơn và các dịch vụ tốt hơn cho người tiêu dùng, thế nhưng người tiêu dùng Việt Nam vẫn chưa tận hưởng được những tiện ích đó. Chính vì vậy ABC Việt Nam được triển khai với mong muốn trở thành trung tâm mua sắm trực tuyến số 1 tại Việt Nam, nơi bạn có thể chọn lựa mọi thứ, từ các mặt hàng điện tử như laptop, điện thoại di động giá rẻ, thiết bị gia dụng như máy lạnh, máy lọc không khí, máy hút bụi mini gia đình, nội thất phòng ngủ… Chúng tôi có tất cả!
                    </div>
                    <div class="col-sm-12 box-text-bt">
                        Tại ABC.vn bạn có thể mua đồ điện tử giá rẻ, cũng như các loại mặt hàng khác với rất nhiều các chương trình khuyến mãi hàng tháng. Ngoài ra bạn cũng có thể tham gia bán hàng trực tuyến thông qua hệ thống marketplace của ABC với rất nhiều hỗ trợ và dịch vụ hấp dẫn.
                    </div>
                    <div class="col-sm-12 box-text-bt">
                        Bây giờ bạn có thể trải nghiệm mua hàng online thỏa thích mà ABC mang lại chỉ với 1 click chuột. Dù bạn là một nhà quản lý bận rộn với công việc hay là người nội trợ với danh sách dài việc phải làm, chắc chắn bạn cũng sẽ yêu thích trải nghiệm mua hàng tại <span class="text-dam">ABC Việt Nam - mua hàng trực tuyến dễ dàng hơn, thuận tiện hơn và tiết kiệm thời gian.</span>
                    </div>
                    <div class="col-sm-12 margin-top-bottom">
                        <div class="col-sm-3 footer-cuoi-left">
                            <div class="col-sm-6 nopading">
                                ABC South-East Asia
                            </div>
                            <div class="col-sm-6 nopading">
                                <div class="la-co">
                                    <a href="#"> 
                                        <img src="<?php echo ROHLIK_LAZADA;?>/img/footer/icon1.png" class="img-responsive" alt="#"/>
                                    </a>
                                </div>
                                <div class="la-co">
                                    <a href="#"> 
                                        <img src="<?php echo ROHLIK_LAZADA;?>/img/footer/iocn2.png" class="img-responsive" alt="#"/>
                                    </a>
                                </div>
                                <div class="la-co">
                                    <a href="#"> 
                                        <img src="<?php echo ROHLIK_LAZADA;?>/img/footer/icon3.png" class="img-responsive" alt="#"/>
                                    </a>
                                </div>
                                <div class="la-co">
                                    <a href="#"> 
                                        <img src="<?php echo ROHLIK_LAZADA;?>/img/footer/icon4.png" class="img-responsive" alt="#"/>
                                    </a>
                                </div>
                                <div class="la-co">
                                    <a href="#"> 
                                        <img src="<?php echo ROHLIK_LAZADA;?>/img/footer/icon5.png" class="img-responsive" alt="#"/>
                                    </a>
                                </div>
                                <div class="la-co">
                                    <a href="#"> 
                                        <img src="<?php echo ROHLIK_LAZADA;?>/img/footer/icon6.png" class="img-responsive" alt="#"/>
                                    </a>

                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4"></div>
                        <div class="col-sm-5 footer-cuoi-right">
                            <div class="col-sm-3 nopading">
                                Kết nối chúng tôi
                            </div>
                            <div class="col-sm-9 nopading">
                                <div class="mangxahoi">
                                    <a href="#"> 
                                        <img src="<?php echo ROHLIK_LAZADA;?>/img/footer/icon-xh-1.png" class="img-responsive" alt="#"/>
                                    </a>
                                </div>
                                <div class="mangxahoi">
                                    <a href="#"> 
                                        <img src="<?php echo ROHLIK_LAZADA;?>/img/footer/iocn-xh-2.png" class="img-responsive" alt="#"/>
                                    </a>
                                </div>
                                <div class="mangxahoi">
                                    <a href="#"> 
                                        <img src="<?php echo ROHLIK_LAZADA;?>/img/footer/icon-xh-3.png" class="img-responsive" alt="#"/>
                                    </a>
                                </div>
                                <div class="mangxahoi">
                                    <a href="#"> 
                                        <img src="<?php echo ROHLIK_LAZADA;?>/img/footer/icon-xh-4.png" class="img-responsive" alt="#"/>
                                    </a>
                                </div>
                                <div class="mangxahoi">
                                    <a href="#"> 
                                        <img src="<?php echo ROHLIK_LAZADA;?>/img/footer/icon-xh-5.png" class="img-responsive" alt="#"/>
                                    </a>
                                </div>
                                <div class="mangxahoi">
                                    <a href="#"> 
                                        <img src="<?php echo ROHLIK_LAZADA;?>/img/footer/icon-xh-6.png" class="img-responsive" alt="#"/>
                                    </a>
                                </div>
                                <div class="mangxahoi">
                                    <a href="#"> 
                                        <img src="<?php echo ROHLIK_LAZADA;?>/img/footer/icon-xh-7.png" class="img-responsive" alt="#"/>
                                    </a>
                                </div>
                                <div class="mangxahoi">
                                    <a href="#"> 
                                        <img src="<?php echo ROHLIK_LAZADA;?>/img/footer/icon-xh-8.png" class="img-responsive" alt="#"/>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <div class="container-fluid footer-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="col-sm-3"></div>
                            <div class="col-sm-6 ">
                                <div class="col-sm-12 can-giua-box-top"><?php echo $setting_session->name;?></div>
                                <div class="col-sm-12 can-giua-box-bottom">
                                    <?php echo $setting_session->address;?>
                                </div>
                            </div>
                            <div class="col-sm-3"></div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </body>
     <script type="text/javascript" defer="defer" src="https://mylivechat.com/chatinline.aspx?hccid=35565043"></script>
</html>  	
        	
        