<div class="container">
	<div class="row">
		<div class="col-sm-3">
			<a class="apply-now-button" title="Apply Now!"
				href="<?php echo WEBPATH;?>/apply-vietnam-visa"><div>APPLY
					NOW!</div>
				<div></div>
				<div>
					Just fill the application form<br>we will do the rest!
				</div></a>
		</div>
		<div class="col-sm-9">
		
			<h1 class="main_title"><?php  echo $detailview->news_name; ?></h1>
			<div class="content">
				<div id="attachment_1147" style="width: 610px"
					class="wp-caption alignright">
					<img class="wp-image-1147 size-full" src="/uploads/<?php  echo $detailview->news_thumbnail; ?>" width="600" height="300">
					<p class="wp-caption-text"><?php  echo $detailview->news_name; ?></p>
				</div>
				<div>
				  <?php  echo $detailview->news_content; ?>
				</div>
			</div>
			<p></p>
		</div>
	</div>
</div>

