<div class="main-container col2-left-layout">
	<div class="container">
		<div class="main">

			<div class="row show-grid">
				<div
					class="col-left sidebar col-lg-3 col-md-3 col-sm-3 col-pull-3 hidden-xs">

					<div id="leftcatalogue"></div>
					<!-- leftcatalogue -->

					<div id="myacountaja"></div>
					<!-- myacountaja -->

					<div id="mycartaja"></div>


					<div id="compareproductaja"></div>
					<!-- compareproductaja -->
					<div id="populartags"></div>
					<!-- populartags -->

					<div id="containernone"></div>
					<!-- container-none -->

					<p></p>
				</div>

				<!--thay trang chi tiet vao--->
				<div
					class="col-main col-lg-9 col-md-9 col-sm-9 col-push-9 col-xs-12">
					<div class="my-account">
						<div class="page-title">
							<h1>My Orders</h1>
						</div>
						<p>You have placed no orders.</p>
						<div class="buttons-set">
							<p class="back-link">
								<a href="<?php echo WEBPATH?>/mydashboard"><small>«
								</small>Back</a>
							</p>
						</div>
					</div>
				</div>
				<!-- end chi tiet -->
			</div>
		</div>
	</div>
</div>