<div class="container">
				<div class="row">
					<div class="box-link rates">
						<h1 class="Pub">Publisher Rates</h1>
						
					</div>
				</div>
				
				<div class="row">
					<div class="col-md-12 text-p-t">				
						The average CPM for <b>22nd December 2014.</b><br>
						<i>Unique = average amount paid for 1000 visitors in the 24-hour period.<br>
						Raw = average amount paid on the 1st advert view for 1000 link views in the 24-hour period. </i>
					</div>
				</div>
					
				
				
				<div class="row view-date">
					<div class="col-lg-12 col-sm-12 col-md-12 col-xs-12 box-link  ">
					<button type="button" class="btn btn-info"> Interstitial</button>
					<button type="button" class="btn btn-info">Banner</button>
					<button type="button" class="btn btn-info">PopAds</button>
    

						
					
					</div>
					
				</div>
				
				<div class="row view-date find-link">
							<table class="data-table table table-bordered table-striped table-new dataTable" style="margin-bottom:0;" id="DataTables_Table_0">
								<thead class="header-th">
									<tr>
										<th class="sorting_asc">
										Country 	
										</th>
										<th colspan="2">
										Desktop CPM 
										</th>
										<th colspan="2">
										Mobile CPM
										</th>
										
									</tr>	
								</thead>
								
								<tbody role="alert" aria-live="polite" aria-relevant="all">
									<tr>
										<td></td>
										<td>
												Unique 
										</td>
										<td>
											Raw
										</td>
										<td>
												Unique 
										</td>
										<td>
											Raw
										</td>
									</tr>
									<tr>
										 				
										<td>United States</td>
										<td>$8.95 </td>
										<td>$3.96 </td>
										<td>$5.76 </td>
										<td>$3.39</td>
									</tr>
										<tr>
										 			 				
										<td>Canada </td>
										<td>$1.89  </td>
										<td>$1.30  </td>
										<td>$2.42</td>
										<td>$1.62</td>
									</tr>
										<tr>
										 	 					 				
										<td>United Kingdom </td>
										<td>$3.91  </td>
										<td>$2.00  </td>
										<td>$3.37 </td>
										<td>$2.14</td>
									</tr>
										 		
										<tr>
										 	 					 				
										<td>Australia  </td>
										<td>$3.59  </td>
										<td>$1.74 </td>
										<td>$3.99 </td>
										<td>	$2.51</td>
									</tr>
													
										<tr>
										 	 					 				
										<td>Italy   </td>
										<td>$2.73  </td>
										<td>$1.41  </td>
										<td>$6.75  </td>
										<td>$3.92</td>
									</tr>
										<tr> 	 	  						 				
										<td> Qatar  </td>
										<td>$5.61 </td>
										<td>$2.73 </td>
										<td>$4.61 </td>
										<td>$2.61</td>
									</tr>
									<tr>
									<td colspan="5" style="height:38px;"></td>
										</tr>
								</tbody>
								
								<tbody><tr style="text-align:center;">
										
								<td>All other countries </td>
								<td colspan="2">$0.25 - $2.00 </td>
								<td colspan="2">$0.06 - $0.22</td>
								</tr>
					
								
							</tbody></table>
							
							
						</div>
					
	
	
					
					
				</div>