<?php echo $this->doctype(); ?>
<?php 
use Zend\Session\Container; 
$setting = $this->layout()->setting; 
$setting_session = new Container('setting');
$Shoppingcart_session = new Container('shoppingcart');
if (isset ( $Shoppingcart_session->Shoppingcart)) {
	$shopingcart = $Shoppingcart_session->Shoppingcart;
}else  { $shopingcart = null; }

?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $setting_session->name;?></title>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
<meta name="description" content="<?php echo $setting_session->seo_description;?>" />
<meta name="keywords" content="<?php echo $setting_session->seo_keywords;?>" />
<meta name="robots" content="INDEX,FOLLOW" />
<link rel="icon" href="<?php echo WEBPATH_UPLOAD_PATH_IMG.'/'.$setting_session->ico;?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo WEBPATH_UPLOAD_PATH_IMG.'/'.$setting_session->ico;?>" type="image/x-icon" />
<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo BAG_REAL_HTML; ?>/smije/js/blank.html';
    var BLANK_IMG = '<?php echo BAG_REAL_HTML; ?>/smije/js/spacer.gif';
//]]>
</script>
<![endif]-->
<link
	href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900'
	rel='stylesheet' type='text/css' />
<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700'
	rel='stylesheet' type='text/css' />
<link
	href='http://fonts.googleapis.com/css?family=Roboto:400,100italic,100,300,300italic,400italic,500,500italic,700,700italic,900,900italic'
	rel='stylesheet' type='text/css' />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/js/calendar/calendar-win2k-1.css" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/magiccart/plugin/fontawesome/css/font-awesome.min.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/magiccart/plugin/css/bootstrap/bootstrap.min.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/magiccart/plugin/css/flexisel.hack.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/css/styles.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/base/default/css/widgets.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/magiccart/blog/css/blog.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/magiccart/magicmenu/css/magicmenu.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/magiccart/magicshop/css/ajaxcart.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/magiccart/magicslider/css/iview.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/magiccart/magicslider/css/style.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/magiccart/magicsocial/css/magicsocial.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/magiccart/plugin/css/jquery.fancybox-1.3.4.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/magiccart/plugin/css/animate.css"
	media="all" />
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/magiccart/magicshop/css/quickview.css"
	media="all" />
<link rel="stylesheet" type="text/css" href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/css/print.css" media="print" />

<link rel="stylesheet" type="text/css" href="<?php echo BAG_REAL_HTML; ?>/css/facebookcss.css" media="print" />
<script type="text/javascript" src="<?php echo BAG_REAL_HTML; ?>/smije/media/js/3ab2ed8946de7c8e38c92d7019e570ed.js"></script>
<link href="<?php echo BAG_REAL_HTML; ?>/store_id_4.xml" title="Blog" rel="alternate" type="application/rss+xml" />
<!--[if lt IE 9]>

<script type="text/javascript" src="<?php echo BAG_REAL_HTML; ?>/smije/media/js/20c96fd37f0b6d1653065f79884b33b7.js"></script>

<![endif]-->
<!--[if lt IE 8]>
<link rel="stylesheet" type="text/css" href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/default/css/styles-ie.css" media="all" />
<![endif]-->
<!--[if lt IE 7]>

   <script type="text/javascript" src="<?php echo BAG_REAL_HTML; ?>/smije/media/js/431482b026b7ce7b6c58e1c2f5f6a7a7.js"></script>

<![endif]-->
<link rel="stylesheet" type="text/css"
	href="<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/css/responsive.css"
	media="all" />

<script type="text/javascript">
	//<![CDATA[
	Mage.Cookies.path = '/bagseshop/smije';
	Mage.Cookies.domain = '.<?php echo BAG_NO_HTTP; ?>'; 
	
	//]]>

</script>

<script type="text/javascript">
	//<![CDATA[
	optionalZipCountries = [ "HK", "IE", "MO", "PA" ];
	//]]>
</script>
<link rel="stylesheet" type="text/css"
	href="http://fonts.googleapis.com/css?family=Roboto" media="all" />
<style type="text/css">
*,body,h1,h2,h3,h4,h5,h6,.h1,.h2,.h3,.h4,.h5,.h6 {
	font-size: 12px;
	font-family: Roboto;
}

body {
	color: #666666;
}

body {
	background-color: transparent;
}

a {
	color: #666666;
}

a:hover {
	color: #e5685d;
}

a:active {
	color: #e5685d;
}

button.button span {
	color: #ffffff;
}

button.button span:hover {
	color: #ffffff;
}

button.button span {
	background-color: #666666;
}

button.button span:hover {
	background-color: #e5685d;
}

.labelnew {
	color: #ffffff;
}

.labelnew {
	background-color: #e5685d;
}

.labelsale {
	color: #ffffff;
}

.labelsale {
	background-color: #f9bd68;
}

/***********************/

a.buttonshoppingcart.button.btn-cart span:hover {
  background-color: #e5685d;
}
a.buttonshoppingcart.button.btn-cart span:hover {
  color: #ffffff;
}

a.buttonshoppingcart.button.btn-cart span {
  background-color: #666666;
  padding: 10px;
  border-radius: 6px;
}
a.buttonshoppingcart.button.btn-cart span {
  color: #ffffff;
}
/*************************/
</style>
<script type="text/javascript">
	Themecfg = {
		"general" : {
			"enabled" : "1",
			"jquery" : "1",
			"tooltip" : "0",
			"themecolor" : "",
			"ajaxloading" : "http:\/\/\<?php echo BAG_REAL_HTML; ?>\/smije\/skin\/frontend\/alosmije\/smije_fashion\/images\/opc-ajax-loader.gif"
		},
		"home" : {
			"portrait" : "1",
			"landscape" : "2",
			"tablet" : "3",
			"visibleItems" : "6",
			"height_images" : "250",
			"width_images" : "200"
		},
		"list" : {
			"portrait" : "1",
			"landscape" : "2",
			"tablet" : "3",
			"visibleItems" : "6",
			"margin_columns" : "10",
			"productDelay" : "500",
			"height_images" : "250",
			"width_images" : "200",
			"action" : "cart,compare,wishlist",
			"sort_name" : "asc"
		},
		"detail" : {
			"imageWidth" : "400",
			"zoomWidth" : "290",
			"zoomHeight" : "374",
			"adjustX" : "10",
			"adjustY" : "10",
			"showTitle" : "1",
			"useWrapper" : "0",
			"thumbSlide" : "vertical",
			"relatedSlide" : "vertical",
			"relatedLimit" : "10",
			"upsellSlide" : "horizontal",
			"upsellLimit" : "10",
			"inforTabs" : "1",
			"activeTab" : "box-up-sell"
		},
		"checkout" : {
			"crosssellsSlide" : "1"
		},
		"newsletter" : {
			"enabled" : "1",
			"width" : "949",
			"height" : "818",
			"overlayColor" : "#353535",
			"background_color" : "#fffaff",
			"background_image" : "stores\/4\/fashion-popup-newleter.jpg"
		}
	}
</script>
<script type="text/javascript">
	//<![CDATA[
	if (typeof MC == 'undefined')
		MC = {};
	MC.Quickview = {
		"dialogWidth" : "1000",
		"zoomWidth" : "265",
		"zoomHeight" : "265",
		"vertical" : "1"
	};

	jQuery(document)
			.ready(
					function($) {
						jQuery(document)
								.magiccart(
										{
											"url" : "<?php echo WEBPATH; ?>\/magicshop\/ajax\/index",
											"updateUrl" : "<?php echo WEBPATH; ?>\/checkout\/cart\/updatepost",
											"src_image_progress" : "\<?php echo BAG_REAL_HTML; ?>\/smije\/skin\/frontend\/alosmije\/smije_fashion\/magiccart\/magicshop\/images\/loading.gif",
											"error" : " \u2191 This is a required field.",
											"isProductView" : 0
										});
					});
	//]]
</script>

<script type="text/javascript">
	//<![CDATA[
	var Translator = new Translate([]);
	//]]>
</script>
<!-- tuy bien -->
<link rel="stylesheet" type="text/css" href="<?php echo BAG_REAL_HTML; ?>/css/stylenew.css" />
</head>
<body class=" cms-index-index cms-home-smije-fashion">
	<div class="social-icons right" style="margin-top: 100px">
		<a class="socialitems" target="_blank" href="https://www.facebook.com/<?php echo $setting_session->facebook;?>"
			id="facebook-btn"> <span class="social-icon"> <span
				class="social-text">Follow via Facebook</span>
		</span>
		</a> <a class="socialitems" target="_blank"
			href="https://www.twitter.com/<?php echo $setting_session->tweets;?>" id="twitter-btn"> <span
			class="social-icon"> <span class="social-text">Follow via Twitter</span>
		</span>
		</a> <a class="socialitems" target="_blank"
			href="https://www.plus.google.com/<?php echo $setting_session->google;?>" id="googleplus-btn"> <span
			class="social-icon"> <span class="social-text">Follow via Google +</span>
		</span>
		</a> <a class="socialitems" target="_blank"
			href="https://www.youtube.com<?php echo $setting_session->youtube_acount;?>" id="youtube-btn"> <span
			class="social-icon"> <span class="social-text">Follow via Youtube</span>
		</span>
		</a> <a class="socialitems" target="_blank"
			href="https://www.pinterest.com/<?php echo $setting_session->printerest;?>" id="pinterest-btn"> <span
			class="social-icon"> <span class="social-text">Follow via Pinterest</span>
		</span>
		</a> <a class="socialitems" target="_blank"
			href="mailto:<?php echo $setting_session->email?>" id="mail-btn"> <span
			class="social-icon"> <span class="social-text">Mail To</span>
		</span>
		</a>
	</div>

	<script type="text/javascript">
		jQuery(document).ready(function($) {
			$('.social-icons .social-icon').mouseenter(function() {
				$(this).stop();
				$(this).animate({
					width : '160'
				}, 500, 'swing', function() {
				});
			});
			$('.social-icons .social-icon').mouseleave(function() {
				$(this).stop();
				$(this).animate({
					width : '43'
				}, 500, 'swing', function() {
				});
			});
		});
	</script>
	<div class="wrapper">
		<noscript>
			<div class="global-site-notice noscript">
				<div class="notice-inner">
					<p>
						<strong>JavaScript seems to be disabled in your browser.</strong><br />
						You must have JavaScript enabled in your browser to utilize the
						functionality of this website.
					</p>
				</div>
			</div>
		</noscript>
		<div class="page">
			<div class="header-container">
				<div class="header">
					<div class="header-top">
						<div class="container">
							<div class="main">
								<div class="row">
									<div
										class="header-block1 col-lg-8 col-md-8 col-sm-8 col-xs-12 pull-left">
										<div class="box-support">
											<ul>
												<li class="first">
													<div class="box-phone">
														<span class="pull-left"><em class="fa fa-phone">&nbsp;</em></span>
														<div class="media-body pull-left">
															<p><?php echo $setting_session->phone;?></p>
														</div>
													</div>
												</li>
												<li class="last">
													<div class="box-email">
														<span class="pull-left"><em class="fa fa-envelope">&nbsp;</em></span>
														<div class="media-body pull-left">
															<p>
																<a href="mailto:<?php echo $setting_session->email;?>"><?php echo $setting_session->email;?></a>
															</p>
														</div>
													</div>
												</li>
											</ul>
										</div>
									</div>
									<div
										class="header-top-left col-lg-4 col-md-4 col-sm-4 col-xs-12 pull-right">
										<div class="top-form-language">
<!--  
											<div class="lang-switcher">
												<div class="dropdown-toggle">
													<div>
														<div class="label dropdown-icon flag"
															style="background-image: url(<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/images/flags/english_fashion.png)">&nbsp;</div>
														<div class="value">English</div>
														<div class="caret">&nbsp;</div>
													</div>
												</div>
												<ul class="dropdown-switcher">
													<li class="current"><span class="label dropdown-icon"
														style="background-image: url(<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/images/flags/english_fashion.png);">&nbsp;</span>English</li>
													<li><a
														href="<?php echo WEBPATH;?>/?___store=french_fashion&amp;___from_store=english_fashion"><span
															class="label dropdown-icon"
															style="background-image: url(<?php echo BAG_REAL_HTML; ?>/smije/skin/frontend/alosmije/smije_fashion/images/flags/french_fashion.png);">&nbsp;</span>French</a></li>
												</ul>
											</div>
											-->
											<!-- transview -->
												<div id="google_translate_element"></div><script type="text/javascript">
												function googleTranslateElementInit() {
												  new google.translate.TranslateElement({pageLanguage: 'vi', layout: google.translate.TranslateElement.InlineLayout.SIMPLE, multilanguagePage: true}, 'google_translate_element');
												}
												</script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
												<!-- end translate -->
											
										</div>
										<div class="currency_top">


											<div class="currency-switcher">
												<div class="dropdown-toggle cover">
													<div>
														<div class="label">Currency:</div>
														<div class="value">USD</div>
														<div class="caret">&nbsp;</div>
													</div>
												</div>
												<ul class="dropdown-switcher">
													<li><a
														href="<?php echo WEBPATH;?>/directory/currency/switch/currency/EUR/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvP19fX3N0b3JlPWVuZ2xpc2hfZmFzaGlvbg,,/">EUR
															- Euro</a></li>
													<li class="current">USD - US Dollar</li>
												</ul>
											</div>
										</div>

										<!--<p class="welcome-msg"> </p>-->
									</div>
								</div>
							</div>
						</div>
					</div>
					<?php  $getuser = $this->layout()->getuser; ?>
					<div class="header-content">
						<div class="container">
							<div class="main">
								<div class="row">
									<div class="inner-box clearfix">
										<div
											class="header-content-left col-lg-3 col-md-3 col-sm-3 col-xs-12">
											<a href="<?php echo WEBPATH;?>/main/index" title="<?php echo $setting_session->name;?>"
												class="logo"><strong><?php echo $setting_session->name;?></strong>
												<img class="img-responsive"
												src="<?php echo WEBPATH_UPLOAD_PATH_IMG.'/'.$setting_session->logo1;?>"
												alt="<?php echo $setting_session->name;?>" />
											</a>
										</div>
										
									 
										<div
											class="header-content-right col-lg-9 col-md-9 col-sm-9 col-xs-12">
											<div class="header-content-top clearfix">
												<div class="header-top-right pull-right">
													<ul class="links">
													  	<li class="first"><a href="<?php echo WEBPATH;?>/wishlist"
															title="My Wishlist">My Wishlist</a></li>
														<?php if(!empty($getuser)) {?>
													    <li><a href="<?php echo WEBPATH;?>/mydashboard"
															title="My Wishlist">My dashboard</a></li>
													  <?php }?>
														<li><a href="<?php echo WEBPATH;?>/checkout"
															title="Checkout" class="top-link-checkout">Checkout</a></li>
													<?php if($_SERVER['SERVER_ADDR'] == IP_SERVER_TEST)  {?>		
														<li><a href="<?php echo WEBPATH;?>/blog.html" title="Blog">Blog</a></li>
														<li><a href="<?php echo WEBPATH;?>/testimonial" title="Testimonial">Testimonial</a></li>
													<?php }// end SERVER_ADDR?>	
														<li class=" last">
														<?php if(!empty($getuser)) {?> <a href="<?php echo WEBPATH;?>/logout" title="Log In">logout</a> <?php  }else { ?>
														    <a href="<?php echo WEBPATH;?>/login/" title="Log In">Log In</a>
														 <?php }?>   
														</li>
													</ul>
													<div class="miniCartWrap">
														
														<div class="mini-maincart">
															<div class="cartSummary">
															   <?php 
															   $Total_sub = 0;
															   if($shopingcart != null){
															       $Iteams = count($shopingcart);
															       $i= 0; 
															       foreach ($shopingcart as $key=>$value_shoppingcart) {
                                                                      $Total_sub = $Total_sub + $value_shoppingcart['total']; 
                                                                      $i++;
                                                                   } // end foreach 
															   }else $Iteams = 0; 
															   ?>
																<span class="icon-cart">Cart:</span> <span class="item"><?php echo $Iteams;?> item(s) -</span> <span><span class="price">$<?php echo @number_format($Total_sub, 0, '', '.');?></span></span>
															</div>
															<div class="mini-contentCart" style="display: none;">
																<div class="block-content">
																	<p class="block-subtitle">Recently added item(s)</p>
																	<ol id="cart-sidebar" class="mini-products-list clearfix">
													<?php  if($shopingcart != null)
														{
															$i= 0;
															$Total_sub = 0;
															foreach ($shopingcart as $key=>$value_shoppingcart) {
															if($i==0) { $class_text = 'item odd'; } else { $class_text ='item last even'; }	
													?>
															 <li class="<?php echo $class_text;?>">
																		<a href="<?php echo WEBPATH;?>/product/index/view/<?php echo $value_shoppingcart['pid'];?>" title="<?php echo $value_shoppingcart['name'];?>" class="product-image">
																		  <img src="<?php echo WEBPATH_UPLOAD_PATH_IMG_THUNB_.$value_shoppingcart['img'];?>"
																				width="79" height="86" alt="<?php echo $value_shoppingcart['name'];?>">
																		</a>
																			<div class="product-details">
																				<p class="product-name">
																					<a href="<?php echo WEBPATH;?>/product/index/view/<?php echo $value_shoppingcart['pid'];?>"><?php echo $value_shoppingcart['name'];?></a>
																				</p>

																				<strong><?php echo $value_shoppingcart['sl'];?></strong> x <span class="price">$<?php echo @number_format($value_shoppingcart['price'], 0, '', '.');?></span>


																				<div class="clearfix">
																					<a href="<?php echo WEBPATH;?>/checkout/cart/configure/<?php echo $value_shoppingcart['pid'];?>"
																						title="Edit item" class="btn-edit">Edit item</a> 
																						
																						<a href="<?php echo WEBPATH;?>/checkout/cart/delete/<?php echo $value_shoppingcart['pid'];?>" title="Remove This Item" onclick="return confirm('Are you sure you would like to remove this item from the shopping cart?');"
																						class="btn-remove btn-remove2">
																						Remove This Item</a>
																				</div>
																			</div>
																		</li>
													<?php 
													$Total_sub = $Total_sub + $value_shoppingcart['total'];
													$i++;
													   }// end foreach shoping cart
													}//end if
													
													?>				
																			
																	</ol>
																	<p class="subtotal">
																		<span class="label">Cart Subtotal:</span> <span
																			class="price">$<?php echo @number_format($Total_sub, 0, '', '.');?></span>
																	</p>
																	<div class="actions">
																		<a
																			href="<?php echo WEBPATH?>/checkout/cart/cart"
																			class="view-cart"> View cart </a> <a
																			href="<?php echo WEBPATH?>/checkout/checkout/onepage">Checkout</a>
																	</div>
																	<script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
																</div>


															</div>
														</div>

													</div>
												</div>
											</div>
											
											<div class="header-content-block clearfix">
												<div class="header-block2">
													<div class="alo-support">
														<div class="support">
														<?php  if($_SERVER['SERVER_ADDR'] == IP_SERVER_TEST) {?>
															<div
																class="box-services box-services1 col-lg-4 col-md-4 col-sm-4 col-xs-12">
																<span class="pull-left"><em class="fa fa-truck">&nbsp;</em></span>
																<div class="media-body">
																	<h3>WORLD DELIVERY</h3>
																	<small>Free delivery on all store items</small>
																</div>
															</div>
															<div
																class="box-services col-lg-4 col-md-4 col-sm-4 col-xs-12">
																<span class="pull-left"><em class="fa fa-refresh">&nbsp;</em></span>
																<div class="media-body">
																	<h3>Return &amp; Exchange</h3>
																	<small>30 Days money back</small>
																</div>
															</div>
															<div
																class="box-services col-lg-4 col-md-4 col-sm-4 col-xs-12">
																<span class="pull-left"><em class="fa fa-phone">&nbsp;</em></span>
																<div class="media-body">
																	<h3>Online Support</h3>
																	<small>(+800) 0123 456 789</small>
																</div>
															</div>
															<?php } //IP_SERVER_TEST ?>
														</div>
													</div>
												</div>
											</div>
											
										</div>
										<div class="box-inner clearfix"></div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="header-bottom clearfix">
						<div class="container custom-menu">
							<div class="main">

								<div class="magicmenu">
									<ul class="nav-desktop ">
										<li class="level0 home">
										<a class="level-top" href="<?php echo WEBPATH;?>/main/index">
										    <span class="icon-home fa fa-home"></span><span class="icon-text">Home</span>
											<span class="short_desc"><?php echo $setting_session->name;?></span> 
										</a>
												<!--  
												<div class="level-top-mega">
													<div>
														<a href="<?php echo WEBPATH;?>"><span class="demo-home">Digital
																Store</span></a>
													</div>
													<div>
														<a href="<?php echo WEBPATH;?>"><span class="demo-home">Fashion
																Store</span></a>
													</div>
													<div>
														<a href="<?php echo WEBPATH;?>"><span class="demo-home">Furniture
																Store</span></a>
													</div>
												</div>
												-->
										</li>
										
										
									<?php 
									if($_SERVER['SERVER_ADDR'] == IP_SERVER_TEST) {?>	
										<li class='level0 ext  first'><a class="level-top"
											href="<?php echo WEBPATH; ?>/newproduct">NEW ARRIVALS <span
												class="short_desc">Commodo consequat</span>
										</a>
											<div class="level-top-mega">
												<div class="caret-down caret-down1">&nbsp;</div>
												<div class="menuextra clearfix">
													<div class="cutom-top menu-extra cutom-hot">
														<div class="banner-inner banner-inner1">
															<a href="#"> <img class="img-responsive"
																src="<?php echo BAG_REAL_HTML; ?>/smije/media/wysiwyg/alothemes/static/img-new.jpg"
																alt="NEW ARRIVALS" />
															</a>
															<div class="block-custom block-custom1">
																<h3>NEW ARRIVAL !</h3>
																<span class="before">&nbsp;</span>
																<h2>SMILE OUTLET WINTER</h2>
																<h2>COLLECTIONS</h2>
																<p>Get a new look with us !</p>
																<a class="view-more" href="#">View more</a>
															</div>
														</div>
													</div>
												</div>
											</div></li>
											
										<li class='level0 ext  '><a class="level-top"
											href="<?php echo WEBPATH; ?>/bestsellers">Bestsellers <span
												class="cat_label Hot">Hot</span><span class="short_desc">Ullamco
													laboris nisi</span>
										</a></li>
										<li class='level0 ext  '>
										<a class="level-top"
											href="<?php echo WEBPATH; ?>/saleproduct">Hotsale <span
												class="short_desc">Duis aute maizi irur</span>
										</a>
											<div class="level-top-mega">
												<div class="caret-down caret-down2">&nbsp;</div>
												<div class="menuextra menuextra2 clearfix">
													<div class="cutom-top menu-extra cutom-hot">
														<div class="banner-inner banner-inner2">
															<a href="#"> <img class="img-responsive"
																src="<?php echo BAG_REAL_HTML; ?>/smije/media/wysiwyg/alothemes/static/fashion_menu_hot.jpg"
																alt="Hot Sale" />
															</a>
															<div class="block-custom block-custom1">
																<h3>HOT SALE ITEMS!</h3>
																<span class="before">&nbsp;</span>
																<h2>
																	GET 25% OFF <br />FIRST PURCHASE
																</h2>
																<p>Free Delivery world wide</p>
																<a class="view-more" href="#">View more</a>
															</div>
														</div>
													</div>
												</div>
											</div></li>
										<li class='level0 ext  '><a class="level-top"
											href="<?php echo WEBPATH;?>">Extra Menu <span
												class="short_desc">Zin reprehen voluptate</span>
										</a>
											<div class="level-top-mega">
												<div class="caret-down caret-down3">&nbsp;</div>
												<div class="custom-width clearfix">
													<div class="cutom-top menu-extra custommenu">
														<div class="banner-inner banner-inner1">
															<div class="block-custom block-custom11">
																<h3>SAMPLE MENU TITLE</h3>
																<ul class="nav-desktop nav-desktop-custom">
																	<li class="level0 level0-custom first"><a
																		class="level-top" href="#">Lorem ipsum dolor</a></li>
																	<li class="level0 level0-custom"><a class="level-top"
																		href="#">Sit amet</a></li>
																	<li class="level0 level0-custom"><a class="level-top"
																		href="#">Consectetur<span class="cat_label new">New</span></a></li>
																	<li class="level0 level0-custom"><a class="level-top"
																		href="#">Adipisicing elit</a></li>
																	<li class="level0 level0-custom"><a class="level-top"
																		href="#">Do eiusmod tempor</a></li>
																	<li class="level0 level0-custom"><a class="level-top"
																		href="#">Consectetur</a></li>
																	<li class="level0 level0-custom"><a class="level-top"
																		href="#">Sit amet</a></li>
																	<li class="level0 level0-custom"><a class="level-top"
																		href="#">Adipisicing elit<span class="cat_label Hot">Hot</span></a></li>
																	<li class="level0 level0-custom"><a class="level-top"
																		href="#">Do eiusmod tempor</a></li>
																	<li class="level0 level0-custom"><a class="level-top"
																		href="#">Adipisicing elit</a></li>
																	<li class="level0 level0-custom"><a class="level-top"
																		href="#">Do eiusmod tempor<span class="cat_label Hot">Hot</span></a></li>
																	<li class="level0 level0-custom"><a class="level-top"
																		href="#">Consectetur</a></li>
																	<li class="level0 level0-custom view-more"><a
																		class="level-top" href="#">More <em
																			class="fa fa-arrow-circle-right">&nbsp;</em>
																	</a></li>
																</ul>
															</div>
														</div>
														<div class="banner-inner banner-inner2">
															<div class="block-custom block-custom21">
																<a href="#"> <img class="img-responsive"
																	src="<?php echo BAG_REAL_HTML; ?>/smije/media/wysiwyg/alothemes/static/fashion_custom1.jpg"
																	alt="SAMPLE TITLE" />
																</a>
																<div class="text-banner-menu text-banner-menu-1">
																	<h2>CUSTOM BLOCK</h2>
																	<span class="border-bottom">&nbsp;</span>
																</div>
															</div>
														</div>
														<div class="banner-inner banner-inner3">
															<div class="block-custom block-custom31">
																<a href="#"> <img class="img-responsive"
																	src="<?php echo BAG_REAL_HTML; ?>/smije/media/wysiwyg/alothemes/static/fashion_custom2.jpg"
																	alt="SAMPLE TITLE" />
																</a>
																<div class="text-banner-menu text-banner-menu-2">
																	<h2>SAMPLE TITLE</h2>
																	<span class="border-bottom">&nbsp;</span>
																</div>
															</div>
															<div class="block-custom block-custom32">
																<a href="#"> <img class="img-responsive"
																	src="<?php echo BAG_REAL_HTML; ?>/smije/media/wysiwyg/alothemes/static/fashion_custom3.jpg"
																	alt="SAMPLE TITLE" />
																</a>
																<div class="text-banner-menu text-banner-menu-3">
																	<h2>SAMPLE TITLE</h2>
																	<span class="border-bottom">&nbsp;</span>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div></li>
										<li class='level0 ext  last'><a class="level-top"
											href="<?php echo WEBPATH; ?>/blog.html">Blog <span
												class="short_desc">ALO Themes</span>
										</a></li>
										<?php }// end IP_SERVER_TEST == 127.0.0.1 ?>
									</ul>
								</div>
								<div class="nav-mobile">
									<h3 class="mobi-title">Categories</h3>
									<ul>
										<li class="level-top"><a class="level-top"
											href="<?php echo WEBPATH;?>/accessories"><span>Accessories </span>
										</a>
											<ul>
												<li><a href="<?php echo WEBPATH;?>/accessories/shop-by.html">Shop
														By <span class="cat_label New">New</span>
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/shop-by/new-arrivals.html">New
																Arrivals </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/shop-by/christmas-gifting.html">Christmas
																Gifting </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/shop-by/workwear.html">Workwear
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/shop-by/brands.html">Brands
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/shop-by/surf-skate.html">Surf
																& Skate </a></li>
													</ul></li>
												<li><a
													href="<?php echo WEBPATH;?>/accessories/clothing.html">Clothing
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/clothing/dresses.html">Dresses
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/clothing/tops.html">Tops
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/clothing/skirts.html">Skirts
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/clothing/swimwear.html">Swimwear
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/clothing/shorts.html">Shorts
														</a></li>
													</ul></li>
												<li><a href="<?php echo WEBPATH;?>/accessories/shoes.html">Shoes
														<span class="cat_label Hot !">Hot !</span>
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/shoes/heels.html">Heels
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/shoes/sandals.html">Sandals
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/shoes/flats.html">Flats
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/shoes/ankle-boots.html">Ankle
																Boots </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/shoes/sneakers.html">Sneakers
														</a></li>
													</ul></li>
												<li><a href="<?php echo WEBPATH;?>/accessories/beauty.html">Beauty
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/beauty/perfume.html">Perfume
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/beauty/make-up.html">Make
																Up </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/beauty/hands-feet.html">Hands
																& Feet </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/beauty/face.html">Face
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/beauty/body.html">Body
														</a></li>
													</ul></li>
												<li><a href="<?php echo WEBPATH;?>/accessories/sports.html">Sports
														<span class="cat_label New">New</span>
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/sports/sports-bras.html">Sports
																Bras </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/sports/sports-tights.html">Sports
																Tights </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/sports/sports-shorts.html">Sports
																Shorts </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/sports/sports-tops.html">Sports
																Tops </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/sports/sports-hoodies.html">Sports
																Hoodies </a></li>
													</ul></li>
												<li><a
													href="<?php echo WEBPATH;?>/accessories/newest-collection.html">Newest
														Collection </a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/newest-collection/christmas-shop.html">Christmas
																shop </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/newest-collection/movember.html">Movember
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/newest-collection/woodlanders.html">Woodlanders
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/newest-collection/tv-advert.html">Tv
																Advert </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/accessories/newest-collection/partywear.html">Partywear
														</a></li>
													</ul></li>
											</ul></li>
										<li class="level-top"><a class="level-top"
											href="<?php echo WEBPATH;?>/shirts.html"><span>Shirts </span></a></li>
										<li class="level-top"><a class="level-top"
											href="<?php echo WEBPATH;?>/tops.html"><span>Tops </span></a>
											<ul>
												<li><a href="<?php echo WEBPATH;?>/tops/shop-by.html">Shop
														By <span class="cat_label New">New</span>
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/shop-by/new-arrivals.html">New
																Arrivals </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/shop-by/christmas-gifting.html">Christmas
																Gifting </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/shop-by/workwear.html">Workwear
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/shop-by/brands.html">Brands
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/shop-by/surf-skate.html">Surf
																& Skate </a></li>
													</ul></li>
												<li><a href="<?php echo WEBPATH;?>/tops/clothing.html">Clothing
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/clothing/dresses.html">Dresses
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/clothing/tops.html">Tops
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/clothing/skirts.html">Skirts
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/clothing/swimwear.html">Swimwear
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/clothing/shorts.html">Shorts
														</a></li>
													</ul></li>
												<li><a href="<?php echo WEBPATH;?>/tops/shoes.html">Shoes <span
														class="cat_label Hot !">Hot !</span>
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/shoes/heels.html">Heels
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/shoes/sandals.html">Sandals
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/shoes/flats.html">Flats
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/shoes/ankle-boots.html">Ankle
																Boots </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/shoes/sneakers.html">Sneakers
														</a></li>
													</ul></li>
												<li><a href="<?php echo WEBPATH;?>/tops/accessories.html">Accessories
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/accessories/bags.html">Bags
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/accessories/jewellery.html">Jewellery
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/accessories/sunglasses.html">Sunglasses
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/accessories/scarves.html">Scarves
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/tops/accessories/watches.html">Watches
														</a></li>
													</ul></li>
											</ul></li>
										<li class="level-top"><a class="level-top"
											href="<?php echo WEBPATH;?>/outerwear.html"><span>Outerwear </span></a></li>
										<li class="level-top"><a class="level-top"
											href="<?php echo WEBPATH;?>/bottoms.html"><span>Bottoms </span></a>
											<ul>
												<li><a href="<?php echo WEBPATH;?>/bottoms/shoes.html">Shoes
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/shoes/heels.html">Heels
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/shoes/sandals.html">Sandals
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/shoes/flats.html">Flats
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/shoes/ankle-boots.html">Ankle
																Boots </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/shoes/sneakers.html">Sneakers
														</a></li>
													</ul></li>
												<li><a href="<?php echo WEBPATH;?>/bottoms/accessories.html">Accessories
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/accessories/bags.html">Bags
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/accessories/jewellery.html">Jewellery
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/accessories/sunglasses.html">Sunglasses
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/accessories/scarves.html">Scarves
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/accessories/watches.html">Watches
														</a></li>
													</ul></li>
												<li><a href="<?php echo WEBPATH;?>/bottoms/beauty.html">Beauty
												</a>
													<ul>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/beauty/perfume.html">Perfume
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/beauty/make-up.html">Make
																Up </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/beauty/hands-feet.html">Hands
																& Feet </a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/beauty/face.html">Face
														</a></li>
														<li class="nav "><a
															href="<?php echo WEBPATH;?>/bottoms/beauty/body.html">Body
														</a></li>
													</ul></li>
											</ul></li>
										<li class="level-top"><a class="level-top"
											href="<?php echo WEBPATH;?>/denim.html"><span>Denim </span></a></li>
										<li class="level-top"><a class="level-top"
											href="<?php echo WEBPATH;?>/luxury-shoes.html"><span>Luxury
													Shoes </span></a></li>
										<li class="level-top"><a class="level-top"
											href="<?php echo WEBPATH;?>/handbags.html"><span>Handbags </span></a></li>
										<li class="level-top"><a class="level-top"
											href="<?php echo WEBPATH;?>/gifts.html"><span>Gifts </span></a></li>
									</ul>
								</div>
								<div class="quick-access">
									<form id="search_mini_form"
										action="<?php echo WEBPATH;?>/catalogsearch/result/"
										method="get">
										<div class="form-search clearfix">
											<label for="search">Search:</label>
											<button type="submit" title="Search" class="button">
												<span><span><i class="fa fa-search"></i></span></span>
											</button>
											<input id="search" type="text" name="q" value=""
												class="input-text" maxlength="128" />
											<div id="search_autocomplete" class="search-autocomplete"></div>
											<script type="text/javascript">
												//<![CDATA[
												var searchForm = new Varien.searchForm(
														'search_mini_form',
														'search',
														'Search entire store here...');
												searchForm
														.initAutocomplete(
																'<?php echo WEBPATH;?>/catalogsearch/ajax/suggest/',
																'search_autocomplete');
												//]]>
											</script>
										</div>
									</form>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
			
			
			
			
			<?php echo $this->content; ?>
			
			
						<div class="footer-container">
						
				<?php if($_SERVER['SERVER_ADDR'] == IP_SERVER_TEST)  {?>		
				<div class="alo-brands">
					<div class="container">
						<div class="main">
							<div class="row show-grid">
								<div class="col-lg-12">
									<div>
										<div id="upcjhlljmp">
											<ul class="magicbrand">
												<li><img class="brand img-responsive"
													src="<?php echo BAG_REAL_HTML; ?>/smije/media//magiccart/magicbrand/cache/242x111/brands.png"
													alt="Brands1" title="Brands1" /></li>
												<li><img class="brand img-responsive"
													src="<?php echo BAG_REAL_HTML; ?>/smije/media//magiccart/magicbrand/cache/242x111/brands1.png"
													alt="2" title="2" /></li>
												<li><img class="brand img-responsive"
													src="<?php echo BAG_REAL_HTML; ?>/smije/media//magiccart/magicbrand/cache/242x111/brands2.png"
													alt="3" title="3" /></li>
												<li><img class="brand img-responsive"
													src="<?php echo BAG_REAL_HTML; ?>/smije/media//magiccart/magicbrand/cache/242x111/brands3.png"
													alt="4" title="4" /></li>
												<li><img class="brand img-responsive"
													src="<?php echo BAG_REAL_HTML; ?>/smije/media//magiccart/magicbrand/cache/242x111/brands_1.png"
													alt="5" title="5" /></li>
												<li><img class="brand img-responsive"
													src="<?php echo BAG_REAL_HTML; ?>/smije/media//magiccart/magicbrand/cache/242x111/brands1_1.png"
													alt="6" title="6" /></li>
											</ul>
										</div>

										<script type="text/javascript">
											jQuery(document)
													.ready(
															function($) {
																(function(
																		selector) {
																	var $content = $(selector);
																	var $slider = $(
																			'.magicbrand',
																			$content);
																	$slider
																			.flexisel({
																				moveSlide : 1,
																				animationSpeed : 1000,
																				autoPlay : 1,
																				autoPlaySpeed : 4000,
																				clone : 1,
																				enableResponsiveBreakpoints : 1,
																				pauseOnHover : 1,
																				visibleItems : 4,
																				responsiveBreakpoints : {
																					portrait : {
																						changePoint : 480,
																						visibleItems : 1
																					},
																					landscape : {
																						changePoint : 640,
																						visibleItems : 2
																					},
																					tablet : {
																						changePoint : 768,
																						visibleItems : 3
																					},
																				}
																			});

																})
																		("#upcjhlljmp");
															});
										</script>

									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				
				<?php } //end  if($_SERVER['SERVER_ADDR'] == IP_SERVER_TEST)  { ?>
				
				
				<div class="block-footer-top">
					<div class="container">
						<div class="main">
							<div class="row show-grid contentfooternew">
								
							</div>
						</div>
					</div>
				</div>
				
				
				<?php if($_SERVER['SERVER_ADDR'] == IP_SERVER_TEST)  { ?>
				<div class="block-footer-bottom">
					<div class="container">
						<div class="main">
							<div class="footer">
								<div class="container-">
									<div class="row">
										<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
											<div class="block-static1 static-alo">
												<h3 class="block-title heading">OUR SERVICES</h3>
												<div class="block2 block-content-statick">
													<ul>
														<li><a href="#">Order History</a></li>
														<li><a href="<?php echo WEBPATH;?>/sales/guest/form/">Returns</a></li>
														<li><a href="#">Libero Sed rhoncus</a></li>
														<li><a href="#">Venenatis augue tellus</a></li>
														<li><a href="#">My vouchers</a></li>
													</ul>
												</div>
											</div>
										</div>
										<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
											<div class="block-static2 static-alo">
												<h3 class="block-title heading">MY ACCOUNT</h3>
												<div class="block2 block-content-statick">
													<ul>
														<li><a href="#">About Us</a></li>
														<li><a href="#">Customer
																Service</a></li>
														<li><a
															href="#">Privacy Policy</a></li>
														<li><a
															href="#">Site Map</a></li>
														<li><a
															href="#">Search Terms</a></li>
													</ul>
												</div>
											</div>
										</div>
										<div class="userful col-lg-3 col-md-3 col-sm-3 col-xs-12">
											<div class="block-static3 static-alo">
												<h3 class="block-title heading">INFORMATION</h3>
												<div class="block3 block-content-statick">
													<ul>
														<li><a href="#">Order History</a></li>
														<li><a href="#">Returns</a></li>
														<li><a href="#">Libero Sed rhoncus</a></li>
														<li><a href="#">Venenatis augue tellus</a></li>
														<li><a href="#">My vouchers</a></li>
													</ul>
												</div>
											</div>
										</div>
										<div class="customer col-lg-3 col-md-3 col-sm-3 col-xs-12">
											<div class="block-static4 static-alo">
												<h3 class="block-title heading">WHY BUY FROM US</h3>
												<div class="block-linkservice block-content-statick">
													<ul>
														<li><a href="#">Shipping &amp; Returns</a></li>
														<li><a href="#">Secure Shopping</a></li>
														<li><a href="#">International Shipping</a></li>
														<li><a href="#">Affiliates</a></li>
														<li><a href="#">Contact</a></li>
													</ul>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				
				<?php } //end if($_SERVER['SERVER_ADDR'] == IP_SERVER_TEST)  { ?>
				
				
				<div class="block-footer-copyright">
					<div class="container">
						<div class="footer">
							<div class="main">
								<div class="row show-grid">
									<div class="container">
										<address>
											Copyright © 2014 <a class="active" href="<?php echo WEBPATH;?>"
												title="<?php echo $setting_session->name;?>"><?php echo $setting_session->name;?></a> by <?php echo $setting_session->name;?>. All rights reserved.
										</address>
										<div class="store-switcher">
										  <!-- 
											<label for="select-store">Select Store:</label> <select
												id="select-store" title="Select Store"
												onchange="location.href=this.value">
												<option
													value="<?php echo WEBPATH;?>/?___store=english_digital">Digital
													Store</option>
												<option value="" selected="selected">Fashion Store</option>
												<option value="<?php echo WEBPATH;?>/?___store=default">Furniture
													Store</option>
											</select>
											 -->
										</div>
										<div class="paypal">
											<p>
												<img class="img-responsive"
													src="<?php echo BAG_REAL_HTML; ?>/smije/media/wysiwyg/alothemes/static/paypal.png"
													alt="" />
											</p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<a href="#" id="backtotop"><span class="fa fa-angle-up"></span><span
					class="back-to-top">Back to Top</span></a>
			</div>


		</div>
	</div>

	<script type="text/javascript">
		     var domain ='<?php echo WEBPATH;?>';var glob=2;
			 jQuery(document).ready(function($) {
				 e = location.pathname;
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/loadleftcataogue",
		               data: {idcode:e,page:glob},
		               success: function(data){
			               //alert(data);console.log( $('.leftcatalogue').html(data));
		                            $('#leftcatalogue').html(data);
		                             glob++;
		                       }
		         });

				 $.ajax({
		               type: "POST",
		               url: domain + "/main/loadsaleproduct",
		               data: {idcode:e,page:glob},
		               success: function(data){
			               //alert("saleproducta "+data);console.log( $('#saleproducta').html(data));
		                            $('#saleproducta').html(data);
		                       }
		         });

		         //bestsellera
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/bestseller",
		               data: {idcode:e,page:glob},
		               success: function(data){
		            	   //alert("bestsellera " + data);console.log( $('#bestsellera').html(data));
		                            $('#bestsellera').html(data);
		                       }
		         });

		         //compareblock
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/compareblock",
		               data: {idcode:e,page:glob},
		               success: function(data){
		            	   //alert("bestsellera " + data);console.log( $('#bestsellera').html(data));
		                            $('#blockcompare').html(data);
		                       }
		         });


		         //populartags
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/populartags",
		               data: {idcode:e,page:glob},
		               success: function(data){
			                  $('#populartags').html(data);
		                       }
		         });

		         //containernone
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/containernone",
		               data: {idcode:e,page:glob},
		               success: function(data){
			                  $('#containernone').html(data);
		                       }
		         });

		         //myacount
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/myacount",
		               data: {idcode:e,page:glob},
		               success: function(data){
			                  $('#myacountaja').html(data);
		                       }
		         });

				//mycart
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/mycart",
		               data: {idcode:e,page:glob},
		               success: function(data){
			                  $('#mycartaja').html(data);
		                       }
		         });


				//myproduct
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/myproduct",
		               data: {idcode:e,page:glob},
		               success: function(data){
			                  $('#myproductaja').html(data);
		                       }
		         });


		         

		         //compareproduct
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/compareproduct",
		               data: {idcode:e,page:glob},
		               success: function(data){
			                  $('#compareproductaja').html(data);
		                       }
		         });

		         //contentfooternew
				 $.ajax({
		               type: "POST",
		               url: domain + "/main/settings",
		               data: {},
		               success: function(data){
			                  $('.contentfooternew').html(data);
		                       }
		         });
		         
			 });


			 function setcartnew(url)
			 {
                var $cart_url = url;
                console.log('hoang hang :'+url);
		     }
			 
				</script>


</body>
</html>


