<div class="main-container col1-layout">
	<div class="alo-breadcrumbs">
		<div class="container">
			<div class="main">
				<div class="row show-grid">
					<div class="col-lg-12"></div>
				</div>
			</div>
		</div>
	</div>
	<div class="alo-top">
		<div class="container">
			<div class="main">
				<div class="row show-grid">
					<div class="col-lg-12"></div>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="main">
		<?php 
		//var_dump($Shoppingcart);
		if($Shoppingcart === NULL) {?>
			<div class="row show-grid">
				<div class="col-main col-lg-12">
					<div class="page-title">
						<h1>Shopping Cart is Empty</h1>
					</div>
					<div class="cart-empty">
						<p>You have no items in your shopping cart.</p>
						<p>
							Click <a href="<?php echo WEBPATH;?>">here</a>
							to continue shopping.
						</p>
					</div>
				</div>
			</div>
			<?php } else { 
              //echo "Shoppingcart co data";
            } ?>
		</div>
	</div>
	<div class="alo-bottom">
		<div class="container">
			<div class="main">
				<div class="row show-grid">
					<div class="col-lg-12"></div>
				</div>
			</div>
		</div>
	</div>
</div>