<?php

$titl_tmp=microtime(true)*100;
$titl=$titl_tmp%10000000000;


//echo 'post_max_size = ' . ini_get('post_max_size') . "\n";
$allowedExts = array("gif", "jpeg", "jpg", "png","mp4","webm");
$temp = explode(".", $_FILES["file"]["name"]);

echo $_FILES["file"]["type"].': '.$_FILES["file"]["size"];
$extension = strtolower(end($temp));
if ((($_FILES["file"]["type"] == "image/gif")
|| ($_FILES["file"]["type"] == "image/jpeg")
|| ($_FILES["file"]["type"] == "image/jpg")
|| ($_FILES["file"]["type"] == "image/pjpeg")
|| ($_FILES["file"]["type"] == "image/x-png")
|| ($_FILES["file"]["type"] == "image/png")
|| ($_FILES["file"]["type"] == "video/webm")
|| ($_FILES["file"]["type"] == "video/mp4"))
&& (($_FILES["file"]["size"]/1000000) < 200)
&& in_array($extension, $allowedExts))
  {
  if ($_FILES["file"]["error"] > 0)
    {
    echo "Return Code: " . $_FILES["file"]["error"] . "<br>";
    }
  else
    {
	$filename=$_FILES["file"]["name"];

    echo "Upload: " . $_FILES["file"]["name"] . "<br>";
    echo "Type: " . $_FILES["file"]["type"] . "<br>";
    echo "Size: " . ($_FILES["file"]["size"] / 1024) . " kB<br>";
    echo "Temp file: " . $_FILES["file"]["tmp_name"] . "<br>";

        if (!file_exists('eclip.tv/data/uploads/user')) 
        {
            mkdir('eclip.tv/data/uploads/user', 0777, true);
        }
   // if (file_exists("embed/media/" . $_FILES["file"]["name"]))
     // {
     // echo $_FILES["file"]["name"] . " already exists. ";
     // }
   // else
     // {
      move_uploaded_file($_FILES["file"]["tmp_name"],
      "eclip.tv/data/uploads/user/".$titl.".".$extension);
     // echo "Stored in: " . "embed/media/" . $_FILES["file"]["name"];
      //$direc="embed/media/".$titl.".".$extension;
      //}
      }
      }



?>