
<div class="mage-magictabs mc-newproduct">
	<ul class="flexisel-content products-grid newproduct zoomOut play">

		<li
			style="-webkit-animation-delay: 0ms; -moz-animation-delay: 0ms; -o-animation-delay: 0ms; animation-delay: 0ms;"
			class="item item-animate">
			<div class="per-product">
				<div class="images-container">
					<div class="product-hover">
						<span class="sticker top-left"><span class="labelnew">New</span></span>
						<a href="<?php echo WEBPATH?>/plaid-cotton-shirt.html"
							title="Plaid Cotton Shirt" class="product-image"> <img
							class="img-responsive"
							src="<?php echo BAG_REAL_HTML;?>/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1.jpg"
							width="290" height="372" alt="Plaid Cotton Shirt" /> <span
							class="product-img-back"> <img class="img-responsive"
								src="<?php echo BAG_REAL_HTML;?>/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/1/-/1-1.jpg"
								width="290" height="372" alt="Plaid Cotton Shirt" />
						</span>
						</a>
					</div>
					<div class="actions-no">
						<div class="actions">
							<button type="button" title="Add to Cart"
								class="pull-left button btn-cart"
								onclick="setLocation('<?php echo WEBPATH?>/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNwcm9kdWN0L2luZGV4L2FqYXgv/product/25/form_key/Z9IuKHJORkq6jWdh/')">
								<span><span>Add to Cart</span></span>
							</button>
							<ul class="add-to-links pull-left">
								<li class="pull-left"><a
									href="<?php echo WEBPATH?>/wishlist/index/add/product/25/form_key/Z9IuKHJORkq6jWdh/"
									title="Add to Wishlist" class="link-wishlist">Add to Wishlist</a></li>
								<li class="pull-right"><span class="separator">|</span> <a
									href="<?php echo WEBPATH?>/catalog/product_compare/add/product/25/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNwcm9kdWN0L2luZGV4L2FqYXgv/form_key/Z9IuKHJORkq6jWdh/"
									title="Add to Compare" class="link-compare">Add to Compare</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="products-textlink clearfix">
					<h2 class="product-name">
						<a href="<?php echo WEBPATH?>/plaid-cotton-shirt.html"
							title="Plaid Cotton Shirt">Plaid Cotton Shirt</a>
					</h2>
					<div class="ratings">
						<div class="rating-box">
							<div class="rating" style="width: 100%"></div>
						</div>
						<span class="amount"><a href="#"
							onclick="var t = opener ? opener.window : window; t.location.href='<?php echo WEBPATH?>/review/product/list/id/25/'; return false;">1
								Review(s)</a></span>
					</div>



					<div class="price-box">
						<span class="regular-price" id="product-price-25"> <span
							class="price">$185.00</span>
						</span>

					</div>

				</div>
			</div>
		</li>

		<li
			style="-webkit-animation-delay: 0ms; -moz-animation-delay: 0ms; -o-animation-delay: 0ms; animation-delay: 0ms;"
			class="item item-animate">
			<div class="per-product">
				<div class="images-container">
					<div class="product-hover">
						<span class="sticker top-left"><span class="labelnew">New</span></span>
						<a href="<?php echo WEBPATH?>/broad-st-flapover.html"
							title="Broad St. Flapover" class="product-image"> <img
							class="img-responsive"
							src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/1/8/18_6.jpg"
							width="290" height="372" alt="Broad St. Flapover" /> <span
							class="product-img-back"> <img class="img-responsive"
								src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/1/4/14_4.jpg"
								width="290" height="372" alt="Broad St. Flapover" />
						</span>
						</a>
					</div>
					<div class="actions-no">
						<div class="actions">
							<button type="button" title="Add to Cart"
								class="pull-left button btn-cart"
								onclick="setLocation('<?php echo WEBPATH?>/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNwcm9kdWN0L2luZGV4L2FqYXgv/product/41/form_key/Z9IuKHJORkq6jWdh/')">
								<span><span>Add to Cart</span></span>
							</button>
							<ul class="add-to-links pull-left">
								<li class="pull-left"><a
									href="<?php echo WEBPATH?>/wishlist/index/add/product/41/form_key/Z9IuKHJORkq6jWdh/"
									title="Add to Wishlist" class="link-wishlist">Add to Wishlist</a></li>
								<li class="pull-right"><span class="separator">|</span> <a
									href="<?php echo WEBPATH?>/catalog/product_compare/add/product/41/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNwcm9kdWN0L2luZGV4L2FqYXgv/form_key/Z9IuKHJORkq6jWdh/"
									title="Add to Compare" class="link-compare">Add to Compare</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="products-textlink clearfix">
					<h2 class="product-name">
						<a href="<?php echo WEBPATH?>/broad-st-flapover.html"
							title="Broad St. Flapover">Broad St. Flapover</a>
					</h2>
					<div class="ratings">
						<div class="rating-box">
							<div class="rating" style="width: 60%"></div>
						</div>
						<span class="amount"><a href="#"
							onclick="var t = opener ? opener.window : window; t.location.href='<?php echo WEBPATH?>/review/product/list/id/41/'; return false;">1
								Review(s)</a></span>
					</div>



					<div class="price-box">
						<span class="regular-price" id="product-price-41"> <span
							class="price">$234.00</span>
						</span>

					</div>

				</div>
			</div>
		</li>

		<li
			style="-webkit-animation-delay: 0ms; -moz-animation-delay: 0ms; -o-animation-delay: 0ms; animation-delay: 0ms;"
			class="item item-animate">
			<div class="per-product">
				<div class="images-container">
					<div class="product-hover">
						<span class="sticker top-left"><span class="labelnew">New</span></span>
						<a href="<?php echo WEBPATH?>/french-cuff-cotton.html"
							title="French Cuff Cotton" class="product-image"> <img
							class="img-responsive"
							src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/2/_/2_3.jpg"
							width="290" height="372" alt="French Cuff Cotton" /> <span
							class="product-img-back"> <img class="img-responsive"
								src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/2/-/2-2_1.jpg"
								width="290" height="372" alt="French Cuff Cotton" />
						</span>
						</a>
					</div>
					<div class="actions-no">
						<div class="actions">
							<button type="button" title="Add to Cart"
								class="pull-left button btn-cart"
								onclick="setLocation('<?php echo WEBPATH?>/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNwcm9kdWN0L2luZGV4L2FqYXgv/product/26/form_key/Z9IuKHJORkq6jWdh/')">
								<span><span>Add to Cart</span></span>
							</button>
							<ul class="add-to-links pull-left">
								<li class="pull-left"><a
									href="<?php echo WEBPATH?>/wishlist/index/add/product/26/form_key/Z9IuKHJORkq6jWdh/"
									title="Add to Wishlist" class="link-wishlist">Add to Wishlist</a></li>
								<li class="pull-right"><span class="separator">|</span> <a
									href="<?php echo WEBPATH?>/catalog/product_compare/add/product/26/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNwcm9kdWN0L2luZGV4L2FqYXgv/form_key/Z9IuKHJORkq6jWdh/"
									title="Add to Compare" class="link-compare">Add to Compare</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="products-textlink clearfix">
					<h2 class="product-name">
						<a href="<?php echo WEBPATH?>/french-cuff-cotton.html"
							title="French Cuff Cotton">French Cuff Cotton</a>
					</h2>
					<div class="ratings">
						<div class="rating-box">
							<div class="rating" style="width: 60%"></div>
						</div>
						<span class="amount"><a href="#"
							onclick="var t = opener ? opener.window : window; t.location.href='<?php echo WEBPATH?>/review/product/list/id/26/'; return false;">1
								Review(s)</a></span>
					</div>



					<div class="price-box">
						<span class="regular-price" id="product-price-26"> <span
							class="price">$168.00</span>
						</span>

					</div>

				</div>
			</div>
		</li>

		<li
			style="-webkit-animation-delay: 0ms; -moz-animation-delay: 0ms; -o-animation-delay: 0ms; animation-delay: 0ms;"
			class="item item-animate">
			<div class="per-product">
				<div class="images-container">
					<div class="product-hover">
						<span class="sticker top-left"><span class="labelnew">New</span></span>
						<a href="<?php echo WEBPATH?>/houston-travel-wallet.html"
							title="Houston Travel Wallet" class="product-image"> <img
							class="img-responsive"
							src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/1/6/16_5.jpg"
							width="290" height="372" alt="Houston Travel Wallet" /> <span
							class="product-img-back"> <img class="img-responsive"
								src="http://alothemes.com/demo/smije/media/catalog/product/cache/4/small_image/290x372/9df78eab33525d08d6e5fb8d27136e95/1/4/14_5.jpg"
								width="290" height="372" alt="Houston Travel Wallet" />
						</span>
						</a>
					</div>
					<div class="actions-no">
						<div class="actions">
							<button type="button" title="Add to Cart"
								class="pull-left button btn-cart"
								onclick="setLocation('<?php echo WEBPATH?>/checkout/cart/add/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNwcm9kdWN0L2luZGV4L2FqYXgv/product/42/form_key/Z9IuKHJORkq6jWdh/')">
								<span><span>Add to Cart</span></span>
							</button>
							<ul class="add-to-links pull-left">
								<li class="pull-left"><a
									href="<?php echo WEBPATH?>/wishlist/index/add/product/42/form_key/Z9IuKHJORkq6jWdh/"
									title="Add to Wishlist" class="link-wishlist">Add to Wishlist</a></li>
								<li class="pull-right"><span class="separator">|</span> <a
									href="<?php echo WEBPATH?>/catalog/product_compare/add/product/42/uenc/aHR0cDovL2Fsb3RoZW1lcy5jb20vZGVtby9zbWlqZS9pbmRleC5waHAvbWFnaWNwcm9kdWN0L2luZGV4L2FqYXgv/form_key/Z9IuKHJORkq6jWdh/"
									title="Add to Compare" class="link-compare">Add to Compare</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="products-textlink clearfix">
					<h2 class="product-name">
						<a href="<?php echo WEBPATH?>/houston-travel-wallet.html"
							title="Houston Travel Wallet">Houston Travel Wallet</a>
					</h2>
					<div class="ratings">
						<div class="rating-box">
							<div class="rating" style="width: 60%"></div>
						</div>
						<span class="amount"><a href="#"
							onclick="var t = opener ? opener.window : window; t.location.href='<?php echo WEBPATH?>/review/product/list/id/42/'; return false;">1
								Review(s)</a></span>
					</div>



					<div class="price-box">
						<span class="regular-price" id="product-price-42"> <span
							class="price">$156.00</span>
						</span>

					</div>

				</div>
			</div>
		</li>
		
		
		
		
		
		
		
		
	</ul>
</div>


